Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:: @ 81C5BC4
	.string "Du kannst mich BEERENMEISTER\n"
	.string "nennen.\p"
	.string "Ich träume davon, die Welt mit hübschen\n"
	.string "Blumen zu bereichern, daher züchte ich\l"
	.string "BEEREN und gebe sie an andere weiter.\p"
	.string "Du hast dir auch eine verdient!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:: @ 81C5C66
	.string "Sei nicht so schüchtern.\n"
	.string "Nimm dir noch eine!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:: @ 81C5C83
	.string "Besuch unbedingt den BLÜTENTRAUM\n"
	.string "BLUMENLADEN bei METAROST CITY.\p"
	.string "Lasst die Welt in Blumen schwelgen.$"

Route123_BerryMastersHouse_Text_DoneForToday:: @ 81C5CDC
	.string "Für heute bin ich fertig.\n"
	.string "Komm ein anderes Mal wieder.\p"
	.string "Lasst die Welt in Blumen schwelgen!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:: @ 81C5D24
	.string "Mein Mann züchtet BEEREN. Er ist be-\n"
	.string "stimmt der beste Züchter der Welt.\p"
	.string "Er macht mich unglaublich stolz.\p"
	.string "Sag mal, Kind, du kennst nicht zufällig\n"
	.string "einen guten Spruch?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:: @ 81C5DC1
	.string "Ah! Was für ein wunderbarer Spruch!\n"
	.string "So inspirierend!\p"
	.string "Das hier möchte ich dir schenken.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:: @ 81C5E0E
	.string "Oh! Das ist ein guter Spruch!\n"
	.string "Du bist bemerkenswert!\p"
	.string "Das hier möchte ich dir schenken.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:: @ 81C5E59
	.string "Unsere vier Enkelkinder sollten noch\n"
	.string "begabter als mein Mann werden.\p"
	.string "Das Leben erfüllt einen immer wieder mit\n"
	.string "Freude!$"

Route123_BerryMastersHouse_Text_Ah:: @ 81C5EC0
	.string "Ah...$"
