Route119_WeatherInstitute_2F_Text_Grunt3Intro:: @ 819EEAF
	.string "Das INSTITUT hat ein POKéMON ent-\n"
	.string "wickelt, das irgendwas mit dem Wetter zu\l"
	.string "tun hat. Das müssen wir kriegen!$"

Route119_WeatherInstitute_2F_Text_Grunt3Defeat:: @ 819EF1B
	.string "Ein Kind hat unsere Pläne durchkreuzt?$"

Route119_WeatherInstitute_2F_Text_Grunt3PostBattle:: @ 819EF3E
	.string "Wenn sie hier tatsächlich ein POKéMON\n"
	.string "entwickelt haben, das das Wetter kon-\l"
	.string "trollieren kann, müssen wir vom TEAM\l"
	.string "{EVIL_TEAM} es in unsere Gewalt bringen!$"

Route119_WeatherInstitute_2F_Text_Grunt4Intro:: @ 819EFA3
	.string "Wir sind TEAM {EVIL_TEAM}!\n"
	.string "Wir sind überall dort, wo Raritäten\l"
	.string "gefunden wurden!$"

Route119_WeatherInstitute_2F_Text_Grunt4Defeat:: @ 819EFDD
	.string "Das war's dann wohl!$"

Route119_WeatherInstitute_2F_Text_Grunt4PostBattle:: @ 819EFE9
	.string "Du hast doch gar keine Ahnung, was wir\n"
	.string "vom TEAM {EVIL_TEAM} vorbereiten!\l"
	.string "Geh uns gefälligst aus dem Weg!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminIntro:: @ 819F042
	.string "Ahahahahaha!!!\p"
	.string "Du willst dich allen Ernstes in die Ange-\n"
	.string "legenheiten von TEAM {EVIL_TEAM} einmischen?\p"
	.string "Dann bist du entweder furchtlos oder\n"
	.string "einfach dumm! Oder beides?\p"
	.string "Du bist ja so niedlich. Einfach widerlich!\n"
	.string "Ich mach dich fertig, du Baby!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminDefeat:: @ 819F0F4
	.string "Ahahahahaha!!!!!\n"
	.string "Du bist einfach widerlich... stark!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminPostBattle:: @ 819F11B
	.string "Ahahahahaha! Wir wurden von\n"
	.string "Unvorhergesehenem gestört!\p"
	.string "Wir haben keine Möglichkeiten mehr. Wir\n"
	.string "müssen uns aus dem Schlamassel ziehen.\p"
	.string "Aber das ist nicht das Letzte, was du\n"
	.string "von TEAM {EVIL_TEAM} siehst! Wir werden\l"
	.string "andere Pläne entwickeln. Merk dir das!$"

Route119_WeatherInstitute_2F_Text_ThanksForSavingUs:: @ 819F1CF
	.string "Danke!\n"
	.string "Vielen Dank! Nun sind wir in Sicherheit!\p"
	.string "Es ist vielleicht eine seltsame Art\n"
	.string "danke zu sagen, aber dieses POKéMON\l"
	.string "ist für dich!$"

Route119_WeatherInstitute_2F_Text_NoRoomForCastform:: @ 819F231
	.string "Oh! Du hast keinen Platz für dieses\n"
	.string "POKéMON.$"

Route119_WeatherInstitute_2F_Text_ReceivedCastform:: @ 819F267
	.string "{PLAYER} erhält FORMEO!$"

Route119_WeatherInstitute_2F_Text_CastformChangesWithWeather:: @ 819F27D
	.string "Dieses POKéMON ändert seine Gestalt\n"
	.string "abhängig vom jeweiligen Wetter.\p"
	.string "Hier im INSTITUT gibt es sehr viele\n"
	.string "davon - du kannst es ruhig annehmen.$"

Route119_WeatherInstitute_2F_Text_StudyingRain:: @ 819F2FE
	.string "Seit Jahren erforsche ich den Regen,\n"
	.string "aber zu denken, dass Menschen das\l"
	.string "Wetter frei bestimmen können, ist dumm.$"
