CaveOfOrigin_B4F_Text_RedOrbBeginsGlowing:: @ 81B4FE4
	.string "Die ROTE KUGEL von {PLAYER}\n"
	.string "beginnt plötzlich von innen\l"
	.string "heraus zu leuchten!$"

CaveOfOrigin_B4F_Text_GroudonSettled:: @ 81B5009
	.string "GROUDON wurde offensichtlich\n"
	.string "wieder in Schlaf versetzt...$"

CaveOfOrigin_B4F_Text_MaxieThis:: @ 81B503D
	.string "MARC: Das...$"

CaveOfOrigin_B4F_Text_MaxieFarewell:: @ 81B504C
	.string "MARC: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das heißt wohl Goodbye. Das ist das\n"
	.string "Letzte, was du von mir siehst.$"
