Route107_Text_DarrinIntro:: @ 81B926B
	.string "Gäähn...\p"
	.string "Ich muss wohl eingeschlafen sein, als\n"
	.string "ich mich auf den Wellen treiben ließ.$"

Route107_Text_DarrinDefeated:: @ 81B92B7
	.string "Ahahaha, ich habe verloren...\n"
	.string "Ich mache jetzt ein Nickerchen...$"

Route107_Text_DarrinPostBattle:: @ 81B92E7
	.string "Sich treiben und von den Wellen\n"
	.string "schaukeln lassen - als ob man in einem\l"
	.string "weichen, bequemen Bett schläft.$"

Route107_Text_TonyIntro:: @ 81B933A
	.string "Das Meer ist wie mein Garten.\n"
	.string "Lass uns kämpfen.$"

Route107_Text_TonyDefeated:: @ 81B9365
	.string "Ich habe in meinem eigenen Garten ver-\n"
	.string "loren... Ich bin geschockt!$"

Route107_Text_TonyPostBattle:: @ 81B938E
	.string "Ich schwimme im Meer, das Herz voller\n"
	.string "Träume...\p"
	.string "Das ist ein Lied!\n"
	.string "Wie auch immer, ich schwimme weiter.$"

Route107_Text_TonyRematchIntro:: @ 81B93EB
	.string "Durch das Schwimmen im Meer ist\n"
	.string "mein POKéMON stärker geworden!$"

Route107_Text_TonyRematchDefeated:: @ 81B9429
	.string "Was für ein Schock!\p"
	.string "Mein POKéMON ist stärker geworden,\n"
	.string "aber ich bin ein Weichei von TRAINER.$"

Route107_Text_TonyRematchPostBattle:: @ 81B9477
	.string "Das, was du im Kampf lernst, macht dich\n"
	.string "zu einem starken TRAINER.\l"
	.string "Das haben mir die Wellen beigebracht.$"

Route107_Text_DeniseIntro:: @ 81B94C8
	.string "Kennst du einen kleinen Ort namens\n"
	.string "FAUSTAUHAVEN?$"

Route107_Text_DeniseDefeated:: @ 81B94F2
	.string "Ich hasse das!$"

Route107_Text_DenisePostBattle:: @ 81B94FF
	.string "Verrücktheiten zu erzählen ist der neue\n"
	.string "Trend in der FAUSTAUHAVEN HALLE.$"

Route107_Text_BethIntro:: @ 81B9538
	.string "Willst du gegen mich kämpfen?\n"
	.string "Natürlich trete ich gegen dich an!$"

Route107_Text_BethDefeated:: @ 81B956B
	.string "Ich war nicht gut genug für dich.$"

Route107_Text_BethPostBattle:: @ 81B9589
	.string "Ich denke, du wirst dich bemühen, noch\n"
	.string "besser zu werden. Das tue ich auch!$"

Route107_Text_LisaIntro:: @ 81B95CB
	.string "BEA: Wir fordern dich als Bruder und\n"
	.string "Schwester heraus!$"

Route107_Text_LisaDefeated:: @ 81B95FB
	.string "BEA: Unglaublich.\n"
	.string "Du bist in einer anderen Stärke-Klasse.$"

Route107_Text_LisaPostBattle:: @ 81B9630
	.string "BEA: Hast du Freunde, die mit dir an den\n"
	.string "Strand gehen würden?$"

Route107_Text_LisaNotEnoughPokemon:: @ 81B9672
	.string "BEA: Wenn du gegen uns kämpfen willst,\n"
	.string "bring mehr POKéMON mit.$"

Route107_Text_RayIntro:: @ 81B96AB
	.string "ERKO: Wir kämpfen immer mit POKéMON,\n"
	.string "meine Schwester und ich.\p"
	.string "Ich alleine verliere ständig, aber wir\n"
	.string "können dich 2-gegen-2 schlagen!$"

Route107_Text_RayDefeated:: @ 81B9707
	.string "ERKO: Huiuiui! Du kämpfst auf einem viel\n"
	.string "höheren Level als wir!$"

Route107_Text_RayPostBattle:: @ 81B9735
	.string "ERKO: Meine Schwester hat mir mein\n"
	.string "POKéMON gegeben und nun ist es mein\l"
	.string "Partner!$"

Route107_Text_RayNotEnoughPokemon:: @ 81B9788
	.string "ERKO: Wenn du gegen uns antreten willst,\n"
	.string "bring mehr POKéMON mit.$"
