Route120_Text_ColinIntro:: @ 81BEFC8
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_ColinDefeat:: @ 81BF000
	.string "You soared above me!$"

Route120_Text_ColinPostBattle:: @ 81BF015
	.string "The move FLY is convenient, don't\n"
	.string "you think?\p"
	.string "While the POKéMON is flying, almost\n"
	.string "no moves can strike it.$"

Route120_Text_RobertIntro:: @ 81BF07E
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:: @ 81BF0A5
	.string "Your POKéMON were stronger...$"

Route120_Text_RobertPostBattle:: @ 81BF0C3
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchIntro:: @ 81BF0FA
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:: @ 81BF131
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:: @ 81BF154
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_CarlosIntro:: @ 81BF193
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_CarlosDefeat:: @ 81BF1D4
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_CarlosPostBattle:: @ 81BF215
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON...\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:: @ 81BF26E
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat:: @ 81BF2D2
	.string "I'm totally fit, but...$"

Route120_Text_JennaPostBattle:: @ 81BF2EA
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_BrandonIntro:: @ 81BF32B
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Want to battle?$"

Route120_Text_BrandonDefeat:: @ 81BF36B
	.string "... ... ... ... ... ...\n"
	.string "I lost...$"

Route120_Text_BrandonPostBattle:: @ 81BF38D
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "I'll try harder...$"

Route120_Text_BrandonRematchIntro:: @ 81BF3D0
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Want to battle again?$"

Route120_Text_BrandonRematchDefeat:: @ 81BF416
	.string "... ... ... ... ... ...\n"
	.string "I lost again...$"

Route120_Text_BrandonPostRematch:: @ 81BF43E
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "I'll try harder...\l"
	.string "For my precious BUG POKéMON...$"

Route120_Text_JenniferIntro:: @ 81BF4A0
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:: @ 81BF504
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:: @ 81BF51F
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro:: @ 81BF560
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat:: @ 81BF5D6
	.string "What a disgraceful setback...$"

Route120_Text_ChipPostBattle:: @ 81BF5F4
	.string "That giant rock... I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:: @ 81BF65B
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:: @ 81BF6A4
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks...$"

Route120_Text_ClarissaPostBattle:: @ 81BF6D0
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:: @ 81BF728
	.string "Me, POKéMON, and my parasol...\p"
	.string "If any one of them is missing, the\n"
	.string "picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:: @ 81BF78C
	.string "You've completely ruined my beauty...$"

Route120_Text_AngelicaPostBattle:: @ 81BF7B2
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro:: @ 81BF80B
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat:: @ 81BF852
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream...$"

Route120_Text_KeigoPostBattle:: @ 81BF891
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_TsunaoIntro:: @ 81BF8C5
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_TsunaoDefeat:: @ 81BF920
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_TsunaoPostBattle:: @ 81BF946
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"
