Route119_Text_BrentIntro:: @ 81BE521
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_BrentDefeat:: @ 81BE54F
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_BrentPostBattle:: @ 81BE561
	.string "What's so good about mimicry?\p"
	.string "Fufufu...\n"
	.string "You'll never understand...$"

Route119_Text_DonaldIntro:: @ 81BE5A4
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_DonaldDefeat:: @ 81BE5DF
	.string "I wish we'd never met...$"

Route119_Text_DonaldPostBattle:: @ 81BE5F8
	.string "I want to MIMIC you some more.\p"
	.string "Can you hurry up and move?$"

Route119_Text_TaylorIntro:: @ 81BE632
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too...$"

Route119_Text_TaylorDefeat:: @ 81BE67B
	.string "But if you win, I lose...$"

Route119_Text_TaylorPostBattle:: @ 81BE695
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible...\l"
	.string "It's burning me up...$"

Route119_Text_DougIntro:: @ 81BE6EA
	.string "Yep, you've finally caught me!\n"
	.string "Or were you trying to avoid me?$"

Route119_Text_DougDefeat:: @ 81BE729
	.string "Whoop, that was a great match!$"

Route119_Text_DougPostBattle:: @ 81BE748
	.string "We're the MIMIC CIRCLE!\n"
	.string "I hope you enjoyed our performance.$"

Route119_Text_GregIntro:: @ 81BE784
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you.\n"
	.string "So, we'll battle!$"

Route119_Text_GregDefeat:: @ 81BE7D3
	.string "You're pretty strong!$"

Route119_Text_GregPostBattle:: @ 81BE7E9
	.string "Until you go away somewhere, we'll\n"
	.string "keep on mimicking your every move.$"

Route119_Text_KentIntro:: @ 81BE82F
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_KentDefeat:: @ 81BE88D
	.string "I surrender!$"

Route119_Text_KentPostBattle:: @ 81BE89A
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:: @ 81BE8BB
	.string "Who has the knowledge and the\n"
	.string "technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:: @ 81BE90E
	.string "I didn't have enough POKéMON\n"
	.string "know-how...$"

Route119_Text_JacksonPostBattle:: @ 81BE937
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRematchIntro:: @ 81BE98D
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:: @ 81BE9D0
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:: @ 81BE9E8
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:: @ 81BEA3A
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure, you're\n"
	.string "traveling awfully light.$"

Route119_Text_CatherineDefeat:: @ 81BEA88
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherinePostBattle:: @ 81BEAB3
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_CatherineRematchIntro:: @ 81BEB22
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:: @ 81BEB49
	.string "I'm still missing something...$"

Route119_Text_CatherinePostRematch:: @ 81BEB68
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_HughIntro:: @ 81BEBC0
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_HughDefeat:: @ 81BEC1C
	.string "Down and out!$"

Route119_Text_HughPostBattle:: @ 81BEC2A
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_PhilIntro:: @ 81BEC5E
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_PhilDefeat:: @ 81BEC9A
	.string "We lacked potential...$"

Route119_Text_PhilPostBattle:: @ 81BECB1
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON...$"

Route119_Text_YasuIntro:: @ 81BECF1
	.string "To lurk in shadows, and live in\n"
	.string "darkness... That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:: @ 81BED4C
	.string "I admit defeat!$"

Route119_Text_YasuPostBattle:: @ 81BED5C
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny...$"

Route119_Text_TakashiIntro:: @ 81BEDB6
	.string "If you're not on your guard, you're in\n"
	.string "for some pain!$"

Route119_Text_TakashiDefeat:: @ 81BEDEC
	.string "You're surprisingly good!$"

Route119_Text_TakashiPostBattle:: @ 81BEE06
	.string "My surprise attack ended in\n"
	.string "failure...$"

Route119_Text_HideoIntro:: @ 81BEE2D
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:: @ 81BEE4B
	.string "I bow to your superiority.$"

Route119_Text_HideoPostBattle:: @ 81BEE66
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that.$"

Route119_Text_EugeneIntro:: @ 81BEED0
	.string "You spoke to me...\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_EugeneDefeat:: @ 81BEF37
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_EugenePostBattle:: @ 81BEF67
	.string "Go for a SURF on my POKéMON...\p"
	.string "Then fish off its back...\p"
	.string "It's an indescribably luxuriant moment!$"
