Route112_Text_EvilTeamGrunt1WaitingForFallarborCrew:: @ 816FDF0
	.string "Grumble...\p"
	.string "What happened to the others who went\n"
	.string "to FALLARBOR? They're late...$"

Route112_Text_EvilTeamGrunt2WantsCableCarRide:: @ 816FE3E
	.string "Grumble...\p"
	.string "I'd like to ride the CABLE CAR to the\n"
	.string "top, too..$"

Route112_Text_NotEasyToGetBackToLavaridge:: @ 816FE7A
	.string "Eh, I'd like to get to MAUVILLE, but if\n"
	.string "I went down these ledges, it'd be no\l"
	.string "easy matter to get back to LAVARIDGE.$"

Route112_Text_MtChimneyCableCarSign:: @ 816FEED
	.string "MT. CHIMNEY CABLE CAR\n"
	.string "“A short walk {0x79} way!”$"

Route112_Text_MtChimneySign:: @ 816FF19
	.string "MT. CHIMNEY\p"
	.string "“For LAVARIDGE TOWN or the summit,\n"
	.string "please take the CABLE CAR.”$"

Route112_Text_RouteSignLavaridge:: @ 816FF64
	.string "ROUTE 112\n"
	.string "{0x7B} LAVARIDGE TOWN$"
