Route112_Text_BriceIntro:: @ 81BB619
	.string "Hahahaha!\n"
	.string "How about we have a battle?\l"
	.string "You and me!\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:: @ 81BB655
	.string "I lost!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:: @ 81BB667
	.string "Hahahahaha! Something flew up my nose!\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:: @ 81BB6A0
	.string "My legs are solid from pounding up\n"
	.string "and down the mountains.\p"
	.string "They're not going to buckle easily,\n"
	.string "friend!$"

Route112_Text_TrentDefeat:: @ 81BB707
	.string "Ouch! My legs cramped up!$"

Route112_Text_TrentPostBattle:: @ 81BB721
	.string "Try hiking, and I mean really\n"
	.string "pounding, on these mountain trails\l"
	.string "with a heavy pack weighing dozens of\l"
	.string "pounds.\p"
	.string "That, my friend, will get your body\n"
	.string "into serious shape.$"

Route112_Text_TrentRematchIntro:: @ 81BB7C7
	.string "I've been keeping fit by hiking.\n"
	.string "Power, I have in spades!$"

Route112_Text_TrentRematchDefeat:: @ 81BB801
	.string "I got trumped in power?$"

Route112_Text_TrentRematchPostBattle:: @ 81BB819
	.string "I hear there are some seriously tough\n"
	.string "TRAINERS on top of MT. CHIMNEY.\p"
	.string "I intend to get up there and give them\n"
	.string "a challenge!$"

Route112_Text_LarryIntro:: @ 81BB893
	.string "I'm strong.\n"
	.string "I won't cry if I lose.$"

Route112_Text_LarryDefeat:: @ 81BB8B6
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:: @ 81BB8BE
	.string "I'm not crying because I miss my mommy!\n"
	.string "Snivel...$"

Route112_Text_CarolIntro:: @ 81BB8F0
	.string "When you're out on a picnic, why, you\n"
	.string "simply have to sing!\l"
	.string "Come on, sing with me!$"

Route112_Text_CarolDefeat:: @ 81BB942
	.string "Oh, you're so strong!$"

Route112_Text_CarolPostBattle:: @ 81BB958
	.string "It doesn't matter if you're good or bad\n"
	.string "at singing or POKéMON.\p"
	.string "If you have the most fun, you win!$"
