Route134_Text_JackIntro:: @ 81C30C6
	.string "Selbst POKéMON, die schwimmen können,\n"
	.string "werden oft von der Strömung erfasst.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "Ich glaube, POKéMON mögen diese\n"
	.string "schnellen Strömungen hier sehr.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "Meine LIEBISKUS möchten ihren Spaß\n"
	.string "bei einem Kampf haben. Machst du mit?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Huupsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "Es gibt da einen Sammler, der sich für \n"
	.string "SCHUPPEN von LIEBISKUS interessiert.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! Genug gerastet, Jungs!\n"
	.string "Zeit für ein Kämpfchen!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Wir wurden wieder fertig gemacht.$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "Mein VOGEL-POKéMON wird nach einem\n"
	.string "langen Flug schnell müde...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "Du bist ein POKéMON-TRAINER.\n"
	.string "Worte sind da überflüssig. Wir kämpfen.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "Ich habe dich herausgefordert und\n"
	.string "doch verloren. Ich bin tief beschämt.$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "Die wilde Strömung in dieser Region hilft\n"
	.string "uns dabei, stärker denn je zu werden.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "Ich gebe meine Niederlage zu.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "Wir werden für weiteres Training nach\n"
	.string "METEORFÄLLE zurückkehren.\p"
	.string "Wenn du magst, komm doch auch mit.\n"
	.string "Das wird auch dich stärker machen!$"
