Route126_Text_BarryIntro:: @ 81C1590
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:: @ 81C15C3
	.string "I admit it! You win!$"

Route126_Text_BarryPostBattle:: @ 81C15D8
	.string "Thanks to my daily swimming routine...\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:: @ 81C1627
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:: @ 81C1660
	.string "I was done in?$"

Route126_Text_DeanPostBattle:: @ 81C166F
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:: @ 81C16AB
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:: @ 81C16C5
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub...$"

Route126_Text_NikkiPostBattle:: @ 81C1702
	.string "You thrashed me... I want to\n"
	.string "disappear in a wave of despair...$"

Route126_Text_BrendaIntro:: @ 81C1741
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:: @ 81C1766
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:: @ 81C1773
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"
