Route126_Text_BarryIntro:: @ 81C1590
	.string "Schwimmen verlangt vollen Körperein-\n"
	.string "satz. Und so wird man fit!$"

Route126_Text_BarryDefeat:: @ 81C15C3
	.string "Ich gebe es zu! Du hast gewonnen!$"

Route126_Text_BarryPostBattle:: @ 81C15D8
	.string "Dank meiner täglichen Schwimmrunden...\n"
	.string "Guck mal! Schau dir diesen Körperbau an!$"

Route126_Text_DeanIntro:: @ 81C1627
	.string "Dieser hohe weiße Berg dort ist\n"
	.string "XENEROVILLE.$"

Route126_Text_DeanDefeat:: @ 81C1660
	.string "Wie, das war's schon?$"

Route126_Text_DeanPostBattle:: @ 81C166F
	.string "Ich kann den Eingang zu XENEROVILLE\n"
	.string "nicht finden. Wo kann er sein?$"

Route126_Text_NikkiIntro:: @ 81C16AB
	.string "Hihihihihi!\n"
	.string "Ich bin eine Meerjungfrau!$"

Route126_Text_NikkiDefeat:: @ 81C16C5
	.string "Mein Traum platzt wie Seifenblasen!\n"
	.string "Plopp, plopp, plopp...$"

Route126_Text_NikkiPostBattle:: @ 81C1702
	.string "Du hast mich geschlagen... Ich möchte im\n"
	.string "Meer der Verzweiflung untergehen...$"

Route126_Text_BrendaIntro:: @ 81C1741
	.string "Hallo, Kindchen!\n"
	.string "Willst du gegen mich antreten?$"

Route126_Text_BrendaDefeat:: @ 81C1766
	.string "Oh, neeeiiin!$"

Route126_Text_BrendaPostBattle:: @ 81C1773
	.string "Ich liebe es, einfach so mit meinen \n"
	.string "POKéMON im Meer abzuhängen!$"
