Route104_Text_PlantBerriesInSoilTakeThis:: @ 81C55B9
	.string "Wenn du BEEREN siehst, die im Lehmboden\n"
	.string "wachsen, pflücke sie ruhig.\p"
	.string "Aber pflanze eine neue BEERE an der\n"
	.string "Stelle. Das ist einfache Höflichkeit.\p"
	.string "Hier, das ist für dich.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:: @ 81C5665
	.string "Du siehst aus wie ein TRAINER. Du\n"
	.string "bist auch einer, stimmt's?\p"
	.string "TRAINER geben ihren POKéMON manchmal\n"
	.string "BEEREN zu tragen.\p"
	.string "Es liegt an dir, ob du BEEREN pflanzt\n"
	.string "oder verwendest.$"
