Route104_Text_GinaIntro:: @ 81B83E9
	.string "GINA: Okay, dann lass uns mit unseren\n"
	.string "POKéMON kämpfen.$"

Route104_Text_GinaDefeat:: @ 81B8414
	.string "GINA: Wenn ich verliere, bin ich sauer.$"

Route104_Text_GinaPostBattle:: @ 81B842C
	.string "GINA: Du bist stark!\n"
	.string "Wir müssen doch mehr trainieren!$"

Route104_Text_GinaNotEnoughMons:: @ 81B845C
	.string "GINA: Oh, nur ein POKéMON?\n"
	.string "Dann können wir nicht kämpfen.\p"
	.string "Wenn du nur ein POKéMON hast, wird es\n"
	.string "sich einsam fühlen. Das ist nicht gut.$"

Route104_Text_MiaIntro:: @ 81B84DB
	.string "MIA: Wir sind Zwillinge und kämpfen auch\n"
	.string "mit unseren POKéMON zusammen.$"

Route104_Text_MiaDefeat:: @ 81B850D
	.string "MIA: Wir haben zusammen gekämpft und\n"
	.string "auch zusammen verloren.$"

Route104_Text_MiaPostBattle:: @ 81B853B
	.string "MIA: Wir werden unsere POKéMON\n"
	.string "trainieren. Und dann gewinnen wir!$"

Route104_Text_MiaNotEnoughMons:: @ 81B8577
	.string "MIA: Du willst gegen uns kämpfen?\p"
	.string "Ein dickes NEIN - da du weniger als zwei\n"
	.string "POKéMON bei dir hast. Wir sind zu\l"
	.string "stark für dich!$"

Route104_Text_IvanIntro:: @ 81B85EB
	.string "Warum soll ich ein Geheimnis daraus\n"
	.string "machen? Ich bin der...\p"
	.string "WASSER-POKéMON-Experte!\n"
	.string "Wie?!? Du kennst mich nicht?!?$"

Route104_Text_IvanDefeat:: @ 81B8637
	.string "Ich dachte, ich wäre gar nicht so\n"
	.string "schlecht. Aber... Ach, Mist...$"

Route104_Text_IvanPostBattle:: @ 81B8680
	.string "Über das Angeln habe ich glatt das\n"
	.string "Training meiner POKéMON vergessen.$"

Route104_Text_BillyIntro:: @ 81B86BE
	.string "Spuren im Sand zu hinterlassen ist total\n"
	.string "lustig!$"

Route104_Text_BillyDefeat:: @ 81B86E8
	.string "Igitt! Ich habe Sand in den Schuhen!\n"
	.string "Das ist vielleicht unangenehm!$"

Route104_Text_BillyPostBattle:: @ 81B871C
	.string "Ich will meine Fußspuren im Sand hinter-\n"
	.string "lassen, aber sie verschwinden viel zu\l"
	.string "schnell wieder...$"

Route104_Text_HaleyIntro:: @ 81B8770
	.string "Soll ich...\n"
	.string "Oder soll ich nicht?\p"
	.string "Okay, natürlich kämpfe ich!$"

Route104_Text_HaleyDefeat:: @ 81B87A7
	.string "Ich hätte doch nicht kämpfen sollen...$"

Route104_Text_HaleyPostBattle:: @ 81B87C3
	.string "Wenn du vor einer Entscheidung stehst\n"
	.string "und einen anderen für dich entscheiden\l"
	.string "lässt, wirst du es bereuen. Egal, was\l"
	.string "dabei am Ende herauskommt.$"

Route104_Text_HaleyRematchIntro:: @ 81B8839
	.string "Komm schon, kämpf mit mir!$"

Route104_Text_HaleyRematchDefeat:: @ 81B8852
	.string "Oohh...\n"
	.string "Ich dachte, ich könnte gewinnen...$"

Route104_Text_HaleyPostRematch:: @ 81B8872
	.string "Ich kann diesen Verlust der Würde\n"
	.string "akzeptieren. Doch, doch...\p"
	.string "Aber trotzdem bin ich stinkig deswegen.$"

Route104_Text_WinstonIntro:: @ 81B88D4
	.string "Oh, natürlich nehme ich die Heraus-\n"
	.string "forderung an! Ich habe eine Menge Geld.$"

Route104_Text_WinstonDefeat:: @ 81B8911
	.string "Warum konnte ich nicht gewinnen?$"

Route104_Text_WinstonPostBattle:: @ 81B8925
	.string "Manche Dinge kann man für Geld nicht\n"
	.string "kaufen. Das sind POKéMON...$"

Route104_Text_WinstonRematchIntro:: @ 81B895E
	.string "Nachdem ich gegen dich verloren hatte,\n"
	.string "habe ich viel über POKéMON gelernt.$"

Route104_Text_WinstonRematchDefeat:: @ 81B899E
	.string "Ich habe schon wieder verloren???\n"
	.string "Warum... kann... ich... nicht... gewinnen?$"

Route104_Text_WinstonPostRematch:: @ 81B89C0
	.string "Ich bin unsagbar reich, aber einen\n"
	.string "Kampf kann ich nicht gewinnen...\p"
	.string "Sie ist so tiefgründig, die Welt der\n"
	.string "POKéMON.$"

Route104_Text_CindyIntro:: @ 81B8A24
	.string "Das Schicksal hat uns zusammengeführt.\n"
	.string "Darf ich um einen Kampf bitten?$"

Route104_Text_CindyDefeat:: @ 81B8A61
	.string "Oh, meine Güte!$"

Route104_Text_CindyPostBattle:: @ 81B8A69
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl.”\l"
	.string "Ich hoffe, wir sehen uns wieder.$"
Route104_Text_CindyRematchIntro:: @ 81B8AA7
	.string "Hallo, so treffen wir uns wieder.\n"
	.string "Darf ich dich um einen Kampf bitten?$"

Route104_Text_CindyRematchDefeat:: @ 81B8AD9
	.string "Oh je...\n"
	.string "Ich habe mein Bestes gegeben...$"

Route104_Text_CindyPostRematch:: @ 81B8B02
	.string "“Hallo” ist der Anfang von\n"
	.string "“Leb wohl.”\l"
	.string "Ich hoffe, wir sehen uns wieder.$"
