MtChimney_Text_MaxieIntensifyVolcanoPlan:: @ 81B37BB
	.string "The power contained in the METEORITE...\p"
	.string "By amplifying its power with this\n"
	.string "machine, MT. CHIMNEY's volcanic activity\l"
	.string "will instantly intensify...\p"
	.string "Fufufu... The volcano will erupt, spewing\n"
	.string "lava that will cool and harden.\l"
	.string "It will expand the landmass...$"

MtChimney_Text_MaxieIntro:: @ 81B38B3
	.string "MAXIE: You again...\p"
	.string "Now listen.\n"
	.string "We humans have grown on dry land.\p"
	.string "The land is everything!\n"
	.string "Its importance is paramount!\p"
	.string "That is why we of TEAM MAGMA are\n"
	.string "committed to expanding the landmass.\p"
	.string "It will create space for new species\n"
	.string "of POKéMON to evolve.\p"
	.string "It will give us humans more space to\n"
	.string "advance.\p"
	.string "That is TEAM MAGMA's vision!\p"
	.string "I can't allow an ignorant child like\n"
	.string "you to get in our way.\p"
	.string "I, MAXIE, will show you the\n"
	.string "consequences of meddling!$"

MtChimney_Text_MaxieDefeat:: @ 81B3A68
	.string "What?!\p"
	.string "I, MAXIE, was caught off guard?!$"

MtChimney_Text_MaxieRetreat:: @ 81B3A90
	.string "MAXIE: Ah, whatever.\n"
	.string "I will give up our plans for MT. CHIMNEY\l"
	.string "for the time being...\p"
	.string "But no one can ever stop us!\n"
	.string "TEAM MAGMA will prevail!\p"
	.string "Don't you ever forget that!$"

MtChimney_Text_TabithaIntro:: @ 81B3B36
	.string "Hehehe!\p"
	.string "So you've come all the way here!\p"
	.string "But you're too late!\n"
	.string "I've already delivered the METEORITE\l"
	.string "from METEOR FALLS to the BOSS!$"

MtChimney_Text_TabithaDefeat:: @ 81B3BB8
	.string "Hehehe...\n"
	.string "So I lost...\p"
	.string "I'm sure glad I never took you on back\n"
	.string "at METEOR FALLS.$"

MtChimney_Text_TabithaPostBattle:: @ 81B3C07
	.string "Hehehe!\p"
	.string "You might have beaten me, but you don't\n"
	.string "stand a chance against the BOSS!\p"
	.string "If you get lost now, you won't have to\n"
	.string "face a sound whipping!$"

MtChimney_Text_MagmaGrunt2Intro:: @ 81B3C96
	.string "We of TEAM MAGMA are working hard for\n"
	.string "everyone's sake.\p"
	.string "Like, if there's more land, there'd be\n"
	.string "more places to live.\l"
	.string "Everyone'd be happy!$"

MtChimney_Text_MagmaGrunt2Defeat:: @ 81B3D1E
	.string "Hunh?\n"
	.string "What do you mean I lost?$"

MtChimney_Text_MagmaGrunt2PostBattle:: @ 81B3D3D
	.string "Our BOSS says, “It will make everyone\n"
	.string "happy.”\p"
	.string "But why does everyone keep getting\n"
	.string "in our way?$"

MtChimney_Text_MagmaGruntTeamAquaInterfering:: @ 81B3D9A
	.string "That annoying TEAM AQUA...\n"
	.string "They always mess with our plans!$"

MtChimney_Text_MagmaGruntMeteoritesPower: @ 81B3DD6
	.string "METEORITES pack amazing power!$"

MtChimney_Text_MagmaGruntExpandLand:: @ 81B3DF5
	.string "Go! Stomp TEAM AQUA!\n"
	.string "And expand the land!$"

MtChimney_Text_MagmaGruntEnlargeLand:: @ 81B3E1F
	.string "Stay out of our way, okay?\p"
	.string "We're trying to enlarge the landmass\n"
	.string "for the good of everybody!$"

MtChimney_Text_MagmaGruntDouseThemInFire:: @ 81B3E7A
	.string "Yeah!\n"
	.string "Douse them in fire!$"

MtChimney_Text_MagmaGruntKeepMakingLand: @ 81B3E94
	.string "We're going to keep making more land!$"

MtChimney_Text_MagmaPoochyena1Cry:: @ 81B3EBA
	.string "Bufoh!$"

MtChimney_Text_ArchieGoStopTeamMagma:: @ 81B3EC1
	.string "ARCHIE: Oh, {PLAYER}{KUN}!\p"
	.string "Please, you must stop TEAM MAGMA\n"
	.string "for me!\p"
	.string "They're trying to make this volcano\n"
	.string "erupt by using the stolen METEORITE's\l"
	.string "power!\p"
	.string "It's all a part of their plans to\n"
	.string "expand the world's landmass!$"

MtChimney_Text_ArchieIHaveMyHandsFull:: @ 81B3F8C
	.string "ARCHIE: {PLAYER}{KUN}!\p"
	.string "Please, you've got to stop TEAM MAGMA\n"
	.string "for me!\p"
	.string "Dealing with these three thugs is\n"
	.string "a lot, even for me!$"

MtChimney_Text_ArchieThankYou:: @ 81B3FFE
	.string "ARCHIE: {PLAYER}{KUN}! Thank you!\p"
	.string "With your help, we thwarted TEAM\n"
	.string "MAGMA's destructive plan!\p"
	.string "But... This victory doesn't mean the\n"
	.string "end of their evil plans.\p"
	.string "We will remain vigilant and keep up\n"
	.string "our pursuit of TEAM MAGMA.\p"
	.string "{PLAYER}{KUN}, we shall meet again!$"

MtChimney_Text_AquaGruntMagmaOutnumbersUs:: @ 81B40EA
	.string "Darn... TEAM MAGMA outnumbers us!\n"
	.string "We can't keep up with them!$"

MtChimney_Text_AquaGruntLessHabitatForWaterPokemon:: @ 81B4128
	.string "If they expand the land, there'll be\n"
	.string "less habitats for WATER POKéMON!$"

MtChimney_Text_AquaGruntMagmaPlanInsane:: @ 81B416E
	.string "TEAM MAGMA wants to expand the\n"
	.string "landmass... How's that for insane?$"

MtChimney_Text_AquaPoochyena2Cry:: @ 81B41B0
	.string "Bushaa!$"
