Route125_Text_CodyIntro:: @ 81C0FCF
	.string "Ich habe dich kommen hören und\n"
	.string "hier auf dich gewartet.$"

Route125_Text_CodyDefeat:: @ 81C1002
	.string "Ich bitte um Frieden!$"

Route125_Text_CodyPostBattle:: @ 81C1013
	.string "Der Schall bewegt sich im Wasser\n"
	.string "schneller als in der Luft.$"

Route125_Text_StanIntro:: @ 81C104B
	.string "Hey, du!\n"
	.string "Schau dir mein süßes POKéMON an!$"

Route125_Text_StanDefeat:: @ 81C1073
	.string "Da habe ich aber rumgewurstelt...$"

Route125_Text_StanPostBattle:: @ 81C1083
	.string "SEEPERS Charme hat mich gefangen, so\n"
	.string "habe ich angefangen zu schwimmen.$"

Route125_Text_TanyaIntro:: @ 81C10C3
	.string "Das Schwimmen hat mich ermüdet.\n"
	.string "Willst du mit mir kämpfen?$"

Route125_Text_TanyaDefeat:: @ 81C10FB
	.string "Du bist mir eine Nummer zu groß.$"

Route125_Text_TanyaPostBattle:: @ 81C110C
	.string "Huuh... Wo geht es denn hier\n"
	.string "nach MOOSBACH CITY?$"

Route125_Text_SharonIntro:: @ 81C1136
	.string "Wie willst du gegen meine WASSER-\n"
	.string "POKéMON ankommen?$"

Route125_Text_SharonDefeat:: @ 81C1175
	.string "Ich habe verloren...$"

Route125_Text_SharonPostBattle:: @ 81C117F
	.string "Deine Kraft... Absolut unglaublich.\n"
	.string "Ich bin begeistert!$"

Route125_Text_ErnestIntro:: @ 81C11AF
	.string "Ahoi! Ich bin ein raubeiniger MATROSE!\n"
	.string "Ich habe die Weltmeere umsegelt.$"

Route125_Text_ErnestDefeat:: @ 81C11ED
	.string "Grrrrooooaaar!\n"
	.string "Ich konnte unmöglich gewinnen!$"

Route125_Text_ErnestPostBattle:: @ 81C1208
	.string "Die Flut kommt und geht in der\n"
	.string "KÜSTENHÖHLE.\p"
	.string "Wusstest du eigentlich, dass zwischen\n"
	.string "Flut und Ebbe immer 6 Stunden liegen?$"

Route125_Text_ErnestRematchIntro:: @ 81C1282
	.string "Jetzt läuft die Flut ein und für dich ist\n"
	.string "Zahltag! Komm, wir kämpfen.$"

Route125_Text_ErnestRematchDefeat:: @ 81C12C5
	.string "Ich konnte nicht gewinnen!\n"
	.string "Die Flut hat mich davongetragen!$"

Route125_Text_ErnestRematchPostBattle:: @ 81C12EE
	.string "Die KÜSTENHÖHLE...\p"
	.string "Es gibt Orte, die sind mal erreichbar und\n"
	.string "mal nicht. Ganz abhängig von Ebbe\l"
	.string "und Flut.\p"
	.string "Übrigens: Vergiss nicht, dass zwischen\n"
	.string "Flut und Ebbe sechs Stunden liegen!$"

Route125_Text_KimIntro:: @ 81C13A1
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "KÜSTENHÖHLE. Das hat mir jemand\l"
	.string "erzählt. Willst du ihn auch besuchen?$"

Route125_Text_KimDefeat:: @ 81C13FF
	.string "ZOE: Ich dachte, wir könnten gewinnen.$"

Route125_Text_KimPostBattle:: @ 81C141C
	.string "ZOE: Ein lustiger alter Mann lebt in der\n"
	.string "KÜSTENHÖHLE, stimmt's?\p"
	.string "Komm, IRIS, wir besuchen ihn.$"

Route125_Text_KimNotEnoughMons:: @ 81C146E
	.string "ZOE: Nein, nein, nein! Du brauchst zwei\n"
	.string "POKéMON oder es funktioniert nicht!$"

Route125_Text_IrisIntro:: @ 81C14AB
	.string "IRIS: ZOE, kannst du mir verraten, was\n"
	.string "wir hier draußen überhaupt wollen?$"

Route125_Text_IrisDefeat:: @ 81C14E7
	.string "IRIS: Oh, wir waren so nah dran.$"

Route125_Text_IrisPostBattle:: @ 81C1508
	.string "IRIS: ZOE, gehen wir wirklich zur\n"
	.string "KÜSTENHÖHLE?\l"
	.string "Dann werden wir ja ganz nass.$"

Route125_Text_IrisNotEnoughMons:: @ 81C154F
	.string "IRIS: Oh, wir würden niemals einen\n"
	.string "2-gegen-1-Kampf ausfechten! Niemals!$"
