Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated. Let's battle!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here...\l"
	.string "I must be cursed...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "I've led a life of woe and misery...\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Another loss...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "A life adrift...\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "No! Please!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "A strong child TRAINER...\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "You...\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "I'd like to go back to FORTREE, but I've\n"
	.string "grown to like this place, too.$"
