Route116_Text_ClarkIntro:: @ 81BCF79
	.string "Wenn es keinen Tunnel gibt, dann\n"
	.string "klettere ich eben über den Berg.$"

Route116_Text_ClarkDefeat:: @ 81BCFBB
	.string "Hechel... Keuch...\n"
	.string "Verlieren erschöpft mich...$"

Route116_Text_ClarkPostBattle:: @ 81BCFE3
	.string "Macht auch nichts, wenn es keinen\n"
	.string "Tunnel gibt. Für WANDERER sind Berge\l"
	.string "wie Straßen.$"

Route116_Text_JoeyIntro:: @ 81BD02B
	.string "Meine POKéMON sind die Kings.\n"
	.string "Überzeug dich selbst!$"

Route116_Text_JoeyDefeat:: @ 81BD04C
	.string "Auaaa! Ein Kratzer!\n"
	.string "Ich brauche dringend einen Verband.$"

Route116_Text_JoeyPostBattle:: @ 81BD078
	.string "Verbände sind Zeichen von Rauheit!\n"
	.string "Ich brauche unbedingt einen weiteren!$"

Route116_Text_JoseIntro:: @ 81BD0AF
	.string "Meine KÄFER-POKéMON sind stark!\n"
	.string "Lass uns kämpfen!$"

Route116_Text_JoseDefeat:: @ 81BD0D7
	.string "Ich habe verloren! Ich dachte,\n"
	.string "ich könnte dich am Kragen packen...$"

Route116_Text_JosePostBattle:: @ 81BD0F4
	.string "KÄFER-POKéMON entwickeln sich schnell.\n"
	.string "So werden sie auch schnell stark.$"

Route116_Text_JaniceIntro:: @ 81BD131
	.string "Ich bringe dir bei, wie stark mein\n"
	.string "geliebtes POKéMON ist!$"

Route116_Text_JaniceDefeat:: @ 81BD165
	.string "Du bist mir haushoch überlegen...$"

Route116_Text_JanicePostBattle:: @ 81BD180
	.string "POKéMON, die Anmut und Stärke besitzen,\n"
	.string "sind ideal, finde ich.$"

Route116_Text_JerryIntro:: @ 81BD1C0
	.string "Wir lernen alle möglichen Sachen in der\n"
	.string "TRAINERSCHULE.\p"
	.string "Ich will einiges jetzt mal ausprobieren.$"

Route116_Text_JerryDefeat:: @ 81BD21A
	.string "Ich habe in der Schule nicht aufge-\n"
	.string "passt. Daher habe ich verloren.$"

Route116_Text_JerryPostBattle:: @ 81BD248
	.string "Ich muss einige Kurse in der TRAINER-\n"
	.string "SCHULE wiederholen.\l"
	.string "Sonst wird FELIZIA vor Wut schäumen.$"

Route116_Text_JerryRematchIntro:: @ 81BD2A5
	.string "Ich habe in der TRAINERSCHULE fleißig\n"
	.string "gelernt. Ich werde dieses Mal also mit\l"
	.string "Sicherheit nicht verlieren.$"

Route116_Text_JerryRematchDefeat:: @ 81BD2FE
	.string "Waaas?\n"
	.string "Aber ich habe doch so fleißig gelernt!$"

Route116_Text_JerryPostRematch:: @ 81BD31A
	.string "Ich muss wohl erneut einige Kurse in der\n"
	.string "TRAINERSCHULE wiederholen.\l"
	.string "Sonst kocht FELIZIA über.$"

Route116_Text_KarenIntro:: @ 81BD377
	.string "Ich lerne in der Schule und auf dem\n"
	.string "Heimweg lerne ich auch!$"

Route116_Text_KarenDefeat:: @ 81BD3AC
	.string "Ich bin geschockt! Ich habe verloren?!?$"

Route116_Text_KarenPostBattle:: @ 81BD3C3
	.string "Argh, so werde ich nie so ein eleganter\n"
	.string "TRAINER wie FELIZIA!$"

Route116_Text_KarenRematchIntro:: @ 81BD405
	.string "Seit unserem letzten Kampf habe ich\n"
	.string "viel gelernt. Das musst du dir ansehen!$"

Route116_Text_KarenRematchDefeat:: @ 81BD44A
	.string "Ach, das gibt es doch nicht...$"

Route116_Text_KarenPostRematch:: @ 81BD466
	.string "Du hast FELIZIA besiegt?!?\n"
	.string "Dann kann ich dich nicht besiegen. Nee...$"
