SootopolisCity_Gym_1F_Text_GymGuideAdvice:: @ 818E8A5
	.string "Na, wie sieht es aus, auf dem Weg zum\n"
	.string "CHAMP, {PLAYER}?\p"
	.string "ARENALEITER WASSILI in XENEROVILLE\n"
	.string "ist der Meister der WASSER-POKéMON.\p"
	.string "Und auf dem Weg zu ihm wirst du auf\n"
	.string "gefrorenem Boden ins Rutschen kommen.\p"
	.string "Tut mir Leid, aber mehr kann ich dir dazu\n"
	.string "auch nicht sagen.\p"
	.string "Den Rest des Weges musst du alleine\n"
	.string "meistern.$"

SootopolisCity_Gym_1F_Text_GymGuidePostVictory:: @ 818E9C9
	.string "Hui! Du hast WASSILI besiegt, von dem\n"
	.string "man sagt, er sei der beste TRAINER in\l"
	.string "der HOENN-Region.\p"
	.string "Okay! Schau auf deinem\n"
	.string "TRAINERPASS nach.\p"
	.string "Wenn du alle ORDEN erhalten hast,\n"
	.string "kannst du die POKéMON LIGA\l"
	.string "herausfordern!$"

.include "data/maps/SootopolisCity_Gym_B1F/trainer_text.inc"

SootopolisCity_Gym_1F_Text_WallaceIntro:: @ 818F0CA
	.string "Erlaube mir, mich kurz vorzustellen.\p"
	.string "Ich bin WASSILI.\n"
	.string "Der ARENALEITER von XENEROVILLE.\p"
	.string "Irgendetwas fällt mir an dir auf...\n"
	.string "Da ist etwas in deinem Auftreten...\p"
	.string "Ich denke, ich spüre etwas in dir.\p"
	.string "Das, was in der URZEITHÖHLE\n"
	.string "passierte und was du getan hast, all das\l"
	.string "werde ich im Kampf mit dir lesen können.\p"
	.string "Gib mir die Gelegenheit dazu. Zeig mir,\n"
	.string "wie du deine POKéMON im Kampf führst.\p"
	.string "Und als Gegenleistung zeige ich dir eine\n"
	.string "Illusion im Wasser. Dargeboten von mir\l"
	.string "und meinen POKéMON.$"

SootopolisCity_Gym_1F_Text_WallaceDefeat:: @ 818F282
	.string "Bravo.\p"
	.string "Jetzt erkenne ich, welch ein groß-\n"
	.string "artiger POKéMON-TRAINER vor mir steht.\p"
	.string "Es hat mir viel Freude gemacht, dich und\n"
	.string "deine POKéMON kennen gelernt zu haben.\p"
	.string "Du verdienst zu Recht den\n"
	.string "SCHAUERORDEN. Bitte nimm ihn an.$"

SootopolisCity_Gym_1F_Text_ReceivedRainBadge:: @ 818F342
	.string "{PLAYER} erhält den SCHAUERORDEN\n"
	.string "von WASSILI.$"

SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis:: @ 818F36B
	.string "Dieser ORDEN sorgt dafür, dass dir alle\n"
	.string "deine POKéMON gehorchen.\p"
	.string "Der ORDEN befähigt dich außerdem dazu,\n"
	.string "mit der VM KASKADE Wasserfälle in jede\l"
	.string "Richtung zu passieren.\p"
	.string "Und damit du unseren Kampf stets in\n"
	.string "Erinnerung behältst, gebe ich dir dies...$"

SootopolisCity_Gym_1F_Text_ExplainWaterPulse:: @ 818F466
	.string "Diese TM enthält AQUAWELLE.\p"
	.string "Damit kann das gegnerische POKéMON\n"
	.string "mit Ultraschallwellen verwirrt werden.$"

SootopolisCity_Gym_1F_Text_WallacePostBattle:: @ 818F4D7
	.string "TRAINER, die alle ORDEN der ARENEN in\n"
	.string "HOENN erhalten haben, sollten sich...\p"
	.string "Auf den Weg zur ultimativen Heraus-\n"
	.string "forderung machen. Der POKéMON LIGA!\p"
	.string "Reise zu den östlichsten Gebieten von\n"
	.string "HOENN, zur Insel PRACHTPOLIS CITY. Dort\l"
	.string "findest du die POKéMON LIGA.$"

SootopolisCity_Gym_1F_Text_GoGetFortreeBadge:: @ 818F5B4
	.string "In HOENN gibt es nur noch einen ORDEN\n"
	.string "zu verdienen.\p"
	.string "Wenn du die POKéMON LIGA herausfordern\n"
	.string "willst, musst du zuerst den ORDEN der\l"
	.string "ARENA in BAUMHAUSEN CITY bekommen.$"

SootopolisCity_Gym_1F_Text_GymStatue:: @ 818F649
	.string "POKéMON ARENA von XENEROVILLE$"

SootopolisCity_Gym_1F_Text_GymStatueCertified:: @ 818F665
	.string "POKéMON ARENA von XENEROVILLE\p"
	.string "WASSILIS ANERKANNTE TRAINER:\n"
	.string "{PLAYER}$"
