SSTidalLowerDeck_Text_PhillipIntro:: @ 81993C1
	.string "Arrrgh! I'm fed up and dog-tired of\n"
	.string "cleaning this huge place!\p"
	.string "Let's have a quick battle!$"

SSTidalLowerDeck_Text_PhillipDefeat:: @ 819941A
	.string "Little bro, I lost!$"

SSTidalLowerDeck_Text_PhillipPostBattle:: @ 819942E
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent,\n"
	.string "and the young one does the scrubbing!$"

SSTidalLowerDeck_Text_LeonardIntro:: @ 8199491
	.string "This is the bottom of the ship's hull.\n"
	.string "There's plenty of room.\l"
	.string "It'll be alright for a POKéMON battle.$"

SSTidalLowerDeck_Text_LeonardDefeat:: @ 81994F7
	.string "Big bro, I lost!$"

SSTidalLowerDeck_Text_LeonardPostBattle:: @ 8199508
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent,\n"
	.string "and the young one does the scrubbing!$"
