SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage:: @ 8199007
	.string "This ferry is built to plow through\n"
	.string "fast-running currents.\p"
	.string "We hope you enjoy your voyage with us.\n"
	.string "Feel free to explore the ship.$"

SSTidal_Text_HopeYouEnjoyVoyage:: @ 8199088
	.string "We hope you enjoy your voyage on\n"
	.string "our ferry.$"

SSTidal_Text_MadeLandInSlateport:: @ 81990B4
	.string "We have made land in SLATEPORT CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidal_Text_MadeLandInLilycove:: @ 81990F8
	.string "We have made land in LILYCOVE CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidalCorridor_Text_CanRestInCabin2:: @ 819913B
	.string "It'll be some time before we make land,\n"
	.string "I reckon.\p"
	.string "You can rest up in your cabin if you'd\n"
	.string "like. Your cabin's No. 2.\p"
	.string "The bed in there is soft and plushy.\n"
	.string "I can attest to how comfy it is!$"

SSTidalCorridor_Text_WeveArrived:: @ 81991F4
	.string "We've arrived!$"

SSTidalCorridor_Text_VisitOtherCabins:: @ 8199203
	.string "Go visit other cabins.\n"
	.string "TRAINERS bored of the boat trip will\l"
	.string "be itching to battle.$"

SSTidalCorridor_Text_EnjoyYourCruise:: @ 8199255
	.string "Enjoy your cruise!$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole:: @ 8199268
	.string "The horizon spreads beyond the\n"
	.string "porthole.$"

SSTidalCorridor_Text_BrineyWelcomeAboard:: @ 8199291
	.string "MR. BRINEY: Welcome aboard, {PLAYER}{KUN}!\p"
	.string "They made me honorary captain of the\n"
	.string "S.S. TIDAL!\p"
	.string "You can call me CAPTAIN BRINEY now!\p"
	.string "You know, I retired once before, but\n"
	.string "when I saw this majestic ship...\p"
	.string "Let me just say, it stirred my sleeping\n"
	.string "soul as a sailor!$"

SSTidalCorridor_Text_Peeko:: @ 8199388
	.string "PEEKO: Pihyo pihyohyo...$"

SSTidalCorridor_Text_Cabin1:: @ 81993A1
	.string "Cabin 1$"

SSTidalCorridor_Text_Cabin2:: @ 81993A9
	.string "Cabin 2$"

SSTidalCorridor_Text_Cabin3:: @ 81993B1
	.string "Cabin 3$"

SSTidalCorridor_Text_Cabin4:: @ 81993B9
	.string "Cabin 4$"
