MtPyre_3F_Text_WilliamIntro:: @ 819672B
	.string "The rich atmosphere of the mountain\n"
	.string "has elevated my psychic power!\p"
	.string "A mere child like you...\n"
	.string "You dream of winning?$"

MtPyre_3F_Text_WilliamDefeat:: @ 819679D
	.string "I drown in self-pity...$"

MtPyre_3F_Text_WilliamPostBattle:: @ 81967B5
	.string "My psychic powers have surely\n"
	.string "grown several times, but...$"

MtPyre_3F_Text_KaylaIntro:: @ 81967EF
	.string "Ahahahaha!\p"
	.string "This is no place for children, least\n"
	.string "of all you!$"

MtPyre_3F_Text_KaylaDefeat:: @ 819682B
	.string "I lost that cleanly...$"

MtPyre_3F_Text_KaylaPostBattle:: @ 8196842
	.string "This means my training is still not\n"
	.string "enough...\p"
	.string "I've got to keep working toward the\n"
	.string "summit...\p"
	.string "Go, me!$"
