Route116_Text_ClarkIntro:: @ 81BCF79
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go over the top.$"

Route116_Text_ClarkDefeat:: @ 81BCFBB
	.string "Gasp... Gasp...\n"
	.string "Losing made me tired...$"

Route116_Text_ClarkPostBattle:: @ 81BCFE3
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_JoeyIntro:: @ 81BD02B
	.string "My POKéMON rule!\n"
	.string "Check them out!$"

Route116_Text_JoeyDefeat:: @ 81BD04C
	.string "Ouch! A scrape!\n"
	.string "I have to put on a bandage!$"

Route116_Text_JoeyPostBattle:: @ 81BD078
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_JoseIntro:: @ 81BD0AF
	.string "My BUG POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:: @ 81BD0D7
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_JosePostBattle:: @ 81BD0F4
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_JaniceIntro:: @ 81BD131
	.string "Let me teach you how strong my\n"
	.string "adorable POKéMON is!$"

Route116_Text_JaniceDefeat:: @ 81BD165
	.string "You're a notch above me...$"

Route116_Text_JanicePostBattle:: @ 81BD180
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_JerryIntro:: @ 81BD1C0
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test things out for real!$"

Route116_Text_JerryDefeat:: @ 81BD21A
	.string "I slacked off in school...\n"
	.string "That's why I lost.$"

Route116_Text_JerryPostBattle:: @ 81BD248
	.string "I'll have to redo some courses at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_JerryRematchIntro:: @ 81BD2A5
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:: @ 81BD2FE
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch:: @ 81BD31A
	.string "I'll have to redo some courses at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:: @ 81BD377
	.string "I study at school, and I study on the\n"
	.string "way home, too!$"

Route116_Text_KarenDefeat:: @ 81BD3AC
	.string "I'm in shock - I lost?$"

Route116_Text_KarenPostBattle:: @ 81BD3C3
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_KarenRematchIntro:: @ 81BD405
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat:: @ 81BD44A
	.string "I'm in shock. I lost again?$"

Route116_Text_KarenPostRematch:: @ 81BD466
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"
