SeafloorCavern_Room1_Text_EvilTeamGrunt1Intro:: @ 81974BA
	.string "We don't need a kid around!\n"
	.string "Go on home already!$"

SeafloorCavern_Room1_Text_EvilTeamGrunt1Defeat:: @ 81974EA
	.string "I want to go home...$"

SeafloorCavern_Room1_Text_EvilTeamGrunt1PostBattle:: @ 81974FF
	.string "I want to get a promotion so I can\n"
	.string "boss around the GRUNTS...$"

SeafloorCavern_Room1_Text_EvilTeamGrunt2Intro:: @ 819753C
	.string "That submarine... It's tiny inside.\n"
	.string "I'm sore all over!$"

SeafloorCavern_Room1_Text_EvilTeamGrunt2Defeat:: @ 8197573
	.string "Losing makes me sore!$"

SeafloorCavern_Room1_Text_EvilTeamGrunt2PostBattle:: @ 8197589
	.string "That submarine we jacked, man, it's\n"
	.string "brutal as a ride.\l"
	.string "It's way too tight in there!$"
