#ifndef GUARD_CONSTANTS_CABLE_CLUB_H
#define GUARD_CONSTANTS_CABLE_CLUB_H

// States for VAR_CABLE_CLUB_STATE
#define USING_SINGLE_BATTLE  1
#define USING_DOUBLE_BATTLE  2
#define USING_TRADE_CENTER   3
#define USING_RECORD_CORNER  4
#define USING_MULTI_BATTLE   5

// Return states for Ruby/Sapphire's wired Cable Club linkup specials.
#define LINKUP_ONGOING           0
#define LINKUP_SUCCESS           1
#define LINKUP_SOMEONE_NOT_READY 2
#define LINKUP_DIFF_SELECTIONS   3
#define LINKUP_WRONG_NUM_PLAYERS 4
#define LINKUP_FAILED            5
#define LINKUP_CONNECTION_ERROR  6
#define LINKUP_FOREIGN_GAME      7

#endif // GUARD_CONSTANTS_CABLE_CLUB_H
