#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

// PC Locations
#define PC_LOCATION_OTHER           0
#define PC_LOCATION_BRENDANS_HOUSE  1
#define PC_LOCATION_MAYS_HOUSE      2

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
