#ifndef GUARD_CONSTANTS_FIELD_SPECIALS_H
#define GUARD_CONSTANTS_FIELD_SPECIALS_H

// S.S. Tidal locations
#define SS_TIDAL_LOCATION_CURRENTS  0
#define SS_TIDAL_LOCATION_SLATEPORT 1
#define SS_TIDAL_LOCATION_LILYCOVE  2
#define SS_TIDAL_LOCATION_ROUTE124  3
#define SS_TIDAL_LOCATION_ROUTE131  4

// S.S. Tidal cruise states
#define SS_TIDAL_BOARD_SLATEPORT     1
#define SS_TIDAL_DEPART_SLATEPORT    2
#define SS_TIDAL_HALFWAY_LILYCOVE    3
#define SS_TIDAL_LAND_LILYCOVE       4
#define SS_TIDAL_BOARD_LILYCOVE      5
#define SS_TIDAL_DEPART_LILYCOVE     6
#define SS_TIDAL_HALFWAY_SLATEPORT   7
#define SS_TIDAL_LAND_SLATEPORT      8
#define SS_TIDAL_EXIT_CURRENTS_RIGHT 9
#define SS_TIDAL_EXIT_CURRENTS_LEFT  10

#define SS_TIDAL_MAX_STEPS 205

#endif // GUARD_CONSTANTS_FIELD_SPECIALS_H
