#ifndef GUARD_CONSTANTS_TRADE_H
#define GUARD_CONSTANTS_TRADE_H

// In-game Trade IDs
#define INGAME_TRADE_MAKUHITA 0
#define INGAME_TRADE_SKITTY   1
#define INGAME_TRADE_CORSOLA  2

#endif // GUARD_CONSTANTS_TRADE_H
