Route115_Text_NeverKnowWhenCavePokemonWillAppear:: @ 8170273
	.string "Exploring a cave isn't like walking\n"
	.string "on a road.\p"
	.string "You never know when wild POKéMON will\n"
	.string "appear. It's full of suspense.$"

Route115_Text_RouteSignRustboro:: @ 81702E7
	.string "ROUTE 115\n"
	.string "{0x7A} RUSTBORO CITY$"

Route115_Text_MeteorFallsSign:: @ 8170301
	.string "METEOR FALLS\n"
	.string "FALLARBOR TOWN THROUGH HERE$"
