Route115_Text_TimothyIntro:: @ 81BC9AC
	.string "Hm...\n"
	.string "You seem rather capable...\l"
	.string "Let me keep you company!$"

Route115_Text_TimothyDefeat:: @ 81BC9E6
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_TimothyPostBattle:: @ 81BCA0E
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe...$"

Route115_Text_TimothyRematchIntro:: @ 81BCA6B
	.string "Hm... As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:: @ 81BCAB3
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch:: @ 81BCAC6
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:: @ 81BCB0D
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a battle!$"

Route115_Text_KoichiDefeat:: @ 81BCB2E
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:: @ 81BCB40
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_NobIntro:: @ 81BCB8A
	.string "My strongest skill is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_NobDefeat:: @ 81BCBC1
	.string "Ugwaaaah!\n"
	.string "My head is busted!$"

Route115_Text_NobPostBattle:: @ 81BCBDE
	.string "I've been teaching my POKéMON karate.\p"
	.string "It looks like they'll get a lot better\n"
	.string "than me. I'm excited about that.$"

Route115_Text_NobRematchIntro:: @ 81BCC4C
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat:: @ 81BCCA2
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_NobPostRematch:: @ 81BCCBA
	.string "My POKéMON will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_CyndyIntro:: @ 81BCCF4
	.string "This beach is my secret training spot!\n"
	.string "Don't come butting in!$"

Route115_Text_CyndyDefeat:: @ 81BCD32
	.string "I haven't trained enough!$"

Route115_Text_CyndyPostBattle:: @ 81BCD4C
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_CyndyRematchIntro:: @ 81BCDB0
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:: @ 81BCDD0
	.string "I can battle but my POKéMON...$"

Route115_Text_CyndyPostRematch:: @ 81BCDEF
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love POKéMON.$"

Route115_Text_HectorSapphireIntro: @ 81BCE47
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorSapphireDefeat: @ 81BCE7D
	.string "You...\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_HectorSapphirePostBattle: @ 81BCEA4
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_HectorIntro:: @ 81BCEE0
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorDefeat:: @ 81BCF16
	.string "You...\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_HectorPostBattle:: @ 81BCF3D
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"
