Route111_Text_BattleOurFamily:: @ 816F705
	.string "Hallo! Ich hab's, du bist ein Reisender.\p"
	.string "Was hältst du davon? Du trittst mit\n"
	.string "deinen POKéMON gegen alle vier Familien-\l"
	.string "mitglieder hintereinander an?$"

Route111_Text_IsThatSo:: @ 816F785
	.string "Ach, wirklich? Nun, wenn du deine\n"
	.string "Meinung änderst, komm einfach wieder.$"

Route111_Text_VictorIntro:: @ 816F7B3
	.string "Das nenne ich Kampfgeist! Ich mag dich!$"

Route111_Text_VictorDefeat:: @ 816F7D2
	.string "Aiyah!\n"
	.string "Du bist stärker, als ich dachte.$"

Route111_Text_VictorPostBattle:: @ 816F7FF
	.string "Hey, ihr! Ich habe einen starken\n"
	.string "TRAINER gefunden!$"

Route111_Text_VictoriaIntro:: @ 816F82D
	.string "Oh, du meine Güte! Bist du jung!\p"
	.string "Du musst ein sehr guter TRAINER sein,\n"
	.string "wenn du meinen Mann besiegen konntest.\p"
	.string "Nun bin ich an der Reihe.$"

Route111_Text_VictoriaDefeat:: @ 816F8A6
	.string "Ach, nein! Ich komme nicht darüber\n"
	.string "hinweg, wie stark du bist!$"

Route111_Text_VictoriaPostBattle:: @ 816F8D5
	.string "Hier draußen ist ein starker TRAINER!\n"
	.string "Ein wirklich starker, sage ich euch!$"

Route111_Text_ViviIntro:: @ 816F90E
	.string "Du bist stärker als Mami? Wow!\p"
	.string "Aber ich bin auch stark!\n"
	.string "Wirklich! Ganz ehrlich!$"

Route111_Text_ViviDefeat:: @ 816F956
	.string "Was? Habe ich verloren?$"

Route111_Text_ViviPostBattle:: @ 816F96C
	.string "Das ist gemein...\p"
	.string "...Schluchz... Heul... Omaaaaa... Schluchz...$"

Route111_Text_VickyIntro:: @ 816F991
	.string "Wie konntest du nur meine Enkelin zum\n"
	.string "Weinen bringen? Schäm dich!\p"
	.string "Dafür werde ich dich in Grund und Boden\n"
	.string "stampfen. Mach dich auf was gefasst!$"

Route111_Text_VickyDefeat:: @ 816F9EC
	.string "Uaah! Du bist stark...\n"
	.string "Meine Enkelin hatte Recht...$"

Route111_Text_VickyPostBattle:: @ 816FA22
	.string "Wenn du es nicht allzu eilig hast,\n"
	.string "besuche uns doch mal wieder!$"

Route111_Text_RootFossil:: @ 816FA54
	.string "Du hast das WURZELFOSSIL gefunden.\p"
	.string "Wenn du dieses FOSSIL nimmst,\n"
	.string "versinkt das andere im Sand...\p"
	.string "Willst du das WURZELFOSSIL nehmen?$"

Route111_Text_LeaveRootFossil:: @ 816FACE
	.string "{PLAYER} lässt das WURZELFOSSIL liegen.$"

Route111_Text_ClawFossil:: @ 816FAED
	.string "Du hast das KLAUENFOSSIL gefunden.\p"
	.string "Wenn du dieses FOSSIL nimmst,\n"
	.string "versinkt das andere im Sand...\p"
	.string "Willst du das KLAUENFOSSIL nehmen?$"

Route111_Text_LeaveClawFossil:: @ 816FB67
	.string "{PLAYER} lässt das KLAUENFOSSIL liegen.$"

Route111_Text_ToughToKeepWinningUpTheRanks:: @ 816FB86
	.string "Wenn du deine POKéMON nicht ein\n"
	.string "bisschen besser trainierst, wird es\l"
	.string "schwer, sich hier durchzukämpfen.\p"
	.string "Ich habe gehört, dass die TOP VIER der\n"
	.string "POKéMON LIGA um einiges schwerer zu\l"
	.string "besiegen sind als die ARENALEITER.$"

Route111_Text_WinstrateFamilyDestroyedMe:: @ 816FC3A
	.string "Ich habe die Familie SIHGERS heraus-\n"
	.string "gefordert und viermal hintereinander\l"
	.string "gekämpft... Hinterher war ich kaputt...$"

Route111_Text_RouteSignMauville:: @ 816FC9C
	.string "ROUTE 111\n"
	.string "{DOWN_ARROW} MALVENFROH CITY$"

Route111_Text_WinstrateHouseSign:: @ 816FCB6
	.string "“Die Herzen unserer Familie schlagen im\n"
	.string "Einklang!”\l"
	.string "DAS HAUS DER SIHGERS$"

Route111_Text_RouteSign112:: @ 816FCEF
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 112$"

Route111_Text_RouteSign113:: @ 816FD05
	.string "ROUTE 111\n"
	.string "{LEFT_ARROW} ROUTE 113$"

Route111_Text_OldLadysRestStopSign:: @ 816FD1B
	.string "HOTEL DER ALTEN DAME\n"
	.string "“Komm, ruh deine müden Knochen aus.”$"

Route111_Text_TrainerTipsSpAtkSpDef:: @ 816FD55
	.string "TIPPS für TRAINER\p"
	.string "Ein Indikator für die Stärke eines\n"
	.string "POKéMON ist der SP. ANG. Das steht\l"
	.string "für “SPEZIAL ANGRIFF”.\p"
	.string "SP. VER. steht für “SPEZIAL\n"
	.string "VERTEIDIGUNG”.$"
