.include "data/maps/Route110/trainer_text.inc"

Route111_Text_DrewIntro:: @ 81BAB4B
	.string "Das WÜSTENGLAS steht dir gut. Aber\n"
	.string "ich bin sicher, mir steht es besser!\p"
	.string "Wir entscheiden das besser in einem\n"
	.string "Kampf!$"

Route111_Text_DrewDefeat:: @ 81BABC7
	.string "Das WÜSTENGLAS hat meine Sicht\n"
	.string "eingeschränkt.$"

Route111_Text_DrewPostBattle:: @ 81BAC10
	.string "Mit dem WÜSTENGLAS kann man durch\n"
	.string "Sandstürme laufen.\l"
	.string "Das macht mich richtig glücklich.$"

Route111_Text_HeidiIntro:: @ 81BAC60
	.string "Ich mache ein Picknick in der Wüste.\p"
	.string "Hier findet man überall TRAINER und so\n"
	.string "kann ich hier auch Kämpfe genießen.$"

Route111_Text_HeidiDefeat:: @ 81BACC5
	.string "Oooh, du bist so gemein!$"

Route111_Text_HeidiPostBattle:: @ 81BACD8
	.string "Wenn du in einem Sandsturm kämpfst,\n"
	.string "achte auf die KP deiner POKéMON.\p"
	.string "Sie können vom Sandsturm verletzt\n"
	.string "werden und KP verlieren.$"

Route111_Text_CliffIntro:: @ 81BAD4B
	.string "Mit diesem WÜSTENGLAS fühle ich mich\n"
	.string "wie ein Superheld. Im Moment kann\l"
	.string "mich einfach niemand besiegen!$"

Route111_Text_CliffDefeat:: @ 81BADA3
	.string "Ich kann doch nicht nur im Geiste\n"
	.string "gewinnen...$"

Route111_Text_CliffPostBattle:: @ 81BADC2
	.string "Eines Tages werde ich ein echter Held\n"
	.string "sein. Ich arbeite daran, mich und meine\l"
	.string "POKéMON richtig stark zu machen.$"

Route111_Text_BeckyIntro:: @ 81BAE24
	.string "Ich habe gehört, dass man in der Wüste\n"
	.string "Fossilien finden kann. Aber wo?$"

Route111_Text_BeckyDefeat:: @ 81BAE6E
	.string "Ich war in Gedanken bei den Fossilien...$"

Route111_Text_BeckyPostBattle:: @ 81BAE81
	.string "Da man in der Wüste Fossilien finden\n"
	.string "kann, war hier früher sicher ein Meer...$"

Route111_Text_DustyIntro:: @ 81BAEC9
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\l"
	.string "Werde ich jetzt herausgefordert?$"

Route111_Text_DustyDefeat:: @ 81BAF14
	.string "Ich habe nach Ruinen, aber leider nicht\n"
	.string "nach starken POKéMON gesucht...$"

Route111_Text_DustyPostBattle:: @ 81BAF5B
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Nee, warte... Seit 40 Jahren, oder? Oder\n"
	.string "doch 30 Jahre? Ach, ich weiß nicht...$"

Route111_Text_DustyRematchIntro:: @ 81BAFC1
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Oder seit 40 Jahren???\n"
	.string "Egal! Forderst du mich heraus?$"

Route111_Text_DustyRematchDefeat:: @ 81BB034
	.string "Ich habe keine Ruinen, und auch keine\n"
	.string "starken POKéMON gefunden...$"

Route111_Text_DustyPostRematch:: @ 81BB070
	.string "Seit 30 Jahren suche ich nach antiken\n"
	.string "Ruinen!\p"
	.string "Glaube ich... Es können auch schon\n"
	.string "40 Jahre sein...\p"
	.string "Hmm... Andererseits kämen 50 Jahre auch\n"
	.string "hin... Mein Gedächtnis ist eine Ruine...$"

Route111_Text_TravisIntro:: @ 81BB111
	.string "Ich bin voller Schwung und Elan!\n"
	.string "Und mein POKéMON nicht minder!$"

Route111_Text_TravisDefeat:: @ 81BB140
	.string "Mein POKéMON hat ausgeschwungen.$"

Route111_Text_TravisPostBattle:: @ 81BB15B
	.string "Wenn ich einen TRAINER mit Schwung und\n"
	.string "Elan sehe, muss ich ihn anstarren.$"

Route111_Text_IreneIntro:: @ 81BB199
	.string "Ich weiß ja nicht, wo du hin willst, aber\n"
	.string "was sagst du zu einem Kämpfchen?$"

Route111_Text_IreneDefeat:: @ 81BB1D8
	.string "Hui, du bist außergewöhnlich gut!$"

Route111_Text_IrenePostBattle:: @ 81BB1F6
	.string "Ich denke, ich sollte zum SCHLOTBERG\n"
	.string "gehen, aber hier ist es sooo schön...$"

Route111_Text_DaisukeIntro:: @ 81BB250
	.string "Ich trainiere ganz individuell: Ich for-\n"
	.string "dere alle TRAINER, die ich sehe, heraus.$"

Route111_Text_DaisukeDefeat:: @ 81BB27E
	.string "Ich gebe auf! Ich gebe auf!$"

Route111_Text_DaisukePostBattle:: @ 81BB290
	.string "Alles was ich tun kann, ist weiter\n"
	.string "trainieren, bis ich starke TRAINER wie\l"
	.string "dich besiegen kann.$"

Route111_Text_WiltonIntro:: @ 81BB2E3
	.string "Zeig mir, wie stark deine POKéMON\n"
	.string "geworden sind.$"

Route111_Text_WiltonDefeat:: @ 81BB313
	.string "Ich habe es zu spüren bekommen. Deine\n"
	.string "POKéMON sind viel stärker geworden.$"

Route111_Text_WiltonPostBattle:: @ 81BB33E
	.string "POKéMON und TRAINER lernen durch\n"
	.string "Kämpfe sehr viel.\p"
	.string "Wichtig ist, niemals aufzugeben, auch\n"
	.string "wenn du verlierst.$"

Route111_Text_WiltonRematchIntro:: @ 81BB3A7
	.string "Wir trainieren hier, um im Spiel einen\n"
	.string "Level weiterzukommen.\l"
	.string "Bleib hier und trainiere mit uns!$"

Route111_Text_WiltonRematchDefeat:: @ 81BB3FA
	.string "Ooh, du bist unglaublich!$"

Route111_Text_WiltonPostRematch:: @ 81BB40E
	.string "Da du so stark bist, solltest du dir die\n"
	.string "POKéMON LIGA zum Ziel setzen.$"

Route111_Text_BrookeIntro:: @ 81BB44F
	.string "Oh, deine POKéMON machen den Eindruck\n"
	.string "ernsthafter Schauspieler.\l"
	.string "Ich möchte sie gerne engagieren.$"

Route111_Text_BrookeDefeat:: @ 81BB49F
	.string "Sie sehen nicht nur stark aus, sie sind\n"
	.string "auch stark.$"

Route111_Text_BrookePostBattle:: @ 81BB4CE
	.string "Ich war überzeugt, meine POKéMON sorg-\n"
	.string "fältig aufgezogen zu haben. Aber nein,\l"
	.string "ich muss mich noch mehr anstrengen.$"

Route111_Text_BrookeRematchIntro:: @ 81BB529
	.string "Abhängig von den Attacken, die du ihnen\n"
	.string "beibringst, sind deine POKéMON stärker\l"
	.string "oder schwächer.\p"
	.string "Welche Attacken haben deine POKéMON\n"
	.string "auf Lager?$"

Route111_Text_BrookeRematchDefeat:: @ 81BB5A2
	.string "Ihre Attacken sind wirklich gut.$"

Route111_Text_BrookePostRematch:: @ 81BB5C1
	.string "Meine POKéMON sollten sich vielleicht\n"
	.string "nicht eher entwickeln, bis sie wirklich\l"
	.string "gute Attacken gelernt haben...$"
