Route121_Text_OkayMoveOutToMtPyre:: @ 8171C8F
	.string "Okay!\n"
	.string "Wir sind auf dem Weg zum PYROBERG!$"

Route121_Text_AheadLoomsMtPyre:: @ 8171CB4
	.string "Vor uns erhebt sich der PYROBERG...\p"
	.string "Er ist das natürlich gewachsene\n"
	.string "Monument der Geister der von uns\l"
	.string "gegangenen POKéMON.$"

Route121_Text_MtPyrePierSign:: @ 8171D0C
	.string "PIER AM PYROBERG\p"
	.string "...Das Schild ist alt und verwittert.\n"
	.string "Die Worte sind kaum noch lesbar...$"

Route121_Text_SafariZoneSign:: @ 8171D5B
	.string "“Hier sind seltene POKéMON zu Hause!”\n"
	.string "SAFARI-ZONE$"
