Route121_Text_VanessaIntro:: @ 81BF96E
	.string "Möchtest du mit meinem wunderhübschen\n"
	.string "POKéMON spielen?$"

Route121_Text_VanessaDefeat:: @ 81BF9A1
	.string "So habe ich das aber nicht gemeint!$"

Route121_Text_VanessaPostBattle:: @ 81BF9BA
	.string "Ich gehe zu einem WETTBEWERB in\n"
	.string "SEEGRASULB CITY.\p"
	.string "Mein POKéMON sollte kein Problem haben,\n"
	.string "in der MASTER-KLASSE zu glänzen.$"

Route121_Text_WalterIntro:: @ 81BFA1B
	.string "Mit meinem POKéMON habe ich alle vier\n"
	.string "Ecken der Welt bereist.\p"
	.string "Man könnte sagen, dass ich viel\n"
	.string "Vertrauen in mein Können habe.$"

Route121_Text_WalterDefeat:: @ 81BFA8C
	.string "Ah, gut gespielt.$"

Route121_Text_WalterPostBattle:: @ 81BFA9D
	.string "Ich möchte noch einmal die Welt mit\n"
	.string "meinem POKéMON umrunden.$"

Route121_Text_WalterRematchIntro:: @ 81BFADA
	.string "Mit meinem POKéMON habe ich erneut die\n"
	.string "vier Ecken der Welt bereist.\p"
	.string "Ich habe noch größeres Vertrauen in\n"
	.string "meine Fähigkeiten.$"

Route121_Text_WalterRematchDefeat:: @ 81BFB4B
	.string "Ah, gut gespielt.$"

Route121_Text_WalterPostRematch:: @ 81BFB5C
	.string "Deine POKéMON und du...\p"
	.string "Eure Fähigkeiten werden auch in\n"
	.string "Übersee als außerordentlich angesehen.$"

Route121_Text_TammyIntro:: @ 81BFBB4
	.string "Auf der Welt gibt es Dinge, die jenseits\n"
	.string "deines Verständnisses liegen...$"

Route121_Text_TammyDefeat:: @ 81BFBEE
	.string "Ich habe verloren...$"

Route121_Text_TammyPostBattle:: @ 81BFBFD
	.string "PYROBERG...\n"
	.string "Dort ist eine geheimnisvolle Kraft am\l"
	.string "Werk...$"

Route121_Text_KateIntro:: @ 81BFC36
	.string "EVA: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_KateDefeat:: @ 81BFC7A
	.string "EVA: Ich habe vor den Augen meiner\n"
	.string "Juniorpartnerin versagt...$"

Route121_Text_KatePostBattle:: @ 81BFCB3
	.string "EVA: Wenn sich jemand auf mich\n"
	.string "verlässt, versuche ich ihm gegenüber\l"
	.string "immer cool aufzutreten...$"

Route121_Text_KateNotEnoughMons:: @ 81BFD08
	.string "EVA: Wenn du nur ein POKéMON hast,\n"
	.string "können wir nicht mit dir kämpfen.\p"
	.string "Das wäre äußerst unfair.$"

Route121_Text_JoyIntro:: @ 81BFD60
	.string "UTE: Zusammen sind wir furchtlos!\n"
	.string "Wir demonstrieren dir unsere Stärke!$"

Route121_Text_JoyDefeat:: @ 81BFDA3
	.string "UTE: Bitte vergib mir, EVA!$"

Route121_Text_JoyPostBattle:: @ 81BFDC1
	.string "UTE: Ehehehe, ich muss wohl noch etwas\n"
	.string "mit meiner Seniorpartnerin trainieren.$"

Route121_Text_JoyNotEnoughMons:: @ 81BFE0D
	.string "UTE: Du brauchst mindestens zwei\n"
	.string "POKéMON, um gegen uns zu kämpfen.$"

Route121_Text_JessicaIntro:: @ 81BFE51
	.string "Stopp! Schau dir meine wunderbaren\n"
	.string "POKéMON gut an!$"

Route121_Text_JessicaDefeat:: @ 81BFE80
	.string "Oh, wie konntest du nur! Nimm die\n"
	.string "Sache doch nicht gleich so ernst!$"

Route121_Text_JessicaPostBattle:: @ 81BFEAE
	.string "Vielleicht werde ich in die SAFARI-ZONE\n"
	.string "gehen und mehr POKéMON fangen!$"

Route121_Text_JessicaRematchIntro:: @ 81BFEDE
	.string "Meine wertvollen POKéMON sind ge-\n"
	.string "wachsen! Schau mal!$"

Route121_Text_JessicaRematchDefeat:: @ 81BFF0A
	.string "Oh, du hast es wieder getan!\n"
	.string "Du nimmst es wirklich zu ernst!$"

Route121_Text_JessicaPostRematch:: @ 81BFF3A
	.string "Ich werde wohl wieder in die SAFARI-\n"
	.string "ZONE gehen und POKéMON fangen.$"
