Route108_Text_JeromeIntro:: @ 81B97C3
	.string "My dream is to swim the world's seven\n"
	.string "seas!$"

Route108_Text_JeromeDefeated:: @ 81B97EF
	.string "I won't be able to swim the seven seas\n"
	.string "like this...$"

Route108_Text_JeromePostBattle:: @ 81B9823
	.string "Playing with marine POKéMON is one of\n"
	.string "the pleasures of swimming!$"

Route108_Text_MatthewIntro:: @ 81B9864
	.string "Ahoy, there! Are you going out to the\n"
	.string "ABANDONED SHIP, too?$"

Route108_Text_MatthewDefeated:: @ 81B989F
	.string "I'm sinking!\n"
	.string "Glub... Glub...$"

Route108_Text_MatthewPostBattle:: @ 81B98BC
	.string "Some people even go inside that\n"
	.string "ABANDONED SHIP.$"

Route108_Text_TaraIntro:: @ 81B98EC
	.string "My liar of a boyfriend told me that\n"
	.string "I look great in a bikini...$"

Route108_Text_TaraDefeated:: @ 81B992C
	.string "Oh, boo!$"

Route108_Text_TaraPostBattle:: @ 81B9935
	.string "Even if it's a lie, I love being told\n"
	.string "I look great...\l"
	.string "We girls are so complex...$"

Route108_Text_MissyIntro:: @ 81B9986
	.string "I love the sea!\n"
	.string "I forget all my worries when I swim!$"

Route108_Text_MissyDefeated:: @ 81B99BB
	.string "When I lose a battle, I get all\n"
	.string "stressed out!$"

Route108_Text_MissyPostBattle:: @ 81B99E9
	.string "Work off your stress by swimming!\n"
	.string "It's so healthy!$"
