SootopolisCity_Gym_B1F_Text_AndreaIntro:: @ 818EA87
	.string "Ich zeige dir die sublimen Techniken,\n"
	.string "die ich vom ARENALEITER WASSILI\l"
	.string "gelernt habe.$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:: @ 818EACF
	.string "Bitte verzeih mir, WASSILI...$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:: @ 818EAED
	.string "Pass auf, was passiert, wenn du alle\n"
	.string "Bodenfliesen betreten hast...$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:: @ 818EB22
	.string "Du bist den ganzen Weg hierher ge-\n"
	.string "kommen, aber bis zu WASSILI dringst\l"
	.string "du nicht vor.\p"
	.string "Weil du gegen mich verlieren wirst!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:: @ 818EB81
	.string "Du bist stark! Ich habe mich durch dein\n"
	.string "unschuldiges Aussehen täuschen lassen.$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:: @ 818EBB1
	.string "Du bist gut genug, um nicht sofort von\n"
	.string "WASSILI besiegt zu werden.$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:: @ 818EBFA
	.string "Die Art, wie WASSILI kämpft...\p"
	.string "Dieser wunderbare Anblick hat mich dazu\n"
	.string "inspiriert, TRAINER zu werden.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:: @ 818EC5E
	.string "Du kämpfst mit mehr Anmut als ich...$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:: @ 818EC92
	.string "Die Ästhetik, die du in den Kampf ein-\n"
	.string "bringst, ist unbeschreiblich.\p"
	.string "Oh... Ich bin so glücklich, dass ich mich\n"
	.string "für POKéMON entschieden habe.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:: @ 818ECEB
	.string "Ich werde dir beibringen, dass Kämpfe\n"
	.string "kein Zuckerschlecken sind!$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:: @ 818ED18
	.string "Oh.\n"
	.string "Du bist stark.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:: @ 818ED2B
	.string "Ich verrate dir etwas.\p"
	.string "Wenn du zu WASSILI willst, dann darfst\n"
	.string "du auf jede Fliese nur ein Mal treten.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:: @ 818ED91
	.string "Die POKéMON ARENA mit den höchsten\n"
	.string "Anforderungen in der HOENN-Region...\p"
	.string "Das ist die ARENA von XENEROVILLE.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:: @ 818EDE8
	.string "Du kämpfst aber auf einem hohen Niveau!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:: @ 818EE03
	.string "Statt damit zufrieden zu sein, zur\n"
	.string "besten ARENA zu gehören, würde ich\l"
	.string "gerne auch an anderen Orten trainieren.\l"
	.string "Aber hier ist es so lustig!$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:: @ 818EE96
	.string "Ich trainiere meine POKéMON zusammen\n"
	.string "mit WASSILI.\p"
	.string "Ich bin nicht leicht zu nehmen!$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:: @ 818EEDC
	.string "Da wurde ich glatt überrollt...$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:: @ 818EEF7
	.string "Ich denke, du hast durchaus Potential.\n"
	.string "Warum bleibst du nicht bei uns?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:: @ 818EF39
	.string "Anmutig über das Eis zu gleiten, ohne\n"
	.string "die Linien zu berühren...\p"
	.string "Ein TRAINER, der das beherrscht, wird\n"
	.string "auch in anderen Dingen elegant wirken.$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:: @ 818EFB8
	.string "Äh, entschuldige mich...$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:: @ 818EFCA
	.string "Es ist offensichtlich: Die Stärke eines\n"
	.string "TRAINERS hat nichts mit seinem Alter\l"
	.string "zu tun!$"

SootopolisCity_Gym_B1F_Text_MarissaIntro:: @ 818F037
	.string "Wenn ich mit meinen POKéMON zusammen\n"
	.string "bin, vergeht die Zeit so schnell, dass\l"
	.string "ich noch nicht mal “Uuups” sagen kann.$"

SootopolisCity_Gym_B1F_Text_MarissaDefeat:: @ 818F07F
	.string "Uuups!$"

SootopolisCity_Gym_B1F_Text_MarissaPostBattle:: @ 818F085
	.string "Ich wollte, ich könnte meine Niederlagen\n"
	.string "vergessen, bevor ich “Uuups”\l"
	.string "ausgesprochen habe.$"
