Route125_Text_CodyIntro:: @ 81C0FCF
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_CodyDefeat:: @ 81C1002
	.string "I beg for peace!$"

Route125_Text_CodyPostBattle:: @ 81C1013
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:: @ 81C104B
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:: @ 81C1073
	.string "I floundered...$"

Route125_Text_StanPostBattle:: @ 81C1083
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:: @ 81C10C3
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:: @ 81C10FB
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:: @ 81C110C
	.string "Whew...\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:: @ 81C1136
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:: @ 81C1175
	.string "I lost...$"

Route125_Text_SharonPostBattle:: @ 81C117F
	.string "Your power... You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:: @ 81C11AF
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:: @ 81C11ED
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:: @ 81C1208
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRematchIntro:: @ 81C1282
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:: @ 81C12C5
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:: @ 81C12EE
	.string "The SHOAL CAVE...\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:: @ 81C13A1
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:: @ 81C13FF
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:: @ 81C141C
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:: @ 81C146E
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:: @ 81C14AB
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:: @ 81C14E7
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:: @ 81C1508
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:: @ 81C154F
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"
