Route114_FossilManiacsHouse_Text_HaveThisToDigLikeMyBrother:: @ 81925E1
	.string "Mein großer Bruder ist ein FOSSIL-\n"
	.string "MANIAC... Er ist ein netter Kerl, der\l"
	.string "Fossilien liebt...\p"
	.string "Er liebt es auch, Löcher zu graben...\n"
	.string "Dieses Loch hat er alleine gegraben!\p"
	.string "Hier, das kannst du haben. Damit kannst\n"
	.string "du Löcher graben, wie mein Bruder...$"

Route114_FossilManiacsHouse_Text_DigReturnsYouToEntrance:: @ 81926AE
	.string "Wenn ein POKéMON in einer Höhle\n"
	.string "SCHAUFLER einsetzt, kommst du zum\l"
	.string "Eingang zurück.$"

Route114_FossilManiacsHouse_Text_RocksFillDisplayCase:: @ 81926FA
	.string "Steine in den unterschiedlichsten\n"
	.string "Formen liegen im Glasschaukasten.$"

Route114_FossilManiacsHouse_Text_CrammedWithBooks:: @ 8192729
	.string "DIE ZUSAMMENSETZUNG DER ERDSCHICHT...\n"
	.string "WIE REGEN DAS LAND FORMT...\l"
	.string "STEINE, BODEN UND FELSEN...\p"
	.string "Gerammelt voll mit Büchern.$"
