Route123_Text_WendyIntro:: @ 81BFF6A
	.string "Möchtest du wissen, wie stark du bist?\n"
	.string "Ich werde dich testen!$"

Route123_Text_WendyDefeat:: @ 81BFFA2
	.string "Du hast glänzend abgeschnitten!$"

Route123_Text_WendyPostBattle:: @ 81BFFC1
	.string "Um gegen mich bestehen zu können...\n"
	.string "Deine Stärke ist einfach unglaublich!$"

Route123_Text_ClydeIntro:: @ 81BFFF0
	.string "Du hast da aber eine große Sammlung an\n"
	.string "ORDEN der verschiedenen ARENEN!\p"
	.string "Zeig mir, dass du diese ORDEN auch\n"
	.string "zu Recht trägst!$"

Route123_Text_ClydeDefeat:: @ 81C0057
	.string "Oh, du bist ihrer würdig, wirklich!$"

Route123_Text_ClydePostBattle:: @ 81C0075
	.string "Du wurdest deinen ORDEN in diesem\n"
	.string "Kampf mehr als gerecht.$"

Route123_Text_VioletIntro:: @ 81C009E
	.string "Man sagt, dass gute Zeiten auch mit\n"
	.string "guten Aromen erfüllt sind.$"

Route123_Text_VioletDefeat:: @ 81C00D4
	.string "Oh... Ich rieche den bitteren Geruch\n"
	.string "der Niederlage...$"

Route123_Text_VioletPostBattle:: @ 81C0100
	.string "Der Garten des BEERENMEISTERS ist\n"
	.string "erfüllt mit den erhebendsten Aromen.$"

Route123_Text_CameronIntro:: @ 81C013F
	.string "Ein Psycho zu sein ist eine Frage des\n"
	.string "Willens.\p"
	.string "Mein Wille will gegen niemanden verlieren.\n"
	.string "Das macht mich stark.$"

Route123_Text_CameronDefeat:: @ 81C01A3
	.string "Mir ist schlecht...$"

Route123_Text_CameronPostBattle:: @ 81C01B1
	.string "Es ist alles eine Frage des Willens. Ich\n"
	.string "dachte, ich würde gegen dich gewinnen.$"

Route123_Text_CameronRematchIntro:: @ 81C01F9
	.string "Ich habe mich selbst davon überzeugt,\n"
	.string "dass ich einfach nicht verlieren werde.$"

Route123_Text_CameronRematchDefeat:: @ 81C0240
	.string "So überzeugend war das gar nicht...$"

Route123_Text_CameronPostRematch:: @ 81C024E
	.string "Ich sollte am PYROBERG trainieren...\n"
	.string "So werde ich dich nie schlagen...$"

Route123_Text_JackiIntro:: @ 81C028C
	.string "Sei nicht zu erfreut, wenn deine\n"
	.string "POKéMON Psychokräfte entwickeln.\p"
	.string "Du musst diese Kräfte modellieren,\n"
	.string "um sie sinnvoll einsetzen zu können.$"

Route123_Text_JackiDefeat:: @ 81C0303
	.string "Erstaunlich!$"

Route123_Text_JackiPostBattle:: @ 81C030F
	.string "Wir alle besitzen Psychokräfte. Wir\n"
	.string "haben nur vergessen, sie zu nutzen.$"

Route123_Text_JackiRematchIntro:: @ 81C0351
	.string "Hast du die Psychokräfte in dir\n"
	.string "erweckt?$"

Route123_Text_JackiRematchDefeat:: @ 81C0380
	.string "Erstaunlich!$"

Route123_Text_JackiPostRematch:: @ 81C038C
	.string "Dein Einfluss auf deine POKéMON...\n"
	.string "Auch das sind Psychokräfte.$"

Route123_Text_MiuIntro:: @ 81C03CB
	.string "LEA: Hallo, TRAINER. Ich hoffe, deine\n"
	.string "POKéMON fangen nicht an zu weinen,\l"
	.string "wenn sie verlieren.$"

Route123_Text_MiuDefeat:: @ 81C040E
	.string "LEA: Oh oh, wir haben verloren.$"

Route123_Text_MiuPostBattle:: @ 81C0423
	.string "LEA: TRAINER, deine POKéMON sind stark,\n"
	.string "weil ihr eine starke Freundschaft teilt.$"

Route123_Text_MiuNotEnoughMons:: @ 81C0462
	.string "LEA: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_YukiIntro:: @ 81C049C
	.string "GRIT: Okay!\n"
	.string "Wir schlagen die POKéMON des TRAINERS.$"

Route123_Text_YukiDefeat:: @ 81C04CD
	.string "GRIT: Oh oh. Wir haben verloren...$"

Route123_Text_YukiPostBattle:: @ 81C04E3
	.string "GRIT: Wieso bist du so stark?\n"
	.string "Wir haben bisher noch nie verloren!$"

Route123_Text_YukiNotEnoughMons:: @ 81C0519
	.string "GRIT: Es macht keinen Spaß, wenn du\n"
	.string "weniger als zwei POKéMON hast.$"

Route123_Text_KindraIntro:: @ 81C0554
	.string "PYROBERG...\n"
	.string "Wo die Geister der POKéMON ruhen...\l"
	.string "Ruhen deine POKéMON auch?$"

Route123_Text_KindraDefeat:: @ 81C059F
	.string "Überschäumend mit Leben...$"

Route123_Text_KindraPostBattle:: @ 81C05BC
	.string "PYROBERG...\n"
	.string "Wo die Geister der POKéMON ruhen...\p"
	.string "Dort muss es eine Kraft geben, die die\n"
	.string "Geister beruhigt...$"
