Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Hat die Strömung dich hergebracht? Das\n"
	.string "nenne ich Schicksal. Lass uns kämpfen!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Stark!\n"
	.string "Viel zu stark!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "Soll ich das jetzt Glück nennen, dass ich\n"
	.string "auf einen so starken TRAINER wie dich\l"
	.string "gestoßen bin? Ich bin verflucht...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "Ich führte ein Leben in Kummer und\n"
	.string "Elend. Es hat mich hierher verschlagen\l"
	.string "und hier bin ich gestrandet...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Eine weitere Niederlage...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "Treibend auf dem Meer des Lebens...\n"
	.string "Ich habe dazu keine Lust mehr!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Willkommen!\n"
	.string "Ich habe dich schon erwartet!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "Nein! Bitte!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "Ein Kind als starker TRAINER...\n"
	.string "Boh, ist das äääärgerlich!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "Ich möchte, wie jeder andere auch,\n"
	.string "gewinnen, aber ich ziehe meine POKéMON\l"
	.string "nicht auf wie jeder andere auch...$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Mist!\n"
	.string "Meine Art und Weise reicht nicht aus!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "Es macht mehr Spaß, die Dinge auf meine\n"
	.string "Art zu erledigen, als auf die Art aller\l"
	.string "anderen. Das ist doch klar!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "Ich bin mit meinen VOGEL-POKéMON\n"
	.string "hierher gekommen.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "Du...\n"
	.string "Du bist total cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "Ich könnte nach BAUMHAUSEN CITY zu-\n"
	.string "rückkehren, aber ich mag Orte wie diese.$"
