CaveOfOrigin_B4F_Text_BlueOrbGlows:: @ 81B4F03
	.string "{PLAYER}'s BLUE ORB suddenly began\n"
	.string "glowing!$"

CaveOfOrigin_B4F_Text_KyogreReturnsToSleep:: @ 81B4F29
	.string "KYOGRE appears to have settled\n"
	.string "into sleep again...$"

AquaSettled_Text_ArchieHesitates:: @ 81B4F5C
	.string "ARCHIE: This...$"

AquaSettled_Text_ArchieFarewell:: @ 81B4F6C
	.string "ARCHIE: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you've seen of me...$"
