PetalburgCity_Gym_Text_GiveEnigmaBerry:: @ 81C5570
	.string "DAD: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"

.include "data/maps/Route104/berry_text.inc"

Route111_Text_WateredPlantsEveryDayTakeBerry:: @ 81C56F0
	.string "I watered my plants lots and lots!\n"
	.string "A whole bunch of flowers bloomed!\p"
	.string "And then a whole bunch of BERRIES\n"
	.string "appeared!\p"
	.string "Here you go!\n"
	.string "You can have this!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:: @ 81C5781
	.string "I'm going to try really hard and make\n"
	.string "some RED {POKEBLOCK}S!\p"
	.string "I hope you try hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:: @ 81C57D2
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:: @ 81C5803
	.string "I'm gathering BERRIES so I can win a\n"
	.string "POKéMON CONTEST.\p"
	.string "If you'd like, I'll share one with you.$"

Route114_Text_TryBerryCrushWithFriends:: @ 81C5861
	.string "Good luck to you, too!$"

Route114_Text_FunToThinkAboutBerries:: @ 81C5878
	.string "What BERRIES should I plant today?\n"
	.string "What color {POKEBLOCK}S should I make?\p"
	.string "Fretting over stuff like that is fun\n"
	.string "in its own way.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:: @ 81C58F1
	.string "Give the case a shake, and out pops\n"
	.string "a {POKEBLOCK}...\p"
	.string "And that {POKEBLOCK} is caught and eaten\n"
	.string "by a POKéMON...\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_YesYouUnderstand:: @ 81C5979
	.string "Yes, yes.\n"
	.string "You understand what I mean.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:: @ 81C59B5
	.string "Oh... But it is important to make your\n"
	.string "own impressions, I guess...\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:: @ 81C5A0B
	.string "I think that BERRY is rare.\n"
	.string "I hope you raise it with loving care.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:: @ 81C5A4D
	.string "I'll get more BERRIES from the\n"
	.string "BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:: @ 81C5A7A
	.string "When it gets right down to it...\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”...\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:: @ 81C5B1D
	.string "When it gets right down to it...\p"
	.string "It's because you're a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:: @ 81C5B5D
	.string "When it gets right down to it...\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

.include "data/maps/Route123_BerryMastersHouse/berry_text.inc"

.include "data/maps/Route104_PrettyPetalFlowerShop/text.inc"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:: @ 81C63F2
	.string "Hi, what's your name?\p"
	.string "... ... ...  ... ... ...  ... ... ...\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so\n"
	.string "I would grow healthy and warmhearted.\l"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo:: @ 81C64D0
	.string "KIRI will give you this BERRY, too!\n"
	.string "I really like it lots!$"

SootopolisCity_Text_WhatKindOfWishInYourName:: @ 81C650B
	.string "I wonder what kind of wish is included\n"
	.string "in your name.$"

SootopolisCity_Text_KiriBornInSeasons:: @ 81C6540
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you like\n"
	.string "the spring, and if you're born in the\l"
	.string "summer, do you like the summer?$"

SootopolisCity_Text_ThenILoveAutumn:: @ 81C65D4
	.string "Then KIRI was born in the autumn,\n"
	.string "so I love the autumn!\p"
	.string "Which season do you like?$"

SootopolisCity_Text_OhDoesntMatter:: @ 81C6626
	.string "Oh...\n"
	.string "It doesn't matter...\p"
	.string "There's so much that I want to know...$"
