BerryTree_Text_ItsSoftLoamySoil:: @ 81A16B6
	.string "It's soft, loamy soil.$"

BerryTree_Text_WantToPlant:: @ 81A16CD
	.string "It's soft, loamy soil.\n"
	.string "Want to plant a BERRY?$"

BerryTree_Text_PlantedOneBerry:: @ 81A16FB
	.string "{PLAYER} planted one {STR_VAR_1} BERRY in\n"
	.string "the soft, loamy soil.$"

BerryTree_Text_BerryGrowthStage1:: @ 81A172C
	.string "One {STR_VAR_1} BERRY was planted here.$"

BerryTree_Text_BerryGrowthStage2:: @ 81A174B
	.string "{STR_VAR_1} has sprouted.$"

BerryTree_Text_BerryGrowthStage3:: @ 81A175C
	.string "This {STR_VAR_1} plant is growing taller.$"

BerryTree_Text_BerryGrowthStage4:: @ 81A177D
	.string "These {STR_VAR_1} flowers are blooming\n"
	.string "{STR_VAR_2}.$"

BerryTree_Text_CareAdverbGreat:: @ 81A179F
	.string "very beautifully$"

BerryTree_Text_CareAdverbPoor:: @ 81A17B0
	.string "cutely$"

BerryTree_Text_CareAdverbGood:: @ 81A17B7
	.string "prettily$"

BerryTree_Text_WantToPick:: @ 81A17C0
	.string "There are {STR_VAR_2} {STR_VAR_1} BERRIES!\p"
	.string "Do you want to pick the\n"
	.string "{STR_VAR_1} BERRIES?$"

BerryTree_Text_PickedTheBerry:: @ 81A17FD
	.string "{PLAYER} picked the {STR_VAR_2} {STR_VAR_1} BERRIES.$"

BerryTree_Text_PutAwayBerry:: @ 81A181A
	.string "{PLAYER} put away the {STR_VAR_1} BERRIES\n"
	.string "in the BAG's BERRIES POCKET.\p"
	.string "The soil returned to its soft and\n"
	.string "loamy state.$"

BerryTree_Text_BerryPocketFull:: @ 81A1881
	.string "The BAG's BERRIES POCKET is full.\p"
	.string "The {STR_VAR_1} BERRIES couldn't be taken.$"

BerryTree_Text_BerryLeftUnpicked:: @ 81A18C5
	.string "{PLAYER} left the {STR_VAR_1} BERRIES\n"
	.string "unpicked.$"

BerryTree_Text_WantToWater:: @ 81A18E6
	.string "Want to water the {STR_VAR_1} with the\n"
	.string "WAILMER PAIL?$"

BerryTree_Text_WateredTheBerry:: @ 81A1912
	.string "{PLAYER} watered the {STR_VAR_1}.$"

BerryTree_Text_PlantIsDelighted:: @ 81A1925
	.string "The plant seems to be delighted.$"

BerryTree_Text_ExclamationPoint:: @ 81A1946
	.string "!$"
