CableClub_Text_WelcomeToColosseum:: @ 81A4510
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "COLOSSEUM.\p"
	.string "You may battle with your friends here.\p"
	.string "Would you like to battle?$"

CableClub_Text_WelcomeToTradeCenter:: @ 81A457E
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TRADE CENTER.\p"
	.string "You may trade your POKéMON here\n"
	.string "with a friend.\p"
	.string "Would you like to trade POKéMON?$"

CableClub_Text_WelcomeToRecordCorner:: @ 81A45FE
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.if REVISION >= 1
	.string "RECORD CORNER.\p"
	.else
	.string "RECORD CENTER.\p"
	.endif
	.string "You may mix your records as a TRAINER\n"
	.string "with the records of your friends.\p"
	.string "Would you like to mix records?$"

CableClub_Text_ExplainBattleModes:: @ 81A4696
	.string "There are three link battle modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER will send out two\n"
	.string "POKéMON in battle at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.$"

CableClub_Text_WouldYouLikeToBattle:: @ 81A4826
	.string "Would you like to battle?$"

CableClub_Text_PlayWhichBattleMode:: @ 81A4840
	.string "Which Battle Mode would you like\n"
	.string "to play?$"

CableClub_Text_NeedTwoMonsForDoubleBattle:: @ 81A486A
	.string "For a DOUBLE BATTLE, you must have\n"
	.string "at least two POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:: @ 81A48A3
	.string "For trading, you must have at least\n"
	.string "two POKéMON with you.$"

CableClub_Text_CantTradeEnigmaBerry:: @ 81A48DD
	.string "Your {STR_VAR_1} BERRY-holding POKéMON\n"
	.string "can't be traded.$"

gText_PleaseWaitForLink:: @ 81A490C
	.string "Please wait.\n"
	.string "... ... B Button: Cancel$"

gText_ConfirmLinkWhenPlayersReady:: @ 81A4932
	.string "When all players are ready...\n"
	.string "A Button: Confirm   B Button: Cancel$"

gText_ConfirmStartLinkWithXPlayers:: @ 81A4975
	.string "Start link with {STR_VAR_1} players.\n"
	.string "A Button: Confirm   B Button: Cancel$"

gText_AwaitingLinkup:: @ 81A49B6
	.string "Awaiting linkup...\n"
	.string "... ... B Button: Cancel$"

CableClub_Text_OkayToSaveProgress: @ 81A49E2
	.string "Your progress must be saved before\n"
	.string "linking. Is it okay to save?$"

CableClub_Text_PleaseEnter:: @ 81A4A22
	.string "Please enter.$"

Text_SomeoneIsNotReadyToLink:: @ 81A4A30
	.string "Someone is not ready to link.\p"
	.string "Please come back after everyone has\n"
	.string "made preparations.$"

Text_LinkErrorPleaseReset:: @ 81A4A85
	.string "Sorry, we have a transmission error...\n"
	.string "Please reset and try again.$"

CableClub_Text_CantMixWithDifferentLanguage:: @ 81A4AC8
	.string "Sorry, we have a transmission error.\n"
	.string "You may not mix records in different\l"
	.string "languages.$"

Text_PlayersMadeDifferentSelections:: @ 81A4B1D
	.string "The link partners appear to have made\n"
	.string "different selections.$"

CableClub_Text_PleaseVisitAgain:: @ 81A4B59
	.string "Please come again.$"

CableClub_Text_IncorrectNumberOfParticipants:: @ 81A4B6C
	.string "The number of participants is\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:: @ 81A4B95
	.string "The SINGLE Battle Mode cannot be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_CantDoubleBattleWithXPlayers:: @ 81A4BCC
	.string "The DOUBLE Battle Mode cannot be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_NeedFourPlayers:: @ 81A4C03
	.string "There must be four players to play\n"
	.string "this Battle Mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart:: @ 81A4C38
	.string "Please confirm the number of players\n"
	.string "and start again.$"

Text_TerminateLinkConfirmation: @ 81A4C6E
	.string "The link will be terminated if you\n"
	.string "leave the room. Is that okay?$"

Text_TerminateLinkPleaseWait: @ 81A4CAF
	.string "Terminating link... You will be\n"
	.string "escorted out of the room. Please wait.$"

CableClub_Text_TooBusyToNotice: @ 81A4CF6
	.string "This TRAINER is too busy to notice...$"

CableClub_Text_GotToLookAtTrainerCard: @ 81A4D1C
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!$"

CableClub_Text_GotToLookAtColoredTrainerCard: @ 81A4D45
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD! It's a {STR_VAR_2} card!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:: @ 81A4D7E
	.string "Please take your seat and start\n"
	.string "your battle.$"

TradeCenter_Text_TakeSeatStartTrade:: @ 81A4DAB
	.string "Please take your seat and start\n"
	.string "your trade.$"

RecordCorner_Text_TakeSeatAndWait:: @ 81A4DD7
	.string "Please take your seat and wait.$"

RecordCorner_Text_ThanksForComing:: @ 81A4DF7
	.string "Thanks for coming.$"

BattleColosseum_4P_Text_ChoosePokemon: @ 81A4E0A
	.string "Please choose your POKéMON for the\n"
	.string "MULTI BATTLE.$"

RecordCorner_Text_PlayerSentOverOneX:: @ 81A4E3B
	.string "{STR_VAR_1} sent over one\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_TrainerCardDataOverwritten:: @ 81A4E50
	.string "The TRAINER CARD data will\n"
	.string "be rewritten.$"

CableClub_Text_HopeToSeeYouAgain:: @ 81A4E79
	.string "I hope to see you again!$"
