EventTicket_Text_DadHasLetter:: @ 81C5033
	.string "DAD: {PLAYER}! Good to see you!\n"
	.string "There's a letter here for you, {PLAYER}.$"

EventTicket_Text_DadExplainsPass:: @ 81C5070
	.string "DAD: I guess this is a PASS for a ship.\n"
	.string "But I've never seen this ship before.\p"
	.string "You should find out what this is about\n"
	.string "in LILYCOVE.$"

EventTicket_Text_ThatPass:: @ 81C50F2
	.string "The ferry to SLATEPORT is...\p"
	.string "Oh?\n"
	.string "That PASS...$"

EventTicket_Text_ShowEonTicket:: @ 81C5120
	.string "Aye, mate, are you the one who brought\n"
	.string "that mighty odd PASS?\p"
	.string "I'll tell you, you're trying to reach a\n"
	.string "tiny spit of an island far in the south.\p"
	.string "There's no telling what we'll encounter\n"
	.string "once we reach there, aye.\l"
	.string "That shivers my timbers!\p"
	.string "All aboard!$"

EventTicket_Text_SouthernIslandSailBack:: @ 81C5215
	.string "Aye, mate, there's nothing here to\n"
	.string "see or do on this forgettable island.\p"
	.string "What say we sail back to LILYCOVE?$"

EventTicket_Text_SailHome:: @ 81C5281
	.string "Aye, right, then!\n"
	.string "Sail home we will!$"

EventTicket_Text_AsYouLike:: @ 81C52A6
	.string "Aye, right, as you like, then.$"

SouthernIsland_Interior_Text_Sign:: @ 81C52C5
	.string "“All dreams are but another reality.\n"
	.string "Never forget...”$"

SouthernIsland_Exterior_Text_Sign:: @ 81C52FB
	.string "“Those whose memories fade seek to\n"
	.string "carve them in their hearts...”$"
