MauvilleCity_PokemonCenter_1F_Text_HearMyStory:: @ 81B092A
	.string "I'm GIDDY!\n"
	.string "I have a scintillating story for you!\p"
	.string "Would you like to hear my story?$"

MauvilleCity_PokemonCenter_1F_Text_GiddyFeelingTheBlues:: @ 81B097C
	.string "Oh...\n"
	.string "You've deflated me...$"

MauvilleCity_PokemonCenter_1F_Text_AlsoIWasThinking:: @ 81B0998
	.string "Also, I was thinking...$"

MauvilleCity_PokemonCenter_1F_Text_WeShouldChatAgain:: @ 81B09B0
	.string "That's about it, I think...\p"
	.string "We should chat again!\n"
	.string "Bye-bye!$"
