CaveOfOrigin_B4F_Text_RedOrbBeginsGlowing:: @ 81B4FE4
	.string "{PLAYER}'s RED ORB suddenly began\n"
	.string "glowing!$"

CaveOfOrigin_B4F_Text_GroudonSettled:: @ 81B5009
	.string "GROUDON appears to have settled\n"
	.string "into sleep again...$"

MagmaLeader_Text_This: @ 81B503D
	.string "MAXIE: This...$"

MagmaLeader_Text_Farewell: @ 81B504C
	.string "MAXIE: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you've seen of me...$"
