SeafloorCavern_Room9_Text_MaxieHoldItRightThere:: @ 81B4850
	.string "MAXIE: Hold it right there.$"

SeafloorCavern_Room9_Text_MaxieSoItWasYou:: @ 81B486C
	.string "MAXIE: Fufufu...\n"
	.string "So it was you, after all.$"

SeafloorCavern_Room9_Text_MaxieBeholdGroudon:: @ 81B4897
	.string "MAXIE: Behold!\p"
	.string "See how beautiful it is, the sleeping\n"
	.string "form of the ancient POKéMON GROUDON!\p"
	.string "I have waited so long for this day to\n"
	.string "come...$"

SeafloorCavern_Room9_Text_MaxieYouMustDisappear:: @ 81B491F
	.string "MAXIE: It surprises me, how you've\n"
	.string "managed to chase me here.\p"
	.string "But that's all over now.\p"
	.string "For the realization of my dream,\n"
	.string "you must disappear now!$"

SeafloorCavern_Room9_Text_MaxieDefeat:: @ 81B49AE
	.string "I...\n"
	.string "I lost again?$"

SeafloorCavern_Room9_Text_MaxieWithThisBlueOrb:: @ 81B49C1
	.string "MAXIE: Fufufu...\p"
	.string "I commend you. I must recognize that\n"
	.string "you are truly gifted.\p"
	.string "But!\n"
	.string "I have this in my possession!\p"
	.string "With this BLUE ORB, I can make\n"
	.string "GROUDON...$"

SeafloorCavern_Room9_Text_BlueOrbShinesByItself:: @ 81B4A5A
	.string "The BLUE ORB suddenly began shining\n"
	.string "by itself!$"

SeafloorCavern_Room9_Text_MaxieWhereDidGroudonGo:: @ 81B4A89
	.string "MAXIE: What?!\p"
	.string "I didn't do anything.\n"
	.string "Why did the BLUE ORB...\p"
	.string "Where did GROUDON go?$"

SeafloorCavern_Room9_Text_MaxieAMessageFromOutside:: @ 81B4ADB
	.string "MAXIE: Hm? It's a message from our\n"
	.string "members outside...$"

SeafloorCavern_Room9_Text_MaxieWhatSunIsTooBright:: @ 81B4B11
	.string "MAXIE: Yes, what is it?\p"
	.string "Hm...\n"
	.string "The sun is burning brightly?\p"
	.string "Good... That should have happened.\n"
	.string "That is why we awakened GROUDON,\l"
	.string "to realize TEAM MAGMA's vision of\l"
	.string "expanding the world's landmass.\p"
	.string "What?!\p"
	.string "It's far hotter than we envisioned?\n"
	.string "It's so hot that it's dangerous?\p"
	.string "That can't be...\n"
	.string "That's just not possible...\p"
	.string "Hold your position and monitor the\n"
	.string "situation!$"

SeafloorCavern_Room9_Text_MaxieWhyDidGroudonDisappear:: @ 81B4C79
	.string "MAXIE: There's something wrong...\p"
	.string "The BLUE ORB is supposed to awaken\n"
	.string "and control GROUDON...\p"
	.string "But... Why?\n"
	.string "Why did GROUDON disappear?\p"
	.string "Why?!$"

SeafloorCavern_Room9_Text_ArchieWhatHaveYouWrought:: @ 81B4D02
	.string "ARCHIE: What have you wrought?\p"
	.string "MAXIE... You've finally awoken GROUDON,\n"
	.string "haven't you?\p"
	.string "What will happen to the world if this\n"
	.string "sunshine continues for all eternity?\p"
	.string "The world's seas will all dry up and\n"
	.string "disappear...$"

SeafloorCavern_Room9_Text_MaxieDoubtsBlueOrbFailure:: @ 81B4DD3
	.string "MAXIE: What are you saying?\p"
	.string "The BLUE ORB should let me control\n"
	.string "GROUDON...\l"
	.string "That can't be possible...$"

SeafloorCavern_Room9_Text_ArchieWeDontHaveTimeToArgue:: @ 81B4E37
	.string "ARCHIE: We don't have the time to\n"
	.string "argue about it here!\p"
	.string "Get outside and see for yourself!\p"
	.string "See if what you've wrought is the\n"
	.string "world that you desired!$"

SeafloorCavern_Room9_Text_ArchieComeOnPlayer:: @ 81B4ECA
	.string "ARCHIE: {PLAYER}{KUN}, come on, you have\n"
	.string "to get out of here, too!$"
