CaveOfOrigin_B4F_Text_RedOrbGlows:: @ 81B4FE4
	.string "{PLAYER}'s RED ORB suddenly began\n"
	.string "glowing!$"

CaveOfOrigin_B4F_Text_GroudonReturnsToSleep:: @ 81B5009
	.string "GROUDON appears to have settled\n"
	.string "into sleep again...$"

MagmaSettled_Text_MaxieHesitates:: @ 81B503D
	.string "MAXIE: This...$"

MagmaSettled_Text_MaxieFarewell:: @ 81B504C
	.string "MAXIE: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you've seen of me...$"
