BerryBlender_Text_WantToMakePokeblocks:: @ 81B6E63
	.string "Oh? Did you want to make some {POKEBLOCK}S\n"
	.string "with this old-timer?$"

BerryBlender_Text_Excellent:: @ 81B6E9D
	.string "Excellent!$"

BerryBlender_Text_MadeOldTimerSad:: @ 81B6EA8
	.string "Oh...\n"
	.string "You've made this old-timer sad...$"

BerryBlender_Text_KnowHowToMakePokeblocks:: @ 81B6ED0
	.string "Do you know how to make a {POKEBLOCK}?$"

BerryBlender_Text_LetsBerryBlender:: @ 81B6EF1
	.string "Let's get started, then!\p"
	.string "Let's BERRY BLENDER!$"

BerryBlender_Text_ExplainBerryBlending:: @ 81B6F1F
	.string "Okay, a little explanation, then.\p"
	.string "Oh, don't worry, it's quite simple.\p"
	.string "When the BLENDER's arrow comes to\n"
	.string "your marker, just press the A Button.\p"
	.string "That's all you have to do.\n"
	.string "You'll see how easy it is when you try.$"

BerryBlender_Text_DontHaveAnyBerries:: @ 81B6FF0
	.string "Oh?\n"
	.string "You don't have any BERRIES?\p"
	.string "If you don't have any BERRIES,\n"
	.string "you can't make any {POKEBLOCK}S.$"

BerryBlender_Text_CanHaveOneOfMyBerries:: @ 81B704A
	.string "Well, that won't do at all now, will it?\p"
	.string "If you don't mind leftovers, you can\n"
	.string "have one of my BERRIES.\p"
	.string "That way, we could make some {POKEBLOCK}S\n"
	.string "together using the BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:: @ 81B70F6
	.string "If I had some BERRIES left over,\n"
	.string "I'd gladly give you one...\p"
	.string "But, I don't have any to spare today.\n"
	.string "We'll have to do this another time.$"

BerryBlender_Text_PokeblockCaseIsFull:: @ 81B717C
	.string "But your {POKEBLOCK} CASE is full.\p"
	.string "You should use some {POKEBLOCK}S before\n"
	.string "you come see me again.$"

BerryBlender_Text_DontHavePokeblockCase:: @ 81B71D2
	.string "But you don't have a {POKEBLOCK} CASE.\p"
	.string "You should get a {POKEBLOCK} CASE and then\n"
	.string "come see me.$"

BerryBlender_Text_LetsGetBlendingAlready:: @ 81B7225
	.string "Let's get blending already!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:: @ 81B7241
	.string "I wonder what kind of {POKEBLOCK} I'll get?\n"
	.string "This is so exciting!$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:: @ 81B727C
	.string "{POKEBLOCK}S will be made with your friends \n"
	.string "from BERRIES in the BERRY BLENDER.\p"
	.string "Is it okay to save the game before\n"
	.string "linking with your friends?$"

BerryBlender_Text_SearchingForFriends:: @ 81B7304
	.string "Searching for your friends...\n"
	.string "... ... B Button: Cancel$"

BerryBlender_Text_Player1Arrived:: @ 81B733B
	.string "{STR_VAR_1} arrived.$"

BerryBlender_Text_Player1And2Arrived:: @ 81B7347
	.string "{STR_VAR_1} and {STR_VAR_2} arrived.$"

BerryBlender_Text_AllPlayersArrived:: @ 81B735A
	.string "{STR_VAR_1}, {STR_VAR_2}, and\n"
	.string "{STR_VAR_3} arrived.$"

BerryBlender_Text_NobodyCame: @ 81B7372
	.string "Nobody came...$"

BerryBlender_Text_NoBerriesLink:: @ 81B7381
	.string "You have no BERRIES.\n"
	.string "The BERRY BLENDER can't be used.$"

BerryBlender_Text_PokeblockCaseIsFullLink:: @ 81B73B7
	.string "Your {POKEBLOCK} CASE is full.\n"
	.string "The BERRY BLENDER can't be used.$"

BerryBlender_Text_DontHavePokeblockCaseLink:: @ 81B73F1
	.string "You don't have a {POKEBLOCK} CASE.\n"
	.string "The BERRY BLENDER can't be used.$"

BerryBlender_Text_LoveMakingPokeblocks:: @ 81B742F
	.string "I love making {POKEBLOCK}S.\p"
	.string "I always have some BERRIES with me.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:: @ 81B7469
	.string "If you'd like, we could make some\n"
	.string "{POKEBLOCK}S together using the\l"
	.string "BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:: @ 81B74B4
	.string "Oh?\n"
	.string "You don't have any BERRIES?\p"
	.string "Well, that won't do at all now, will it?\p"
	.string "If you don't mind leftovers, you can\n"
	.string "have one of my BERRIES.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:: @ 81B753A
	.string "We'll use it to make {POKEBLOCK}S together\n"
	.string "using the BERRY BLENDER.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:: @ 81B7578
	.string "Oh?\n"
	.string "You don't have any BERRIES?\p"
	.string "If I had some left over, I'd gladly\n"
	.string "give you one...\p"
	.string "But, I don't have any to spare today.\n"
	.string "Sorry about that.$"
