gText_ConfirmSave:: @ 81C6C85
	.string "Would you like to save the game?$"

gText_AlreadySavedFile:: @ 81C6CA6
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff:: @ 81C6CE1
	.string "SAVING...\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame:: @ 81C6D05
	.string "{PLAYER} saved the game.$"

gText_SaveError:: @ 81C6D18
	.string "Save error...$"

gText_DifferentSaveFile:: @ 81C6D26
	.string "There is a different game file that is\n"
	.string "already saved.\p"
	.string "Is it okay to overwrite it?$"
