SecretBase_Text_TreeCanBeClimbed: @ 81A1948
	.string "If some vines drop down, this tree can\n"
	.string "be climbed.$"

SecretBase_Text_TreeUseSecretPower: @ 81A197B
	.string "If some vines drop down, this tree can\n"
	.string "be climbed.\p"
	.string "Use the SECRET POWER?$"

SecretBase_Text_VineDroppedDown: @ 81A19C4
	.string "A thick vine dropped down!$"

SecretBase_Text_TreeWantToMakeYourSecretBaseHere: @ 81A19DF
	.string "Want to make your SECRET BASE here?$"

SecretBase_Text_ClumpOfGrass: @ 81A1A03
	.string "If this clump of grass can be moved,\n"
	.string "it might be possible to go inside.$"

SecretBase_Text_ClumpUseSecretPower: @ 81A1A4B
	.string "If this clump of grass can be moved,\n"
	.string "it might be possible to go inside.\p"
	.string "Use the SECRET POWER?$"

SecretBase_Text_DiscoveredSmallEntrance: @ 81A1AA9
	.string "Discovered a small entrance!$"

SecretBase_Text_ShrubWantToMakeYourSecretBaseHere: @ 81A1AC6
	.string "Want to make your SECRET BASE here?$"
