ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:: @ 81C6668
	.string "Are you planning on going deep in\n"
	.string "there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can make you something good if\n"
	.string "you bring me the ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:: @ 81C670D
	.string "If you bring me four each of the\n"
	.string "SHOAL SALT and SHOAL SHELLS,\l"
	.string "I can make you a SHELL BELL...\p"
	.string "You can get those ingredients\n"
	.string "every day.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:: @ 81C6793
	.string "Oh, hey! SHOAL SALT and SHOAL\n"
	.string "SHELLS! And enough of them, too!\p"
	.string "Would you like me to make you a\n"
	.string "SHELL BELL with them?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:: @ 81C6808
	.string "All righty, then! I'll make you a\n"
	.string "SHELL BELL right away.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "There! Done!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:: @ 81C688E
	.string "Have a POKéMON hold on to that.\n"
	.string "It'll love it, that's for certain.\p"
	.string "Why, the SHELL BELL's chime...\n"
	.string "It's simply sublime!\p"
	.string "You can get its ingredients every\n"
	.string "day, so I can make you more.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:: @ 81C6944
	.string "Oh... Is that so...\n"
	.string "I wanted to make a SHELL BELL...$"

ShoalCave_Text_WasShoalSaltNowNothing:: @ 81C6979
	.string "There was some SHOAL SALT here.\n"
	.string "But, there's nothing here now.$"

ShoalCave_Text_WasShoallShellNowNothing:: @ 81C69B8
	.string "There was a SHOAL SHELL here.\n"
	.string "But, there's nothing here now.$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:: @ 81C69F5
	.string "You don't have space in your BAG\n"
	.string "if I were to make it for you.\p"
	.string "You should make room and come back\n"
	.string "for a SHELL BELL.$"
