MauvilleCity_PokemonCenter_1F_Text_WantToTradeDecor:: @ 81AE88F
	.string "Hi, I'm the TRADER.\n"
	.string "Want to trade decorations with me?$"

MauvilleCity_PokemonCenter_1F_Text_TraderFeelingTheBlues:: @ 81AE8C6
	.string "Oh...\n"
	.string "I feel unwanted...$"

MauvilleCity_PokemonCenter_1F_Text_WeveAlreadyTraded:: @ 81AE8DF
	.string "But we've traded decorations already,\n"
	.string "you and I.$"

MauvilleCity_PokemonCenter_1F_Text_PickADecorItem:: @ 81AE910
	.string "If you see any decorative item that\n"
	.string "you want of mine, speak up.$"

MauvilleCity_PokemonCenter_1F_Text_YouDontWantAnything:: @ 81AE950
	.string "You don't want anything?\n"
	.string "I feel unwanted...$"

MauvilleCity_PokemonCenter_1F_Text_OnceBelongedToPlayerDoYouWantIt:: @ 81AE97C
	.string "That decorative item once belonged\n"
	.string "to {STR_VAR_1}.\p"
	.string "Do you want it?$"

MauvilleCity_PokemonCenter_1F_Text_YouDontHaveAnyDecor:: @ 81AE9B6
	.string "Uh... Wait a second. You don't have a\n"
	.string "single piece of decoration!$"

MauvilleCity_PokemonCenter_1F_Text_PickTheDecorToTrade:: @ 81AE9F8
	.string "Okay, pick the decoration that you'll\n"
	.string "trade to me.$"

MauvilleCity_PokemonCenter_1F_Text_YouDontWantToTrade:: @ 81AEA2B
	.string "You won't trade with me?\n"
	.string "I feel unwanted...$"

MauvilleCity_PokemonCenter_1F_Text_YouveNoRoomForThis:: @ 81AEA57
	.string "You've got all the {STR_VAR_2}S that can\n"
	.string "be stored. You've no room for this.$"

MauvilleCity_PokemonCenter_1F_Text_SoWellTradeTheseDecor:: @ 81AEA9B
	.string "Okay, so we'll trade my {STR_VAR_3}\n"
	.string "for your {STR_VAR_2}?$"

MauvilleCity_PokemonCenter_1F_Text_ThatDecorIsInUse:: @ 81AEAC3
	.string "That piece of decoration is in use.\n"
	.string "You can't trade it.$"

MauvilleCity_PokemonCenter_1F_Text_SendDecorToYourPC:: @ 81AEAFB
	.string "Then we'll trade!\n"
	.string "I'll send my decoration to your PC.$"

MauvilleCity_PokemonCenter_1F_Text_CantTradeThatOne:: @ 81AEB31
	.string "Oops! Sorry!\n"
	.string "That's a really rare piece of decoration.\l"
	.string "I can't trade that one away!\p"
	.string "Can I interest you in something else?$"
