Route102_Text_CalvinIntro:: @ 81B79C3
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Arrgh, I lost...\n"
	.string "I should have trained mine more...$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Listen, you. If you're strong, you\n"
	.string "should have told me before!$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Arrgh, I lost...\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "If you're going to get stronger, I'll\n"
	.string "get stronger, too.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "I called you because I thought I\n"
	.string "could beat you...$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "I haven't won once yet...\n"
	.string "I wish I would win soon...$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my BUG POKéMON!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "I ended up furthering your career...$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route110/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

.include "data/maps/Route114/trainer_text.inc"

.include "data/maps/Route115/trainer_text.inc"

.include "data/maps/Route116/trainer_text.inc"

.include "data/maps/Route117/trainer_text.inc"

.include "data/maps/Route118/trainer_text.inc"

.include "data/maps/Route119/trainer_text.inc"

.include "data/maps/Route120/trainer_text.inc"

.include "data/maps/Route121/trainer_text.inc"

.include "data/maps/Route123/trainer_text.inc"

.include "data/maps/Route124/trainer_text.inc"

.include "data/maps/Route125/trainer_text.inc"

.include "data/maps/Route126/trainer_text.inc"

.include "data/maps/Route127/trainer_text.inc"

.include "data/maps/Route128/trainer_text.inc"

.include "data/maps/Route129/trainer_text.inc"

.include "data/maps/Route130/trainer_text.inc"

.include "data/maps/Route131/trainer_text.inc"

.include "data/maps/Route132/trainer_text.inc"

Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated. Let's battle!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here...\l"
	.string "I must be cursed...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "I've led a life of woe and misery...\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Another loss...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "A life adrift...\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "No! Please!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "A strong child TRAINER...\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "You...\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "I'd like to go back to FORTREE, but I've\n"
	.string "grown to like this place, too.$"

Route134_Text_JackIntro:: @ 81C30C6
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "There's a collector who's after the\n"
	.string "SCALES of LUVDISC.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Tuckered out again...$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed...$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "I concede defeat.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"
