Route102_Text_CalvinIntro:: @ 81B79C3
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Arrgh, I lost...\n"
	.string "I should have trained mine more...$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Listen, you. If you're strong, you\n"
	.string "should have told me before!$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Arrgh, I lost...\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "If you're going to get stronger, I'll\n"
	.string "get stronger, too.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "I called you because I thought I\n"
	.string "could beat you...$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "I haven't won once yet...\n"
	.string "I wish I would win soon...$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my BUG POKéMON!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "I ended up furthering your career...$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route110/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

Route114_Text_LennyIntro:: @ 81BC05B
	.string "Yodelayhihoo!\p"
	.string "... ...\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_LennyDefeat:: @ 81BC0B5
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:: @ 81BC0C3
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:: @ 81BC125
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_LucasDefeat:: @ 81BC163
	.string "The mountains are unforgiving...$"

Route114_Text_LucasPostBattle:: @ 81BC184
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_ShaneIntro:: @ 81BC1C8
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_ShaneDefeat:: @ 81BC23F
	.string "Way too strong!$"

Route114_Text_ShanePostBattle:: @ 81BC24F
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_NancyIntro:: @ 81BC289
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_NancyDefeat:: @ 81BC2BE
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:: @ 81BC2C6
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy...$"

Route114_Text_SteveIntro:: @ 81BC2F5
	.string "Ufufufufufu...\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_SteveDefeat:: @ 81BC327
	.string "M-My POKéMON...$"

Route114_Text_StevePostBattle:: @ 81BC337
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs...\p"
	.string "Ufufufufu...\n"
	.string "I wish I had a POKéMON like that...$"

Route114_Text_SteveRematchIntro:: @ 81BC3B3
	.string "Ufufufufufu...\n"
	.string "Come on, battle my POKéMON...$"

Route114_Text_SteveRematchDefeat:: @ 81BC3E0
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON...$"

Route114_Text_StevePostRematch:: @ 81BC40F
	.string "Ufufufufufu...\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky...$"

Route114_Text_BernieIntro:: @ 81BC45A
	.string "If you're lighting a campfire, make\n"
	.string "sure you have water handy.$"

Route114_Text_BernieDefeat:: @ 81BC499
	.string "Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:: @ 81BC4B5
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_BernieRematchIntro:: @ 81BC525
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:: @ 81BC559
	.string "I got hosed down before I could flare\n"
	.string "up, I guess.$"

Route114_Text_BerniePostRematch:: @ 81BC58C
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:: @ 81BC5FC
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_ClaudeDefeat:: @ 81BC653
	.string "If we were fishing, I would've won...$"

Route114_Text_ClaudePostBattle:: @ 81BC679
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_NolanIntro:: @ 81BC6EC
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_NolanDefeat:: @ 81BC750
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it...$"

Route114_Text_NolanPostBattle:: @ 81BC78A
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_TyraIntro:: @ 81BC7E3
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_TyraDefeat:: @ 81BC834
	.string "TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:: @ 81BC858
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_TyraNotEnoughMons:: @ 81BC88A
	.string "TYRA: Giggle...\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_IvyIntro:: @ 81BC8D8
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_IvyDefeat:: @ 81BC8FB
	.string "IVY: What an amazing battle style!$"

Route114_Text_IvyPostBattle:: @ 81BC91E
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons:: @ 81BC96A
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"

Route115_Text_TimothyIntro:: @ 81BC9AC
	.string "Hm...\n"
	.string "You seem rather capable...\l"
	.string "Let me keep you company!$"

Route115_Text_TimothyDefeat:: @ 81BC9E6
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_TimothyPostBattle:: @ 81BCA0E
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe...$"

Route115_Text_TimothyRematchIntro:: @ 81BCA6B
	.string "Hm... As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:: @ 81BCAB3
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch:: @ 81BCAC6
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:: @ 81BCB0D
	.string "You!\p"
	.string "My MACHOP!\p"
	.string "Demand a battle!$"

Route115_Text_KoichiDefeat:: @ 81BCB2E
	.string "Ouch, ouch, ouch!$"

Route115_Text_KoichiPostBattle:: @ 81BCB40
	.string "My MACHOP crew!\p"
	.string "So long as they seek power, I will\n"
	.string "grow strong with them!$"

Route115_Text_NobIntro:: @ 81BCB8A
	.string "My strongest skill is busting bricks\n"
	.string "with my forehead!$"

Route115_Text_NobDefeat:: @ 81BCBC1
	.string "Ugwaaaah!\n"
	.string "My head is busted!$"

Route115_Text_NobPostBattle:: @ 81BCBDE
	.string "I've been teaching my POKéMON karate.\p"
	.string "It looks like they'll get a lot better\n"
	.string "than me. I'm excited about that.$"

Route115_Text_NobRematchIntro:: @ 81BCC4C
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat:: @ 81BCCA2
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_NobPostRematch:: @ 81BCCBA
	.string "My POKéMON will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_CyndyIntro:: @ 81BCCF4
	.string "This beach is my secret training spot!\n"
	.string "Don't come butting in!$"

Route115_Text_CyndyDefeat:: @ 81BCD32
	.string "I haven't trained enough!$"

Route115_Text_CyndyPostBattle:: @ 81BCD4C
	.string "The sand acts as a cushion to reduce\n"
	.string "impact and prevent injury.\l"
	.string "This is the perfect place to train.$"

Route115_Text_CyndyRematchIntro:: @ 81BCDB0
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat:: @ 81BCDD0
	.string "I can battle but my POKéMON...$"

Route115_Text_CyndyPostRematch:: @ 81BCDEF
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love POKéMON.$"

Route115_Text_HectorSapphireIntro: @ 81BCE47
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorSapphireDefeat: @ 81BCE7D
	.string "You...\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_HectorSapphirePostBattle: @ 81BCEA4
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route115_Text_HectorIntro:: @ 81BCEE0
	.string "I have a rare POKéMON!\n"
	.string "Would you like me to show you?$"

Route115_Text_HectorDefeat:: @ 81BCF16
	.string "You...\n"
	.string "You want my POKéMON, don't you?$"

Route115_Text_HectorPostBattle:: @ 81BCF3D
	.string "I have this rare POKéMON.\n"
	.string "It's enough to keep me satisfied.$"

Route116_Text_ClarkIntro:: @ 81BCF79
	.string "If the tunnel doesn't go through, then\n"
	.string "I'll just go over the top.$"

Route116_Text_ClarkDefeat:: @ 81BCFBB
	.string "Gasp... Gasp...\n"
	.string "Losing made me tired...$"

Route116_Text_ClarkPostBattle:: @ 81BCFE3
	.string "It's no big deal if there's no tunnel.\n"
	.string "To a HIKER, mountains are roads!$"

Route116_Text_JoeyIntro:: @ 81BD02B
	.string "My POKéMON rule!\n"
	.string "Check them out!$"

Route116_Text_JoeyDefeat:: @ 81BD04C
	.string "Ouch! A scrape!\n"
	.string "I have to put on a bandage!$"

Route116_Text_JoeyPostBattle:: @ 81BD078
	.string "Bandages are signs of toughness!\n"
	.string "I've got another one!$"

Route116_Text_JoseIntro:: @ 81BD0AF
	.string "My BUG POKéMON are tough!\n"
	.string "Let's battle!$"

Route116_Text_JoseDefeat:: @ 81BD0D7
	.string "I lost!\n"
	.string "I thought I had you!$"

Route116_Text_JosePostBattle:: @ 81BD0F4
	.string "BUG POKéMON evolve quickly.\n"
	.string "So they get strong quickly, too.$"

Route116_Text_JaniceIntro:: @ 81BD131
	.string "Let me teach you how strong my\n"
	.string "adorable POKéMON is!$"

Route116_Text_JaniceDefeat:: @ 81BD165
	.string "You're a notch above me...$"

Route116_Text_JanicePostBattle:: @ 81BD180
	.string "POKéMON that possess cuteness and\n"
	.string "power, that's ideal, I think.$"

Route116_Text_JerryIntro:: @ 81BD1C0
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test things out for real!$"

Route116_Text_JerryDefeat:: @ 81BD21A
	.string "I slacked off in school...\n"
	.string "That's why I lost.$"

Route116_Text_JerryPostBattle:: @ 81BD248
	.string "I'll have to redo some courses at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_JerryRematchIntro:: @ 81BD2A5
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat:: @ 81BD2FE
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch:: @ 81BD31A
	.string "I'll have to redo some courses at the\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "If I don't, ROXANNE will be steamed.$"

Route116_Text_KarenIntro:: @ 81BD377
	.string "I study at school, and I study on the\n"
	.string "way home, too!$"

Route116_Text_KarenDefeat:: @ 81BD3AC
	.string "I'm in shock - I lost?$"

Route116_Text_KarenPostBattle:: @ 81BD3C3
	.string "Awww, I'll never become an elegant\n"
	.string "TRAINER like ROXANNE this way!$"

Route116_Text_KarenRematchIntro:: @ 81BD405
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat:: @ 81BD44A
	.string "I'm in shock. I lost again?$"

Route116_Text_KarenPostRematch:: @ 81BD466
	.string "You've beaten ROXANNE?\n"
	.string "I can't beat you, then. Not yet.$"

Route117_Text_IsaacIntro:: @ 81BD49E
	.string "Listen, could I get you to battle the\n"
	.string "POKéMON I'm raising?$"

Route117_Text_IsaacDefeat:: @ 81BD4D9
	.string "You've raised yours superbly...$"

Route117_Text_IsaacPostBattle:: @ 81BD4F9
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_IsaacRematchIntro:: @ 81BD569
	.string "The POKéMON I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:: @ 81BD5AB
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills...$"

Route117_Text_IsaacPostRematch:: @ 81BD5F2
	.string "Your POKéMON are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:: @ 81BD634
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your POKéMON properly.$"

Route117_Text_LydiaDefeat:: @ 81BD67B
	.string "Yes, they are growing properly.$"

Route117_Text_LydiaPostBattle:: @ 81BD69B
	.string "If you feed {POKEBLOCK}S to POKéMON, the\n"
	.string "unique aspects of their character\l"
	.string "will be enhanced.$"

Route117_Text_LydiaRematchIntro:: @ 81BD6F2
	.string "Allow me to reevaluate if you have\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaRematchDefeat:: @ 81BD733
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch:: @ 81BD74F
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:: @ 81BD79A
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's have a battle!$"

Route117_Text_DylanDefeat:: @ 81BD7E0
	.string "I ran out of energy!$"

Route117_Text_DylanPostBattle:: @ 81BD7F5
	.string "I may have blown it...\p"
	.string "I might have dropped to last during\n"
	.string "that battle...$"

Route117_Text_DylanRematchIntro:: @ 81BD83F
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:: @ 81BD8A2
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:: @ 81BD8BD
	.string "I was tops in swimming and cycling, but\n"
	.string "I'm not quite that confident with\l"
	.string "POKéMON yet.$"

Route117_Text_MariaIntro:: @ 81BD914
	.string "I do my triathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:: @ 81BD965
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:: @ 81BD98F
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_MariaRematchIntro:: @ 81BD9F1
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:: @ 81BDA41
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:: @ 81BDA6B
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:: @ 81BDAA7
	.string "Once a BUG CATCHER!\n"
	.string "And now a BUG MANIAC!\p"
	.string "But my love for POKéMON remains\n"
	.string "unchanged!$"

Route117_Text_DerekDefeat:: @ 81BDAFC
	.string "My ineptitude also remains\n"
	.string "unchanged...$"

Route117_Text_DerekPostBattle:: @ 81BDB24
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC...\p"
	.string "Still, I am an expert on BUG POKéMON,\n"
	.string "so it's only natural that they call me\l"
	.string "a BUG MANIAC.$"

Route117_Text_AnnaIntro:: @ 81BDBC3
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_AnnaDefeat:: @ 81BDC07
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_AnnaPostBattle:: @ 81BDC44
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaNotEnoughMons:: @ 81BDC96
	.string "ANNA: If you want to battle us, bring\n"
	.string "two POKéMON with you.$"

Route117_Text_MegIntro:: @ 81BDCD2
	.string "MEG: I'm going to tag up with my super\n"
	.string "senior student partner and beat you!$"

Route117_Text_MegDefeat:: @ 81BDD1E
	.string "MEG: Oh, no!\n"
	.string "I'm sorry, ANNA! I let you down...$"

Route117_Text_MegPostBattle:: @ 81BDD4E
	.string "MEG: I dragged ANNA down...\n"
	.string "If I didn't, she would have won!$"

Route117_Text_MegNotEnoughMons:: @ 81BDD8B
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:: @ 81BDDEF
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:: @ 81BDE2F
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:: @ 81BDE55
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:: @ 81BDEA7
	.string "ANNA: If you want to battle us, bring\n"
	.string "two POKéMON with you.$"

Route117_Text_MegRematchIntro:: @ 81BDEE3
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat:: @ 81BDF26
	.string "MEG: Too strong!$"

Route117_Text_MegPostRematch:: @ 81BDF37
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost...\p"
	.string "That's so discouraging...$"

Route117_Text_MegRematchNotEnoughMons:: @ 81BDF90
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route118_Text_RoseIntro:: @ 81BDFF4
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_RoseDefeat:: @ 81BE03C
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_RosePostBattle:: @ 81BE05E
	.string "Flowers, POKéMON...\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things...\n"
	.string "I'll pass.$"

Route118_Text_RoseRematchIntro:: @ 81BE0AB
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:: @ 81BE0D3
	.string "The power of aroma...\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch:: @ 81BE104
	.string "If you use a sweet aroma properly,\n"
	.string "POKéMON will be attracted by it.$"

Route118_Text_PerryIntro:: @ 81BE148
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky... They're the best!$"

Route118_Text_PerryDefeat:: @ 81BE188
	.string "Urgh... I crashed...$"

Route118_Text_PerryPostBattle:: @ 81BE19D
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_ChesterIntro:: @ 81BE1D7
	.string "Take flight!\n"
	.string "My BIRD POKéMON!$"

Route118_Text_ChesterDefeat:: @ 81BE1F5
	.string "They did take flight...$"

Route118_Text_ChesterPostBattle:: @ 81BE20D
	.string "If they'd get stronger, they'd be able\n"
	.string "to fly more freely...$"

Route118_Text_BarnyIntro:: @ 81BE24A
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'm raising the POKéMON I caught.$"

Route118_Text_BarnyDefeat:: @ 81BE291
	.string "I thought I was doing okay in my\n"
	.string "training...$"

Route118_Text_BarnyPostBattle:: @ 81BE2BE
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished...\p"
	.string "Was I doing things in half measures?$"

Route118_Text_WadeIntro:: @ 81BE318
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are POKéMON and heart, of course!$"

Route118_Text_WadeDefeat:: @ 81BE385
	.string "I was beaten in heart?$"

Route118_Text_WadePostBattle:: @ 81BE39C
	.string "Come to think of it, fishing is a battle\n"
	.string "between a FISHERMAN and a POKéMON.$"

Route118_Text_DaltonIntro:: @ 81BE3E8
	.string "Let my melody rock your soul!$"

Route118_Text_DaltonDefeat:: @ 81BE406
	.string "La-lalala...$"

Route118_Text_DaltonPostBattle:: @ 81BE413
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy...\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody...$"

Route118_Text_DaltonRematchIntro:: @ 81BE489
	.string "A melody from my POKéMON and me...\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:: @ 81BE4CC
	.string "La-lalala...$"

Route118_Text_DaltonPostRematch:: @ 81BE4D9
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar...$"

Route119_Text_BrentIntro:: @ 81BE521
	.string "We're the MIMIC CIRCLE!\n"
	.string "We MIMIC what you do!$"

Route119_Text_BrentDefeat:: @ 81BE54F
	.string "Whoopsie!\n"
	.string "I lost!$"

Route119_Text_BrentPostBattle:: @ 81BE561
	.string "What's so good about mimicry?\p"
	.string "Fufufu...\n"
	.string "You'll never understand...$"

Route119_Text_DonaldIntro:: @ 81BE5A4
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_DonaldDefeat:: @ 81BE5DF
	.string "I wish we'd never met...$"

Route119_Text_DonaldPostBattle:: @ 81BE5F8
	.string "I want to MIMIC you some more.\p"
	.string "Can you hurry up and move?$"

Route119_Text_TaylorIntro:: @ 81BE632
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too...$"

Route119_Text_TaylorDefeat:: @ 81BE67B
	.string "But if you win, I lose...$"

Route119_Text_TaylorPostBattle:: @ 81BE695
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible...\l"
	.string "It's burning me up...$"

Route119_Text_DougIntro:: @ 81BE6EA
	.string "Yep, you've finally caught me!\n"
	.string "Or were you trying to avoid me?$"

Route119_Text_DougDefeat:: @ 81BE729
	.string "Whoop, that was a great match!$"

Route119_Text_DougPostBattle:: @ 81BE748
	.string "We're the MIMIC CIRCLE!\n"
	.string "I hope you enjoyed our performance.$"

Route119_Text_GregIntro:: @ 81BE784
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you.\n"
	.string "So, we'll battle!$"

Route119_Text_GregDefeat:: @ 81BE7D3
	.string "You're pretty strong!$"

Route119_Text_GregPostBattle:: @ 81BE7E9
	.string "Until you go away somewhere, we'll\n"
	.string "keep on mimicking your every move.$"

Route119_Text_KentIntro:: @ 81BE82F
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_KentDefeat:: @ 81BE88D
	.string "I surrender!$"

Route119_Text_KentPostBattle:: @ 81BE89A
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:: @ 81BE8BB
	.string "Who has the knowledge and the\n"
	.string "technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonDefeat:: @ 81BE90E
	.string "I didn't have enough POKéMON\n"
	.string "know-how...$"

Route119_Text_JacksonPostBattle:: @ 81BE937
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRematchIntro:: @ 81BE98D
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:: @ 81BE9D0
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch:: @ 81BE9E8
	.string "Believe in your POKéMON.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro:: @ 81BEA3A
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure, you're\n"
	.string "traveling awfully light.$"

Route119_Text_CatherineDefeat:: @ 81BEA88
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherinePostBattle:: @ 81BEAB3
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_CatherineRematchIntro:: @ 81BEB22
	.string "How's your journey with POKéMON\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat:: @ 81BEB49
	.string "I'm still missing something...$"

Route119_Text_CatherinePostRematch:: @ 81BEB68
	.string "In the same way that you, as a TRAINER,\n"
	.string "rely on your POKéMON, your POKéMON\l"
	.string "rely on you.$"

Route119_Text_HughIntro:: @ 81BEBC0
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_HughDefeat:: @ 81BEC1C
	.string "Down and out!$"

Route119_Text_HughPostBattle:: @ 81BEC2A
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_PhilIntro:: @ 81BEC5E
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_PhilDefeat:: @ 81BEC9A
	.string "We lacked potential...$"

Route119_Text_PhilPostBattle:: @ 81BECB1
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON...$"

Route119_Text_YasuIntro:: @ 81BECF1
	.string "To lurk in shadows, and live in\n"
	.string "darkness... That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:: @ 81BED4C
	.string "I admit defeat!$"

Route119_Text_YasuPostBattle:: @ 81BED5C
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows.\l"
	.string "That, too, is destiny...$"

Route119_Text_TakashiIntro:: @ 81BEDB6
	.string "If you're not on your guard, you're in\n"
	.string "for some pain!$"

Route119_Text_TakashiDefeat:: @ 81BEDEC
	.string "You're surprisingly good!$"

Route119_Text_TakashiPostBattle:: @ 81BEE06
	.string "My surprise attack ended in\n"
	.string "failure...$"

Route119_Text_HideoIntro:: @ 81BEE2D
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoDefeat:: @ 81BEE4B
	.string "I bow to your superiority.$"

Route119_Text_HideoPostBattle:: @ 81BEE66
	.string "To hide a tree, use a forest!\n"
	.string "To hide a POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning\n"
	.string "to that.$"

Route119_Text_EugeneIntro:: @ 81BEED0
	.string "You spoke to me...\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_EugeneDefeat:: @ 81BEF37
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_EugenePostBattle:: @ 81BEF67
	.string "Go for a SURF on my POKéMON...\p"
	.string "Then fish off its back...\p"
	.string "It's an indescribably luxuriant moment!$"

Route120_Text_ColinIntro:: @ 81BEFC8
	.string "Do you have any moves that can strike\n"
	.string "a flying POKéMON?$"

Route120_Text_ColinDefeat:: @ 81BF000
	.string "You soared above me!$"

Route120_Text_ColinPostBattle:: @ 81BF015
	.string "The move FLY is convenient, don't\n"
	.string "you think?\p"
	.string "While the POKéMON is flying, almost\n"
	.string "no moves can strike it.$"

Route120_Text_RobertIntro:: @ 81BF07E
	.string "My POKéMON is strong!\n"
	.string "How about yours?$"

Route120_Text_RobertDefeat:: @ 81BF0A5
	.string "Your POKéMON were stronger...$"

Route120_Text_RobertPostBattle:: @ 81BF0C3
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchIntro:: @ 81BF0FA
	.string "A POKéMON that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat:: @ 81BF131
	.string "Your POKéMON are seriously strong.$"

Route120_Text_RobertPostRematch:: @ 81BF154
	.string "My POKéMON are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_CarlosIntro:: @ 81BF193
	.string "I'll check your POKéMON and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_CarlosDefeat:: @ 81BF1D4
	.string "With POKéMON that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_CarlosPostBattle:: @ 81BF215
	.string "To travel wherever your heart desires\n"
	.string "with POKéMON...\l"
	.string "That's the joy of being a TRAINER.$"

Route120_Text_JennaIntro:: @ 81BF26E
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat:: @ 81BF2D2
	.string "I'm totally fit, but...$"

Route120_Text_JennaPostBattle:: @ 81BF2EA
	.string "Fitness training is in my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_BrandonIntro:: @ 81BF32B
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Want to battle?$"

Route120_Text_BrandonDefeat:: @ 81BF36B
	.string "... ... ... ... ... ...\n"
	.string "I lost...$"

Route120_Text_BrandonPostBattle:: @ 81BF38D
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "I'll try harder...$"

Route120_Text_BrandonRematchIntro:: @ 81BF3D0
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Want to battle again?$"

Route120_Text_BrandonRematchDefeat:: @ 81BF416
	.string "... ... ... ... ... ...\n"
	.string "I lost again...$"

Route120_Text_BrandonPostRematch:: @ 81BF43E
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "I'll try harder...\l"
	.string "For my precious BUG POKéMON...$"

Route120_Text_JenniferIntro:: @ 81BF4A0
	.string "POKéMON have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "TRAINER, learn about them.$"

Route120_Text_JenniferDefeat:: @ 81BF504
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle:: @ 81BF51F
	.string "The special abilities of POKéMON\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro:: @ 81BF560
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat:: @ 81BF5D6
	.string "What a disgraceful setback...$"

Route120_Text_ChipPostBattle:: @ 81BF5F4
	.string "That giant rock... I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro:: @ 81BF65B
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can win against me.$"

Route120_Text_ClarissaDefeat:: @ 81BF6A4
	.string "A parasol can't ward off POKéMON\n"
	.string "attacks...$"

Route120_Text_ClarissaPostBattle:: @ 81BF6D0
	.string "I don't think strong sunlight is good\n"
	.string "for my POKéMON.\l"
	.string "So I shield them with my parasol.$"

Route120_Text_AngelicaIntro:: @ 81BF728
	.string "Me, POKéMON, and my parasol...\p"
	.string "If any one of them is missing, the\n"
	.string "picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat:: @ 81BF78C
	.string "You've completely ruined my beauty...$"

Route120_Text_AngelicaPostBattle:: @ 81BF7B2
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro:: @ 81BF80B
	.string "I will adopt the movements of POKéMON\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat:: @ 81BF852
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream...$"

Route120_Text_KeigoPostBattle:: @ 81BF891
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_TsunaoIntro:: @ 81BF8C5
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_TsunaoDefeat:: @ 81BF920
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_TsunaoPostBattle:: @ 81BF946
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route121_Text_VanessaIntro:: @ 81BF96E
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:: @ 81BF9A1
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:: @ 81BF9BA
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:: @ 81BFA1B
	.string "With my POKéMON, I have traveled the\n"
	.string "world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:: @ 81BFA8C
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:: @ 81BFA9D
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRematchIntro:: @ 81BFADA
	.string "With my POKéMON, I have traveled the\n"
	.string "world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:: @ 81BFB4B
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:: @ 81BFB5C
	.string "Your POKéMON and you...\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:: @ 81BFBB4
	.string "There are powers beyond our\n"
	.string "understanding in the world...$"

Route121_Text_TammyDefeat:: @ 81BFBEE
	.string "I have lost...$"

Route121_Text_TammyPostBattle:: @ 81BFBFD
	.string "MT. PYRE...\n"
	.string "There is a mysterious power\l"
	.string "at work there...$"

Route121_Text_KateIntro:: @ 81BFC36
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:: @ 81BFC7A
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner...$"

Route121_Text_KatePostBattle:: @ 81BFCB3
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them...$"

Route121_Text_KateNotEnoughMons:: @ 81BFD08
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:: @ 81BFD60
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:: @ 81BFDA3
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:: @ 81BFDC1
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:: @ 81BFE0D
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:: @ 81BFE51
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:: @ 81BFE80
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:: @ 81BFEAE
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRematchIntro:: @ 81BFEDE
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:: @ 81BFF0A
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:: @ 81BFF3A
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route123_Text_WendyIntro:: @ 81BFF6A
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:: @ 81BFFA2
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:: @ 81BFFC1
	.string "To best even me...\n"
	.string "Your strength is marvelous!$"

Route123_Text_ClydeIntro:: @ 81BFFF0
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_ClydeDefeat:: @ 81C0057
	.string "Oh, you're worthy, all right!$"

Route123_Text_ClydePostBattle:: @ 81C0075
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:: @ 81C009E
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:: @ 81C00D4
	.string "Oh...\n"
	.string "I smell the bitter scent of misery...$"

Route123_Text_VioletPostBattle:: @ 81C0100
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:: @ 81C013F
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:: @ 81C01A3
	.string "I feel sad...$"

Route123_Text_CameronPostBattle:: @ 81C01B1
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you...$"

Route123_Text_CameronRematchIntro:: @ 81C01F9
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:: @ 81C0240
	.string "I feel sad...$"

Route123_Text_CameronPostRematch:: @ 81C024E
	.string "I should train at MT. PYRE...\n"
	.string "I'll never beat you this way...$"

Route123_Text_JackiIntro:: @ 81C028C
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:: @ 81C0303
	.string "Astounding!$"

Route123_Text_JackiPostBattle:: @ 81C030F
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRematchIntro:: @ 81C0351
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:: @ 81C0380
	.string "Astounding!$"

Route123_Text_JackiPostRematch:: @ 81C038C
	.string "Your power with POKéMON...\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:: @ 81C03CB
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:: @ 81C040E
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:: @ 81C0423
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:: @ 81C0462
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:: @ 81C049C
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:: @ 81C04CD
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:: @ 81C04E3
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:: @ 81C0519
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:: @ 81C0554
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:: @ 81C059F
	.string "Overflowing with vitality...$"

Route123_Text_KindraPostBattle:: @ 81C05BC
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits...$"

Route124_Text_SpencerIntro:: @ 81C0624
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON, I can\n"
	.string "serve as your pilot.$"

Route124_Text_SpencerDefeat:: @ 81C0675
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:: @ 81C0693
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:: @ 81C06F7
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself...\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:: @ 81C0741
	.string "Oh!\n"
	.string "I can't...$"

Route124_Text_RolandPostBattle:: @ 81C0750
	.string "I'm getting chilled...\n"
	.string "I've been in the water too long...\p"
	.string "I wish I could ride a POKéMON like you...$"

Route124_Text_JennyIntro:: @ 81C07B4
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:: @ 81C07F9
	.string "Oh...\n"
	.string "Lost at sea...$"

Route124_Text_JennyPostBattle:: @ 81C080E
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRematchIntro:: @ 81C0888
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:: @ 81C08C8
	.string "That's strange...\n"
	.string "I lost again...$"

Route124_Text_JennyPostRematch:: @ 81C08EA
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:: @ 81C0936
	.string "I'm growing bored of swimming...\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:: @ 81C096B
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:: @ 81C0994
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:: @ 81C09CE
	.string "Fufufufu... I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:: @ 81C0A2F
	.string "Glub, glub, glub...\n"
	.string "I'm sinking...$"

Route124_Text_ChadPostBattle:: @ 81C0A52
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again...$"

Route124_Text_RitaIntro:: @ 81C0ABD
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_RitaDefeat:: @ 81C0B36
	.string "RITA: SAM! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_RitaPostBattle:: @ 81C0B72
	.string "RITA: Sigh...\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend...$"

Route124_Text_RitaNotEnoughMons:: @ 81C0BC8
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamIntro:: @ 81C0C0E
	.string "SAM: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_SamDefeat:: @ 81C0C4F
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out...$"

Route124_Text_SamPostBattle:: @ 81C0C7F
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_SamNotEnoughMons:: @ 81C0CE0
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"

Route124_Text_RitaRematchIntro:: @ 81C0D1F
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_RitaRematchDefeat:: @ 81C0DB5
	.string "RITA: SAM!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_RitaPostRematch:: @ 81C0E06
	.string "RITA: Sigh...\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations...$"

Route124_Text_RitaRematchNotEnoughMons:: @ 81C0E5C
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamRematchIntro:: @ 81C0EA2
	.string "SAM: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_SamRematchDefeat:: @ 81C0EE5
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out again.$"

Route124_Text_SamPostRematch:: @ 81C0F19
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later...$"

Route124_Text_SamRematchNotEnoughMons:: @ 81C0F90
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"

Route125_Text_CodyIntro:: @ 81C0FCF
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_CodyDefeat:: @ 81C1002
	.string "I beg for peace!$"

Route125_Text_CodyPostBattle:: @ 81C1013
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:: @ 81C104B
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:: @ 81C1073
	.string "I floundered...$"

Route125_Text_StanPostBattle:: @ 81C1083
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:: @ 81C10C3
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:: @ 81C10FB
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:: @ 81C110C
	.string "Whew...\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:: @ 81C1136
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:: @ 81C1175
	.string "I lost...$"

Route125_Text_SharonPostBattle:: @ 81C117F
	.string "Your power... You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:: @ 81C11AF
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:: @ 81C11ED
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:: @ 81C1208
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRematchIntro:: @ 81C1282
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:: @ 81C12C5
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:: @ 81C12EE
	.string "The SHOAL CAVE...\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:: @ 81C13A1
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:: @ 81C13FF
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:: @ 81C141C
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:: @ 81C146E
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:: @ 81C14AB
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:: @ 81C14E7
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:: @ 81C1508
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:: @ 81C154F
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route126_Text_BarryIntro:: @ 81C1590
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:: @ 81C15C3
	.string "I admit it! You win!$"

Route126_Text_BarryPostBattle:: @ 81C15D8
	.string "Thanks to my daily swimming routine...\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:: @ 81C1627
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:: @ 81C1660
	.string "I was done in?$"

Route126_Text_DeanPostBattle:: @ 81C166F
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:: @ 81C16AB
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:: @ 81C16C5
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub...$"

Route126_Text_NikkiPostBattle:: @ 81C1702
	.string "You thrashed me... I want to\n"
	.string "disappear in a wave of despair...$"

Route126_Text_BrendaIntro:: @ 81C1741
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:: @ 81C1766
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:: @ 81C1773
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route127_Text_CalebIntro:: @ 81C17A8
	.string "I can see it in your face. You want\n"
	.string "to challenge me.$"

Route127_Text_CalebDefeat:: @ 81C17DD
	.string "Awawawawawa...$"

Route127_Text_CalebPostBattle:: @ 81C17EC
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_ConnorIntro:: @ 81C1828
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_ConnorDefeat:: @ 81C1860
	.string "Arrrgh! I hate losing!$"

Route127_Text_ConnorPostBattle:: @ 81C1877
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:: @ 81C18CC
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity...\l"
	.string "Please, allow me to demonstrate...$"

Route127_Text_JonahDefeat:: @ 81C1930
	.string "Though I have lost, my heart remains\n"
	.string "calm...$"

Route127_Text_JonahPostBattle:: @ 81C195D
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water...$"

Route127_Text_HenryIntro:: @ 81C19A3
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:: @ 81C19D6
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:: @ 81C19E7
	.string "Your POKéMON look pretty strong.\n"
	.string "They'd be a handful if I hooked them!$"

Route127_Text_RogerIntro:: @ 81C1A2E
	.string "Well, hey! This is a match between a\n"
	.string "POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:: @ 81C1A73
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:: @ 81C1AA0
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_KojiIntro:: @ 81C1AE2
	.string "What I learned at DEWFORD's POKéMON\n"
	.string "GYM, I will put into practice here.$"

Route127_Text_KojiDefeat:: @ 81C1B2A
	.string "I was swamped!$"

Route127_Text_KojiPostBattle:: @ 81C1B39
	.string "BRAWLY, DEWFORD's GYM LEADER, used\n"
	.string "to train with a guy named BRUNO in\l"
	.string "KANTO, I've heard.$"

Route127_Text_ByronIntro:: @ 81C1B92
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_ByronDefeat:: @ 81C1BD9
	.string "Whew... I give up.$"

Route127_Text_ByronPostBattle:: @ 81C1BEC
	.string "There're lots of diving spots in the\n"
	.string "sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route128_Text_IsaiahIntro:: @ 81C1C67
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away...$"

Route128_Text_IsaiahDefeat:: @ 81C1C95
	.string "My first victory seems to be far\n"
	.string "away, too...$"

Route128_Text_IsaiahPostBattle:: @ 81C1CC3
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRematchIntro:: @ 81C1D02
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:: @ 81C1D45
	.string "I've yet to taste my first victory...$"

Route128_Text_IsaiahPostRematch:: @ 81C1D6B
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win...$"

Route128_Text_KatelynIntro:: @ 81C1DB0
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:: @ 81C1E25
	.string "A POKéMON battle is grueling, too...$"

Route128_Text_KatelynPostBattle:: @ 81C1E4A
	.string "I have to ride a BIKE next, but...\n"
	.string "I'm about to throw in the towel...$"

Route128_Text_KatelynRematchIntro:: @ 81C1E90
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:: @ 81C1EFA
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving...$"

Route128_Text_KatelynPostRematch:: @ 81C1F2E
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:: @ 81C1F6D
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge...\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:: @ 81C1FCC
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:: @ 81C1FE8
	.string "After all I've done to get here, I won't\n"
	.string "give up after one setback.$"

Route128_Text_RubenIntro:: @ 81C202C
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:: @ 81C2051
	.string "This can't be!$"

Route128_Text_RubenPostBattle:: @ 81C2060
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:: @ 81C2090
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:: @ 81C20FC
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:: @ 81C210D
	.string "Awww, phooey!\p"
	.string "My POKéMON know WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route129_Text_ChaseIntro:: @ 81C2161
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:: @ 81C2198
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:: @ 81C21B4
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:: @ 81C21ED
	.string "I'm in the middle of a triathlon, but,\n"
	.string "sure, why don't we battle?$"

Route129_Text_AllisonDefeat:: @ 81C222F
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:: @ 81C2243
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:: @ 81C22C8
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:: @ 81C22EC
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:: @ 81C230F
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:: @ 81C2349
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:: @ 81C2378
	.string "Oh, my.\n"
	.string "I wanted to relax a little more...$"

Route129_Text_TishaPostBattle:: @ 81C23A3
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route130_Text_RodneyIntro:: @ 81C2401
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:: @ 81C245D
	.string "This kid's awfully tough...$"

Route130_Text_RodneyPostBattle:: @ 81C2479
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:: @ 81C24DC
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:: @ 81C2525
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:: @ 81C256E
	.string "The world's children dream\n"
	.string "of one day becoming the\l"
	.string "POKéMON CHAMPION.$"

Route131_Text_RichardIntro:: @ 81C25B3
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:: @ 81C25F8
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough...$"

Route131_Text_RichardPostBattle:: @ 81C262A
	.string "Gasp... Gasp... I'm wiped out...\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:: @ 81C26B9
	.string "The sea... The sea... The sea...\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:: @ 81C271F
	.string "Bleah!$"

Route131_Text_HermanPostBattle:: @ 81C2726
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:: @ 81C2774
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:: @ 81C27A4
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:: @ 81C27CF
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:: @ 81C284A
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:: @ 81C2883
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:: @ 81C2898
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:: @ 81C28E2
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:: @ 81C2918
	.string "RELI: We couldn't win even though we\n"
	.string "worked together...$"

Route131_Text_ReliPostBattle:: @ 81C2950
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:: @ 81C29B2
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:: @ 81C29F3
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:: @ 81C2A20
	.string "IAN: I did my best with my sis, but\n"
	.string "we still couldn't win...$"

Route131_Text_IanPostBattle:: @ 81C2A5D
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea, that's\n"
	.string "a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:: @ 81C2ACA
	.string "IAN: If you have two POKéMON, we'll\n"
	.string "take you on!$"

Route132_Text_GilbertIntro:: @ 81C2AFB
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:: @ 81C2B5B
	.string "I crave more power...$"

Route132_Text_GilbertPostBattle:: @ 81C2B71
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:: @ 81C2BB5
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:: @ 81C2BEA
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:: @ 81C2BFA
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place...$"

Route132_Text_RonaldIntro:: @ 81C2C32
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:: @ 81C2C60
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:: @ 81C2C78
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:: @ 81C2CD9
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:: @ 81C2D1F
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:: @ 81C2D3E
	.string "Urggh...\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated. Let's battle!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here...\l"
	.string "I must be cursed...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "I've led a life of woe and misery...\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Another loss...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "A life adrift...\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "No! Please!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "A strong child TRAINER...\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "You...\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "I'd like to go back to FORTREE, but I've\n"
	.string "grown to like this place, too.$"

Route134_Text_JackIntro:: @ 81C30C6
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "There's a collector who's after the\n"
	.string "SCALES of LUVDISC.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Tuckered out again...$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed...$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "I concede defeat.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"
