Route102_Text_CalvinIntro:: @ 81B79C3
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Arrgh, I lost...\n"
	.string "I should have trained mine more...$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Listen, you. If you're strong, you\n"
	.string "should have told me before!$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Arrgh, I lost...\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "If you're going to get stronger, I'll\n"
	.string "get stronger, too.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "I called you because I thought I\n"
	.string "could beat you...$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "I haven't won once yet...\n"
	.string "I wish I would win soon...$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my BUG POKéMON!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "I ended up furthering your career...$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route110/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

.include "data/maps/Route114/trainer_text.inc"

.include "data/maps/Route115/trainer_text.inc"

.include "data/maps/Route116/trainer_text.inc"

.include "data/maps/Route117/trainer_text.inc"

.include "data/maps/Route118/trainer_text.inc"

.include "data/maps/Route119/trainer_text.inc"

.include "data/maps/Route120/trainer_text.inc"

.include "data/maps/Route121/trainer_text.inc"

Route123_Text_WendyIntro:: @ 81BFF6A
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:: @ 81BFFA2
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:: @ 81BFFC1
	.string "To best even me...\n"
	.string "Your strength is marvelous!$"

Route123_Text_ClydeIntro:: @ 81BFFF0
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_ClydeDefeat:: @ 81C0057
	.string "Oh, you're worthy, all right!$"

Route123_Text_ClydePostBattle:: @ 81C0075
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:: @ 81C009E
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:: @ 81C00D4
	.string "Oh...\n"
	.string "I smell the bitter scent of misery...$"

Route123_Text_VioletPostBattle:: @ 81C0100
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:: @ 81C013F
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:: @ 81C01A3
	.string "I feel sad...$"

Route123_Text_CameronPostBattle:: @ 81C01B1
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you...$"

Route123_Text_CameronRematchIntro:: @ 81C01F9
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:: @ 81C0240
	.string "I feel sad...$"

Route123_Text_CameronPostRematch:: @ 81C024E
	.string "I should train at MT. PYRE...\n"
	.string "I'll never beat you this way...$"

Route123_Text_JackiIntro:: @ 81C028C
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:: @ 81C0303
	.string "Astounding!$"

Route123_Text_JackiPostBattle:: @ 81C030F
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRematchIntro:: @ 81C0351
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:: @ 81C0380
	.string "Astounding!$"

Route123_Text_JackiPostRematch:: @ 81C038C
	.string "Your power with POKéMON...\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:: @ 81C03CB
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:: @ 81C040E
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:: @ 81C0423
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:: @ 81C0462
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:: @ 81C049C
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:: @ 81C04CD
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:: @ 81C04E3
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:: @ 81C0519
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:: @ 81C0554
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:: @ 81C059F
	.string "Overflowing with vitality...$"

Route123_Text_KindraPostBattle:: @ 81C05BC
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits...$"

Route124_Text_SpencerIntro:: @ 81C0624
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON, I can\n"
	.string "serve as your pilot.$"

Route124_Text_SpencerDefeat:: @ 81C0675
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:: @ 81C0693
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:: @ 81C06F7
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself...\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:: @ 81C0741
	.string "Oh!\n"
	.string "I can't...$"

Route124_Text_RolandPostBattle:: @ 81C0750
	.string "I'm getting chilled...\n"
	.string "I've been in the water too long...\p"
	.string "I wish I could ride a POKéMON like you...$"

Route124_Text_JennyIntro:: @ 81C07B4
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:: @ 81C07F9
	.string "Oh...\n"
	.string "Lost at sea...$"

Route124_Text_JennyPostBattle:: @ 81C080E
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRematchIntro:: @ 81C0888
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:: @ 81C08C8
	.string "That's strange...\n"
	.string "I lost again...$"

Route124_Text_JennyPostRematch:: @ 81C08EA
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:: @ 81C0936
	.string "I'm growing bored of swimming...\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:: @ 81C096B
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:: @ 81C0994
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:: @ 81C09CE
	.string "Fufufufu... I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:: @ 81C0A2F
	.string "Glub, glub, glub...\n"
	.string "I'm sinking...$"

Route124_Text_ChadPostBattle:: @ 81C0A52
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again...$"

Route124_Text_RitaIntro:: @ 81C0ABD
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_RitaDefeat:: @ 81C0B36
	.string "RITA: SAM! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_RitaPostBattle:: @ 81C0B72
	.string "RITA: Sigh...\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend...$"

Route124_Text_RitaNotEnoughMons:: @ 81C0BC8
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamIntro:: @ 81C0C0E
	.string "SAM: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_SamDefeat:: @ 81C0C4F
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out...$"

Route124_Text_SamPostBattle:: @ 81C0C7F
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_SamNotEnoughMons:: @ 81C0CE0
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"

Route124_Text_RitaRematchIntro:: @ 81C0D1F
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_RitaRematchDefeat:: @ 81C0DB5
	.string "RITA: SAM!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_RitaPostRematch:: @ 81C0E06
	.string "RITA: Sigh...\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations...$"

Route124_Text_RitaRematchNotEnoughMons:: @ 81C0E5C
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamRematchIntro:: @ 81C0EA2
	.string "SAM: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_SamRematchDefeat:: @ 81C0EE5
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out again.$"

Route124_Text_SamPostRematch:: @ 81C0F19
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later...$"

Route124_Text_SamRematchNotEnoughMons:: @ 81C0F90
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"

Route125_Text_CodyIntro:: @ 81C0FCF
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_CodyDefeat:: @ 81C1002
	.string "I beg for peace!$"

Route125_Text_CodyPostBattle:: @ 81C1013
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro:: @ 81C104B
	.string "Hey, there!\n"
	.string "Check out my sweet POKéMON!$"

Route125_Text_StanDefeat:: @ 81C1073
	.string "I floundered...$"

Route125_Text_StanPostBattle:: @ 81C1083
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:: @ 81C10C3
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat:: @ 81C10FB
	.string "You're too much!$"

Route125_Text_TanyaPostBattle:: @ 81C110C
	.string "Whew...\n"
	.string "Which way is it to MOSSDEEP CITY?$"

Route125_Text_SharonIntro:: @ 81C1136
	.string "How would you like to take on the\n"
	.string "WATER-type POKéMON I raised?$"

Route125_Text_SharonDefeat:: @ 81C1175
	.string "I lost...$"

Route125_Text_SharonPostBattle:: @ 81C117F
	.string "Your power... You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:: @ 81C11AF
	.string "Ahoy! I'm a buff, tough SAILOR!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat:: @ 81C11ED
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle:: @ 81C1208
	.string "The tide ebbs and flows inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRematchIntro:: @ 81C1282
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat:: @ 81C12C5
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle:: @ 81C12EE
	.string "The SHOAL CAVE...\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:: @ 81C13A1
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat:: @ 81C13FF
	.string "KIM: I thought we would win.$"

Route125_Text_KimPostBattle:: @ 81C141C
	.string "KIM: A funny old man lives in the\n"
	.string "SHOAL CAVE, doesn't he?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:: @ 81C146E
	.string "KIM: No, no, no! You need two POKéMON,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro:: @ 81C14AB
	.string "IRIS: KIM, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat:: @ 81C14E7
	.string "IRIS: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle:: @ 81C1508
	.string "IRIS: KIM, are we really going into\n"
	.string "the SHOAL CAVE?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons:: @ 81C154F
	.string "IRIS: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route126_Text_BarryIntro:: @ 81C1590
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat:: @ 81C15C3
	.string "I admit it! You win!$"

Route126_Text_BarryPostBattle:: @ 81C15D8
	.string "Thanks to my daily swimming routine...\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro:: @ 81C1627
	.string "This towering white mountain of rock\n"
	.string "is SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:: @ 81C1660
	.string "I was done in?$"

Route126_Text_DeanPostBattle:: @ 81C166F
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_NikkiIntro:: @ 81C16AB
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat:: @ 81C16C5
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub...$"

Route126_Text_NikkiPostBattle:: @ 81C1702
	.string "You thrashed me... I want to\n"
	.string "disappear in a wave of despair...$"

Route126_Text_BrendaIntro:: @ 81C1741
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat:: @ 81C1766
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle:: @ 81C1773
	.string "I love frolicking with POKéMON in\n"
	.string "the sea like this!$"

Route127_Text_CalebIntro:: @ 81C17A8
	.string "I can see it in your face. You want\n"
	.string "to challenge me.$"

Route127_Text_CalebDefeat:: @ 81C17DD
	.string "Awawawawawa...$"

Route127_Text_CalebPostBattle:: @ 81C17EC
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_ConnorIntro:: @ 81C1828
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_ConnorDefeat:: @ 81C1860
	.string "Arrrgh! I hate losing!$"

Route127_Text_ConnorPostBattle:: @ 81C1877
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:: @ 81C18CC
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity...\l"
	.string "Please, allow me to demonstrate...$"

Route127_Text_JonahDefeat:: @ 81C1930
	.string "Though I have lost, my heart remains\n"
	.string "calm...$"

Route127_Text_JonahPostBattle:: @ 81C195D
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water...$"

Route127_Text_HenryIntro:: @ 81C19A3
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:: @ 81C19D6
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:: @ 81C19E7
	.string "Your POKéMON look pretty strong.\n"
	.string "They'd be a handful if I hooked them!$"

Route127_Text_RogerIntro:: @ 81C1A2E
	.string "Well, hey! This is a match between a\n"
	.string "POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:: @ 81C1A73
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:: @ 81C1AA0
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_KojiIntro:: @ 81C1AE2
	.string "What I learned at DEWFORD's POKéMON\n"
	.string "GYM, I will put into practice here.$"

Route127_Text_KojiDefeat:: @ 81C1B2A
	.string "I was swamped!$"

Route127_Text_KojiPostBattle:: @ 81C1B39
	.string "BRAWLY, DEWFORD's GYM LEADER, used\n"
	.string "to train with a guy named BRUNO in\l"
	.string "KANTO, I've heard.$"

Route127_Text_ByronIntro:: @ 81C1B92
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_ByronDefeat:: @ 81C1BD9
	.string "Whew... I give up.$"

Route127_Text_ByronPostBattle:: @ 81C1BEC
	.string "There're lots of diving spots in the\n"
	.string "sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route128_Text_IsaiahIntro:: @ 81C1C67
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away...$"

Route128_Text_IsaiahDefeat:: @ 81C1C95
	.string "My first victory seems to be far\n"
	.string "away, too...$"

Route128_Text_IsaiahPostBattle:: @ 81C1CC3
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRematchIntro:: @ 81C1D02
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:: @ 81C1D45
	.string "I've yet to taste my first victory...$"

Route128_Text_IsaiahPostRematch:: @ 81C1D6B
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win...$"

Route128_Text_KatelynIntro:: @ 81C1DB0
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:: @ 81C1E25
	.string "A POKéMON battle is grueling, too...$"

Route128_Text_KatelynPostBattle:: @ 81C1E4A
	.string "I have to ride a BIKE next, but...\n"
	.string "I'm about to throw in the towel...$"

Route128_Text_KatelynRematchIntro:: @ 81C1E90
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:: @ 81C1EFA
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving...$"

Route128_Text_KatelynPostRematch:: @ 81C1F2E
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:: @ 81C1F6D
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge...\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:: @ 81C1FCC
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:: @ 81C1FE8
	.string "After all I've done to get here, I won't\n"
	.string "give up after one setback.$"

Route128_Text_RubenIntro:: @ 81C202C
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:: @ 81C2051
	.string "This can't be!$"

Route128_Text_RubenPostBattle:: @ 81C2060
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:: @ 81C2090
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:: @ 81C20FC
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:: @ 81C210D
	.string "Awww, phooey!\p"
	.string "My POKéMON know WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"

Route129_Text_ChaseIntro:: @ 81C2161
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:: @ 81C2198
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:: @ 81C21B4
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:: @ 81C21ED
	.string "I'm in the middle of a triathlon, but,\n"
	.string "sure, why don't we battle?$"

Route129_Text_AllisonDefeat:: @ 81C222F
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:: @ 81C2243
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:: @ 81C22C8
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:: @ 81C22EC
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:: @ 81C230F
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:: @ 81C2349
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:: @ 81C2378
	.string "Oh, my.\n"
	.string "I wanted to relax a little more...$"

Route129_Text_TishaPostBattle:: @ 81C23A3
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route130_Text_RodneyIntro:: @ 81C2401
	.string "What a surprise! I didn't expect to\n"
	.string "see a TRAINER out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:: @ 81C245D
	.string "This kid's awfully tough...$"

Route130_Text_RodneyPostBattle:: @ 81C2479
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro:: @ 81C24DC
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat:: @ 81C2525
	.string "Like the vast blue sea,\n"
	.string "the world of POKéMON spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle:: @ 81C256E
	.string "The world's children dream\n"
	.string "of one day becoming the\l"
	.string "POKéMON CHAMPION.$"

Route131_Text_RichardIntro:: @ 81C25B3
	.string "The sea is teeming with POKéMON.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat:: @ 81C25F8
	.string "POKéMON raised by TRAINERS are\n"
	.string "seriously tough...$"

Route131_Text_RichardPostBattle:: @ 81C262A
	.string "Gasp... Gasp... I'm wiped out...\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro:: @ 81C26B9
	.string "The sea... The sea... The sea...\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:: @ 81C271F
	.string "Bleah!$"

Route131_Text_HermanPostBattle:: @ 81C2726
	.string "Bored I am by the sea, but swim I must.\p"
	.string "I'm a born swimmer!\n"
	.string "That's what I am.$"

Route131_Text_SusieIntro:: @ 81C2774
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat:: @ 81C27A4
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle:: @ 81C27CF
	.string "Did you see a guy over there who whines\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk.\n"
	.string "He's hopelessly in love with the sea!$"

Route131_Text_KaraIntro:: @ 81C284A
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat:: @ 81C2883
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle:: @ 81C2898
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro:: @ 81C28E2
	.string "RELI: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat:: @ 81C2918
	.string "RELI: We couldn't win even though we\n"
	.string "worked together...$"

Route131_Text_ReliPostBattle:: @ 81C2950
	.string "RELI: The people of PACIFIDLOG are\n"
	.string "together with the sea and POKéMON from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons:: @ 81C29B2
	.string "RELI: You don't have two POKéMON?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro:: @ 81C29F3
	.string "IAN: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat:: @ 81C2A20
	.string "IAN: I did my best with my sis, but\n"
	.string "we still couldn't win...$"

Route131_Text_IanPostBattle:: @ 81C2A5D
	.string "IAN: You know how PACIFIDLOG is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea, that's\n"
	.string "a part of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:: @ 81C2ACA
	.string "IAN: If you have two POKéMON, we'll\n"
	.string "take you on!$"

Route132_Text_GilbertIntro:: @ 81C2AFB
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:: @ 81C2B5B
	.string "I crave more power...$"

Route132_Text_GilbertPostBattle:: @ 81C2B71
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:: @ 81C2BB5
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:: @ 81C2BEA
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:: @ 81C2BFA
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place...$"

Route132_Text_RonaldIntro:: @ 81C2C32
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:: @ 81C2C60
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:: @ 81C2C78
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:: @ 81C2CD9
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:: @ 81C2D1F
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:: @ 81C2D3E
	.string "Urggh...\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated. Let's battle!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "It's just my luck that a tough TRAINER\n"
	.string "like you would drift here...\l"
	.string "I must be cursed...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "I've led a life of woe and misery...\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Another loss...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "A life adrift...\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "No! Please!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "A strong child TRAINER...\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "I want to win like everyone else, but I\n"
	.string "won't raise POKéMON like everyone else.$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "I came all the way out here with my\n"
	.string "BIRD POKéMON.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "You...\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "I'd like to go back to FORTREE, but I've\n"
	.string "grown to like this place, too.$"

Route134_Text_JackIntro:: @ 81C30C6
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "There's a collector who's after the\n"
	.string "SCALES of LUVDISC.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Tuckered out again...$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed...$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "I concede defeat.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"
