UnusedText_MonSizeRecord_AskToShow: @ 81C426C
	.string "I'm very interested in big {STR_VAR_1}.\n"
	.string "The bigger the better.\p"
	.string "Huh? Do you have a {STR_VAR_1}?\n"
	.string "P-p-please, show me!$"

UnusedText_MonSizeRecord_WowThatsBig: @ 81C42CE
	.string "Oh, my gosh, this is a big one!\n"
	.string "This is a grand {STR_VAR_1}!\p"
	.string "Thanks for showing me.\n"
	.string "This is my thanks!$"

UnusedText_MonSizeRecord_ReceivedItem: @ 81C432C
	.string "{PLAYER} received one {STR_VAR_2}.$"

UnusedText_MonSizeRecord_BagIsFull: @ 81C4340
	.string "Hunh?\n"
	.string "Your BAG is crammed full.$"

UnusedText_MonSizeRecord_SeenBigger: @ 81C4360
	.string "Hmm... I've seen a bigger {STR_VAR_1}\n"
	.string "than this one.$"

UnusedText_MonSizeRecord_NotRequestedSpecies: @ 81C438C
	.string "Oh, now this is quite something...\n"
	.string "But it's not a {STR_VAR_1}!$"

UnusedText_MonSizeRecord_NoLargeSpecies: @ 81C43C2
	.string "You don't have a big {STR_VAR_1}?\n"
	.string "That's too bad...\p"
	.string "If you get a big {STR_VAR_1},\n"
	.string "please come show me.$"

UnusedText_MonSizeRecord_BiggestInHistory: @ 81C4417
	.string "The biggest {STR_VAR_1} in history!\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}-inch colossus!$"
