Route102_Text_WatchMeCatchPokemon:: @ 816D361
	.string "WALLY: {PLAYER}...\n"
	.string "POKéMON hide in tall grass like this,\l"
	.string "don't they?\p"
	.string "Please watch me and see if I can\n"
	.string "catch one properly.\p"
	.string "...Whoa!$"

Route102_Text_WallyIDidIt:: @ 816D3DE
	.string "WALLY: I did it... It's my...\n"
	.string "My POKéMON!$"

Route102_Text_LetsGoBack:: @ 816D408
	.string "{PLAYER}, thank you!\n"
	.string "Let's go back to the GYM!$"

Route102_Text_ImNotVeryTall:: @ 816D431
	.string "I'm...not very tall, so I sink right\n"
	.string "into tall grass.\p"
	.string "The grass goes up my nose and...\n"
	.string "Fwafwafwafwafwa...\p"
	.string "Fwatchoo!$"

Route102_Text_UnusedWatchMe:: @ 816D4A5
	.string "Fufufufu...\n"
	.string "Watch me.$"

Route102_Text_UnusedLedgeExplanation:: @ 816D4BB
	.string "Ta-daaaah! Awesome, huh?\p"
	.string "There are some ledges that you can't\n"
	.string "climb up, but you can jump down.$"

Route102_Text_CatchWholeBunchOfPokemon:: @ 816D51A
	.string "I'm going to catch a whole bunch of\n"
	.string "POKéMON!$"

Route102_Text_RouteSignOldale:: @ 816D547
	.string "ROUTE 102\n"
	.string "{0x7C} OLDALE TOWN$"

Route102_Text_RouteSignPetalburg:: @ 816D55F
	.string "ROUTE 102\n"
	.string "{0x7B} PETALBURG CITY$"
