Route102_Text_CalvinIntro:: @ 81B79C3
	.string "If you have POKéMON with you, then\n"
	.string "you're an official POKéMON TRAINER!\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Arrgh, I lost...\n"
	.string "I should have trained mine more...$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Listen, you. If you're strong, you\n"
	.string "should have told me before!$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Ever since I lost to you, I desperately\n"
	.string "trained my POKéMON.\l"
	.string "You can't say no to my challenge!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Arrgh, I lost...\n"
	.string "Is my training method not right?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "If you're going to get stronger, I'll\n"
	.string "get stronger, too.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Did you just become a TRAINER?\n"
	.string "We're both beginners!$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "I called you because I thought I\n"
	.string "could beat you...$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "I haven't won once yet...\n"
	.string "I wish I would win soon...$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Hahah! Our eyes met!\n"
	.string "I'll take you on with my BUG POKéMON!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Ow! Down and out!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "If you lock eyes with a TRAINER,\n"
	.string "you have to challenge! It's a rule!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "I'm going to keep winning and aim\n"
	.string "to be the best TRAINER.\p"
	.string "Help me further my career!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "I ended up furthering your career...$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "To keep winning my way up, I see that\n"
	.string "I have to catch more POKéMON.$"
