Route127_Text_CalebIntro:: @ 81C17A8
	.string "Ich sehe es dir an. Du willst mich\n"
	.string "herausfordern!$"

Route127_Text_CalebDefeat:: @ 81C17DD
	.string "Auauauauahahaha!$"

Route127_Text_CalebPostBattle:: @ 81C17EC
	.string "Ein gut gespieltes Match lässt immer ein\n"
	.string "frisches und heiteres Gefühl zurück.$"

Route127_Text_ConnorIntro:: @ 81C1828
	.string "Hast du auch einen Rivalen, gegen den\n"
	.string "du es hasst zu verlieren?$"

Route127_Text_ConnorDefeat:: @ 81C1860
	.string "Aaargh! Ich hasse es, zu verlieren!$"

Route127_Text_ConnorPostBattle:: @ 81C1877
	.string "Wenn du einen Rivalen hast, willst du\n"
	.string "dann nicht auch immer besser werden?$"

Route127_Text_JonahIntro:: @ 81C18CC
	.string "Durch das Angeln habe ich eine\n"
	.string "gelassene Heiterkeit entwickelt...\l"
	.string "Bitte lass mich sie dir zeigen...$"

Route127_Text_JonahDefeat:: @ 81C1930
	.string "Auch wenn ich verloren habe, so bleibt\n"
	.string "mein Herz doch ruhig...$"

Route127_Text_JonahPostBattle:: @ 81C195D
	.string "Es macht nichts, wenn ich nichts fange.\n"
	.string "Die Schnur bleibt im Wasser.$"

Route127_Text_HenryIntro:: @ 81C19A3
	.string "Hups! Jetzt sag nicht, dass ich ein\n"
	.string "SURFENDES POKéMON am Haken habe?$"

Route127_Text_HenryDefeat:: @ 81C19D6
	.string "Ich kann so nicht weitermachen!$"

Route127_Text_HenryPostBattle:: @ 81C19E7
	.string "Deine POKéMON sehen stark aus! Und\n"
	.string "doch wären sie nur ein Häppchen, wenn\l"
	.string "ich sie als Köder am Haken hätte.$"

Route127_Text_RogerIntro:: @ 81C1A2E
	.string "Nun! Das ist ein Kampf zwischen einem\n"
	.string "POKéMON-Fan und einem Angel-Fan.$"

Route127_Text_RogerDefeat:: @ 81C1A73
	.string "Nein! Meine Schnur hat sich verheddert.\n"
	.string "Die Party ist vorbei!$"

Route127_Text_RogerPostBattle:: @ 81C1AA0
	.string "Meine Angelschnur tanzt im Wasser!\n"
	.string "Sie tanzt Tango! Hahahah, hiiiks!$"

Route127_Text_KojiIntro:: @ 81C1AE2
	.string "Das, was ich in der ARENA von\n"
	.string "FAUSTAUHAVEN gelernt habe,\l"
	.string "wende ich jetzt an.$"

Route127_Text_KojiDefeat:: @ 81C1B2A
	.string "Ich wurde weggeschwemmt.$"

Route127_Text_KojiPostBattle:: @ 81C1B39
	.string "KAMILLO, der ARENALEITER von\n"
	.string "FAUSTAUHAVEN, soll mit einem Typen\l"
	.string "namens BRUNO in KANTO trainiert haben.$"

Route127_Text_ByronIntro:: @ 81C1B92
	.string "VOGEL-POKéMON haben exzellente Augen.\n"
	.string "Sie erspähen Beute aus großer Höhe.$"

Route127_Text_ByronDefeat:: @ 81C1BD9
	.string "Huuh... Ich gebe auf.$"

Route127_Text_ByronPostBattle:: @ 81C1BEC
	.string "Hier gibt es viele Plätze, an denen man\n"
	.string "sehr gut tauchen kann.\p"
	.string "Aus der Luft sind sie leicht zu\n"
	.string "erkennen, da sie dunkler sind.$"
