Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:: @ 81C5EC6
	.string "Hallo!\p"
	.string "Dies ist der BLÜTENTRAUM BLUMENLADEN.\n"
	.string "Verwandelt die Welt in ein Blumenmeer!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:: @ 81C5F1B
	.string "{PLAYER}{KUN}, möchtest du etwas über\n"
	.string "BEEREN lernen?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:: @ 81C5F48
	.string "Wie heißt du?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Das ist aber ein hübscher Name.\p"
	.string "Möchtest du etwas über BEEREN lernen?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:: @ 81C5F9D
	.string "BEEREN wachsen an Bäumen, die nur in\n"
	.string "dunklem Lehmboden gedeihen.\p"
	.string "Wenn du BEEREN pflückst, pflanze\n"
	.string "immer neue in den Boden ein.\p"
	.string "Eine gepflanzte BEERE wird bald an-\n"
	.string "fangen zu sprießen, dann mit einer\p"
	.string "wunderhübschen Blüte erblühen, die bald\n"
	.string "zu einer BEERE wird.\p"
	.string "Ich würde die ganze Welt am liebsten mit\n"
	.string "wunderhübschen Blüten bedeckt sehen.\l"
	.string "Das ist mein Traum.\p"
	.string "Bitte, hilf mir, {PLAYER}{KUN}. Pflanze BEEREN\n"
	.string "und bring so Blüten in die Welt.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:: @ 81C6121
	.string "Blumen erfreuen jedes Herz, nicht\n"
	.string "wahr?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:: @ 81C6158
	.string "Hallo!\p"
	.string "Je mehr du dich um die Blumen kümmerst,\n"
	.string "desto schöner werden sie blühen.\p"
	.string "Auch du hast Blumen gerne.\n"
	.string "Das weiß ich genau. Das ist für dich.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:: @ 81C61E8
	.string "Nachdem du die BEEREN eingepflanzt\n"
	.string "hast, musst du sie mit der\l"
	.string "WAILMERKANNE wässern.\p"
	.string "Oh, und noch etwas!\p"
	.string "Wenn die BEEREN nicht gepflückt werden,\n"
	.string "fallen sie zu Boden. Aber sie werden\l"
	.string "wieder nachwachsen.\p"
	.string "Ist das nicht unglaublich? Es ist, als\n"
	.string "hätten sie den Willen zu leben.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:: @ 81C62DA
	.string "Ich versuche, so zu sein wie meine große\n"
	.string "Schwester. Ich züchte auch Blumen!\p"
	.string "Hier, das ist für dich!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:: @ 81C6335
	.string "Du kannst eine BEERE pflanzen und sie\n"
	.string "wachsen lassen, oder du gibst sie einem\l"
	.string "POKéMON zum Tragen.\p"
	.string "Und neuerdings gibt es eine Maschine,\n"
	.string "mit der kann man die verschiedensten\l"
	.string "BEEREN mixen und Süßigkeiten für die\l"
	.string "POKéMON daraus machen.\p"
	.string "Ich möchte auch Süßigkeiten haben.$"
