Route104_Text_PlantBerriesInSoilTakeThis:: @ 81C55B9
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to take them.\p"
	.string "But make sure you plant a BERRY in the\n"
	.string "same spot. That's common courtesy.\p"
	.string "Here, I'll share this with you.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:: @ 81C5665
	.string "The way you look, you must be a\n"
	.string "TRAINER, no?\p"
	.string "TRAINERS often make POKéMON hold\n"
	.string "BERRIES.\p"
	.string "It's up to you whether to grow BERRIES\n"
	.string "or use them.$"
