Route104_Text_GinaIntro:: @ 81B83E9
	.string "GINA: Okay, let's battle with our\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:: @ 81B8414
	.string "GINA: Losing upsets me!$"

Route104_Text_GinaPostBattle:: @ 81B842C
	.string "GINA: {STR_VAR_1} is strong!\n"
	.string "We have to train lots more!$"

Route104_Text_GinaNotEnoughMons:: @ 81B845C
	.string "GINA: Oh? Only one POKéMON?\n"
	.string "Then, we don't battle with you.\p"
	.string "If there's only one POKéMON, it will\n"
	.string "be lonesome. That's not nice.$"

Route104_Text_MiaIntro:: @ 81B84DB
	.string "MIA: We are twins, so we battle\n"
	.string "POKéMON together.$"

Route104_Text_MiaDefeat:: @ 81B850D
	.string "MIA: We battled together, but we\n"
	.string "both lost...$"

Route104_Text_MiaPostBattle:: @ 81B853B
	.string "MIA: We will train our POKéMON more\n"
	.string "and be strong like you.$"

Route104_Text_MiaNotEnoughMons:: @ 81B8577
	.string "MIA: You want to battle with us?\p"
	.string "It's a big no-no if you don't have two\n"
	.string "POKéMON with you.\l"
	.string "We're too strong for you!$"

Route104_Text_IvanIntro:: @ 81B85EB
	.string "Why keep it a secret?\n"
	.string "I'm the WATER POKéMON expert!\p"
	.string "Huh?\n"
	.string "You don't know me?$"

Route104_Text_IvanDefeat:: @ 81B8637
	.string "I thought I wasn't too bad, if I may\n"
	.string "say so, but I guess not... Bleah...$"

Route104_Text_IvanPostBattle:: @ 81B8680
	.string "I got too into fishing.\n"
	.string "I forgot I had to raise my POKéMON...$"

Route104_Text_BillyIntro:: @ 81B86BE
	.string "Leaving footprints in the sand is\n"
	.string "so fun!$"

Route104_Text_BillyDefeat:: @ 81B86E8
	.string "Waah! I got sand in my runners!\n"
	.string "They're all gritty!$"

Route104_Text_BillyPostBattle:: @ 81B871C
	.string "I want to leave my footprints in the\n"
	.string "sand everywhere, but they disappear\l"
	.string "quickly...$"

Route104_Text_HaleyIntro:: @ 81B8770
	.string "Should I...\n"
	.string "Or shouldn't I?\p"
	.string "Okay, sure, I will battle!$"

Route104_Text_HaleyDefeat:: @ 81B87A7
	.string "I shouldn't have battled...$"

Route104_Text_HaleyPostBattle:: @ 81B87C3
	.string "If you're faced with a decision and\n"
	.string "you let someone else choose for you,\l"
	.string "you will regret it, however things\l"
	.string "turn out.$"

Route104_Text_HaleyRematchIntro:: @ 81B8839
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat:: @ 81B8852
	.string "Ohh...\n"
	.string "I thought I could win...$"

Route104_Text_HaleyPostRematch:: @ 81B8872
	.string "I made the decision to battle, so I\n"
	.string "can accept this loss in grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro:: @ 81B88D4
	.string "Oh, sure, I'll accept your challenge.\n"
	.string "I have a lot of money.$"

Route104_Text_WinstonDefeat:: @ 81B8911
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostBattle:: @ 81B8925
	.string "There are some things money can't buy.\n"
	.string "That's POKéMON...$"

Route104_Text_WinstonRematchIntro:: @ 81B895E
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_WinstonRematchDefeat:: @ 81B899E
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch:: @ 81B89C0
	.string "I'm fabulously wealthy, but I can't\n"
	.string "seem to win at POKéMON...\p"
	.string "It's so deep, the world of POKéMON...$"

Route104_Text_CindyIntro:: @ 81B8A24
	.string "We must have been fated to meet.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyDefeat:: @ 81B8A61
	.string "Oh, my!$"

Route104_Text_CindyPostBattle:: @ 81B8A69
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"
Route104_Text_CindyRematchIntro:: @ 81B8AA7
	.string "Hello, we meet again.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyRematchDefeat:: @ 81B8AD9
	.string "Oh, my...\n"
	.string "I did the best that I could...$"

Route104_Text_CindyPostRematch:: @ 81B8B02
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"
