Route124_Text_SpencerIntro:: @ 81C0624
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON, I can\n"
	.string "serve as your pilot.$"

Route124_Text_SpencerDefeat:: @ 81C0675
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle:: @ 81C0693
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the POKéNAV's MAP.$"

Route124_Text_RolandIntro:: @ 81C06F7
	.string "Hm! You're riding a POKéMON instead\n"
	.string "of swimming yourself...\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat:: @ 81C0741
	.string "Oh!\n"
	.string "I can't...$"

Route124_Text_RolandPostBattle:: @ 81C0750
	.string "I'm getting chilled...\n"
	.string "I've been in the water too long...\p"
	.string "I wish I could ride a POKéMON like you...$"

Route124_Text_JennyIntro:: @ 81C07B4
	.string "If you just float in the sea like\n"
	.string "this, POKéMON come around to play.$"

Route124_Text_JennyDefeat:: @ 81C07F9
	.string "Oh...\n"
	.string "Lost at sea...$"

Route124_Text_JennyPostBattle:: @ 81C080E
	.string "While swimming, I noticed that some\n"
	.string "POKéMON attack, and some just watch.\p"
	.string "I guess POKéMON have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRematchIntro:: @ 81C0888
	.string "If you just float in the sea like this,\n"
	.string "TRAINERS challenge you!$"

Route124_Text_JennyRematchDefeat:: @ 81C08C8
	.string "That's strange...\n"
	.string "I lost again...$"

Route124_Text_JennyPostRematch:: @ 81C08EA
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:: @ 81C0936
	.string "I'm growing bored of swimming...\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat:: @ 81C096B
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle:: @ 81C0994
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:: @ 81C09CE
	.string "Fufufufu... I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat:: @ 81C0A2F
	.string "Glub, glub, glub...\n"
	.string "I'm sinking...$"

Route124_Text_ChadPostBattle:: @ 81C0A52
	.string "I have it on good authority that\n"
	.string "there's a DIVE spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again...$"

Route124_Text_RitaIntro:: @ 81C0ABD
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_RitaDefeat:: @ 81C0B36
	.string "RITA: SAM! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_RitaPostBattle:: @ 81C0B72
	.string "RITA: Sigh...\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend...$"

Route124_Text_RitaNotEnoughMons:: @ 81C0BC8
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamIntro:: @ 81C0C0E
	.string "SAM: My big sister is tough at POKéMON!\p"
	.string "Don't cry when you lose!$"

Route124_Text_SamDefeat:: @ 81C0C4F
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out...$"

Route124_Text_SamPostBattle:: @ 81C0C7F
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_SamNotEnoughMons:: @ 81C0CE0
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"

Route124_Text_RitaRematchIntro:: @ 81C0D1F
	.string "RITA: Sigh...\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_RitaRematchDefeat:: @ 81C0DB5
	.string "RITA: SAM!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_RitaPostRematch:: @ 81C0E06
	.string "RITA: Sigh...\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations...$"

Route124_Text_RitaRematchNotEnoughMons:: @ 81C0E5C
	.string "RITA: You're planning to battle us?\n"
	.string "Not unless you have more POKéMON.$"

Route124_Text_SamRematchIntro:: @ 81C0EA2
	.string "SAM: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_SamRematchDefeat:: @ 81C0EE5
	.string "SAM: Uh-oh...\n"
	.string "My big sister will chew me out again.$"

Route124_Text_SamPostRematch:: @ 81C0F19
	.string "SAM: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with POKéMON later...$"

Route124_Text_SamRematchNotEnoughMons:: @ 81C0F90
	.string "SAM: Did you want to battle us?\n"
	.string "Bring some more POKéMON, then.$"
