Route113_Text_NealIntro:: @ 81BB9BA
	.string "Rate mal, warum es hier draußen so\n"
	.string "kühl ist.$"

Route113_Text_NealDefeat:: @ 81BB9E6
	.string "Puuuh äääh!\n"
	.string "Das stinkt!$"

Route113_Text_NealPostBattle:: @ 81BB9FB
	.string "Die Vulkanasche lässt die Sonnen-\n"
	.string "strahlen nicht durch. Es bleibt kalt.\p"
	.string "Ich finde das angenehm, ich mag\n"
	.string "Hitze nicht.$"

Route113_Text_DillonIntro:: @ 81BBA62
	.string "Der Vulkanausbruch ist der eindeutige\n"
	.string "Beweis, dass die Erde lebt.$"

Route113_Text_DillonDefeat:: @ 81BBA9B
	.string "Du bist auf die eine oder andere\n"
	.string "Weise stark!$"

Route113_Text_DillonPostBattle:: @ 81BBAB7
	.string "Aua! Au au au! Ich kann nichts sehen!\n"
	.string "Ich habe ein Aschenauge!\p"
	.string "Hast du verstanden? Asche und Auge?\p"
	.string "Okay, blöder Witz, tut mir Leid...$"

Route113_Text_MadelineIntro:: @ 81BBB27
	.string "Ich habe einen Sonnenschirm, um diese\n"
	.string "staubige, widerliche Vulkanasche von\l"
	.string "meinem niedlichen CAMAUB fernzuhalten.$"

Route113_Text_MadelineDefeat:: @ 81BBB7A
	.string "Keuchl, pust...\n"
	.string "Ich bin total außer Atem...$"

Route113_Text_MadelinePostBattle:: @ 81BBB9A
	.string "Du bist wirklich sehr gut. Ich muss\n"
	.string "sagen, ich bin schwer beeindruckt.$"

Route113_Text_MadelineRematchIntro:: @ 81BBBCE
	.string "Oh, hallo, wir haben uns ja ewig nicht ge-\n"
	.string "sehen. Ich lade dich zu einem Kampf ein.$"

Route113_Text_MadelineRematchDefeat:: @ 81BBC0D
	.string "Oh, suuuuuper!$"

Route113_Text_MadelinePostRematch:: @ 81BBC1C
	.string "Du bist immer noch sehr gut! Ich muss\n"
	.string "sagen, ich bin immer noch beeindruckt.$"

Route113_Text_LaoIntro:: @ 81BBC59
	.string "Aus den Aschen erhebe ich mich! Kiyaih!\n"
	.string "Herausfordern tue ich dich! Kiyaih!$"

Route113_Text_LaoDefeat:: @ 81BBC90
	.string "Eine Ehre, von dir besiegt zu werden!$"

Route113_Text_LaoPostBattle:: @ 81BBCAB
	.string "Ich muss die Kunst des Versteckens\n"
	.string "verbessern. Mein Reimen auch. Leb wohl.$"

Route113_Text_LaoRematchIntro:: @ 81BBCE6
	.string "Erhebe ich mich aus den Aschen, hast du\n"
	.string "nichts zu lachen. Kiyaih!$"

Route113_Text_LaoRematchDefeat:: @ 81BBD1D
	.string "Mein Versagen gereicht dir zur Ehre.$"

Route113_Text_LaoPostRematch:: @ 81BBD38
	.string "Mein Versteck ist so lausig wie mein\n"
	.string "Kampfstil. Und meine Wortwahl erst...\p"
	.string "Ich lasse das Reimen und sage Lebwohl.$"

Route113_Text_LungIntro:: @ 81BBD92
	.string "Danke, dass du mich gefunden hast!\n"
	.string "Aber nun müssen wir kämpfen!$"

Route113_Text_LungDefeat:: @ 81BBDC6
	.string "Ich werde mein Ninjutsu gegen dich\n"
	.string "einsetzen...\p"
	.string "“VULKANASCHEN WIRBLER”!\n"
	.string "...Was? Es ist schon vorbei?$"

Route113_Text_LungPostBattle:: @ 81BBE1D
	.string "Weißt du, was Sch... am Verstecken ist?\n"
	.string "Es ist einsam, wenn keiner vorbeikommt.$"

Route113_Text_ToriIntro:: @ 81BBE65
	.string "LI: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_ToriDefeat:: @ 81BBEA1
	.string "LI: Wir haben verloren... Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_ToriPostBattle:: @ 81BBEE4
	.string "LI: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_ToriNotEnoughMons:: @ 81BBF25
	.string "LI: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"

Route113_Text_TiaIntro:: @ 81BBF62
	.string "FLO: Wir beide sammeln Asche.\n"
	.string "Wir beide kämpfen auch mit POKéMON.$"

Route113_Text_TiaDefeat:: @ 81BBF9D
	.string "FLO: Wir haben verloren... Mir ist lang-\n"
	.string "weilig, daher sammle ich jetzt Asche.$"

Route113_Text_TiaPostBattle:: @ 81BBFE2
	.string "FLO: Wie viel Asche wir haben? Ich\n"
	.string "hoffe, genug für eine WEISSE FLÖTE.$"

Route113_Text_TiaNotEnoughMons:: @ 81BC021
	.string "FLO: Wir wollen einen 2-gegen-2-Kampf.\n"
	.string "Anderenfalls würden wir verlieren.$"
