Hideout_B1F_Text_EvilTeamGrunt1Intro:: @ 8196E6F
	.string "If you want to know the secret about\n"
	.string "our HIDEOUT, you have me to beat!$"

Hideout_B1F_Text_EvilTeamGrunt1Defeat:: @ 8196EB6
	.string "I can't win at all...$"

Hideout_B1F_Text_EvilTeamGrunt1PostBattle:: @ 8196ECC
	.string "Our HIDEOUT's secret?\p"
	.string "Well, let's just say...\n"
	.string "There's a submarine at the far end!\p"
	.string "But, by now...\n"
	.string "Kekekeke...$"

Hideout_B1F_Text_EvilTeamGrunt2Intro:: @ 8196F39
	.string "Fuel supply loaded A-OK!\n"
	.string "In-cruise snacks loaded A-OK!\p"
	.string "Nothing left to do but KO a pesky\n"
	.string "meddler!$"

Hideout_B1F_Text_EvilTeamGrunt2Defeat:: @ 8196F9B
	.string "I took a serious licking!$"

Hideout_B1F_Text_EvilTeamGrunt2PostBattle:: @ 8196FB5
	.string "Humph!\n"
	.string "This was supposed to happen!\p"
	.string "My mission was to just hold you up!$"

Hideout_B1F_Text_EvilTeamGrunt3Intro:: @ 8196FFD
	.string "Yawn... Keeping watch over the\n"
	.string "HIDEOUT bores me. I'll take you on.$"

Hideout_B1F_Text_EvilTeamGrunt3Defeat:: @ 8197040
	.string "Yawn...\n"
	.string "Oh, I lost...$"

Hideout_B1F_Text_EvilTeamGrunt3PostBattle:: @ 8197056
	.string "If you scurry too much, other TEAM\n"
	.string "{EVIL_TEAM} members might get you.$"
