Route109_Text_DavidIntro:: @ 81B9A1C
	.string "Hiyah! Look at my chiseled abs!\n"
	.string "This is what you call “cut”!$"

Route109_Text_DavidDefeated:: @ 81B9A59
	.string "Aiyah!\n"
	.string "Flubbed out!$"

Route109_Text_DavidPostBattle:: @ 81B9A6D
	.string "Hiyah!\p"
	.string "My sculpted abs have nothing to do\n"
	.string "with POKéMON battles!$"

Route109_Text_AliceIntro:: @ 81B9AAD
	.string "Are you properly protected against\n"
	.string "the sun?$"

Route109_Text_AliceDefeated:: @ 81B9AD9
	.string "Ouch, ouch, ouch!$"

Route109_Text_AlicePostBattle:: @ 81B9AEB
	.string "Cheeks are the most prone to burning!$"

Route109_Text_HueyIntro:: @ 81B9B11
	.string "I've laid anchor in ports around the\n"
	.string "world, but SLATEPORT's the best.$"

Route109_Text_HueyDefeated:: @ 81B9B57
	.string "You're the best!$"

Route109_Text_HueyPostBattle:: @ 81B9B68
	.string "In the best port was the best\n"
	.string "TRAINER...$"

Route109_Text_EdmondIntro:: @ 81B9B91
	.string "Urrrrppp...\n"
	.string "Battle? With me?$"

Route109_Text_EdmondDefeated:: @ 81B9BAE
	.string "Urp... Ooooooohhhhhh...\n"
	.string "Urrrrpppp...$"

Route109_Text_EdmondPostBattle:: @ 81B9BD3
	.string "I'm usually stronger than this!\n"
	.string "I'm just seasick as a dog!\p"
	.string "I'm a SAILOR, but...$"

Route109_Text_RickyIntro:: @ 81B9C23
	.string "I'm thirsty... I could go for a SODA POP\n"
	.string "at the SEASHORE HOUSE...$"

Route109_Text_RickyDefeated:: @ 81B9C65
	.string "Groan...$"

Route109_Text_RickyPostBattle:: @ 81B9C6E
	.string "I'm getting famished... My inner tube\n"
	.string "looks like a giant doughnut...$"

Route109_Text_RickyRematchIntro:: @ 81B9CB3
	.string "I'm hungry, but I've got enough pep in\n"
	.string "me for a battle!$"

Route109_Text_RickyRematchDefeated:: @ 81B9CEB
	.string "I lost...\n"
	.string "It's because I'm hungry...$"

Route109_Text_RickyRematchPostBattle:: @ 81B9D10
	.string "When you eat on a beach, everything\n"
	.string "seems to taste a little better.$"

Route109_Text_LolaIntro:: @ 81B9D54
	.string "Doesn't a beach umbrella look like\n"
	.string "a giant flower?$"

Route109_Text_LolaDefeated:: @ 81B9D87
	.string "Mommy!$"

Route109_Text_LolaPostBattle:: @ 81B9D8E
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_LolaRematchIntro:: @ 81B9DD8
	.string "I'm not losing to you again!\n"
	.string "That's why I have my inner tube!$"

Route109_Text_LolaRematchDefeated:: @ 81B9E16
	.string "Mommy!$"

Route109_Text_LolaRematchPostBattle:: @ 81B9E1D
	.string "If I have an inner tube, me and my\n"
	.string "POKéMON's cuteness goes way up!$"

Route109_Text_CarmenIntro:: @ 81B9E60
	.string "I can't swim without my inner tube,\n"
	.string "but I won't lose at POKéMON!$"

Route109_Text_CarmenDefeated:: @ 81B9EA1
	.string "Did I lose because I have an inner\n"
	.string "tube?$"

Route109_Text_CarmenPostBattle:: @ 81B9ECA
	.string "My inner tube is a fashion item.\n"
	.string "I can't be seen without it.$"

Route109_Text_GwenIntro:: @ 81B9F07
	.string "Hi, big TRAINER.\n"
	.string "Will you battle with me?$"

Route109_Text_GwenDefeated:: @ 81B9F31
	.string "Oh, you're strong.$"

Route109_Text_GwenPostBattle:: @ 81B9F44
	.string "How did you get to be so strong?$"

Route109_Text_CarterIntro:: @ 81B9F65
	.string "Wahahah! This dude's going to catch\n"
	.string "himself a big one!$"

Route109_Text_CarterDefeated:: @ 81B9F9C
	.string "This dude just lost one...$"

Route109_Text_CarterPostBattle:: @ 81B9FB7
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_PaulIntro:: @ 81B9FF6
	.string "PAUL: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't disturb our\n"
	.string "precious time together.$"

Route109_Text_PaulDefeated:: @ 81BA052
	.string "PAUL: Well, I give up.$"

Route109_Text_PaulPostBattle:: @ 81BA069
	.string "PAUL: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_PaulNotEnoughPokemon:: @ 81BA0BF
	.string "PAUL: We're totally, deeply in love.\n"
	.string "That's why we make our POKéMON battle\l"
	.string "together.$"

Route109_Text_MelIntro:: @ 81BA114
	.string "MEL: We're, like, totally in love.\n"
	.string "Our romance is heating up all of HOENN!$"

Route109_Text_MelDefeated:: @ 81BA15F
	.string "MEL: We lost, and it's my fault!\n"
	.string "PAUL will hate me!$"

Route109_Text_MelPostBattle:: @ 81BA193
	.string "MEL: Um, PAUL, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_MelNotEnoughPokemon:: @ 81BA1D0
	.string "MEL: We're, like, deeply and truly in love.\n"
	.string "That's why we make our POKéMON\l"
	.string "battle together.$"
