Route123_Text_WendyIntro:: @ 81BFF6A
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:: @ 81BFFA2
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle:: @ 81BFFC1
	.string "To best even me...\n"
	.string "Your strength is marvelous!$"

Route123_Text_ClydeIntro:: @ 81BFFF0
	.string "You seem to have a big collection\n"
	.string "of GYM BADGES.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those BADGES!$"

Route123_Text_ClydeDefeat:: @ 81C0057
	.string "Oh, you're worthy, all right!$"

Route123_Text_ClydePostBattle:: @ 81C0075
	.string "You did your BADGES proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro:: @ 81C009E
	.string "They say that good times are filled\n"
	.string "with good aromas.$"

Route123_Text_VioletDefeat:: @ 81C00D4
	.string "Oh...\n"
	.string "I smell the bitter scent of misery...$"

Route123_Text_VioletPostBattle:: @ 81C0100
	.string "The BERRY MASTER's garden is filled\n"
	.string "with uplifting fragrances.$"

Route123_Text_CameronIntro:: @ 81C013F
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat:: @ 81C01A3
	.string "I feel sad...$"

Route123_Text_CameronPostBattle:: @ 81C01B1
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you...$"

Route123_Text_CameronRematchIntro:: @ 81C01F9
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat:: @ 81C0240
	.string "I feel sad...$"

Route123_Text_CameronPostRematch:: @ 81C024E
	.string "I should train at MT. PYRE...\n"
	.string "I'll never beat you this way...$"

Route123_Text_JackiIntro:: @ 81C028C
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat:: @ 81C0303
	.string "Astounding!$"

Route123_Text_JackiPostBattle:: @ 81C030F
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRematchIntro:: @ 81C0351
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:: @ 81C0380
	.string "Astounding!$"

Route123_Text_JackiPostRematch:: @ 81C038C
	.string "Your power with POKéMON...\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro:: @ 81C03CB
	.string "MIU: Hello, TRAINER. I hope your\n"
	.string "POKéMON won't cry when they lose.$"

Route123_Text_MiuDefeat:: @ 81C040E
	.string "MIU: Uh-oh, we lost.$"

Route123_Text_MiuPostBattle:: @ 81C0423
	.string "MIU: TRAINER, your POKéMON are\n"
	.string "strong because you are friends.$"

Route123_Text_MiuNotEnoughMons:: @ 81C0462
	.string "MIU: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_YukiIntro:: @ 81C049C
	.string "YUKI: Okay!\n"
	.string "We're beating the TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:: @ 81C04CD
	.string "YUKI: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle:: @ 81C04E3
	.string "YUKI: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons:: @ 81C0519
	.string "YUKI: It's no fun to battle if you\n"
	.string "don't have two POKéMON.$"

Route123_Text_KindraIntro:: @ 81C0554
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\l"
	.string "Will your POKéMON sleep?$"

Route123_Text_KindraDefeat:: @ 81C059F
	.string "Overflowing with vitality...$"

Route123_Text_KindraPostBattle:: @ 81C05BC
	.string "MT. PYRE...\n"
	.string "Where the spirits of POKéMON sleep...\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits...$"
