Route112_Text_BriceIntro:: @ 81BB619
	.string "Hahahahahaha!\n"
	.string "Wie wäre es, wenn wir kämpfen?\l"
	.string "Du und ich!\l"
	.string "Hahahahahaha!$"

Route112_Text_BriceDefeat:: @ 81BB655
	.string "Ich habe verloren!\n"
	.string "Hahahahahaha!$"

Route112_Text_BricePostBattle:: @ 81BB667
	.string "Hahahahahaha! Irgendetwas ist mir in\n"
	.string "die Nase geflogen! Hahahahahaaatschiii!$"

Route112_Text_TrentIntro:: @ 81BB6A0
	.string "Meine Beine sind durch das Klettern in\n"
	.string "den Bergen richtig muskulös geworden.\p"
	.string "So leicht werden sie also nicht\n"
	.string "einknicken, mein Freund!$"

Route112_Text_TrentDefeat:: @ 81BB707
	.string "Aua! Ich habe Muskelkrämpfe!$"

Route112_Text_TrentPostBattle:: @ 81BB721
	.string "Versuche mal, in den Bergen zu wandern.\n"
	.string "Und zwar mit richtig festem Schritt. Und\l"
	.string "das mit einem schweren Rucksack von\l"
	.string "mehreren Pfund Gewicht...\p"
	.string "So, mein Freund, bringst du deinen\n"
	.string "Körper richtig in Form.$"

Route112_Text_TrentRematchIntro:: @ 81BB7C7
	.string "Ich halte mich mit Wandern fit!\n"
	.string "Dadurch habe ich viele Kräfte im Ärmel!$"

Route112_Text_TrentRematchDefeat:: @ 81BB801
	.string "Meine Ärmel waren wohl verknotet...$"

Route112_Text_TrentRematchPostBattle:: @ 81BB819
	.string "Ich habe gehört, dass es am Gipfel vom\n"
	.string "SCHLOTBERG viele starke TRAINER gibt.\p"
	.string "Ich werde dort hochgehen und sie alle\n"
	.string "herausfordern!$"

Route112_Text_LarryIntro:: @ 81BB893
	.string "Ich bin stark. Ich weine bestimmt\n"
	.string "nicht, wenn ich verliere.$"

Route112_Text_LarryDefeat:: @ 81BB8B6
	.string "Waaahaaa! Heul... Schluchz...$"

Route112_Text_LarryPostBattle:: @ 81BB8BE
	.string "Ich weine, weil ich meine Maaaaamiiii\n"
	.string "vermisse! Schluchz... Jammer...$"

Route112_Text_CarolIntro:: @ 81BB8F0
	.string "Machst du ein Picknick, dann musst du\n"
	.string "einfach vor Freude laut singen!\l"
	.string "Komm, wir singen zusammen.$"

Route112_Text_CarolDefeat:: @ 81BB942
	.string "Oh, du triffst die Töne besser als ich!$"

Route112_Text_CarolPostBattle:: @ 81BB958
	.string "Es ist egal, ob du besser singst oder\n"
	.string "besser mit POKéMON kämpfen kannst.\p"
	.string "Wenn du Spaß hast, hast du schon\n"
	.string "gewonnen!$"
