Route127_Text_CalebIntro:: @ 81C17A8
	.string "I can see it in your face. You want\n"
	.string "to challenge me.$"

Route127_Text_CalebDefeat:: @ 81C17DD
	.string "Awawawawawa...$"

Route127_Text_CalebPostBattle:: @ 81C17EC
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_ConnorIntro:: @ 81C1828
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_ConnorDefeat:: @ 81C1860
	.string "Arrrgh! I hate losing!$"

Route127_Text_ConnorPostBattle:: @ 81C1877
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro:: @ 81C18CC
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity...\l"
	.string "Please, allow me to demonstrate...$"

Route127_Text_JonahDefeat:: @ 81C1930
	.string "Though I have lost, my heart remains\n"
	.string "calm...$"

Route127_Text_JonahPostBattle:: @ 81C195D
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water...$"

Route127_Text_HenryIntro:: @ 81C19A3
	.string "Whoops! Don't tell me I snagged\n"
	.string "a SURFING POKéMON?$"

Route127_Text_HenryDefeat:: @ 81C19D6
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle:: @ 81C19E7
	.string "Your POKéMON look pretty strong.\n"
	.string "They'd be a handful if I hooked them!$"

Route127_Text_RogerIntro:: @ 81C1A2E
	.string "Well, hey! This is a match between a\n"
	.string "POKéMON fan and a fishing buff!$"

Route127_Text_RogerDefeat:: @ 81C1A73
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle:: @ 81C1AA0
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_KojiIntro:: @ 81C1AE2
	.string "What I learned at DEWFORD's POKéMON\n"
	.string "GYM, I will put into practice here.$"

Route127_Text_KojiDefeat:: @ 81C1B2A
	.string "I was swamped!$"

Route127_Text_KojiPostBattle:: @ 81C1B39
	.string "BRAWLY, DEWFORD's GYM LEADER, used\n"
	.string "to train with a guy named BRUNO in\l"
	.string "KANTO, I've heard.$"

Route127_Text_ByronIntro:: @ 81C1B92
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_ByronDefeat:: @ 81C1BD9
	.string "Whew... I give up.$"

Route127_Text_ByronPostBattle:: @ 81C1BEC
	.string "There're lots of diving spots in the\n"
	.string "sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"
