BattleTower_BattleRoom_Text_RestoreMonsToFullHealth:: @ 819ACDC
	.string "Wir heilen deine POKéMON und machen\n"
	.string "sie wieder fit!$"

BattleTower_BattleRoom_Text_ReadyForOpponent:: @ 819AD09
	.string "Nun wirst du dich Gegner Nr. {STR_VAR_1} stellen\n"
	.string "müssen. Bist du bereit?$"

BattleTower_BattleRoom_Text_SaveAndQuitGame:: @ 819AD3C
	.string "Möchtest du das Spiel speichern und\n"
	.string "beenden?$"

BattleTower_BattleRoom_Text_CancelYourChallenge:: @ 819AD66
	.string "Möchtest du die Herausforderung im\n"
	.string "KAMPFRAUM abbrechen?$"
