Route108_Text_JeromeIntro:: @ 81B97C3
	.string "Mein Traum ist es, durch die sieben\n"
	.string "Weltmeere zu schwimmen.$"

Route108_Text_JeromeDefeated:: @ 81B97EF
	.string "So werde ich niemals in der Lage sein,\n"
	.string "die sieben Weltmeere zu durchschwimmen.$"

Route108_Text_JeromePostBattle:: @ 81B9823
	.string "Mit maritimen POKéMON zu spielen, ist\n"
	.string "eine der Freuden beim Schwimmen.$"

Route108_Text_MatthewIntro:: @ 81B9864
	.string "Ahoi, da! Willst du auch zum\n"
	.string "SCHIFFSWRACK?$"

Route108_Text_MatthewDefeated:: @ 81B989F
	.string "Ich gehe unter!\n"
	.string "Blubb... blubb... blubb...$"

Route108_Text_MatthewPostBattle:: @ 81B98BC
	.string "Einige Leute gehen sogar in das\n"
	.string "SCHIFFSWRACK hinein!$"

Route108_Text_TaraIntro:: @ 81B98EC
	.string "Mein Freund, dieser Lügner, sagt,\n"
	.string "ich sähe klasse in dem Bikini aus...$"

Route108_Text_TaraDefeated:: @ 81B992C
	.string "Oh, buuuh!$"

Route108_Text_TaraPostBattle:: @ 81B9935
	.string "Auch wenn es eine Lüge ist, liebe ich es,\n"
	.string "Komplimente zu bekommen.\l"
	.string "Wir Mädchen sind so komplex...$"

Route108_Text_MissyIntro:: @ 81B9986
	.string "Ich liebe das Meer! Ich vergesse all\n"
	.string "meine Probleme, wenn ich schwimme.$"

Route108_Text_MissyDefeated:: @ 81B99BB
	.string "Wenn ich verliere, bin ich total\n"
	.string "gestresst!$"

Route108_Text_MissyPostBattle:: @ 81B99E9
	.string "Baue Stress durch Schwimmen ab.\n"
	.string "Das ist sehr gesund!$"
