Route107_Text_DarrinIntro:: @ 81B926B
	.string "Yawn...\p"
	.string "I must have drifted off to sleep while\n"
	.string "I was drifting in the waves.$"

Route107_Text_DarrinDefeated:: @ 81B92B7
	.string "Ahaha, I lost...\n"
	.string "I'll take a snooze, I think...$"

Route107_Text_DarrinPostBattle:: @ 81B92E7
	.string "Floating and being rocked by the\n"
	.string "waves - it's like sleeping in a plush,\l"
	.string "comfy bed.$"

Route107_Text_TonyIntro:: @ 81B933A
	.string "The sea is like my backyard.\n"
	.string "Let's battle!$"

Route107_Text_TonyDefeated:: @ 81B9365
	.string "I lost on my home field...\n"
	.string "I'm in shock!$"

Route107_Text_TonyPostBattle:: @ 81B938E
	.string "I swim the seas with a heart full of\n"
	.string "dreams...\p"
	.string "It's a song!\n"
	.string "Anyways, I'm swimming some more.$"

Route107_Text_TonyRematchIntro:: @ 81B93EB
	.string "Swimming in the big, wide sea, my\n"
	.string "POKéMON has grown stronger!$"

Route107_Text_TonyRematchDefeated:: @ 81B9429
	.string "What a shock!\p"
	.string "My POKéMON has gotten stronger, but\n"
	.string "I stayed weak as a TRAINER!$"

Route107_Text_TonyRematchPostBattle:: @ 81B9477
	.string "What you learn in battle makes you a\n"
	.string "stronger TRAINER.\l"
	.string "The waves taught me that.$"

Route107_Text_DeniseIntro:: @ 81B94C8
	.string "Do you know a little town called\n"
	.string "DEWFORD?$"

Route107_Text_DeniseDefeated:: @ 81B94F2
	.string "I hate this!$"

Route107_Text_DenisePostBattle:: @ 81B94FF
	.string "A weird saying is getting really\n"
	.string "trendy at DEWFORD HALL.$"

Route107_Text_BethIntro:: @ 81B9538
	.string "Did you want to battle me?\n"
	.string "Sure, I'll go with you!$"

Route107_Text_BethDefeated:: @ 81B956B
	.string "I wasn't good enough for you.$"

Route107_Text_BethPostBattle:: @ 81B9589
	.string "I think you're going to keep getting\n"
	.string "better. I'll go for it, too!$"

Route107_Text_LisaIntro:: @ 81B95CB
	.string "LISA: We challenge you as a sister\n"
	.string "and brother!$"

Route107_Text_LisaDefeated:: @ 81B95FB
	.string "LISA: Awesome.\n"
	.string "You're in a different class of tough.$"

Route107_Text_LisaPostBattle:: @ 81B9630
	.string "LISA: Do you have any friends who\n"
	.string "would go to the beach with you?$"

Route107_Text_LisaNotEnoughPokemon:: @ 81B9672
	.string "LISA: If you want to battle with us,\n"
	.string "bring more POKéMON.$"

Route107_Text_RayIntro:: @ 81B96AB
	.string "RAY: We always battle POKéMON, me\n"
	.string "and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_RayDefeated:: @ 81B9707
	.string "RAY: Wowee, you're at a higher level\n"
	.string "than us!$"

Route107_Text_RayPostBattle:: @ 81B9735
	.string "RAY: My sister gave me my POKéMON.\n"
	.string "I raised it, and now it's my important\l"
	.string "partner!$"

Route107_Text_RayNotEnoughPokemon:: @ 81B9788
	.string "RAY: If you want to battle us, go\n"
	.string "bring some more POKéMON!$"
