Route110_Text_JacobIntro:: @ 81BA22C
	.string "Whoa! Watch it!\n"
	.string "I guess you're not used to BIKE racing.$"

Route110_Text_JacobDefeated:: @ 81BA264
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_JacobPostBattle:: @ 81BA27C
	.string "Flat tires and brake problems can\n"
	.string "cause serious injury!\l"
	.string "Inspect your BIKE for problems!$"

Route110_Text_AnthonyIntro:: @ 81BA2D4
	.string "Yo, you!\n"
	.string "Can you keep up with my speed?$"

Route110_Text_AnthonyDefeated:: @ 81BA2FC
	.string "Crash and burn!$"

Route110_Text_AnthonyPostBattle:: @ 81BA30C
	.string "Speed alone won't let me win at POKéMON.\n"
	.string "I need to reconsider this...$"

Route110_Text_BenjaminIntro:: @ 81BA352
	.string "Don't panic if your BIKE's going fast!$"

Route110_Text_BenjaminDefeated:: @ 81BA379
	.string "I shouldn't panic during POKéMON\n"
	.string "battles...$"

Route110_Text_BenjaminPostBattle:: @ 81BA3A5
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_BenjaminRematchIntro:: @ 81BA3EF
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_BenjaminRematchDefeated:: @ 81BA432
	.string "I didn't panic, but I still lost...$"

Route110_Text_BenjaminRematchPostBattle:: @ 81BA456
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_AbigailIntro:: @ 81BA4A0
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to complete the three events\n"
	.string "of swimming, cycling, and running.$"

Route110_Text_AbigailDefeated:: @ 81BA50F
	.string "POKéMON battles are hard, too!$"

Route110_Text_AbigailPostBattle:: @ 81BA52E
	.string "I'm exhausted, so I need a break.\n"
	.string "It's important to get proper rest.$"

Route110_Text_AbigailRematchIntro:: @ 81BA573
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_AbigailRematchDefeated:: @ 81BA5A1
	.string "Wow...\n"
	.string "How could you be so strong?$"

Route110_Text_AbigailRematchPostBattle:: @ 81BA5C4
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro:: @ 81BA5FF
	.string "I've been riding without stopping.\n"
	.string "My thighs are like rocks!$"

Route110_Text_JasmineDefeated:: @ 81BA63C
	.string "I'm worried about muscle cramps...$"

Route110_Text_JasminePostBattle:: @ 81BA65F
	.string "Oh, you have some GYM BADGES?\n"
	.string "No wonder you're so strong!$"

Route110_Text_EdwardIntro:: @ 81BA699
	.string "I have foreseen your intentions!\n"
	.string "I cannot possibly lose!$"

Route110_Text_EdwardDefeated:: @ 81BA6D2
	.string "I failed to prophesize my own demise!$"

Route110_Text_EdwardPostBattle:: @ 81BA6F8
	.string "I see your future...\p"
	.string "Hmm...\n"
	.string "I see a shining light...$"

Route110_Text_JaclynIntro:: @ 81BA72D
	.string "Ahahahaha!\n"
	.string "I'll dazzle you with my wonders!$"

Route110_Text_JaclynDefeated:: @ 81BA759
	.string "I wondrously lost!$"

Route110_Text_JaclynPostBattle:: @ 81BA76C
	.string "You managed to win only because it was\n"
	.string "a wonder! Yes, a wonder!\l"
	.string "Don't think you can win all the time!$"

Route110_Text_EdwinIntro:: @ 81BA7D2
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinDefeated:: @ 81BA803
	.string "I wanted to complete my\n"
	.string "collection...$"

Route110_Text_EdwinPostBattle:: @ 81BA829
	.string "When I see a POKéMON that I don't know,\n"
	.string "my passion as a collector is ignited!$"

Route110_Text_EdwinRematchIntro:: @ 81BA877
	.string "Hi, have you caught any new POKéMON?\p"
	.string "Could I see your POKéMON?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinRematchDefeated:: @ 81BA8CD
	.string "Your POKéMON...\n"
	.string "I envy you.$"

Route110_Text_EdwinRematchPostBattle:: @ 81BA8E9
	.string "Oh, I long to make all rare POKéMON\n"
	.string "mine!$"

Route110_Text_DaleIntro:: @ 81BA913
	.string "Hey!\n"
	.string "Don't sneak up behind me like that!$"

Route110_Text_DaleDefeated:: @ 81BA93C
	.string "I lost!\n"
	.string "Drat!$"

Route110_Text_DalePostBattle:: @ 81BA94A
	.string "Fishing is all about concentration.\n"
	.string "You have to focus on the floater.$"

Route110_Text_IsabelIntro:: @ 81BA990
	.string "Ahahaha! I would go anywhere to show\n"
	.string "off my delightful POKéMON.$"

Route110_Text_IsabelDefeated:: @ 81BA9D0
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelPostBattle:: @ 81BA9E9
	.string "Perhaps I should groom my POKéMON for\n"
	.string "CONTESTS rather than battles.$"

Route110_Text_IsabelRematchIntro:: @ 81BAA2D
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my POKéMON as often as you like!$"

Route110_Text_IsabelRematchDefeated:: @ 81BAA76
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelRematchPostBattle:: @ 81BAA8F
	.string "CONTESTS are delightful, but I like\n"
	.string "to battle, too.$"

Route110_Text_TimmyIntro:: @ 81BAAC3
	.string "I found some cool POKéMON in the grass\n"
	.string "around here!$"

Route110_Text_TimmyDefeated:: @ 81BAAF7
	.string "Being cool isn't enough to win...$"

Route110_Text_TimmyPostBattle:: @ 81BAB19
	.string "It's hard to battle with POKéMON you\n"
	.string "just caught.$"
