Route104_Prototype_Text_CindyIntro:: @ 819AD9B
	.string "Oh? You look like a good TRAINER.\n"
	.string "Will you look at my POKéMON?$"

Route104_Prototype_Text_CindyDefeated:: @ 819ADDA
	.string "I'm not good enough for you.$"

Route104_Prototype_Text_CindyPostBattle:: @ 819ADF7
	.string "I enjoyed our battle very much.\n"
	.string "Please battle with me some other time.$"

Route104_Prototype_Text_AmyAndLivIntro:: @ 819AE3E
	.string "Go!\n"
	.string "Go, our POKéMON!$"

Route104_Prototype_Text_AmyAndLivDefeated:: @ 819AE53
	.string "Oh... We couldn't win.$"

Route104_Prototype_Text_AmyAndLivPostBattle:: @ 819AE6A
	.string "Did it surprise you that two POKéMON\n"
	.string "battled at the same time?$"

Route104_Prototype_Text_AmyAndLivNotEnoughPokemon:: @ 819AEA9
	.string "You can't battle with us if you have\n"
	.string "only one POKéMON.\l"
	.string "Why? Because we're strong!$"

Route104_Prototype_Text_MikeIntro:: @ 819AEFB
	.string "Hey, hey! This is my first battle in\n"
	.string "a while. I'll give it my all!$"

Route104_Prototype_Text_MikeDefeated:: @ 819AF3E
	.string "But I gave it my all...$"

Route104_Prototype_Text_MikePostBattle:: @ 819AF56
	.string "You're far too strong!\n"
	.string "You must be a great TRAINER!$"

Route104_Prototype_Text_BriannaIntro:: @ 819AF8A
	.string "My POKéMON are extremely cute and\n"
	.string "extremely strong.\l"
	.string "Please allow me to show you.$"

Route104_Prototype_Text_BriannaDefeated:: @ 819AFDB
	.string "I must concede defeat.\n"
	.string "After all, you are strong.$"

Route104_Prototype_Text_BriannaPostBattle:: @ 819B00D
	.string "The next time we meet, I will have raised\n"
	.string "my POKéMON much more.\p"
	.string "Don't expect mercy then!$"

Route104_Prototype_Text_LucasIntro:: @ 819B066
	.string "We HIKERS are always full of energy!\n"
	.string "My POKéMON are also full of energy, too.\l"
	.string "We're always itching for a battle!$"

Route104_Prototype_Text_LucasDefeated:: @ 819B0D7
	.string "We ran out of energy...$"

Route104_Prototype_Text_LucasPostBattle:: @ 819B0EF
	.string "Wahahah! Sure, we lost!\n"
	.string "But we had a great battle, didn't we?\l"
	.string "We're satisfied with that!$"

Route104_Prototype_Text_GinaAndMiaIntro:: @ 819B148
	.string "You look like a strong TRAINER,\n"
	.string "but can you beat us?$"

Route104_Prototype_Text_GinaAndMiaDefeated:: @ 819B17D
	.string "Waaah!\n"
	.string "We lost!$"

Route104_Prototype_Text_GinaAndMiaPostBattle:: @ 819B18D
	.string "If two POKéMON can battle at the same\n"
	.string "time, all sorts of new things can happen.$"

Route104_Prototype_Text_GinaAndMiaNotEnoughPokemon:: @ 819B1DD
	.string "Do you only have one POKéMON that can\n"
	.string "battle?\p"
	.string "Then we can't battle with you yet.$"

Route104_Prototype_Text_BoyAskDefeatAllTrainers:: @ 819B22E
	.string "Have you tried beating all the other\n"
	.string "TRAINERS in battle?$"

Route104_Prototype_Text_BoyThankYouForComing:: @ 819B267
	.string "Thanks for coming today!\p"
	.string "I hope you're looking forward to this\n"
	.string "game's release!$"

Route104_Prototype_Text_GirlAskDefeatAllTrainers:: @ 819B2B6
	.string "Huh? Did you battle with all the\n"
	.string "TRAINERS already?$"

Route104_Prototype_Text_GirlThankYouForComing:: @ 819B2E9
	.string "Thank you for coming today!\p"
	.string "I hope you're looking forward to this\n"
	.string "game's release!$"

Route104_Prototype_Text_NeverSeenPokemonLikeYours:: @ 819B33B
	.string "I've never seen the POKéMON you have.\n"
	.string "It makes me envious a little.$"

Route104_Prototype_Text_TrainersAreWaitingForYou:: @ 819B37F
	.string "Look at all those TRAINERS!\n"
	.string "They have different POKéMON, too.\l"
	.string "And they're all waiting for you!$"

Route104_Prototype_Text_WelcomeToWorldOfPokemon:: @ 819B3DE
	.string "Welcome to the World of POKéMON!$"

Route104_Prototype_Text_PokemonBattlesMessage:: @ 819B3FF
	.string "May all POKéMON battles be bright,\n"
	.string "fun, and ferocious!$"
