Route111_Text_DrewIntro:: @ 81BAB4B
	.string "Oh, hey! Those GO-GOGGLES suit you.\n"
	.string "But I think they look better on me.\p"
	.string "Let's decide who they look better on\n"
	.string "with a battle!$"

Route111_Text_DrewDefeat:: @ 81BABC7
	.string "I couldn't see what was happening at my\n"
	.string "sides because of the GO-GOGGLES.$"

Route111_Text_DrewPostBattle:: @ 81BAC10
	.string "The GO-GOGGLES make it possible to\n"
	.string "get through sandstorms.\l"
	.string "That makes me happy!$"

Route111_Text_HeidiIntro:: @ 81BAC60
	.string "I'm having a picnic in the desert.\p"
	.string "You can always find a TRAINER, so\n"
	.string "I can enjoy a battle here, too!$"

Route111_Text_HeidiDefeat:: @ 81BACC5
	.string "Ohhh! You're mean!$"

Route111_Text_HeidiPostBattle:: @ 81BACD8
	.string "When you're battling in a sandstorm,\n"
	.string "watch out for your POKéMON's HP.\p"
	.string "It can faint if you don't keep an eye\n"
	.string "on it!$"

Route111_Text_CliffIntro:: @ 81BAD4B
	.string "Wearing these GO-GOGGLES makes me\n"
	.string "feel like a superhero.\l"
	.string "Right now, nobody can beat me!$"

Route111_Text_CliffDefeat:: @ 81BADA3
	.string "I can't win on spirit alone...$"

Route111_Text_CliffPostBattle:: @ 81BADC2
	.string "I'm going to be a real hero one day.\n"
	.string "I'm going to work harder to make me\l"
	.string "and my POKéMON stronger.$"

Route111_Text_BeckyIntro:: @ 81BAE24
	.string "I heard there are fossils to be found\n"
	.string "in the desert. Where could they be?$"

Route111_Text_BeckyDefeat:: @ 81BAE6E
	.string "I came up short...$"

Route111_Text_BeckyPostBattle:: @ 81BAE81
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_DustyIntro:: @ 81BAEC9
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\l"
	.string "I am to be challenged?$"

Route111_Text_DustyDefeat:: @ 81BAF14
	.string "While I have searched for ruins, I've\n"
	.string "not searched for strong POKéMON.$"

Route111_Text_DustyPostBattle:: @ 81BAF5B
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Which was it now?$"

Route111_Text_DustyRematchIntro:: @ 81BAFC1
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat:: @ 81BB034
	.string "I've found no ruins, nor have I found\n"
	.string "any strong POKéMON...$"

Route111_Text_DustyPostRematch:: @ 81BB070
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years I've\n"
	.string "searched?\p"
	.string "Hmm... It could even be fifty...\n"
	.string "How long have I been at this?$"

Route111_Text_TravisIntro:: @ 81BB111
	.string "I'm full of pep!\n"
	.string "And my POKéMON is peppy, too!$"

Route111_Text_TravisDefeat:: @ 81BB140
	.string "My POKéMON lost its pep...$"

Route111_Text_TravisPostBattle:: @ 81BB15B
	.string "When I see a TRAINER with a lot of pep,\n"
	.string "I can't help looking.$"

Route111_Text_IreneIntro:: @ 81BB199
	.string "I don't know where you're going, but\n"
	.string "would you like to battle?$"

Route111_Text_IreneDefeat:: @ 81BB1D8
	.string "Oh, you're disgustingly good!$"

Route111_Text_IrenePostBattle:: @ 81BB1F6
	.string "I'm thinking that I should go to\n"
	.string "MT. CHIMNEY, but the view around\l"
	.string "here is very nice, too.$"

Route111_Text_DaisukeIntro:: @ 81BB250
	.string "To train myself, I challenge all\n"
	.string "whom I meet!$"

Route111_Text_DaisukeDefeat:: @ 81BB27E
	.string "Uncle! I give up!$"

Route111_Text_DaisukePostBattle:: @ 81BB290
	.string "All I can do is keep training until\n"
	.string "I can defeat strong TRAINERS such\l"
	.string "as yourself.$"

Route111_Text_WiltonIntro:: @ 81BB2E3
	.string "Show me how much you've toughened\n"
	.string "your POKéMON.$"

Route111_Text_WiltonDefeat:: @ 81BB313
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_WiltonPostBattle:: @ 81BB33E
	.string "POKéMON and TRAINERS learn much\n"
	.string "through battling.\p"
	.string "What's important is to never give up\n"
	.string "even if you lose.$"

Route111_Text_WiltonRematchIntro:: @ 81BB3A7
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:: @ 81BB3FA
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch:: @ 81BB40E
	.string "Since you're that strong, you should\n"
	.string "aim for the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:: @ 81BB44F
	.string "Oh, your POKéMON look like serious\n"
	.string "actors.\l"
	.string "I have to ask you for an engagement.$"

Route111_Text_BrookeDefeat:: @ 81BB49F
	.string "They didn't just look strong, they\n"
	.string "are strong!$"

Route111_Text_BrookePostBattle:: @ 81BB4CE
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but, oh no, there is still\l"
	.string "much to be done.$"

Route111_Text_BrookeRematchIntro:: @ 81BB529
	.string "You can make POKéMON stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your POKéMON\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat:: @ 81BB5A2
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch:: @ 81BB5C1
	.string "Maybe I should have stopped my\n"
	.string "POKéMON from evolving until they\l"
	.string "learned better moves...$"
