Route118_Text_RoseIntro:: @ 81BDFF4
	.string "Der Duft von Blumen hat eine magische\n"
	.string "Kraft. Er reinigt Körper und Geist.$"

Route118_Text_RoseDefeat:: @ 81BE03C
	.string "Oh, du meine Güte.\n"
	.string "Scheinbar habe ich verloren.$"

Route118_Text_RosePostBattle:: @ 81BE05E
	.string "Blumen, POKéMON...\n"
	.string "Ich liebe alles, was gut riecht.\p"
	.string "Stinkende Dinge...\n"
	.string "Bah, da muss ich passen.$"

Route118_Text_RoseRematchIntro:: @ 81BE0AB
	.string "Hat dich der süße Duft hierher\n"
	.string "gebracht?$"

Route118_Text_RoseRematchDefeat:: @ 81BE0D3
	.string "Die Kraft des Duftes...\n"
	.string "Sie scheint nichts zu bewirken.$"

Route118_Text_RosePostRematch:: @ 81BE104
	.string "Wenn du einen süßen Duft richtig ein-\n"
	.string "setzt, werden POKéMON davon\l"
	.string "angezogen.$"

Route118_Text_PerryIntro:: @ 81BE148
	.string "VOGEL-POKéMON, die elegant durch die\n"
	.string "Lüfte FLIEGEN... Sie sind die Besten!$"

Route118_Text_PerryDefeat:: @ 81BE188
	.string "Argh... Das war eine Bruchlandung...$"

Route118_Text_PerryPostBattle:: @ 81BE19D
	.string "Du hast großartige POKéMON.\n"
	.string "Ich muss meines besser trainieren.$"

Route118_Text_ChesterIntro:: @ 81BE1D7
	.string "Erhebt euch!\n"
	.string "Meine VOGEL-POKéMON!$"

Route118_Text_ChesterDefeat:: @ 81BE1F5
	.string "Sie sind abgehoben...$"

Route118_Text_ChesterPostBattle:: @ 81BE20D
	.string "Wenn sie erst einmal stärker geworden\n"
	.string "sind, können sie auch freier fliegen.$"

Route118_Text_BarnyIntro:: @ 81BE24A
	.string "Ich bin ein ANGLER, aber auch ein\n"
	.string "TRAINER. Ich ziehe die POKéMON auf,\l"
	.string "die ich gefangen habe.$"

Route118_Text_BarnyDefeat:: @ 81BE291
	.string "Ich dachte, ich wäre gut im Training...$"

Route118_Text_BarnyPostBattle:: @ 81BE2BE
	.string "Ich kann nicht gewinnen, wenn ich\n"
	.string "POKéMON trainiere, während ich angle.\p"
	.string "Habe ich alles nur halb getan?$"

Route118_Text_WadeIntro:: @ 81BE318
	.string "Für ANGLER ist die Ausrüstung\n"
	.string "entscheidend.\p"
	.string "Aber für TRAINER sind natürlich die\n"
	.string "POKéMON und das Herz entscheidend!$"

Route118_Text_WadeDefeat:: @ 81BE385
	.string "Ich wurde im Herzen geschlagen?$"

Route118_Text_WadePostBattle:: @ 81BE39C
	.string "Wenn ich so darüber nachdenke, komme\n"
	.string "ich zu dem Schluss, dass Angeln ein\l"
	.string "Kampf zwischen ANGLER und POKéMON ist.$"

Route118_Text_DaltonIntro:: @ 81BE3E8
	.string "Meine Melodie wird deine Seele\n"
	.string "erschüttern.$"

Route118_Text_DaltonDefeat:: @ 81BE406
	.string "La-lalala...$"

Route118_Text_DaltonPostBattle:: @ 81BE413
	.string "Eine E-Gitarre muss nicht immer laut\n"
	.string "sein...\p"
	.string "Sie kann auch so gespielt werden, dass\n"
	.string "eine herzergreifende Melodie erklingt...$"

Route118_Text_DaltonRematchIntro:: @ 81BE489
	.string "Eine Melodie von meinen POKéMON und mir.\n"
	.string "Lass sie uns deiner Seele schenken.$"

Route118_Text_DaltonRematchDefeat:: @ 81BE4CC
	.string "La-lalala...$"

Route118_Text_DaltonPostRematch:: @ 81BE4D9
	.string "Wenn ich spiele, sollten dich meine Ge-\n"
	.string "fühle über meine E-Gitarre erreichen...$"
