Route134_Text_JackIntro:: @ 81C30C6
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "My LUVDISC are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "There's a collector who's after the\n"
	.string "SCALES of LUVDISC.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Tuckered out again...$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "You're a POKéMON TRAINER.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed...$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "I concede defeat.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"
