Route119_Text_BrentIntro:: @ 81BE521
	.string "Wir gehören zum Mimikry-Zirkel!\n"
	.string "Wir ahmen nach, was du machst!$"

Route119_Text_BrentDefeat:: @ 81BE54F
	.string "Huupsie!\n"
	.string "Ich habe verloren!$"

Route119_Text_BrentPostBattle:: @ 81BE561
	.string "Was so toll an Mimikry sein soll?\p"
	.string "Hähähä...\n"
	.string "Das wirst du nie verstehen...$"

Route119_Text_DonaldIntro:: @ 81BE5A4
	.string "So trifft man sich! Meine KÄFER-POKéMON\n"
	.string "leisten dir Gesellschaft!$"

Route119_Text_DonaldDefeat:: @ 81BE5DF
	.string "Ich wünschte, wir hätten uns nie\n"
	.string "getroffen...$"

Route119_Text_DonaldPostBattle:: @ 81BE5F8
	.string "Ich möchte noch Mimikry bei dir an-\n"
	.string "wenden.\p"
	.string "Kannst du dich mal ein bisschen\n"
	.string "bewegen?$"

Route119_Text_TaylorIntro:: @ 81BE632
	.string "Trittst du einen Schritt vor, treten wir\n"
	.string "auch einen Schritt vor.\p"
	.string "Drehst du dich nach rechts, drehen wir\n"
	.string "uns auch nach rechts...$"

Route119_Text_TaylorDefeat:: @ 81BE67B
	.string "Aber wenn du gewinnst, verliere ich...$"

Route119_Text_TaylorPostBattle:: @ 81BE695
	.string "Ich kann nicht mit Mimikry nachahmen,\n"
	.string "wie du den Kampf gewinnst. Unmöglich!\l"
	.string "Das lässt mich kochen vor Wut.$"

Route119_Text_DougIntro:: @ 81BE6EA
	.string "Hey, geschafft! Du hast mich gefunden!\n"
	.string "Oder wolltest du mir ausweichen?$"

Route119_Text_DougDefeat:: @ 81BE729
	.string "Hui, was für ein großartiger Kampf!$"

Route119_Text_DougPostBattle:: @ 81BE748
	.string "Wir sind der Mimikry-Zirkel! Ich\n"
	.string "hoffe, dir gefiel unsere Vorstellung!$"

Route119_Text_GregIntro:: @ 81BE784
	.string "Du weißt nicht, wer ich bin, stimmt's?\p"
	.string "Aber... Ich kenne dich auch nicht.\n"
	.string "Lass uns kämpfen.$"

Route119_Text_GregDefeat:: @ 81BE7D3
	.string "Du bist ganz schön stark!$"

Route119_Text_GregPostBattle:: @ 81BE7E9
	.string "Solange du hier bist, werden wir jede\n"
	.string "deiner Bewegungen nachahmen.$"

Route119_Text_KentIntro:: @ 81BE82F
	.string "Der Mimikry-Zirkel wurde von Leuten\n"
	.string "gegründet, die die Mimikry lieben.\p"
	.string "Der Kampf beginnt, sobald wir aufei-\n"
	.string "nander treffen!$"

Route119_Text_KentDefeat:: @ 81BE88D
	.string "Ich gebe auf!$"

Route119_Text_KentPostBattle:: @ 81BE89A
	.string "Möchtest du nicht dem Mimikry-Zirkel\n"
	.string "beitreten?$"

Route119_Text_JacksonIntro:: @ 81BE8BB
	.string "Wer besitzt das Wissen und die Technik,\n"
	.string "um zu überleben?\p"
	.string "Das sind die POKéMON-RANGER!$"

Route119_Text_JacksonDefeat:: @ 81BE90E
	.string "Ich besitze nicht genügend Wissen über\n"
	.string "POKéMON...$"

Route119_Text_JacksonPostBattle:: @ 81BE937
	.string "Aus der Zivilisation ausbrechen und die\n"
	.string "wilde Natur in uns erwecken!\p"
	.string "Das ist unsere Vision.$"

Route119_Text_JacksonRematchIntro:: @ 81BE98D
	.string "Meine wilde Natur regt sich in mir, wenn\n"
	.string "ich mit POKéMON zusammen bin.$"

Route119_Text_JacksonRematchDefeat:: @ 81BE9D0
	.string "Du bist immer noch sehr stark!$"

Route119_Text_JacksonPostRematch:: @ 81BE9E8
	.string "Glaube an deine POKéMON.\n"
	.string "Glaube an dich.\p"
	.string "Dein Weg eröffnet sich von selbst.$"

Route119_Text_CatherineIntro:: @ 81BEA3A
	.string "Oh! Schau dich nur an!\p"
	.string "Für einen Abenteurer hast du\n"
	.string "sehr leichtes Gepäck dabei!$"

Route119_Text_CatherineDefeat:: @ 81BEA88
	.string "Unfälle passieren immer dann, wenn du\n"
	.string "nicht damit rechnest!$"

Route119_Text_CatherinePostBattle:: @ 81BEAB3
	.string "Du hast leichtes Gepäck, aber alles, was\n"
	.string "du brauchst dabei.\p"
	.string "Du bist an der Spitze deiner geistigen\n"
	.string "und körperlichen Kraft angekommen.$"

Route119_Text_CatherineRematchIntro:: @ 81BEB22
	.string "Wie läuft es auf deiner Reise mit den\n"
	.string "POKéMON?$"

Route119_Text_CatherineRematchDefeat:: @ 81BEB49
	.string "Bei mir fehlt irgendetwas...$"

Route119_Text_CatherinePostRematch:: @ 81BEB68
	.string "So wie du als TRAINER deinen POKéMON\n"
	.string "vertraust, vertrauen dir deine POKéMON.$"

Route119_Text_HughIntro:: @ 81BEBC0
	.string "Die Weiten des Himmels strahlen die Aura\n"
	.string "unausgesprochener Versprechen ab.\p"
	.string "Nichts ist vergleichbar mit dem\n"
	.string "absoluten Glück des Fliegens!$"

Route119_Text_HughDefeat:: @ 81BEC1C
	.string "Abgewürgt und abgestürzt.$"

Route119_Text_HughPostBattle:: @ 81BEC2A
	.string "Meine VOGEL-POKéMON lassen den Traum\n"
	.string "vom Fliegen für mich wahr werden!$"

Route119_Text_PhilIntro:: @ 81BEC5E
	.string "Ich zeige dir meine wahre Stärke und\n"
	.string "die meiner VOGEL-POKéMON!$"

Route119_Text_PhilDefeat:: @ 81BEC9A
	.string "Uns fehlt es an Potential...$"

Route119_Text_PhilPostBattle:: @ 81BECB1
	.string "Schon als kleines Kind habe ich VOGEL-\n"
	.string "POKéMON geliebt...$"

Route119_Text_YasuIntro:: @ 81BECF1
	.string "Ich lauere in den Schatten und lebe in\n"
	.string "der Dunkelheit... Das ist mein Schicksal.\p"
	.string "Ich tauche auf, um dich heraus-\n"
	.string "zufordern!$"

Route119_Text_YasuDefeat:: @ 81BED4C
	.string "Ich gestehe meine Niederlage ein.$"

Route119_Text_YasuPostBattle:: @ 81BED5C
	.string "Die, die im Kampf geschlagen wurden,\n"
	.string "verschwinden lautlos in der Dunkelheit.\l"
	.string "Auch das ist Schicksal...$"

Route119_Text_TakashiIntro:: @ 81BEDB6
	.string "Wenn du nicht auf deine Deckung auf-\n"
	.string "passt, kommt der Schmerz zu dir!$"

Route119_Text_TakashiDefeat:: @ 81BEDEC
	.string "Du bist überraschend gut!$"

Route119_Text_TakashiPostBattle:: @ 81BEE06
	.string "Mein Überraschungsangriff endete in\n"
	.string "einer Niederlage...$"

Route119_Text_HideoIntro:: @ 81BEE2D
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald!$"

Route119_Text_HideoDefeat:: @ 81BEE4B
	.string "Ich verneige mich vor deiner Stärke.$"

Route119_Text_HideoPostBattle:: @ 81BEE66
	.string "Um einen Baum zu verstecken, nutze den\n"
	.string "Wald. Um ein POKéMON zu verstecken,\l"
	.string "nutze ein POKéMON!\p"
	.string "Dahinter steckt keine tiefere\n"
	.string "Bedeutung.$"

Route119_Text_EugeneIntro:: @ 81BEED0
	.string "Du hast mich angesprochen...\n"
	.string "Also willst du mit mir kämpfen!\p"
	.string "Sicher! Ich will das POKéMON einsetzen,\n"
	.string "das ich gefangen habe, als ich SURFER\l"
	.string "einsetzte.$"

Route119_Text_EugeneDefeat:: @ 81BEF37
	.string "Ich habe keine Ahnung, was verlangt\n"
	.string "wird, um zu gewinnen.$"

Route119_Text_EugenePostBattle:: @ 81BEF67
	.string "Nutze ein POKéMON als SURFER...\p"
	.string "Dann angle von seinem Rücken aus...\p"
	.string "Ein äußerst angenehmer Zeitvertreib!$"
