MtPyre_Summit_Text_TeamAquaGrunt1Intro: @ 81B50C3
	.string "I'll show you exactly how scary\n"
	.string "TEAM AQUA can be!$"

MtPyre_Summit_Text_TeamAquaGrunt1Defeat: @ 81B50F5
	.string "So you think you can stand up alone\n"
	.string "to TEAM AQUA's might...$"

MtPyre_Summit_Text_TeamAquaGrunt1PostBattle: @ 81B5131
	.string "Yeah, so you are strong...\n"
	.string "But there're a lot of us!$"

MtPyre_Summit_Text_TeamAquaGrunt2Intro: @ 81B5166
	.string "What's up with you?\n"
	.string "What does a single kid expect to do?$"

MtPyre_Summit_Text_TeamAquaGrunt2Defeat: @ 81B519F
	.string "Dang...\n"
	.string "Too strong...$"

MtPyre_Summit_Text_TeamAquaGrunt2PostBattle: @ 81B51B5
	.string "You don't know anything.\n"
	.string "Quit messing around with us!$"

MtPyre_Summit_Text_TeamAquaGrunt3Intro: @ 81B51EB
	.string "Hey, I remember you from MT. CHIMNEY!\n"
	.string "It's payback time!$"

MtPyre_Summit_Text_TeamAquaGrunt3Defeat: @ 81B5224
	.string "Urgggh...\n"
	.string "Beaten by some kid again!$"

MtPyre_Summit_Text_TeamAquaGrunt3PostBattle: @ 81B5248
	.string "Heh, it doesn't matter!\n"
	.string "We bought ourselves some time!\p"
	.string "The BOSS should have snatched what\n"
	.string "he was after!$"

MtPyre_Summit_Text_ArchieClaimsRedOrb: @ 81B52B0
	.string "ARCHIE: Not you again...\p"
	.string "You've impeded our plans repeatedly,\n"
	.string "but this time you're too late.\p"
	.string "The RED ORB that rested atop\n"
	.string "MT. PYRE...\l"
	.string "I, ARCHIE, claim it as mine!\p"
	.string "Fufufu... Finally, I can realize my\n"
	.string "grand design...\p"
	.string "Come on, crew!\n"
	.string "It's SLATEPORT next!$"

MtPyre_Summit_Text_OldLadyGivesBlueOrb: @ 81B53AB
	.string "Oh, no...\n"
	.string "This cannot happen...\p"
	.string "How could they take the RED ORB?\p"
	.string "The BLUE ORB and RED ORB must never\n"
	.string "be separated. They belong together.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "Hmm...\p"
	.string "Fine!\n"
	.string "You take the remaining BLUE ORB.\p"
	.string "Please take after that foul man and\n"
	.string "get the other ORB back!$"

MtPyre_Summit_Text_OldLadyWarnsRedOrbStolen: @ 81B54BE
	.string "The BLUE ORB you have been entrusted\n"
	.string "with and the stolen RED ORB...\p"
	.string "They must never be apart...\n"
	.string "Something terrible will happen...$"

MtPyre_Summit_Text_OldLadyKyogreAwakened: @ 81B5540
	.string "So...\n"
	.string "KYOGRE has awoken...\p"
	.string "The wondrous ORB that is said to have\n"
	.string "becalmed the raging KYOGRE...\l"
	.string "It is the BLUE ORB you bear.\p"
	.string "That BLUE ORB was found buried inside\n"
	.string "the CAVE OF ORIGIN in SOOTOPOLIS...\p"
	.string "There is perhaps a link between\n"
	.string "KYOGRE and the CAVE OF ORIGIN...$"

MtPyre_Summit_Text_OldLadyAskReturnBlueOrb: @ 81B5647
	.string "That man, he returned the RED ORB.\p"
	.string "Are you going to return the BLUE ORB\n"
	.string "to its rightful place, too?$"

MtPyre_Summit_Text_OldLadyAskAgainReturnBlueOrb: @ 81B56AB
	.string "What's that?!\p"
	.string "If the balance is not restored, there\n"
	.string "is no telling what could happen.\p"
	.string "You will return the BLUE ORB to its\n"
	.string "rightful place, yes?$"

MtPyre_Summit_Text_PlayerHandsBlueOrbToOldLady: @ 81B5739
	.string "{PLAYER} handed the BLUE ORB to the\n"
	.string "old woman.$"

MtPyre_Summit_Text_OldLadyThanksForReturningBlueOrb: @ 81B5762
	.string "Yes...\n"
	.string "The two ORBS should remain here.\p"
	.string "It is how it should be for the good\n"
	.string "of all HOENN...$"

MtPyre_Summit_Text_OldLadyExplainsKyogre: @ 81B57BE
	.string "The spirit of the sea...\p"
	.string "That is what KYOGRE is said to be in\n"
	.string "POKéMON form...\p"
	.string "In the same manner that we and POKéMON\n"
	.string "have life, the sea is alive...\p"
	.string "KYOGRE has taught us that...$"

MtPyre_Summit_Text_AquaOldManWillYouHearOutMyTale: @ 81B586F
	.string "MT. PYRE is where we calm the spirits\n"
	.string "of POKéMON that have passed on...\p"
	.string "This is a high place where one can\n"
	.string "see all of HOENN...\p"
	.string "The disembodied spirits of POKéMON\n"
	.string "must find solace here...\p"
	.string "Is it coincidence that you are here...\p"
	.string "Will you hear out my tale? A tale long\n"
	.string "told in the HOENN region?$"

MtPyre_Summit_Text_AquaOldManSeaAndLandTale: @ 81B5992
	.string "It happened long, long ago...\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKéMON of the sea\l"
	.string "and the POKéMON of the land...\p"
	.string "The POKéMON of the sea raised huge\n"
	.string "waves and carved out oceans...\p"
	.string "The POKéMON of the land raised\n"
	.string "mountains and created continents...\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive\n"
	.string "infernos and vicious storms.\p"
	.string "The BLUE ORB and the RED ORB brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two ORBS and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, dove deep into\n"
	.string "the sea where eventually they\l"
	.string "disappeared...$"

MtPyre_Summit_Text_AquaOldManDeclineTale: @ 81B5BD7
	.string "I see...\n"
	.string "Well, that, too, is fine...$"

MtPyre_Summit_Text_ArchieReturnsRedOrb: @ 81B5BFC
	.string "ARCHIE: You...\n"
	.string "So you stopped KYOGRE...\p"
	.string "I shouldn't be surprised...\p"
	.string "I understand now that humans cannot\n"
	.string "freely control the balance between\l"
	.string "the land and the sea...\p"
	.string "So I have come to return the\n"
	.string "RED ORB...\p"
	.string "I doubt that we will cross paths again...\n"
	.string "Farewell...$"
