Route119_WeatherInstitute_1F_Text_Grunt1Intro:: @ 819EB8A
	.string "Der BOSS hat Interesse an den \n"
	.string "Forschungen gezeigt, daher hat er uns\l"
	.string "hergeschickt.\p"
	.string "Stör uns gefälligst nicht!$"

Route119_WeatherInstitute_1F_Text_Grunt1Defeat:: @ 819EBEE
	.string "So ein Mist...\n"
	.string "Besiegt... Von einem Kind!$"

Route119_WeatherInstitute_1F_Text_Grunt1PostBattle:: @ 819EC0E
	.string "Unser BOSS weiß alles.\p"
	.string "Ich bin nur ein RÜPEL. Woher soll ich\n"
	.string "wissen, was er denkt?$"

Route119_WeatherInstitute_1F_Text_Grunt2Intro:: @ 819EC6B
	.string "Wie?\n"
	.string "Was macht denn das Kind hier?$"

Route119_WeatherInstitute_1F_Text_Grunt2Defeat:: @ 819EC89
	.string "Wie?\n"
	.string "Ich habe verloren?!?$"

Route119_WeatherInstitute_1F_Text_Grunt2PostBattle:: @ 819EC97
	.string "Oh. Ich werde mir etwas anhören müssen,\n"
	.string "weil ich gegen ein Kind verloren habe...\p"
	.string "Ich muss mich jetzt dringend hinlegen...$"

Route119_WeatherInstitute_1F_Text_EveryoneWentUpstairs:: @ 819ECF4
	.string "Als ich schlief, schlich sich jemand\n"
	.string "nach oben!$"

Route119_WeatherInstitute_1F_Text_WowYoureStrong:: @ 819ED22
	.string "Wow! Bist du aber stark!\p"
	.string "Ich wäre auch gerne ein POKéMON-\n"
	.string "TRAINER wie du!$"

Route119_WeatherInstitute_1F_Text_ProfStudyingRain:: @ 819ED6B
	.string "Der PROFESSOR liebt den Regen.\n"
	.string "Das ist eine Tatsache.\p"
	.string "Aber wenn es noch lange so regnet,\n"
	.string "wird das zu Problemen führen. Das ist\l"
	.string "die andere Seite der Medaille.\p"
	.string "Und daher erforscht der PROFESSOR,\n"
	.string "wie man den Regen positiv nutzen kann.$"

Route119_WeatherInstitute_1F_Text_WhatWereEvilTeamUpTo:: @ 819EE25
	.string "Hallo! Dein beherztes Eingreifen hat\n"
	.string "uns gerettet!\p"
	.string "Ich verstehe nur nicht, was die {EVIL_TEAM}S\n"
	.string "von uns wollten...$"

Route119_WeatherInstitute_1F_Text_TakeRestInBed:: @ 819EE8B
	.string "Da steht ein Bett...\n"
	.string "Eine Pause wäre willkommen.$"
