Route110_SeasideCyclingRoadSouthEntrance_Text_GoAllOutOnCyclingRoad:: @ 819E326
	.string "On CYCLING ROAD, you can go all out\n"
	.string "and cycle as fast as you'd like.\p"
	.string "It feels great to go that fast, but try\n"
	.string "not to crash into anyone!$"

Route110_SeasideCyclingRoad_Text_TooDangerousToWalk:: @ 819E3AD
	.string "Sorry, you can't walk on CYCLING\n"
	.string "ROAD. It's too dangerous.\p"
	.string "Please come back with a BIKE.$"
