MtPyre_5F_Text_TashaIntro:: @ 8196939
	.string "I love all things horrifying...\n"
	.string "It's like a disease...\p"
	.string "When I'm here...\n"
	.string "I shiver with fear...$"

MtPyre_5F_Text_TashaDefeat:: @ 8196997
	.string "Losing, I dislike...$"

MtPyre_5F_Text_TashaPostBattle:: @ 81969AC
	.string "I want to see dreadful things...\n"
	.string "I can't leave...\p"
	.string "Stay...\n"
	.string "Won't you stay with me?$"
