Route131_Text_RichardIntro:: @ 81C25B3
	.string "Das Meer wimmelt von POKéMON.\n"
	.string "Es ist nicht leicht, hier zu schwimmen.$"

Route131_Text_RichardDefeat:: @ 81C25F8
	.string "POKéMON, die von TRAINERN aufgezogen\n"
	.string "wurden, sind sehr stark...$"

Route131_Text_RichardPostBattle:: @ 81C262A
	.string "Keuch... Schnauf... Ich bin K.O.\p"
	.string "Der Hinweg ist leicht. Der Heimweg umso\n"
	.string "härter.\p"
	.string "Ob ich genug Energie für die Heimreise\n"
	.string "habe?$"

Route131_Text_HermanIntro:: @ 81C26B9
	.string "Die See... Die See... Die See...\n"
	.string "Die See... So weit ich mit den Augen seh.\l"
	.string "Das Meer macht mich krank und müde.$"

Route131_Text_HermanDefeat:: @ 81C271F
	.string "Bah!$"

Route131_Text_HermanPostBattle:: @ 81C2726
	.string "Gelangweilt bin ich von der See, aber\n"
	.string "ich muss schwimmen.\p"
	.string "Ich bin der geborene Schwimmer!\n"
	.string "Das bin ich.$"

Route131_Text_SusieIntro:: @ 81C2774
	.string "Hey, Engelchen, warte!\n"
	.string "Wir sollten kämpfen, du und ich!$"

Route131_Text_SusieDefeat:: @ 81C27A4
	.string "Du bist stärker, als du aussiehst.$"

Route131_Text_SusiePostBattle:: @ 81C27CF
	.string "Hast du einen Typen gesehen, der heult,\n"
	.string "weil das Meer ihn langweilt?\p"
	.string "Das ist nur Gerede.\n"
	.string "Er liebt das Meer aus tiefstem Herzen!$"

Route131_Text_KaraIntro:: @ 81C284A
	.string "Warum lieben Männer Bikinis nur so?\p"
	.string "Sie starren alle meinen Bikini an.$"

Route131_Text_KaraDefeat:: @ 81C2883
	.string "Ich bin erledigt.$"

Route131_Text_KaraPostBattle:: @ 81C2898
	.string "Vielleicht bewundern die Männer nicht\n"
	.string "meinen Bikini, sondern mich!$"

Route131_Text_ReliIntro:: @ 81C28E2
	.string "UNA: Wir nehmen es als Geschwister mit\n"
	.string "dir auf!$"

Route131_Text_ReliDefeat:: @ 81C2918
	.string "UNA: Wir konnten nicht gewinnen. Trotz\n"
	.string "unserer Zusammenarbeit.$"

Route131_Text_ReliPostBattle:: @ 81C2950
	.string "UNA: Die Menschen in FLOSSBRUNN\n"
	.string "leben von Geburt an mit POKéMON\l"
	.string "und dem Meer zusammen.$"

Route131_Text_ReliNotEnoughMons:: @ 81C29B2
	.string "UNA: Du hast keine zwei POKéMON?\n"
	.string "Dann werden wir keinen Spaß haben!$"

Route131_Text_IanIntro:: @ 81C29F3
	.string "TOBI: Ich gebe zusammen mit meiner\n"
	.string "Schwester mein Bestes!$"

Route131_Text_IanDefeat:: @ 81C2A20
	.string "TOBI: Meine Schwester und ich gaben\n"
	.string "unser Bestes und haben doch verloren.$"

Route131_Text_IanPostBattle:: @ 81C2A5D
	.string "TOBI: Du weißt, dass FLOSSBRUNN\n"
	.string "eine schwimmende Stadt ist?\p"
	.string "Wo immer auch das Meer ist, ist es Teil\n"
	.string "von FLOSSBRUNN!$"

Route131_Text_IanNotEnoughMons:: @ 81C2ACA
	.string "TOBI: Wenn du zwei POKéMON mitbringst,\n"
	.string "werden wir es mit dir aufnehmen!$"
