Route111_OldLadysRestStop_Text_RestUpHere:: @ 81923AF
	.string "Oh, du meine Güte.\n"
	.string "Sind deine POKéMON nicht erschöpft?\p"
	.string "Wenn du magst, ruhe dich doch hier aus.\n"
	.string "Das ist doch eine gute Idee, oder?$"

Route111_OldLadysRestStop_Text_TakeYourTimeRestUp:: @ 8192423
	.string "Genau.\n"
	.string "Nimm dir Zeit und ruhe dich aus.$"

Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest:: @ 819244D
	.string "Oh, du meine Güte.\n"
	.string "Sind deine POKéMON immer noch müde?\p"
	.string "Dann solltest du dich noch länger hier\n"
	.string "ausruhen. Was meinst du?$"

Route111_OldLadysRestStop_Text_DontNeedToBeShy:: @ 81924C6
	.string "Ach so. Na, das macht doch nichts!\n"
	.string "Besuche mich bald wieder.$"
