Hideout_1F_Text_OurBossIsSnatchingSomething:: @ 8196AFD
	.string "What? What? What do you want with \n"
	.string "TEAM {EVIL_TEAM}?\p"
	.string "Our BOSS isn't here! He's gone off to\n"
	.string "snatch something important!\p"
	.string "... ...\n"
	.string "Where did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"

Hideout_1F_Text_BossWentToJackASubmarine:: @ 8196BC5
	.string "What? What? What do you want with \n"
	.string "TEAM {EVIL_TEAM}?\p"
	.string "Our BOSS isn't here!\n"
	.string "He's gone off to jack a submarine!\p"
	.string "... ...\n"
	.string "Where did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"

Hideout_1F_Text_BossIsOnRoute122:: @ 8196C83
	.string "What? What? What do you want with \n"
	.string "TEAM {EVIL_TEAM}?\p"
	.string "Our BOSS isn't here! He's on his way to\n"
	.string "MT. PYRE on ROUTE 122!\p"
	.string "... ...\n"
	.string "Why did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"

Hideout_1F_Text_BossIsInSlateportCity:: @ 8196D46
	.string "What? What? What do you want with\n"
	.string "TEAM {EVIL_TEAM}?\p"
	.string "Our BOSS isn't here!\n"
	.string "He's on his way to SLATEPORT CITY!\p"
	.string "... ...\n"
	.string "Why did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"

Hideout_1F_Text_EvilTeamGrunt1Intro:: @ 8196E01
	.string "Ayiyiyi!\n"
	.string "Suspicious character spotted!$"

Hideout_1F_Text_EvilTeamGrunt1Defeat:: @ 8196E28
	.string "Grrrrr...\n"
	.string "I lost it!$"

Hideout_1F_Text_EvilTeamGrunt1PostBattle:: @ 8196E3D
	.string "I took the loss for the TEAM, but\n"
	.string "I did my job...$"
