SootopolisCity_Gym_1F_Text_GymGuideAdvice:: @ 818E8A5
	.string "Yo! How's it going, CHAMPION-\n"
	.string "bound {PLAYER}?\p"
	.string "SOOTOPOLIS's GYM LEADER WALLACE is\n"
	.string "a master of WATER-type POKéMON.\p"
	.string "And, to get to WALLACE, an icy floor\n"
	.string "will hamper your progress...\p"
	.string "Listen, I'm sorry, but that's all the\n"
	.string "advice that I have for you.\p"
	.string "The rest of the way, you have to\n"
	.string "go for it yourself!$"

SootopolisCity_Gym_1F_Text_GymGuidePostVictory:: @ 818E9C9
	.string "Yow! You've beaten even WALLACE, who\n"
	.string "was supposedly the best in all HOENN!\p"
	.string "Okay! Check out your TRAINER's CARD.\p"
	.string "If you've gotten all the BADGES, you're\n"
	.string "set for the POKéMON LEAGUE challenge!$"

.include "data/maps/SootopolisCity_Gym_B1F/trainer_text.inc"

SootopolisCity_Gym_1F_Text_WallaceIntro:: @ 818F0CA
	.string "Allow me to formally introduce\n"
	.string "myself.\p"
	.string "I am WALLACE.\n"
	.string "The GYM LEADER of SOOTOPOLIS.\p"
	.string "There's something about you...\n"
	.string "A difference in your demeanor.\p"
	.string "I think I sense that in you.\p"
	.string "What happened inside the CAVE OF\n"
	.string "ORIGIN, and what you did, I will likely\l"
	.string "learn through our upcoming battle.\p"
	.string "Now, show me. Show me the power you\n"
	.string "wield with your POKéMON.\p"
	.string "And I, in turn, shall present you with\n"
	.string "a performance of illusions in water\l"
	.string "by me and my POKéMON!$"

SootopolisCity_Gym_1F_Text_WallaceDefeat:: @ 818F282
	.string "Bravo.\p"
	.string "I realize now your authenticity and\n"
	.string "magnificence as a POKéMON TRAINER.\p"
	.string "I find much joy in having met you and\n"
	.string "your POKéMON.\p"
	.string "You have proven yourself worthy of\n"
	.string "the RAIN BADGE. Accept it.$"

SootopolisCity_Gym_1F_Text_ReceivedRainBadge:: @ 818F342
	.string "{PLAYER} received the RAIN BADGE\n"
	.string "from WALLACE.$"

SootopolisCity_Gym_1F_Text_ExplainRainBadgeTakeThis:: @ 818F36B
	.string "Having that BADGE assures you the\n"
	.string "full obedience of all your POKéMON to\l"
	.string "every command you make.\p"
	.string "The BADGE also allows the use of the\n"
	.string "HM move WATERFALL to scale walls\l"
	.string "of cascading water.\p"
	.string "And, so that you never forget the\n"
	.string "battle we shared, take this...$"

SootopolisCity_Gym_1F_Text_ExplainWaterPulse:: @ 818F466
	.string "The TM I handed you contains\n"
	.string "WATER PULSE.\p"
	.string "In use, it will occasionally confuse\n"
	.string "the target with ultrasonic waves.$"

SootopolisCity_Gym_1F_Text_WallacePostBattle:: @ 818F4D7
	.string "TRAINERS who have gathered all the\n"
	.string "GYM BADGES of HOENN should make way\l"
	.string "for the ultimate destination.\p"
	.string "The POKéMON LEAGUE.\p"
	.string "Travel to the easternmost reaches\n"
	.string "of HOENN, to the island EVER GRANDE.\l"
	.string "The POKéMON LEAGUE is there.$"

SootopolisCity_Gym_1F_Text_GoGetFortreeBadge:: @ 818F5B4
	.string "There remains but one BADGE to\n"
	.string "obtain in HOENN.\p"
	.string "If you wish to challenge the POKéMON\n"
	.string "LEAGUE, you must obtain the last\l"
	.string "BADGE from the GYM in FORTREE.$"

SootopolisCity_Gym_1F_Text_GymStatue:: @ 818F649
	.string "SOOTOPOLIS CITY POKéMON GYM$"

SootopolisCity_Gym_1F_Text_GymStatueCertified:: @ 818F665
	.string "SOOTOPOLIS CITY POKéMON GYM\p"
	.string "WALLACE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
