Route119_WeatherInstitute_2F_Text_Grunt3Intro:: @ 819EEAF
	.string "The INSTITUTE created a type of\n"
	.string "POKéMON that has something to do with\l"
	.string "the weather. We're here to take them!$"

Route119_WeatherInstitute_2F_Text_Grunt3Defeat:: @ 819EF1B
	.string "Our plan's being spoiled by a kid?$"

Route119_WeatherInstitute_2F_Text_Grunt3PostBattle:: @ 819EF3E
	.string "If the POKéMON they made here can\n"
	.string "control the weather freely, then we of\l"
	.string "TEAM {EVIL_TEAM} definitely need it!$"

Route119_WeatherInstitute_2F_Text_Grunt4Intro:: @ 819EFA3
	.string "We're TEAM {EVIL_TEAM}!\n"
	.string "We appear wherever anything rare is\l"
	.string "found!$"

Route119_WeatherInstitute_2F_Text_Grunt4Defeat:: @ 819EFDD
	.string "You got me!$"

Route119_WeatherInstitute_2F_Text_Grunt4PostBattle:: @ 819EFE9
	.string "You don't have any idea what we of\n"
	.string "TEAM {EVIL_TEAM} are working towards!\l"
	.string "You stay out of our way!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminIntro:: @ 819F042
	.string "Ahahahaha!\p"
	.string "You're going to meddle in TEAM {EVIL_TEAM}'s\n"
	.string "affairs?\p"
	.string "You're either absolutely fearless,\n"
	.string "simply ignorant, or both!\p"
	.string "You're so cute, you're disgusting!\n"
	.string "I'll put you down, kiddy!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminDefeat:: @ 819F0F4
	.string "Ahahahaha!\n"
	.string "You're disgustingly strong!$"

Route119_WeatherInstitute_2F_Text_EvilTeamAdminPostBattle:: @ 819F11B
	.string "Ahahahaha!\n"
	.string "We got meddled with unexpectedly!\p"
	.string "We're out of options.\n"
	.string "We'll have to pull out.\p"
	.string "But this isn't the last you'll see of\n"
	.string "TEAM {EVIL_TEAM}! We have other plans!\l"
	.string "Don't you forget it!$"

Route119_WeatherInstitute_2F_Text_ThanksForSavingUs:: @ 819F1CF
	.string "Thanks!\n"
	.string "Thanks to you, we're safe!\p"
	.string "It might be an odd way of thanking you,\n"
	.string "but take this POKéMON.$"

Route119_WeatherInstitute_2F_Text_NoRoomForCastform:: @ 819F231
	.string "Hm? You don't seem to have any room\n"
	.string "for this POKéMON.$"

Route119_WeatherInstitute_2F_Text_ReceivedCastform:: @ 819F267
	.string "{PLAYER} received CASTFORM!$"

Route119_WeatherInstitute_2F_Text_CastformChangesWithWeather:: @ 819F27D
	.string "That POKéMON changes shape according\n"
	.string "to the weather conditions.\p"
	.string "There're plenty of them in the\n"
	.string "INSTITUTE - go ahead and take it.$"

Route119_WeatherInstitute_2F_Text_StudyingRain:: @ 819F2FE
	.string "I've been researching rain for many\n"
	.string "years, but it's ridiculous to think that\l"
	.string "humans can freely change the weather.$"
