MtPyre_3F_Text_WilliamIntro:: @ 819672B
	.string "Die unglaubliche Atmosphäre der Berge\n"
	.string "hat meine psychischen Kräfte gestärkt!\p"
	.string "Ein kleines Kind wie du...\n"
	.string "Du willst gewinnen? Träum weiter!$"

MtPyre_3F_Text_WilliamDefeat:: @ 819679D
	.string "Ich vertiefe mich in Selbstmitleid.$"

MtPyre_3F_Text_WilliamPostBattle:: @ 81967B5
	.string "Meine psychischen Kräfte sind mit\n"
	.string "Sicherheit stärker geworden, aber...$"

MtPyre_3F_Text_KaylaIntro:: @ 81967EF
	.string "Ahahahahaha!!!!!\p"
	.string "Dies ist kein Platz für einen kleinen\n"
	.string "Hosenscheißer wie dich!$"

MtPyre_3F_Text_KaylaDefeat:: @ 819682B
	.string "Oh, ich habe mir in die Hose gemacht.$"

MtPyre_3F_Text_KaylaPostBattle:: @ 8196842
	.string "Mein Training reicht also nicht aus...\p"
	.string "Ich muss mein Training auf die Spitze\n"
	.string "treiben...\p"
	.string "Ich darf keine Zeit verlieren!$"
