Route124_Text_SpencerIntro:: @ 81C0624
	.string "Hey, hast du etwa auf dem Meer die\n"
	.string "Orientierung verloren?\p"
	.string "Wenn du meine POKéMON besiegst, zeige\n"
	.string "ich dir den richtigen Weg.$"

Route124_Text_SpencerDefeat:: @ 81C0675
	.string "Ich habe die Orientierung verloren...$"

Route124_Text_SpencerPostBattle:: @ 81C0693
	.string "Viele Menschen verlieren auf dem Meer\n"
	.string "die Orientierung.\p"
	.string "Wenn du zu denen gehörst, solltest du\n"
	.string "die KARTE des POKéNAV zu Hilfe nehmen.$"

Route124_Text_RolandIntro:: @ 81C06F7
	.string "Hm! Du sitzt auf einem POKéMON anstatt\n"
	.string "selbst zu schwimmen...\p"
	.string "Ich bin richtig neidisch!$"

Route124_Text_RolandDefeat:: @ 81C0741
	.string "Oh!\n"
	.string "Ich kann doch nicht...$"

Route124_Text_RolandPostBattle:: @ 81C0750
	.string "Langsam bekomme ich eine Gänsehaut.\n"
	.string "Ich bin schon zu lange im Wasser.\p"
	.string "Ich wollte, ich könnte auf einem\n"
	.string "POKéMON reiten. So wie du!$"

Route124_Text_JennyIntro:: @ 81C07B4
	.string "Wenn du dich einfach nur im Meer treiben\n"
	.string "lässt, kommen POKéMON, um zu spielen.$"

Route124_Text_JennyDefeat:: @ 81C07F9
	.string "Oh.\n"
	.string "Verschollen auf hoher See...$"

Route124_Text_JennyPostBattle:: @ 81C080E
	.string "Ich habe beim Schwimmen festgestellt,\n"
	.string "dass einige POKéMON angreifen und\l"
	.string "manche einen nur beobachten.\p"
	.string "Ich glaube, POKéMON haben unter-\n"
	.string "schiedliche Persönlichkeiten.$"

Route124_Text_JennyRematchIntro:: @ 81C0888
	.string "Wenn du dich hier treiben lässt, triffst\n"
	.string "du auf TRAINER, die kämpfen wollen.$"

Route124_Text_JennyRematchDefeat:: @ 81C08C8
	.string "Das ist sehr merkwürdig...\n"
	.string "Ich habe schon wieder verloren...$"

Route124_Text_JennyPostRematch:: @ 81C08EA
	.string "Das hat zwar nichts damit zu tun, aber\n"
	.string "ich glaube, ich besuche das RÄTSELHAUS.$"

Route124_Text_GraceIntro:: @ 81C0936
	.string "Ich fange an, mich beim Schwimmen zu\n"
	.string "langweilen. Wie wär's mit einem Kampf?$"

Route124_Text_GraceDefeat:: @ 81C096B
	.string "Ich hatte ja keine Ahnung, dass du so\n"
	.string "stark bist!$"

Route124_Text_GracePostBattle:: @ 81C0994
	.string "Alles was du bisher erreicht hast, hat\n"
	.string "dich so stark werden lassen.$"

Route124_Text_ChadIntro:: @ 81C09CE
	.string "Hähähä... Ich tauche tief hinab, um mich\n"
	.string "tief und sicher zu verstecken.\l"
	.string "Die Tiefen auszuloten ist meine Mission.$"

Route124_Text_ChadDefeat:: @ 81C0A2F
	.string "Blubb, blubb, blubb...\n"
	.string "So saufe ich ab...$"

Route124_Text_ChadPostBattle:: @ 81C0A52
	.string "Aus zuverlässiger Quelle weiß ich, dass\n"
	.string "es hier in der Nähe einen Platz zum\l"
	.string "TAUCHEN gibt.\p"
	.string "Das gibt mir das Verlangen, mich tief\n"
	.string "fallen zu lassen...$"

Route124_Text_RitaIntro:: @ 81C0ABD
	.string "UTA: Seufz...\p"
	.string "Ich bin hier im Meer, aber wer ist bei\n"
	.string "mir? Mein kleiner Bruder!\p"
	.string "Lass uns kämpfen, dann brauche ich\n"
	.string "nicht darüber nachzudenken.$"

Route124_Text_RitaDefeat:: @ 81C0B36
	.string "UTA: TOM! Es ist deine Schuld, dass wir\n"
	.string "verloren haben! Das wirst du mir büßen!$"

Route124_Text_RitaPostBattle:: @ 81C0B72
	.string "UTA: Seufz...\p"
	.string "Wenn anstelle meines kleinen\n"
	.string "Bruders ein hübscher Freund hier wäre...$"

Route124_Text_RitaNotEnoughMons:: @ 81C0BC8
	.string "UTA: Du willst gegen uns antreten?\n"
	.string "Dann brauchst du aber mehr POKéMON.$"

Route124_Text_SamIntro:: @ 81C0C0E
	.string "TOM: Meine Schwester ist stark!\p"
	.string "Heul bloß nicht, wenn du verlierst!$"

Route124_Text_SamDefeat:: @ 81C0C4F
	.string "TOM: Oh oh...\n"
	.string "Meine Schwester wird mich fressen...$"

Route124_Text_SamPostBattle:: @ 81C0C7F
	.string "TOM: Meine Schwester wird richtig\n"
	.string "unheimlich, wenn sie wütend ist.\p"
	.string "Daher hat sie auch noch keinen Freund.$"

Route124_Text_SamNotEnoughMons:: @ 81C0CE0
	.string "TOM: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_RitaRematchIntro:: @ 81C0D1F
	.string "UTA: Megaseufz... Ich bin hier mitten\n"
	.string "im Meer.\p"
	.string "Und mit wem? Meinem kleinen Bruder!\n"
	.string "Oh, dich habe ich lange nicht gesehen.\p"
	.string "Lass uns kämpfen, dann muss ich nicht\n"
	.string "länger über die Situation nachdenken.$"

Route124_Text_RitaRematchDefeat:: @ 81C0DB5
	.string "UTA: TOM!!! Du hast schon wieder für\n"
	.string "eine Niederlage gesorgt!\p"
	.string "Ich werde dir gleich eine Lektion\n"
	.string "erteilen!$"

Route124_Text_RitaPostRematch:: @ 81C0E06
	.string "UTA: Seeeuuufz...\p"
	.string "Wenn ich einen netten Freund hätte,\n"
	.string "würden wir alle in Kombination schlagen.$"

Route124_Text_RitaRematchNotEnoughMons:: @ 81C0E5C
	.string "UTA: Du willst gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"

Route124_Text_SamRematchIntro:: @ 81C0EA2
	.string "TOM: Wenn wir verlieren, stecke ich tief\n"
	.string "in der Klemme. Dann flippe ich aus!$"

Route124_Text_SamRematchDefeat:: @ 81C0EE5
	.string "TOM: Oh oh...\n"
	.string "Meine Schwester wird mich umbringen...$"

Route124_Text_SamPostRematch:: @ 81C0F19
	.string "TOM: Meine Schwester ist bizarr und\n"
	.string "Furcht erregend, wenn sie wütend ist.\p"
	.string "Sie wird mich später hart mit den\n"
	.string "POKéMON trainieren lassen...$"

Route124_Text_SamRematchNotEnoughMons:: @ 81C0F90
	.string "TOM: Willst du gegen uns antreten?\n"
	.string "Dann bring mehr POKéMON mit.$"
