Route103_Text_DaisyIntro:: @ 81B7D55
	.string "Did you feel the tug of our soul-\n"
	.string "soothing fragrance?$"

Route103_Text_DaisyDefeated:: @ 81B7D8B
	.string "You weren't led astray by our aroma...$"

Route103_Text_DaisyPostBattle:: @ 81B7DB2
	.string "Aromatherapy is a form of mental\n"
	.string "healing that works with fragrances.$"

Route103_Text_AmyIntro:: @ 81B7DF7
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyDefeated:: @ 81B7E3B
	.string "AMY: Uh-oh, we lost.$"

Route103_Text_AmyPostBattle:: @ 81B7E50
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyNotEnoughPokemon:: @ 81B7EAC
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivIntro:: @ 81B7EFB
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivDefeated:: @ 81B7F20
	.string "LIV: Oh, we lost, big sister...$"

Route103_Text_LivPostBattle:: @ 81B7F40
	.string "LIV: We work perfectly together, me\n"
	.string "and my big sister...\p"
	.string "But we still lost...$"

Route103_Text_LivNotEnoughPokemon:: @ 81B7F8E
	.string "LIV: If you want to battle us, you\n"
	.string "have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AmyRematchIntro:: @ 81B7FE7
	.string "AMY: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyRematchDefeated:: @ 81B802B
	.string "AMY: Aww, boo!\n"
	.string "We couldn't win again...$"

Route103_Text_AmyRematchPostBattle:: @ 81B8053
	.string "AMY: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two TRAINERS.$"

Route103_Text_AmyRematchNotEnoughPokemon:: @ 81B80AF
	.string "AMY: Uh-oh, you have only one\n"
	.string "POKéMON with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivRematchIntro:: @ 81B80FE
	.string "LIV: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated:: @ 81B8123
	.string "LIV: Awww, we lost again...\n"
	.string "Big sister...$"

Route103_Text_LivRematchPostBattle:: @ 81B814D
	.string "LIV: We work perfectly together, me\n"
	.string "and my big sister...\p"
	.string "But why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon:: @ 81B81A1
	.string "LIV: If you want to battle us, you\n"
	.string "have to have two POKéMON!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AndrewIntro:: @ 81B81FA
	.string "Gah! My fishing line's all snarled up!\n"
	.string "I'm getting frustrated and mean!\l"
	.string "That's it! Battle me!$"

Route103_Text_AndrewDefeated:: @ 81B8258
	.string "Gah! Lost it!\n"
	.string "I'm even more annoyed now!$"

Route103_Text_AndrewPostBattle:: @ 81B8281
	.string "Gah, I'm still boiling mad...\n"
	.string "Grrrrr...$"

Route103_Text_MiguelIntro:: @ 81B82A9
	.string "My POKéMON is delightfully adorable!\n"
	.string "Don't be shy - I'll show you!$"

Route103_Text_MiguelDefeated:: @ 81B82EC
	.string "Oh, my gosh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelPostBattle:: @ 81B830D
	.string "My delightful POKéMON looks darling\n"
	.string "even when it's fainted!$"

Route103_Text_MiguelRematchIntro:: @ 81B8349
	.string "Hi, you! My delightfully adorable\n"
	.string "POKéMON has become more darling!$"

Route103_Text_MiguelRematchDefeated:: @ 81B838C
	.string "Oh!\n"
	.string "My darling POKéMON!$"

Route103_Text_MiguelRematchPostBattle:: @ 81B83A4
	.string "The more I spend time with it, the\n"
	.string "more adorable my POKéMON becomes.$"
