Route102_Text_WatchMeCatchPokemon:: @ 816D361
	.string "HEIKO: {PLAYER}...\n"
	.string "POKéMON verstecken sich in hohem Gras\l"
	.string "wie diesem hier, oder?\p"
	.string "Bitte bleib hier und schau, ob ich sie\n"
	.string "auch richtig fange.\p"
	.string "...Whoa!$"

Route102_Text_WallyIDidIt:: @ 816D3DE
	.string "HEIKO: Ich habe es geschafft... Es\n"
	.string "gehört mir... Mein POKéMON!!!$"

Route102_Text_LetsGoBack:: @ 816D408
	.string "{PLAYER}, danke schön!\n"
	.string "Lass uns zurück zur ARENA gehen!$"

Route102_Text_ImNotVeryTall:: @ 816D431
	.string "Ich... bin nicht groß, ich versinke im\n"
	.string "hohen Gras.\p"
	.string "Das Gras erreicht meine Nase und...\n"
	.string "Hahahaha...\p"
	.string "Haaatschiiii!$"

Route102_Text_UnusedWatchMe:: @ 816D4A5
	.string "Hähähä...\n"
	.string "Beobachte mich gut.$"

Route102_Text_UnusedLedgeExplanation:: @ 816D4BB
	.string "Ta-daaaaah! Unglaublich, oder?\p"
	.string "Es gibt einige Absätze, die man nicht\n"
	.string "hochklettern, aber von denen man\l"
	.string "herunterspringen kann.$"

Route102_Text_CatchWholeBunchOfPokemon:: @ 816D51A
	.string "Ich werde jede Menge POKéMON fangen!$"

Route102_Text_RouteSignOldale:: @ 816D547
	.string "ROUTE 102\n"
	.string "{RIGHT_ARROW} ROSALTSTADT$"

Route102_Text_RouteSignPetalburg:: @ 816D55F
	.string "ROUTE 102\n"
	.string "{LEFT_ARROW} BLÜTENBURG CITY$"
