Route110_SeasideCyclingRoadNorthEntrance_Text_GoAllOutOnCyclingRoad:: @ 819E406
	.string "Auf dem RADWEG kannst du so\n"
	.string "schnell fahren, wie du willst.\p"
	.string "Schnell fahren macht Spaß, pass aber\n"
	.string "auf, dass du mit niemandem\l"
	.string "zusammenstößt.$"

Route110_SeasideCyclingRoadNorthEntrance_Text_TooDangerousToWalkUnused: @ 819E48D
	.string "Tut mir Leid, aber auf dem RADWEG\n"
	.string "sind Fußgänger nicht gestattet.\p"
	.string "Das ist gefährlich. Bring dein RAD mit...$"
