EventScript_PictureBookShelf:: @ 81A085B
    msgbox Text_PictureBookShelf, MSGBOX_SIGN
    end

EventScript_BookShelf:: @ 81A0864
    msgbox Text_BookShelf, MSGBOX_SIGN
    end

EventScript_PokemonCenterBookShelf:: @ 81A086D
    msgbox Text_PokemonCenterBookShelf, MSGBOX_SIGN
    end

EventScript_Vase:: @ 81A0876
    msgbox Text_Vase, MSGBOX_SIGN
    end

EventScript_EmptyTrashCan:: @ 81A087F
    msgbox Text_EmptyTrashCan, MSGBOX_SIGN
    end

EventScript_ShopShelf:: @ 81A0888
    msgbox Text_ShopShelf, MSGBOX_SIGN
    end

EventScript_Blueprint:: @ 81A0891
    msgbox Text_Blueprint, MSGBOX_SIGN
    end
