Route132_Text_GilbertIntro:: @ 81C2AFB
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat:: @ 81C2B5B
	.string "I crave more power...$"

Route132_Text_GilbertPostBattle:: @ 81C2B71
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro:: @ 81C2BB5
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat:: @ 81C2BEA
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle:: @ 81C2BFA
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place...$"

Route132_Text_RonaldIntro:: @ 81C2C32
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat:: @ 81C2C60
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle:: @ 81C2C78
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:: @ 81C2CD9
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:: @ 81C2D1F
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle:: @ 81C2D3E
	.string "Urggh...\n"
	.string "You're a POKéMON fanatic, aren't you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"
