SSTidalLowerDeck_Text_PhillipIntro:: @ 81993C1
	.string "Arrgh! Ich habe die Schnauze voll und\n"
	.string "bin hundemüde vom Putzen.\p"
	.string "Ein Kampf ist jetzt genau das Richtige!$"

SSTidalLowerDeck_Text_PhillipDefeat:: @ 819941A
	.string "Brüderchen, ich habe verloren!$"

SSTidalLowerDeck_Text_PhillipPostBattle:: @ 819942E
	.string "Wir sind die GEBRÜDER SAUBERMANN!\p"
	.string "Der Ältere verteilt die Schmierseife und\n"
	.string "der Jüngere schrubbt das Deck!$"

SSTidalLowerDeck_Text_LeonardIntro:: @ 8199491
	.string "Dies ist der untere Bereich des Schiffs.\n"
	.string "Hier gibt es sehr viel Platz.\l"
	.string "Genau richtig für einen POKéMON-Kampf.$"

SSTidalLowerDeck_Text_LeonardDefeat:: @ 81994F7
	.string "Oh, großer Bruder. Ich habe verloren.$"

SSTidalLowerDeck_Text_LeonardPostBattle:: @ 8199508
	.string "Wir sind die GEBRÜDER SAUBERMANN!\p"
	.string "Der Ältere verteilt die Schmierseife und\n"
	.string "der Jüngere schrubbt das Deck!$"
