SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage:: @ 8199007
	.string "Diese Fähre ist so konstruiert, dass sie\n"
	.string "auch durch starke Strömungen\l"
	.string "fahren kann.\p"
	.string "Wir hoffen, du genießt die Reise mit\n"
	.string "uns. Schau dich ruhig auf dem Schiff um.$"

SSTidal_Text_HopeYouEnjoyVoyage:: @ 8199088
	.string "Wir hoffen, du genießt die Reise mit\n"
	.string "uns. Schau dich ruhig auf dem Schiff um.$"

SSTidal_Text_MadeLandInSlateport:: @ 81990B4
	.string "Wir gehen in GRAPHITPORT CITY vor\n"
	.string "Anker. Danke, dass du mit uns gefahren\l"
	.string "bist.$"

SSTidal_Text_MadeLandInLilycove:: @ 81990F8
	.string "Wir gehen in SEEGRASULB CITY vor Anker.\n"
	.string "Danke, dass du mit uns gefahren bist.$"

SSTidalCorridor_Text_CanRestInCabin2:: @ 819913B
	.string "Ich schätze, es wird einige Zeit dauern,\n"
	.string "bis wir an Land gehen.\p"
	.string "Du kannst dich in deiner Kabine aus-\n"
	.string "ruhen. Du hast Kabine 2.\p"
	.string "Das Bett ist weich und gemütlich. Das\n"
	.string "habe ich bereits überprüft!$"

SSTidalCorridor_Text_WeveArrived:: @ 81991F4
	.string "Wir sind angekommen!$"

SSTidalCorridor_Text_VisitOtherCabins:: @ 8199203
	.string "Schau dir ruhig die anderen Kabinen an.\n"
	.string "TRAINER langweilen sich auf der Über-\l"
	.string "fahrt und werden sicher gerne kämpfen.$"

SSTidalCorridor_Text_EnjoyYourCruise:: @ 8199255
	.string "Genieße die Überfahrt.$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole:: @ 8199268
	.string "Durch das Bullauge sieht man\n"
	.string "den Horizont.$"

SSTidalCorridor_Text_BrineyWelcomeAboard:: @ 8199291
	.string "MR. BRACK: Willkommen an Bord, {PLAYER}{KUN}!\p"
	.string "Ich bin jetzt der Kapitän der\n"
	.string "MS TIDE!\p"
	.string "Du kannst mich ab sofort\n"
	.string "KAPITÄN BRACK nennen.\p"
	.string "Ich war zwar schon in Rente gegangen,\n"
	.string "aber als ich dieses majestätische\l"
	.string "Schiff gesehen habe...\p"
	.string "Lass es mich so sagen: Es weckte die\n"
	.string "schlafende Seele des Seemannes in mir.$"

SSTidalCorridor_Text_Peeko:: @ 8199388
	.string "PECKO: Pihyo pihyohyo...$"

SSTidalCorridor_Text_Cabin1:: @ 81993A1
	.string "Kabine 1$"

SSTidalCorridor_Text_Cabin2:: @ 81993A9
	.string "Kabine 2$"

SSTidalCorridor_Text_Cabin3:: @ 81993B1
	.string "Kabine 3$"

SSTidalCorridor_Text_Cabin4:: @ 81993B9
	.string "Kabine 4$"
