Route110_Text_JacobIntro:: @ 81BA22C
	.string "Wow! Pass auf! Ich glaube, du hast\n"
	.string "keine Übung im RAD-Rennen.$"

Route110_Text_JacobDefeated:: @ 81BA264
	.string "Wow! Pass auf!\n"
	.string "Meine Bremsen versagen!$"

Route110_Text_JacobPostBattle:: @ 81BA27C
	.string "Platte Reifen und schwache Bremsen\n"
	.string "können zu Unfällen mit schweren Ver-\l"
	.string "letzungen führen! Also: Prüfe dein RAD!$"

Route110_Text_AnthonyIntro:: @ 81BA2D4
	.string "Hey, du!\n"
	.string "Kannst du mit mir mithalten?$"

Route110_Text_AnthonyDefeated:: @ 81BA2FC
	.string "Du hast die Schallmauer durchbrochen!$"

Route110_Text_AnthonyPostBattle:: @ 81BA30C
	.string "Geschwindigkeit alleine lässt mich nicht\n"
	.string "gewinnen. Das darf ich nicht vergessen.$"

Route110_Text_BenjaminIntro:: @ 81BA352
	.string "Nur keine Panik, wenn dein RAD immer\n"
	.string "schneller wird!$"

Route110_Text_BenjaminDefeated:: @ 81BA379
	.string "Ich muss während eines POKéMON-\n"
	.string "Kampfes ruhig bleiben...$"

Route110_Text_BenjaminPostBattle:: @ 81BA3A5
	.string "Kein Grund zur Panik. Nimm's leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_BenjaminRematchIntro:: @ 81BA3EF
	.string "Bist du nicht ein wenig zu schnell? \n"
	.string "Brems ab und lass uns kämpfen.$"

Route110_Text_BenjaminRematchDefeated:: @ 81BA432
	.string "Ich war ganz ruhig und habe doch\n"
	.string "verloren...$"

Route110_Text_BenjaminRematchPostBattle:: @ 81BA456
	.string "Kein Grund zur Panik. Nimm's leicht.\n"
	.string "Wir haben doch jede Menge Zeit.$"

Route110_Text_AbigailIntro:: @ 81BA4A0
	.string "Ein Triathlon ist extrem hart.\p"
	.string "Du musst schwimmen, Rad fahren und\n"
	.string "laufen.$"

Route110_Text_AbigailDefeated:: @ 81BA50F
	.string "POKéMON-Kämpfe sind auch hart.$"

Route110_Text_AbigailPostBattle:: @ 81BA52E
	.string "Ich bin erschöpft und brauche eine\n"
	.string "Pause. Pausen sind extrem wichtig.$"

Route110_Text_AbigailRematchIntro:: @ 81BA573
	.string "Gibt es etwas Eleganteres, als einen\n"
	.string "Kampf während man Rad fährt?$"

Route110_Text_AbigailRematchDefeated:: @ 81BA5A1
	.string "Wow...\n"
	.string "Wie kann man nur so stark sein?$"

Route110_Text_AbigailRematchPostBattle:: @ 81BA5C4
	.string "Bist du auf der Jagd nach Rekorden?\p"
	.string "Tut mir Leid, wenn ich dich dabei auf-\n"
	.string "gehalten habe.$"

Route110_Text_JasmineIntro:: @ 81BA5FF
	.string "Ich radle ohne aufzuhören! Meine Ober-\n"
	.string "schenkel sind hart wie Stein!$"

Route110_Text_JasmineDefeated:: @ 81BA63C
	.string "Muskelkrämpfe beunruhigen mich!$"

Route110_Text_JasminePostBattle:: @ 81BA65F
	.string "Oh, du besitzt einige ORDEN der ARENEN.\n"
	.string "Kein Wunder, dass du so stark bist!$"

Route110_Text_EdwardIntro:: @ 81BA699
	.string "Ich habe deine Absichten vorherge-\n"
	.string "sehen. Daher werde ich nicht verlieren!$"

Route110_Text_EdwardDefeated:: @ 81BA6D2
	.string "Ich konnte noch nicht einmal meine\n"
	.string "eigene Niederlage vorhersehen.$"

Route110_Text_EdwardPostBattle:: @ 81BA6F8
	.string "Ich sehe deine Zukunft...\p"
	.string "Hmm...\n"
	.string "Ich sehe ein helles Licht...$"

Route110_Text_JaclynIntro:: @ 81BA72D
	.string "Ahahahahaha! Ich werde dich mit meinen\n"
	.string "Wundern verwirren!$"

Route110_Text_JaclynDefeated:: @ 81BA759
	.string "Ich habe ganz wunderlich verloren!$"

Route110_Text_JaclynPostBattle:: @ 81BA76C
	.string "Du konntest nur gewinnen, weil eben das\n"
	.string "das Wunder war! Ja, ein Wunder! Glaub ja\l"
	.string "nicht, dass du immer gewinnen kannst!$"

Route110_Text_EdwinIntro:: @ 81BA7D2
	.string "Zeigst du mir deine POKéMON?\n"
	.string "Nur ganz kurz, ja?$"

Route110_Text_EdwinDefeated:: @ 81BA803
	.string "Ich möchte meine Sammlung\n"
	.string "vervollständigen...$"

Route110_Text_EdwinPostBattle:: @ 81BA829
	.string "Wenn ich ein mir unbekanntes POKéMON\n"
	.string "sehe, kommt der Sammler in mir durch!$"

Route110_Text_EdwinRematchIntro:: @ 81BA877
	.string "Hi, hast du neue POKéMON gesammelt?\p"
	.string "Ich möchte einen Blick auf deine\n"
	.string "POKéMON werfen. Ganz kurz, bitte?$"

Route110_Text_EdwinRematchDefeated:: @ 81BA8CD
	.string "Deine POKéMON...\n"
	.string "Ich bin richtig neidisch!$"

Route110_Text_EdwinRematchPostBattle:: @ 81BA8E9
	.string "Oh, ich möchte so gerne alle seltenen\n"
	.string "POKéMON besitzen.$"

Route110_Text_DaleIntro:: @ 81BA913
	.string "Hey!\n"
	.string "Schleich dich nicht so von hinten heran!$"

Route110_Text_DaleDefeated:: @ 81BA93C
	.string "Ich habe verloren!\n"
	.string "Verflixt!$"

Route110_Text_DalePostBattle:: @ 81BA94A
	.string "Angeln bedeutet höchste Konzentra-\n"
	.string "tion. Immer auf den Blinker achten!$"

Route110_Text_IsabelIntro:: @ 81BA990
	.string "Ich würde überall hingehen, um meine\n"
	.string "elysischen POKéMON zu präsentieren.$"

Route110_Text_IsabelDefeated:: @ 81BA9D0
	.string "Oh, Schönheit reicht nicht aus...$"

Route110_Text_IsabelPostBattle:: @ 81BA9E9
	.string "Ich sollte mich mehr auf WETTBEWERBE\n"
	.string "statt auf Kämpfe konzentrieren.$"

Route110_Text_IsabelRematchIntro:: @ 81BAA2D
	.string "Ich zeige dir meine elysischen\n"
	.string "POKéMON, sooft du willst!$"

Route110_Text_IsabelRematchDefeated:: @ 81BAA76
	.string "Oh, das war wieder nichts...$"

Route110_Text_IsabelRematchPostBattle:: @ 81BAA8F
	.string "WETTBEWERBE sind wunderbar, aber ich\n"
	.string "mag auch Kämpfe.$"

Route110_Text_TimmyIntro:: @ 81BAAC3
	.string "Ich habe hier im hohen Gras einige coole\n"
	.string "POKéMON gefunden!$"

Route110_Text_TimmyDefeated:: @ 81BAAF7
	.string "Nur cool zu sein verhilft einem nicht\n"
	.string "zum Sieg...$"

Route110_Text_TimmyPostBattle:: @ 81BAB19
	.string "Mit POKéMON zu kämpfen, die man gerade\n"
	.string "erst gefangen hat, ist verdammt schwer.$"
