NewMauville_Inside_Text_GeneratorRadiatingHeat:: @ 8198315
	.string "Der Generator strahlt eine Hitze ab, die\n"
	.string "sogar aus der Entfernung zu spüren ist.\p"
	.string "Man sollte ihn so schnell wie möglich\n"
	.string "abschalten.$"

NewMauville_Inside_Text_GeneratorQuietedDown:: @ 8198395
	.string "Der Generator ist ausgeschaltet.$"

NewMauville_Inside_Text_SteppedOnSwitchGeneratorStopped:: @ 81983B1
	.string "{PLAYER} stellt sich auf den Schalter.\p"
	.string "Klick.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Der Generator ist ausgeschaltet...$"
