Hideout_1F_Text_OurBossIsSnatchingSomething:: @ 8196AFD
	.string "Was? Wie? Was hast du mit TEAM {EVIL_TEAM} zu\n"
	.string "schaffen?\p"
	.string "Unser BOSS ist nicht hier! Er ist dabei,\n"
	.string "sich etwas sehr Wichtiges unter den\l"
	.string "Nagel zu reißen.\p"
	.string "... ...\n"
	.string "Wo er hin ist?\p"
	.string "Uahahaha! Du glaubst doch nicht im\n"
	.string "Ernst, dass ich dir das verrate!?!$"

Hideout_1F_Text_BossWentToJackASubmarine:: @ 8196BC5
	.string "Was? Wie? Was hast du mit TEAM {EVIL_TEAM} zu\n"
	.string "schaffen?\p"
	.string "Unser BOSS ist nicht hier! Er ist dabei,\n"
	.string "sich ein U-Boot unter den Nagel zu\l"
	.string "reißen.\p"
	.string "... ...\n"
	.string "Wo er hin ist?\p"
	.string "Uahahaha! Du glaubst doch nicht im\n"
	.string "Ernst, dass ich dir das verrate!?!$"

Hideout_1F_Text_BossIsOnRoute122:: @ 8196C83
	.string "Was? Wie? Was hast du mit TEAM {EVIL_TEAM} zu\n"
	.string "schaffen?\p"
	.string "Unser BOSS ist nicht hier! Er ist auf dem\n"
	.string "Weg nach PYROBERG auf der ROUTE 122!\p"
	.string "... ...\n"
	.string "Warum er dorthin ist?\p"
	.string "Uahahaha! Du glaubst doch nicht im\n"
	.string "Ernst, dass ich dir das verrate!?!$"

Hideout_1F_Text_BossIsInSlateportCity:: @ 8196D46
	.string "Was? Wie? Was hast du mit TEAM {EVIL_TEAM} zu\n"
	.string "schaffen?\p"
	.string "Unser BOSS ist nicht hier! Er ist auf dem\n"
	.string "Weg nach GRAPHITPORT CITY!\p"
	.string "... ...\n"
	.string "Warum er dorthin ist?\p"
	.string "Uahahaha! Du glaubst doch nicht im\n"
	.string "Ernst, dass ich dir das verrate!?!$"

Hideout_1F_Text_EvilTeamGrunt1Intro:: @ 8196E01
	.string "Huhuuhuhuu!\n"
	.string "Verdächtige Person gesichtet!$"

Hideout_1F_Text_EvilTeamGrunt1Defeat:: @ 8196E28
	.string "Grrr...\n"
	.string "Ich habe verloren!$"

Hideout_1F_Text_EvilTeamGrunt1PostBattle:: @ 8196E3D
	.string "Nun hat das TEAM verloren, aber ich habe\n"
	.string "meinen Job gemacht...$"
