Route106_Text_ElliotIntro:: @ 81B8EF0
	.string "Which do you prefer, fishing in the\n"
	.string "sea or a stream?$"

Route106_Text_ElliotDefeated:: @ 81B8F25
	.string "Like in deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:: @ 81B8F55
	.string "Fishing is the greatest whether it's\n"
	.string "in the sea or a stream.\l"
	.string "You agree with me, right?$"

Route106_Text_ElliotRematchIntro:: @ 81B8FAC
	.string "I caught a bunch of POKéMON fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated:: @ 81B8FF5
	.string "I lost again spectacularly!$"

Route106_Text_ElliotRematchPostBattle:: @ 81B9011
	.string "Win or lose, POKéMON are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro:: @ 81B9052
	.string "What do people do if they need to go\n"
	.string "to a washroom?\p"
	.string "What if my ROD hooks a big one while\n"
	.string "I'm in the washroom? I just can't go...$"

Route106_Text_NedDefeated:: @ 81B90D3
	.string "I lost because I'm trying to not go\n"
	.string "to the washroom...$"

Route106_Text_NedPostBattle:: @ 81B910A
	.string "Oh, no! I've got this feeling I'll hook\n"
	.string "a big one!$"

Route106_Text_DouglasIntro:: @ 81B913D
	.string "Hahahah! I'm a lousy runner, but in\n"
	.string "the water you can't catch me!$"

Route106_Text_DouglasDefeated:: @ 81B917F
	.string "I give up!$"

Route106_Text_DouglasPostBattle:: @ 81B918A
	.string "I wouldn't lose in a swim race...$"

Route106_Text_NicoleIntro:: @ 81B91AC
	.string "The sea is my backyard. I'm not going\n"
	.string "to take it easy because you're a kid!$"

Route106_Text_NicoleDefeated:: @ 81B91F8
	.string "Did you take it easy on me by any\n"
	.string "chance?$"

Route106_Text_NicolePostBattle:: @ 81B9222
	.string "Drifting along with the waves...\n"
	.string "I love it! Why don't you give it a try?$"
