AquaHideout_B2F_Text_AdminIntro:: @ 8197093
	.string "Hehehehe... Du hast es tatsächlich\n"
	.string "bis hierher geschafft?\p"
	.string "Da haben wir dich wohl etwas\n"
	.string "unterschätzt!\p"
	.string "Aber hier geht es für dich nicht weiter!\p"
	.string "Ich bin besser als die anderen RÜPEL,\n"
	.string "die dir bisher begegnet sind.\p"
	.string "Ich schinde keine Zeit heraus. Ich\n"
	.string "werde dich pulverisieren!$"

AquaHideout_B2F_Text_AdminDefeat:: @ 8197145
	.string "Hehehe...\n"
	.string "Dann habe ich eben auch verloren. Pöh.$"

AquaHideout_B2F_Text_OurBossGotThroughHisPreparations:: @ 8197162
	.string "Hehehe!\p"
	.string "Während ich mit dir gespielt habe, hat\n"
	.string "sich unser BOSS vorbereitet!$"

AquaHideout_B2F_Text_AdminPostBattle:: @ 81971AE
	.string "Hehehe!\p"
	.string "Unser BOSS ist schon unterwegs zu\n"
	.string "einer Unterwasserhöhle!\p"
	.string "Falls du ihn verfolgen willst, suche doch\n"
	.string "mal die Tiefsee in der Region um\l"
	.string "SEEGRASULB CITY ab.\p"
	.string "Aber ob du ihn dort auch finden wirst?\n"
	.string "Hehehehehehe...$"

AquaHideout_B2F_Text_Grunt2Intro:: @ 8197270
	.string "Wahahahah, ich bin müde vom Warten!\n"
	.string "Du schuldest mir einen Kampf!$"

AquaHideout_B2F_Text_Grunt2Defeat:: @ 81972AC
	.string "Des Wartens müde...\n"
	.string "Gedöst und verloren...$"

AquaHideout_B2F_Text_Grunt2PostBattle:: @ 81972D2
	.string "BOSS...\n"
	.string "Reicht das aus?$"

AquaHideout_B2F_Text_Grunt3Intro:: @ 81972EF
	.string "Teleporter... Der ganze Stolz des\n"
	.string "VERSTECKS!\p"
	.string "Du weißt gar nicht mehr, wo du gerade\n"
	.string "bist, stimmt's? Kicher...\p"
	.string "Den Gegner verwirren, ermüden und dann\n"
	.string "auf ihn mit Gebrüll! Das ist der Plan!$"

AquaHideout_B2F_Text_Grunt3Defeat:: @ 8197390
	.string "Was stimmt nicht mit dir?\n"
	.string "Du bist ja überhaupt nicht müde!$"

AquaHideout_B2F_Text_Grunt3PostBattle:: @ 81973C0
	.string "Da fällt mir ein... Wo habe ich nur den\n"
	.string "MEISTERBALL hingelegt?\p"
	.string "Wenn ich den verloren habe, zieht mir\n"
	.string "der BOSS die Ohren lang...$"
