Route120_Text_ColinIntro:: @ 81BEFC8
	.string "Hast du Attacken auf Lager, die ein\n"
	.string "fliegendes POKéMON schlagen können?$"

Route120_Text_ColinDefeat:: @ 81BF000
	.string "Du bist mir überlegen!$"

Route120_Text_ColinPostBattle:: @ 81BF015
	.string "Die Attacke FLIEGEN ist sehr praktisch,\n"
	.string "meinst du nicht auch?\p"
	.string "Wenn ein POKéMON fliegt, kann ihm fast\n"
	.string "keine Attacke Schaden zufügen.$"

Route120_Text_RobertIntro:: @ 81BF07E
	.string "Mein POKéMON ist stark!\n"
	.string "Wie sieht es mit deinen aus?$"

Route120_Text_RobertDefeat:: @ 81BF0A5
	.string "Deine POKéMON sind stärker...$"

Route120_Text_RobertPostBattle:: @ 81BF0C3
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig...$"

Route120_Text_RobertRematchIntro:: @ 81BF0FA
	.string "Ein POKéMON, das beständig wächst, ist\n"
	.string "absolut zuverlässig...$"

Route120_Text_RobertRematchDefeat:: @ 81BF131
	.string "Deine POKéMON sind enorm stark.$"

Route120_Text_RobertPostRematch:: @ 81BF154
	.string "Meine POKéMON werden immer stärker.\n"
	.string "Ich muss auch immer stärker werden.$"

Route120_Text_CarlosIntro:: @ 81BF193
	.string "Ich prüfe deine POKéMON und schaue, ob\n"
	.string "sie fit für das Leben im Freien sind.$"

Route120_Text_CarlosDefeat:: @ 81BF1D4
	.string "Mit solch starken POKéMON brauchst du\n"
	.string "in der Natur keine Angst zu haben.$"

Route120_Text_CarlosPostBattle:: @ 81BF215
	.string "Mit POKéMON dorthin zu reisen, wohin\n"
	.string "man auch immer will... Das ist das\l"
	.string "Schöne an einem Leben als TRAINER.$"

Route120_Text_JennaIntro:: @ 81BF26E
	.string "Wie sieht es mit deiner Fitness aus?\n"
	.string "Wenn du nicht fit bist, könnten \l"
	.string "harte Zeiten auf dich zukommen.$"

Route120_Text_JennaDefeat:: @ 81BF2D2
	.string "Ich bin fit wie ein Turnschuh, aber...$"

Route120_Text_JennaPostBattle:: @ 81BF2EA
	.string "Fitnesstraining gehört zu meinem\n"
	.string "Leben. Ich laufe mit meinen POKéMON.$"

Route120_Text_BrandonIntro:: @ 81BF32B
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Kampf gefällig?$"

Route120_Text_BrandonDefeat:: @ 81BF36B
	.string "... ... ... ... ... ...\n"
	.string "Ich habe verloren...$"

Route120_Text_BrandonPostBattle:: @ 81BF38D
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Muss mich mehr anstrengen...$"

Route120_Text_BrandonRematchIntro:: @ 81BF3D0
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Noch ein Kampf gefällig?$"

Route120_Text_BrandonRematchDefeat:: @ 81BF416
	.string "... ... ... ... ... ...\n"
	.string "Ich habe wieder verloren...$"

Route120_Text_BrandonPostRematch:: @ 81BF43E
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Ich werde mich mehr anstrengen...\l"
	.string "Für meine kostbaren KÄFER-POKéMON...$"

Route120_Text_JenniferIntro:: @ 81BF4A0
	.string "POKéMON haben viele spezielle Fähig-\n"
	.string "keiten. Wenn du ein klasse TRAINER\l"
	.string "werden willst, lerne etwas darüber.$"

Route120_Text_JenniferDefeat:: @ 81BF504
	.string "Du setzt offensichtlich dein Gehirn ein.$"

Route120_Text_JenniferPostBattle:: @ 81BF51F
	.string "Die speziellen Fähigkeiten eines\n"
	.string "POKéMON bestimmen den Kampfstil.$"

Route120_Text_ChipIntro:: @ 81BF560
	.string "Wer magst du sein?\p"
	.string "Suchst du etwa nach antiken Ruinen,\n"
	.string "von denen die Legende sagt, sie\l"
	.string "seien hier zu finden?$"

Route120_Text_ChipDefeat:: @ 81BF5D6
	.string "Was für ein erbärmlicher Rückschritt...$"

Route120_Text_ChipPostBattle:: @ 81BF5F4
	.string "Dieser gigantische Felsen... Ich würde\n"
	.string "zu gerne glauben, er enthielte antike\l"
	.string "Schätze. Aber ich sehe keinen Eingang.$"

Route120_Text_ClarissaIntro:: @ 81BF65B
	.string "Warum ich diesen Schirm trage?\p"
	.string "Das verrate ich dir, wenn du mich\n"
	.string "besiegen kannst.$"

Route120_Text_ClarissaDefeat:: @ 81BF6A4
	.string "Ein Schirm kann nicht vor den Attacken\n"
	.string "der POKéMON schützen...$"

Route120_Text_ClarissaPostBattle:: @ 81BF6D0
	.string "Ich glaube nicht, dass starkes Sonnen-\n"
	.string "licht gut für meine POKéMON ist.\l"
	.string "Daher schütze ich sie mit meinem Schirm.$"

Route120_Text_AngelicaIntro:: @ 81BF728
	.string "Mein Schirm, mein POKéMON und ich...\p"
	.string "Würde eines dieser Elemente fehlen,\n"
	.string "wäre dieses Bild der Schönheit ruiniert.$"

Route120_Text_AngelicaDefeat:: @ 81BF78C
	.string "Du hast das Bild der Schönheit ruiniert!$"

Route120_Text_AngelicaPostBattle:: @ 81BF7B2
	.string "Mein Schirm würde dir überhaupt nicht\n"
	.string "stehen.\p"
	.string "Er wäre dir sogar hinderlich.$"

Route120_Text_KeigoIntro:: @ 81BF80B
	.string "Ich werde die Techniken der POKéMON\n"
	.string "übernehmen und neue Ninja-Techniken\l"
	.string "daraus entwickeln.$"

Route120_Text_KeigoDefeat:: @ 81BF852
	.string "Die Entwicklung neuer Ninja-Techniken\n"
	.string "bleibt ein Traum...$"

Route120_Text_KeigoPostBattle:: @ 81BF891
	.string "Vielleicht sollte ich unter einem Ninja-\n"
	.string "Meister lernen...$"

Route120_Text_TsunaoIntro:: @ 81BF8C5
	.string "Wir Ninja verbergen uns unter unseren\n"
	.string "Tarnmänteln. Ich wette, du wusstest\l"
	.string "nicht, wo ich versteckt war!$"

Route120_Text_TsunaoDefeat:: @ 81BF920
	.string "Ich habe verloren! Ich wünschte, mein\n"
	.string "Tarnmantel würde meine Schande tarnen.$"

Route120_Text_TsunaoPostBattle:: @ 81BF946
	.string "Unsere Tarnmäntel sind alle handge-\n"
	.string "arbeitet.$"
