Route128_Text_IsaiahIntro:: @ 81C1C67
	.string "EVER GRANDE CITY is still a long ways\n"
	.string "away...$"

Route128_Text_IsaiahDefeat:: @ 81C1C95
	.string "My first victory seems to be far\n"
	.string "away, too...$"

Route128_Text_IsaiahPostBattle:: @ 81C1CC3
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRematchIntro:: @ 81C1D02
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:: @ 81C1D45
	.string "I've yet to taste my first victory...$"

Route128_Text_IsaiahPostRematch:: @ 81C1D6B
	.string "I'll eventually reach EVER GRANDE CITY\n"
	.string "where I can eventually win...$"

Route128_Text_KatelynIntro:: @ 81C1DB0
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat:: @ 81C1E25
	.string "A POKéMON battle is grueling, too...$"

Route128_Text_KatelynPostBattle:: @ 81C1E4A
	.string "I have to ride a BIKE next, but...\n"
	.string "I'm about to throw in the towel...$"

Route128_Text_KatelynRematchIntro:: @ 81C1E90
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the POKéMON CHAMPION\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat:: @ 81C1EFA
	.string "A POKéMON battle really is harsh\n"
	.string "and unforgiving...$"

Route128_Text_KatelynPostRematch:: @ 81C1F2E
	.string "You should give serious thought to\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:: @ 81C1F6D
	.string "We've been working so hard to mount\n"
	.string "a POKéMON LEAGUE challenge...\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:: @ 81C1FCC
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle:: @ 81C1FE8
	.string "After all I've done to get here, I won't\n"
	.string "give up after one setback.$"

Route128_Text_RubenIntro:: @ 81C202C
	.string "There is no stronger TRAINER than I!$"

Route128_Text_RubenDefeat:: @ 81C2051
	.string "This can't be!$"

Route128_Text_RubenPostBattle:: @ 81C2060
	.string "There probably is no stronger TRAINER\n"
	.string "than you!$"

Route128_Text_WayneIntro:: @ 81C2090
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught myself a POKéMON that knows\l"
	.string "the move WATERFALL to crest the falls.$"

Route128_Text_WayneDefeat:: @ 81C20FC
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle:: @ 81C210D
	.string "Awww, phooey!\p"
	.string "My POKéMON know WATERFALL, but\n"
	.string "I don't have the SOOTOPOLIS GYM BADGE!$"
