Route103_Text_DaisyIntro:: @ 81B7D55
	.string "Spürst du die wohlige Berührung\n"
	.string "unseres wohltuenden Wohlgeruches?$"

Route103_Text_DaisyDefeated:: @ 81B7D8B
	.string "Du hast dich vom Duft nicht ablenken\n"
	.string "lassen...$"

Route103_Text_DaisyPostBattle:: @ 81B7DB2
	.string "Aromatherapie ist eine Form der\n"
	.string "mentalen Kur, die mit Düften arbeitet.$"

Route103_Text_AmyIntro:: @ 81B7DF7
	.string "NORA: Hallo, ich bin NORA.\n"
	.string "Und das ist meine kleine Schwester JO.\l"
	.string "Wir kämpfen stets zusammen!$"

Route103_Text_AmyDefeated:: @ 81B7E3B
	.string "NORA: Oh, wir haben verloren.$"

Route103_Text_AmyPostBattle:: @ 81B7E50
	.string "NORA: Du musst auf alles Mögliche\n"
	.string "achten, wenn du gegen zwei TRAINER\l"
	.string "antrittst.$"

Route103_Text_AmyNotEnoughPokemon:: @ 81B7EAC
	.string "NORA: Oh oh, du hast nur ein POKéMON\n"
	.string "dabei. Damit kannst du nicht gegen uns\l"
	.string "beide antreten.$"

Route103_Text_LivIntro:: @ 81B7EFB
	.string "JO: Wir kämpfen als Team...$"

Route103_Text_LivDefeated:: @ 81B7F20
	.string "JO: Schwesterherz, wir haben verloren.$"

Route103_Text_LivPostBattle:: @ 81B7F40
	.string "JO: Wir arbeiten sehr gut zusammen, ich\n"
	.string "und meine große Schwester...\p"
	.string "Aber wir haben verloren...$"

Route103_Text_LivNotEnoughPokemon:: @ 81B7F8E
	.string "JO: Wenn du gegen uns kämpfen willst,\n"
	.string "brauchst du zwei POKéMON. Hast du die\l"
	.string "nicht, wäre der Kampf unfair!$"

Route103_Text_AmyRematchIntro:: @ 81B7FE7
	.string "NORA: Hallo, weißt du noch? Ich bin NORA.\n"
	.string "Und das ist meine kleine Schwester JO.\l"
	.string "Wir kämpfen stets zusammen!$"

Route103_Text_AmyRematchDefeated:: @ 81B802B
	.string "NORA: Aahaaa, buuuh!\n"
	.string "Wir haben es nicht geschafft...$"

Route103_Text_AmyRematchPostBattle:: @ 81B8053
	.string "NORA: Du musst auf alles Mögliche\n"
	.string "achten, wenn du gegen zwei TRAINER\l"
	.string "antrittst. Erwähnte ich das schon?$"

Route103_Text_AmyRematchNotEnoughPokemon:: @ 81B80AF
	.string "NORA: Oh oh, du hast nur ein POKéMON\n"
	.string "dabei. Damit kannst du nicht gegen uns\l"
	.string "beide antreten.$"

Route103_Text_LivRematchIntro:: @ 81B80FE
	.string "JO: Wir kämpfen als Team...$"

Route103_Text_LivRematchDefeated:: @ 81B8123
	.string "JO: Heul... Große Schwester, wir haben\n"
	.string "schon wieder verloren.$"

Route103_Text_LivRematchPostBattle:: @ 81B814D
	.string "JO: Wir haben wieder perfekt zusammen-\n"
	.string "gearbeitet, ich und meine Schwester...\p"
	.string "Warum haben wir wieder verloren?$"

Route103_Text_LivRematchNotEnoughPokemon:: @ 81B81A1
	.string "JO: Wenn du gegen uns kämpfen willst,\n"
	.string "brauchst du zwei POKéMON. Hast du die\l"
	.string "nicht, wäre der Kampf unfair!$"

Route103_Text_AndrewIntro:: @ 81B81FA
	.string "Ach! Meine Angelschnur hat sich ver-\n"
	.string "heddert! Jetzt bin ich frustriert und\l"
	.string "wütend! So! Und du darfst es ausbaden!$"

Route103_Text_AndrewDefeated:: @ 81B8258
	.string "Ach! Verloren!\n"
	.string "Nun bin ich noch wütender...$"

Route103_Text_AndrewPostBattle:: @ 81B8281
	.string "Ach! Ich koche vor Wut, Mann...\n"
	.string "Grrrr...$"

Route103_Text_MiguelIntro:: @ 81B82A9
	.string "Mein POKéMON ist einfach anbetungs-\n"
	.string "würdig. Nur keine Scheu, ich zeig's dir.$"

Route103_Text_MiguelDefeated:: @ 81B82EC
	.string "Oh, so was aber auch!\n"
	.string "Mein geliebtes POKéMON!$"

Route103_Text_MiguelPostBattle:: @ 81B830D
	.string "Mein wunderbares POKéMON sieht sogar\n"
	.string "besiegt noch wunderbar aus.$"

Route103_Text_MiguelRematchIntro:: @ 81B8349
	.string "Hey, du! Mein anbetungswürdiges\n"
	.string "POKéMON ist noch anbetungswürdiger\l"
	.string "geworden.$"

Route103_Text_MiguelRematchDefeated:: @ 81B838C
	.string "Oh!\n"
	.string "Mein geliebtes POKéMON.$"

Route103_Text_MiguelRematchPostBattle:: @ 81B83A4
	.string "Je mehr Zeit ich mit ihm verbringe,\n"
	.string "desto anbetungswürdiger wird es.$"
