CaveOfOrigin_B4F_Text_BlueOrbBeginsGlowing: @ 81B4F03
	.string "Die BLAUE KUGEL von {PLAYER}\n"
	.string "beginnt plötzlich von innen\l"
	.string "heraus zu leuchten!$"

CaveOfOrigin_B4F_Text_KyogreSettled: @ 81B4F29
	.string "KYOGRE wurde offensichtlich\n"
	.string "wieder in Schlaf versetzt...$"

AquaLeader_Text_This: @ 81B4F5C
	.string "ADRIAN: Das...$"

AquaLeader_Text_Farewell: @ 81B4F6C
	.string "ADRIAN: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Das heißt wohl Goodbye. Das ist das\n"
	.string "Letzte, was du von mir siehst.$"
