PetalburgCity_Gym_Text_GiveEnigmaBerry:: @ 81C5570
	.string "VATER: Hallo, {PLAYER}!\p"
	.string "Ich habe gerade eine sehr seltene\n"
	.string "BEERE erhalten. Die schenke ich dir.$"

.include "data/maps/Route104/berry_text.inc"

Route111_Text_WateredPlantsEveryDayTakeBerry:: @ 81C56F0
	.string "Ich habe meine Pflanzen sehr oft ge-\n"
	.string "wässert! Sie trugen sehr viele Blüten.\p"
	.string "Und dann wuchsen auf einmal viele\n"
	.string "BEEREN!\p"
	.string "Hier, bitte!\n"
	.string "Die schenke ich dir!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:: @ 81C5781
	.string "Ich werde mich anstrengen und einige\n"
	.string "rote {POKEBLOCK} herstellen!\p"
	.string "Ich hoffe, du strengst dich auch an.$"

Route111_Text_WhatColorBerriesToLookForToday:: @ 81C57D2
	.string "Ich frage mich, welche BEEREN-Farbe ich\n"
	.string "heute wählen soll.$"

Route114_Text_LoveUsingBerryCrushShareBerry:: @ 81C5803
	.string "Ich sammle BEEREN, damit ich einen\n"
	.string "POKéMON WETTBEWERB gewinnen kann.\p"
	.string "Wenn du magst, gebe ich dir eine ab.$"

Route114_Text_TryBerryCrushWithFriends:: @ 81C5861
	.string "Dir auch viel Glück!$"

Route114_Text_FunToThinkAboutBerries:: @ 81C5878
	.string "Welche BEEREN soll ich heute pflanzen?\n"
	.string "Welche Farben sollen die {POKEBLOCK} haben?\p"
	.string "Darüber nachzudenken, macht irre Spaß.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:: @ 81C58F1
	.string "Gib dieser Box einen Stoß und ein\n"
	.string "{POKEBLOCK} kommt heraus...\p"
	.string "Und dieser {POKEBLOCK} wird von einem\n"
	.string "POKéMON gefressen...\p"
	.string "Es ist ein Ausdruck der Liebe, richtig?$"

Route120_Text_YesYouUnderstand:: @ 81C5979
	.string "Ja, ja.\n"
	.string "Du verstehst, was ich meine.\p"
	.string "Das hier ist für dich.$"

Route120_Text_MakeYourOwnImpressions:: @ 81C59B5
	.string "Oh... Aber es ist wichtig, dass man sich\n"
	.string "einen eigenen Eindruck verschafft...\p"
	.string "Hier. Das kannst du haben.$"

Route120_Text_BerryIsRareRaiseItWithCare:: @ 81C5A0B
	.string "Dies ist eine seltene BEERE. Ich hoffe,\n"
	.string "du gehst sorgfältig mit ihr um.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:: @ 81C5A4D
	.string "Ich habe einige BEEREN vom\n"
	.string "BEERENMEISTER erhalten.$"

LilycoveCity_Text_BerrySuitsYou:: @ 81C5A7A
	.string "Also, im Grunde ist es so...\p"
	.string "Ein Anzug passt zu mir wie die\n"
	.string "Brise zum Meer - perfekt!\p"
	.string "Und bei dir... Eine BEERE passt zu\n"
	.string "“T”...\p"
	.string "Warum ist das so?$"

LilycoveCity_Text_BecauseYoureTrainer:: @ 81C5B1D
	.string "Also, im Grunde ist es so...\p"
	.string "Weil du ein TRAINER bist.$"

LilycoveCity_Text_PokeblocksSuitPokemon:: @ 81C5B5D
	.string "Grundsätzlich verhält es sich so...\p"
	.string "So wie die würdevolle Einfachheit mich\n"
	.string "ziert, zieren {POKEBLOCK} POKéMON.$"

.include "data/maps/Route123_BerryMastersHouse/berry_text.inc"

.include "data/maps/Route104_PrettyPetalFlowerShop/text.inc"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:: @ 81C63F2
	.string "Hi, wie heißt du?\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "Okay. Netter Name!\p"
	.string "Ich heiße BERTA.\p"
	.string "Meine Eltern haben mich so genannt,\n"
	.string "damit ich gesund und warmherzig werde.\l"
	.string "Das war ihr Wunsch.\p"
	.string "Hier, das schenke ich dir.$"

SootopolisCity_Text_GiveYouThisBerryToo:: @ 81C64D0
	.string "BERTA will dir auch diese BEERE geben.\n"
	.string "Ich mag sie sehr!$"

SootopolisCity_Text_WhatKindOfWishInYourName:: @ 81C650B
	.string "Ich frage mich, welcher Wunsch in deinem\n"
	.string "Namen verborgen ist.$"

SootopolisCity_Text_LikeSeasonBornIn:: @ 81C6540
	.string "Frühling, Sommer, Herbst und Winter.\p"
	.string "Wenn du im Frühling geboren bist, magst\n"
	.string "du dann den Frühling? Wenn du im Sommer\l"
	.string "geboren bist, magst du den Sommer?$"

SootopolisCity_Text_ThenILoveAutumn:: @ 81C65D4
	.string "Dann wurde BERTA im Herbst geboren,\n"
	.string "denn ich liebe den Herbst!\p"
	.string "Welche Jahreszeit hast du am liebsten?$"

SootopolisCity_Text_OhDoesntMatter:: @ 81C6626
	.string "Oh...\n"
	.string "Das macht nichts...\p"
	.string "Es gibt so viel, was ich wissen möchte...$"
