BerryTree_Text_ItsSoftLoamySoil:: @ 81A16B6
	.string "Das ist weicher Lehmboden.$"

BerryTree_Text_WantToPlant:: @ 81A16CD
	.string "Das ist weicher Lehmboden.\n"
	.string "Möchtest du eine BEERE pflanzen?$"

BerryTree_Text_PlantedOneBerry:: @ 81A16FB
	.string "{PLAYER} pflanzt eine\n"
	.string "{STR_VAR_1}BEERE in den Lehmboden.$"

BerryTree_Text_BerryGrowthStage1:: @ 81A172C
	.string "Eine {STR_VAR_1}BEERE wurde\n"
	.string "hier gepflanzt.$"

BerryTree_Text_BerryGrowthStage2:: @ 81A174B
	.string "{STR_VAR_1} blüht auf.$"

BerryTree_Text_BerryGrowthStage3:: @ 81A175C
	.string "Die {STR_VAR_1}pflanze wächst.$"

BerryTree_Text_BerryGrowthStage4:: @ 81A177D
	.string "Diese {STR_VAR_1}blumen sind\n"
	.string "{STR_VAR_2}.$"

BerryTree_Text_CareAdverbGreat:: @ 81A179F
	.string "wunderschön$"

BerryTree_Text_CareAdverbPoor:: @ 81A17B0
	.string "zierlich$"

BerryTree_Text_CareAdverbGood:: @ 81A17B7
	.string "hübsch$"

BerryTree_Text_WantToPick:: @ 81A17C0
	.string "{STR_VAR_2} {STR_VAR_1}BEERE/N!\p"
	.string "Möchtest du die {STR_VAR_1}BEERE/N\n"
	.string "pflücken?$"

BerryTree_Text_PickedTheBerry:: @ 81A17FD
	.string "{PLAYER} pflückt die {STR_VAR_2}\n"
	.string "{STR_VAR_1}BEERE/N.$"

BerryTree_Text_PutAwayBerry:: @ 81A181A
	.string "{PLAYER} packt die {STR_VAR_1}BEERE/N\n"
	.string "in die BEERENTASCHE des BEUTELS.\p"
	.string "Der Boden ist wieder weich und lehmig.$"

BerryTree_Text_BerryPocketFull:: @ 81A1881
	.string "Die BEERENTASCHE des BEUTELS ist voll.\p"
	.string "Die {STR_VAR_1}BEERE/N können nicht\n"
	.string "mitgenommen werden.$"

BerryTree_Text_BerryLeftUnpicked:: @ 81A18C5
	.string "{PLAYER} pflückt keine\n"
	.string "{STR_VAR_1}BEEREN.$"

BerryTree_Text_WantToWater:: @ 81A18E6
	.string "Möchtest du die {STR_VAR_1} mit der\n"
	.string "WAILMERKANNE gießen?$"

BerryTree_Text_WateredTheBerry:: @ 81A1912
	.string "{PLAYER} gießt die {STR_VAR_1}.$"

BerryTree_Text_PlantIsDelighted:: @ 81A1925
	.string "Die Pflanze scheint sich zu freuen.$"

BerryTree_Text_ExclamationPoint:: @ 81A1946
	.string "!$"
