gText_Birch_Welcome:: @ 81C6D78
	.string "Sorry, dass du warten musstest.\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist BIRK.\p"
	.string "Aber jeder nennt mich nur\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon:: @ 81C6DF8
	.string "Das nennen wir ein “POKéMON”.$"

gText_Birch_MainSpeech:: @ 81C6E1A
	.string "Auf dieser Welt leben Wesen,\n"
	.string "die uns als POKéMON bekannt sind.\p"
	.string "Wir Menschen leben Seite an Seite\n"
	.string "mit ihnen, als Freunde oder als\l"
	.string "Arbeitskollegen.\p"
	.string "Und manchmal schließen wir uns mit\n"
	.string "ihnen zusammen und tragen Kämpfe\l"
	.string "gegen andere von uns aus.\p"
	.string "Doch obwohl wir den POKéMON so\n"
	.string "nahe stehen, wissen wir noch nicht\l"
	.string "alles über sie.\p"
	.string "Es gibt noch viele, viele Geheim-\n"
	.string "nisse über die POKéMON.\p"
	.string "Um die Mysterien der POKéMON\n"
	.string "aufzudecken, widme ich mich der\l"
	.string "Forschung. Genau das tue ich.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 81C6FCB
	.string "Und wer bist du?$"

gText_Birch_BoyOrGirl:: @ 81C6FD8
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"

gText_Birch_WhatsYourName:: @ 81C6FFA
	.string "Fein!\n"
	.string "Und wie heißt du?$"

gText_Birch_SoItsPlayer:: @ 81C7017
	.string "Ah, du bist also {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt {PLAYER}{KUN}\n"
	.string "und bist gerade nach WURZELHEIM,\l"
	.string "meinem Heimatort, gezogen!$"

gText_Birch_AreYouReady:: @ 81C7074
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird\n"
	.string "nun beginnen.\p"
	.string "Hab nur Mut und stürze dich in die\n"
	.string "Welt der POKéMON, wo Abenteuer,\l"
	.string "Träume und Freundschaft warten.\p"
	.string "Komm später in mein POKéMON-LABOR,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
