CableClub_Text_WelcomeToColosseum:: @ 81A4510
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "KOLOSSEUM.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "kämpfen.\p"
	.string "Möchtest du jetzt kämpfen?$"

CableClub_Text_WelcomeToTradeCenter:: @ 81A457E
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "HANDELSCENTER.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "POKéMON tauschen.\p"
	.string "Möchtest du jetzt POKéMON tauschen?$"

CableClub_Text_WelcomeToRecordCorner:: @ 81A45FE
	.string "Willkommen beim POKéMON KABEL-CLUB-\n"
	.string "STATISTIKTAUSCH.\p"
	.string "Hier kannst du mit deinen Freunden\n"
	.string "die Rekorde als TRAINER austauschen.\p"
	.string "Möchtest du Rekorde austauschen?$"

CableClub_Text_ExplainBattleModes:: @ 81A4696
	.string "Es gibt drei Arten des Kampfes\n"
	.string "via Verbindungskabel.\p"
	.string "EINZELKAMPF ist für zwei TRAINER, die\n"
	.string "jeder ein oder mehrere POKéMON\l"
	.string "besitzen.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.\p"
	.string "DOPPELKAMPF ist für zwei TRAINER mit\n"
	.string "zwei oder mehr POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde zwei\n"
	.string "POKéMON in den Kampf.\p"
	.string "MULTIKÄMPFE sind für vier TRAINER mit\n"
	.string "einem oder mehr POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde ein\n"
	.string "POKéMON in den Kampf.$"

CableClub_Text_WouldYouLikeToBattle:: @ 81A4826
	.string "Möchtest du kämpfen?$"

CableClub_Text_PlayWhichBattleMode:: @ 81A4840
	.string "Welche Art des Kampfes?$"

CableClub_Text_NeedTwoMonsForDoubleBattle:: @ 81A486A
	.string "Für einen DOPPELKAMPF brauchst du\n"
	.string "mindestens zwei POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:: @ 81A48A3
	.string "Für einen Tausch musst du mindestens\n"
	.string "zwei POKéMON bei dir haben.$"

CableClub_Text_CantTradeEnigmaBerry:: @ 81A48DD
	.string "Dein POKéMON trägt eine {STR_VAR_1}-\n"
	.string "BEERE und kann nicht getauscht werden.$"

gText_PleaseWaitForLink:: @ 81A490C
	.string "Bitte warten.\n"
	.string "... ... B-Knopf: Abbruch$"

gText_ConfirmLinkWhenPlayersReady:: @ 81A4932
	.string "Wenn die Spieler bereit sind...\n"
	.string "A-Knopf: Bestätigen  B-Knopf: Abbruch$"

gText_ConfirmStartLinkWithXPlayers:: @ 81A4975
	.string "Verbindung für {STR_VAR_1} Spieler aufbauen.\n"
	.string "A-Knopf: Bestätigen  B-Knopf: Abbruch$"

gText_AwaitingLinkup:: @ 81A49B6
	.string "Verbindungsaufbau...\n"
	.string "... ... B-Knopf: Abbruch$"

CableClub_Text_OkayToSaveProgress: @ 81A49E2
	.string "Dein Spiel muss vor Verbindungsaufbau\n"
	.string "gespeichert werden. Speichern?$"

CableClub_Text_PleaseEnter:: @ 81A4A22
	.string "Bitte eintreten.$"

Text_SomeoneIsNotReadyToLink:: @ 81A4A30
	.string "Ein Spieler ist noch nicht bereit\n"
	.string "für den Link.\p"
	.string "Bitte kommt wieder, wenn jeder seine\n"
	.string "Vorbereitungen getroffen hat.$"

Text_LinkErrorPleaseReset:: @ 81A4A85
	.string "Verbindungsfehler...\n"
	.string "Die Kabelverbindungen überprüfen und\l"
	.string "die Geräte aus- und wieder einschalten.$"

CableClub_Text_CantMixWithDifferentLanguage:: @ 81A4AC8
	.string "Tut uns Leid. Hier liegt ein Über-\n"
	.string "tragungsfehler vor. Rekorde können\l"
	.string "nicht in unterschiedlichen Sprachen\l"
	.string "ausgetauscht werden.$"

Text_PlayersMadeDifferentSelections:: @ 81A4B1D
	.string "Die Link-Partner haben eine unter-\n"
	.string "schiedliche Auswahl getroffen.$"

CableClub_Text_PleaseVisitAgain:: @ 81A4B59
	.string "Bitte komm bald wieder.$"

CableClub_Text_IncorrectNumberOfParticipants:: @ 81A4B6C
	.string "Die Anzahl der Teilnehmer ist nicht\n"
	.string "korrekt.$"

CableClub_Text_CantSingleBattleWithXPlayers:: @ 81A4B95
	.string "Ein EINZELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_CantDoubleBattleWithXPlayers:: @ 81A4BCC
	.string "Ein DOPPELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_NeedFourPlayers:: @ 81A4C03
	.string "Für diesen Kampfmodus werden vier\n"
	.string "Spieler benötigt.$"

CableClub_Text_PleaseConfirmNumberAndRestart:: @ 81A4C38
	.string "Bitte überprüfe die Anzahl der Spieler\n"
	.string "und fange noch einmal an.$"

Text_TerminateLinkConfirmation: @ 81A4C6E
	.string "Wenn du den Raum verlässt, wird die Ver-\n"
	.string "bindung abgebrochen. Einverstanden?$"

Text_TerminateLinkPleaseWait: @ 81A4CAF
	.string "Verbindung wird abgebrochen... Du wirst\n"
	.string "aus dem Raum begleitet. Bitte warten.$"

CableClub_Text_TooBusyToNotice: @ 81A4CF6
	.string "Dieser TRAINER ist zu beschäftigt...$"

CableClub_Text_GotToLookAtTrainerCard: @ 81A4D1C
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an!$"

CableClub_Text_GotToLookAtColoredTrainerCard: @ 81A4D45
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an! Es ist ein\l"
	.string "{STR_VAR_2}PASS.$"

BattleColosseum_2P_Text_TakePlaceStartBattle:: @ 81A4D7E
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Kampf.$"

TradeCenter_Text_TakeSeatStartTrade:: @ 81A4DAB
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Tausch.$"

RecordCorner_Text_TakeSeatAndWait:: @ 81A4DD7
	.string "Bitte geh in Position und warte.$"

RecordCorner_Text_ThanksForComing:: @ 81A4DF7
	.string "Danke für den Besuch!$"

BattleColosseum_4P_Text_ChoosePokemon: @ 81A4E0A
	.string "Bitte wähle die POKéMON für den\n"
	.string "MULTIKAMPF.$"

RecordCorner_Text_PlayerSentOverOneX:: @ 81A4E3B
	.string "{STR_VAR_1} hat ein {STR_VAR_2}\n"
	.string "versendet.$"

CableClub_Text_TrainerCardDataOverwritten:: @ 81A4E50
	.string "Der Eintrag auf dem TRAINERPASS wird\n"
	.string "geändert.$"

CableClub_Text_HopeToSeeYouAgain:: @ 81A4E79
	.string "Ich hoffe, du kommst bald wieder vorbei.$"
