Route117_Text_SeeWifeIfYoudLikeMeToRaiseMon:: @ 81B25CB
	.string "Ich bin der PENSIONSLEITER.\p"
	.string "Ich kümmere mich um die wertvollen\n"
	.string "POKéMON der TRAINER.\p"
	.string "Wenn ich eines deiner POKéMON auf-\n"
	.string "ziehen soll, sprich mit meiner Frau.$"

Route117_Text_DoYouWantEgg:: @ 81B2659
	.string "Ach, du bist es!\p"
	.string "Wir haben deine POKéMON aufgezogen\n"
	.string "und wurden überrascht!\p"
	.string "Deine POKéMON haben nun ein EI!\p"
	.string "Wir wissen nicht, wie das passiert ist,\n"
	.string "aber deine POKéMON haben es.\p"
	.string "Möchtest du es haben?$"

Route117_Text_YourMonIsDoingFine:: @ 81B2710
	.string "Ach, du bist es! Schön, dich zu sehen.\n"
	.string "Deinem {STR_VAR_1} geht es sehr gut.$"

Route117_Text_IllKeepIt:: @ 81B2745
	.string "Ich werde es behalten.$"

Route117_Text_YouHaveNoRoomForIt:: @ 81B2766
	.string "Du hast keinen Platz dafür... Komm\n"
	.string "wieder, wenn du Platz geschaffen hast.$"

Route117_Text_ReceivedEgg:: @ 81B27A2
	.string "{PLAYER} erhält das EI vom\n"
	.string "PENSIONSLEITER.$"

Route117_Text_TakeGoodCareOfIt:: @ 81B27CD
	.string "Kümmere dich gut darum.$"

Route117_Text_FriendlyWithOtherTrainersMon:: @ 81B27E3
	.string "Übrigens, dein {STR_VAR_1} scheint sich\n"
	.string "gut mit dem {STR_VAR_3} von {STR_VAR_2} \l"
	.string "zu verstehen.\p"
	.string "Ich habe gesehen, wie sie einen BRIEF\n"
	.string "ausgetauscht haben...$"

Route117_Text_SeeWifeIfYouWantToPickUpMon: @ 81B2858
	.string "Wenn du deine POKéMON zurückhaben\n"
	.string "möchtest, sprich doch mit meiner Frau.$"

Route117_Text_YourMonsAreDoingFine:: @ 81B2897
	.string "Ah, du bist es! Deine POKéMON\n"
	.string "{STR_VAR_1} und {STR_VAR_2} entwickeln\l"
	.string "sich prächtig.$"

Route117_Text_IWillKeepDoYouWantIt:: @ 81B28C4
	.string "Ich werde es behalten.\n"
	.string "Oder möchtest du es haben?$"

Route117_PokemonDayCare_Text_WouldYouLikeUsToRaiseAMon:: @ 81B28F2
	.string "Ich bin die PENSIONSLEITERIN.\p"
	.string "Wir ziehen POKéMON für dich auf.\p"
	.string "Sollen wir eins für dich aufziehen?$"

Route117_PokemonDayCare_Text_WhichMonShouldWeRaise:: @ 81B2947
	.string "Welches POKéMON sollen wir für dich\n"
	.string "aufziehen?$"

Route117_PokemonDayCare_Text_WellRaiseYourMon:: @ 81B296E
	.string "Fein, dann nehmen wir dein {STR_VAR_1}\n"
	.string "für eine Weile in Pflege.\p"
	.string "Schau später mal nach ihm.$"

Route117_PokemonDayCare_Text_WeCanRaiseOneMore:: @ 81B29AD
	.string "Wir können zwei deiner POKéMON nehmen.\n"
	.string "Möchtest du noch eins in Pflege geben?$"

Route117_PokemonDayCare_Text_HusbandWasLookingForYou:: @ 81B29F4
	.string "Mein Mann hat dich schon gesucht.$"

Route117_PokemonDayCare_Text_FineThenComeAgain:: @ 81B2A14
	.string "Oh, gut.\n"
	.string "Komm bald wieder.$"

Route117_PokemonDayCare_Text_NotEnoughMoney:: @ 81B2A30
	.string "Du hast nicht genug Geld...$"

Route117_PokemonDayCare_Text_TakeOtherOneBackToo:: @ 81B2A4F
	.string "Möchtest du das andere auch wieder\n"
	.string "mitnehmen?$"

Route117_PokemonDayCare_Text_ComeAgain:: @ 81B2A76
	.string "Gut.\n"
	.string "Komm bald wieder.$"

Route117_PokemonDayCare_Text_GoodToSeeYou:: @ 81B2A88
	.string "Ach, du bist es! Schön dich zu sehen.\n"
	.string "Deinen POKéMON kann es einfach\l"
	.string "nur gut gehen!$"

Route117_PokemonDayCare_Text_YourMonHasGrownXLevels:: @ 81B2ACC
	.string "Dein {STR_VAR_1} ist um {STR_VAR_2} Level\n"
	.string "gewachsen.$"

Route117_PokemonDayCare_Text_YourTeamIsFull:: @ 81B2AEF
	.string "Dein POKéMON-Team ist vollzählig.\n"
	.string "Schaffe Platz und komm dann wieder.$"

Route117_PokemonDayCare_Text_TakeBackWhichMon: @ 81B2B27
	.string "Welches POKéMON nimmst du wieder mit?$"

Route117_PokemonDayCare_Text_ItWillCostX:: @ 81B2B49
	.string "Wenn du dein {STR_VAR_1}\n"
	.string "mitnehmen willst, kostet das ¥{STR_VAR_2}.$"

Route117_PokemonDayCare_Text_HeresYourMon:: @ 81B2B75
	.string "Sehr schön!\n"
	.string "Hier ist dein POKéMON!$"

Route117_PokemonDayCare_Text_TookBackMon:: @ 81B2B93
	.string "{PLAYER} hat {STR_VAR_1} von der\n"
	.string "PENSIONSLEITERIN zurückerhalten.$"

Route117_PokemonDayCare_Text_YouHaveJustOneMon:: @ 81B2BBB
	.string "Oh! Du hast aber nur ein POKéMON.\p"
	.string "Komm einfach später wieder.$"

Route117_PokemonDayCare_Text_TakeYourMonBack:: @ 81B2BF6
	.string "Möchtest du dein POKéMON wieder\n"
	.string "mitnehmen?$"

Route117_PokemonDayCare_Text_WhatWillYouBattleWith:: @ 81B2C17
	.string "Wenn du das POKéMON hier lässt, womit\n"
	.string "willst du denn dann kämpfen?\p"
	.string "Komm einfach später wieder.$"

Text_EggHatchHuh: @ 81B2C68
	.string "Wie?$"

@ XXX JP
	.string "\p"
	.string "たまごの　ようすが‥\p"
	.string "‥‥‥‥\p"
	.string "おめでとう！\n"
	.string "たまごから　{STR_VAR_1}が　うまれた！$"
