SafariZone_Text_WouldYouLikeToExit: @ 81C34B2
	.string "Möchtest du die SAFARI-ZONE jetzt\n"
	.string "verlassen?$"

SafariZone_Text_TimesUp: @ 81C34E4
	.string "Ding Dong! Die Zeit ist abgelaufen!\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

SafariZone_Text_OutOfBalls: @ 81C3514
	.string "Du hast keine SAFARIBÄLLE mehr.\n"
	.string "Dein SAFARI-Spiel ist vorbei.$"

SafariZone_Text_PlacePokeblockOnFeeder: @ 81C354E
	.string "Möchtest du einen {POKEBLOCK} in den\n"
	.string "{POKEBLOCK}NAPF legen?$"

SafariZone_Text_PokeblockStillHere: @ 81C3583
	.string "Dein {STR_VAR_1} befindet sich\n"
	.string "noch in unserer Obhut.$"

SafariZone_Text_PokeblockWasPlaced: @ 81C35A9
	.string "{STR_VAR_1} wurde in den {POKEBLOCK}-\n"
	.string "NAPF gelegt.$"

Route121_SafariZoneEntrance_Text_WelcomeToSafariZone:: @ 81C35D0
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Hier bekommst du viele POKéMON zu\n"
	.string "Gesicht, die sehr selten in der HOENN-\l"
	.string "Region sind.\p"
	.string "Du kannst sie in ihrer ganzen Wildheit\n"
	.string "und ungezähmt in ihrer natürlichen\l"
	.string "Umgebung beobachten.\p"
	.string "Wir haben unsere Tore für die POKéMON-\n"
	.string "TRAINER geöffnet.\p"
	.string "Fangt euch POKéMON. Und behaltet sie!\p"
	.string "Kommt und genießt die Welt der\n"
	.string "SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_WelcomeFirstTime:: @ 81C3704
	.string "Willkommen in der SAFARI-ZONE!\n"
	.string "Bist du zum ersten Mal hier?$"

Route121_SafariZoneEntrance_Text_ComeInAndEnjoy:: @ 81C373C
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_FirstTimeInfo:: @ 81C375F
	.string "Sobald du die SAFARI-ZONE betrittst,\n"
	.string "stehen dir 30 SAFARIBÄLLE zur Ver-\l"
	.string "fügung, um POKéMON zu fangen.\p"
	.string "Das SAFARI-Spiel ist vorbei, sobald du\n"
	.string "deine SAFARIBÄLLE verbraucht oder\l"
	.string "500 Schritte gemacht hast.\p"
	.string "Komm und genieße die SAFARI-ZONE!$"

Route121_SafariZoneEntrance_Text_WouldYouLikeToPlay:: @ 81C3832
	.string "Willkommen in der SAFARI-ZONE!\p"
	.string "Alles, was du fangen kannst für nur\n"
	.string "¥500! Möchtest du es einmal probieren?$"

Route121_SafariZoneEntrance_Text_PlayAnotherTime:: @ 81C3895
	.string "Okay.\n"
	.string "Bitte beehre uns doch später einmal.$"

Route121_SafariZoneEntrance_Text_NotEnoughMoney:: @ 81C38B5
	.string "Du hast nicht genug Geld dabei.\n"
	.string "Tut mir Leid.$"

Route121_SafariZoneEntrance_Text_ThatWillBe500Please:: @ 81C38D9
	.string "Das macht dann ¥500, bitte.$"

Route121_SafariZoneEntrance_Text_HereAreYourSafariBalls:: @ 81C38F4
	.string "Hier sind deine SAFARIBÄLLE.$"

Route121_SafariZoneEntrance_Text_Received30SafariBalls:: @ 81C3910
	.string "{PLAYER} erhält 30 SAFARIBÄLLE.$"

Route121_SafariZoneEntrance_Text_PleaseEnjoyYourself:: @ 81C392D
	.string "Wir geben dir Bescheid, wenn das Spiel\n"
	.string "vorbei ist.\p"
	.string "Bis dahin wünschen wir viel Spaß!\n"
	.string "Und auf geht's in die Wildnis!$"

Route121_SafariZoneEntrance_Text_PCIsFull:: @ 81C39A3
	.string "Entschuldigung!\n"
	.string "Deine PC-BOXEN sind voll.$"

Route121_SafariZoneEntrance_Text_YouNeedPokeblockCase:: @ 81C39C3
	.string "Entschuldigung!\n"
	.string "Du besitzt keine {POKEBLOCK}BOX.\p"
	.string "Dein SAFARI-Spiel wäre viel erfolg-\n"
	.string "reicher, wenn du {POKEBLOCK} benutzen\l"
	.string "würdest.\p"
	.string "Bitte besorge dir doch eine {POKEBLOCK}BOX.$"

SafariZone_South_Text_StillHaveTimeExit:: @ 81C3A56
	.string "Du hast noch Zeit übrig. Möchtest du\n"
	.string "die SAFARI-ZONE jetzt verlassen?$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure:: @ 81C3A9C
	.string "Viel Vergnügen bei dem Rest deines\n"
	.string "wilden Abenteuers!$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying:: @ 81C3ACA
	.string "Okay.\p"
	.string "Ich nehme die verbleibenden\n"
	.string "SAFARIBÄLLE zurück.\p"
	.string "Vielen Dank für deine Teilnahme.\n"
	.string "Komm bald wieder!$"

SafariZone_South_Text_GoodLuck:: @ 81C3B2D
	.string "Viel Glück!\p"
	.string "Wenn du irgendetwas brauchst, zögere\n"
	.string "nicht, mich anzusprechen!$"

SafariZone_South_Text_Boy:: @ 81C3B71
	.string "Weißt du was?\p"
	.string "Wenn du einen {POKEBLOCK} in diese Kiste\n"
	.string "dort legst, werden POKéMON angelockt.$"

SafariZone_South_Text_Man:: @ 81C3BBD
	.string "Ich wollte noch weiter hinein, aber\n"
	.string "ich habe mein RAD vergessen.\p"
	.string "Irgendetwas sagt mir, dass in den abge-\n"
	.string "legenen Gegenden seltene POKéMON\l"
	.string "leben.$"

SafariZone_Southwest_Text_Woman:: @ 81C3C39
	.string "Manchmal, wenn ich einem POKéMON einen\n"
	.string "{POKEBLOCK} zuwerfe, ignoriert es das total.\p"
	.string "Ob POKéMON auch manche Dinge mögen\n"
	.string "und manche nicht? Wie wir Menschen?$"

SafariZone_Northwest_Text_Man:: @ 81C3CAE
	.string "Hechel... Keuch...\n"
	.string "Ich... bin hierher gekommen... aber...\p"
	.string "Ich bin erschöpft... Japs... Ich habe\n"
	.string "keine Energie, ein POKéMON zu fangen.$"

SafariZone_North_Text_Fisherman:: @ 81C3D19
	.string "Ich habe eine Mission. Ich will WASSER-\n"
	.string "POKéMON fangen, die es in HOENN nicht\l"
	.string "gibt.\p"
	.string "Weißt du zufällig, wo hier der See ist?$"

SafariZone_North_Text_Man:: @ 81C3D80
	.string "Ich will viele seltene POKéMON fangen\n"
	.string "und mit meinen Freunden tauschen.$"

SafariZone_South_Text_Youngster:: @ 81C3DCE
	.string "Ich habe einen {POKEBLOCK} in den {POKEBLOCK}-\n"
	.string "NAPF gelegt. Er ist verschwunden.\p"
	.string "Ein POKéMON muss ihn gefuttert haben,\n"
	.string "ohne dass ich das gemerkt habe.$"

Route121_SafariZoneEntrance_Text_TrainerTip:: @ 81C3E4B
	.string "TIPP für TRAINER in der SAFARI-ZONE!\p"
	.string "Wirf POKéMON {POKEBLOCK} zu, dann ergreifen\n"
	.string "sie nicht so schnell die Flucht.$"

SafariZone_Southwest_Text_RestHouseSign:: @ 81C3EA3
	.string "“Erhole deine gemarterten Füße.”\n"
	.string "RASTHAUS$"

SafariZone_RestHouse_Text_Youngster:: @ 81C3EC9
	.string "Ich habe keine {POKEBLOCK}, aber ich habe\n"
	.string "trotzdem viele POKéMON gefangen.\p"
	.string "Du kannst deine Chancen erhöhen, indem\n"
	.string "du näher an das POKéMON herangehst,\l"
	.string "bevor du den SAFARIBALL wirfst.$"

SafariZone_RestHouse_Text_PsychicM:: @ 81C3F71
	.string "POKéMON fliehen nicht so schnell, wenn\n"
	.string "man ihnen {POKEBLOCK} zuwirft.\p"
	.string "POKéMON, die von Natur aus nicht schnell\n"
	.string "fliehen, braucht man sie nicht\l"
	.string "unbedingt zuzuwerfen.$"

SafariZone_RestHouse_Text_FatMan:: @ 81C3FF4
	.string "Wird ein {POKEBLOCK} in den NAPF gelegt,\n"
	.string "werden POKéMON angelockt.\p"
	.string "Ich glaube, POKéMON mit der gleichen\n"
	.string "Wesensart werden von ähnlichen {POKEBLOCK}N\l"
	.string "angezogen.$"
