gText_ConfirmSave:: @ 81C6C85
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile:: @ 81C6CA6
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Spielstand überschreiben?$"

gText_SavingDontTurnOff:: @ 81C6CE1
	.string "SPEICHERN...\n"
	.string "BITTE DAS GERÄT NICHT AUSSCHALTEN.$"

gText_PlayerSavedGame:: @ 81C6D05
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_SaveError:: @ 81C6D18
	.string "Fehler beim Speichern...$"

gText_DifferentSaveFile:: @ 81C6D26
	.string "Es gibt schon einen anderen Spielstand.\p"
	.string "Soll er überschrieben werden?$"
