SecretBase_Text_TreeCanBeClimbed: @ 81A1948
	.string "Wenn einige Äste herunterhängen, kann\n"
	.string "man auf den Baum klettern.$"

SecretBase_Text_TreeUseSecretPower: @ 81A197B
	.string "Wenn einige Äste herunterhängen, kann\n"
	.string "man auf den Baum klettern.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

SecretBase_Text_VineDroppedDown: @ 81A19C4
	.string "Ein dicker Ast fällt herunter!$"

SecretBase_Text_TreeWantToMakeYourSecretBaseHere: @ 81A19DF
	.string "Möchtest du hier deine GEHEIMBASIS\n"
	.string "einrichten?$"

SecretBase_Text_ClumpOfGrass: @ 81A1A03
	.string "Dieser Busch kann bewegt werden,\n"
	.string "so dass man hineinklettern kann.$"

SecretBase_Text_ClumpUseSecretPower: @ 81A1A4B
	.string "Dieser Busch kann bewegt werden,\n"
	.string "so dass man hineinklettern kann.\p"
	.string "Möchtest du GEHEIMPOWER einsetzen?$"

SecretBase_Text_DiscoveredSmallEntrance: @ 81A1AA9
	.string "Ein kleiner Eingang wird sichtbar.$"

SecretBase_Text_ShrubWantToMakeYourSecretBaseHere: @ 81A1AC6
	.string "Möchtest du hier deine GEHEIMBASIS\n"
	.string "einrichten?$"
