MauvilleCity_PokemonCenter_1F_Text_WillYouHearMyTale:: @ 81AECC6
	.string "Ich bin der GESCHICHTENERZÄHLER.\n"
	.string "Ich erzähle dir die Geschichten von\l"
	.string "legendären TRAINERN.\p"
	.string "Soll ich dir etwas erzählen?$"

MauvilleCity_PokemonCenter_1F_Text_StorytellerFeelingTheBlues:: @ 81AED1D
	.string "Oh...\n"
	.string "Keiner mag mich...$"

MauvilleCity_PokemonCenter_1F_Text_WhichTaleToTell:: @ 81AED35
	.string "Ich kenne viele dieser Legenden.\n"
	.string "Welche möchtest du hören?$"

MauvilleCity_PokemonCenter_1F_Text_IKnowNoTales:: @ 81AED70
	.string "Aber ich weiß nichts über legendäre\n"
	.string "TRAINER. Also habe ich keine Ge-\l"
	.string "schichte auf Lager.\p"
	.string "Wo findet man wohl einen TRAINER, der\n"
	.string "einer lebenden Legende gleicht?$"

MauvilleCity_PokemonCenter_1F_Text_YouDidStatXTimes:: @ 81AEDE8
	.string "Was ist?\n"
	.string "Du... Du...\p"
	.string "{STR_VAR_2}\n"
	.string "{STR_VAR_1}-mal?\p"
	.string "Das ist einfach großartig!\n"
	.string "Die Geburt einer neuen Legende!$"

MauvilleCity_PokemonCenter_1F_Text_CouldThereBeOtherLegends:: @ 81AEE50
	.string "Ich überlege, ob es nicht noch andere\n"
	.string "TRAINER gibt, die mir beeindruckende\l"
	.string "Geschichten erzählen können.$"

MauvilleCity_PokemonCenter_1F_Text_HaveYouAnyLegendaryTales:: @ 81AEEB4
	.string "Bist du ein TRAINER?\p"
	.string "Dann sag mir, ob du Geschichten\n"
	.string "für mich hast, die legendär sind?$"

MauvilleCity_PokemonCenter_1F_Text_HearAnotherLegendaryTale:: @ 81AEF0A
	.string "Übrigens... Möchtest du eine weitere\n"
	.string "legendäre Geschichte hören?$"

MauvilleCity_PokemonCenter_1F_Text_NotWorthyOfLegend:: @ 81AEF49
	.string "Hmm...\n"
	.string "Ich bin nicht zufrieden...\p"
	.string "Ich wünschte, du würdest mir Neuig-\n"
	.string "keiten erzählen, die den Titel Legende\l"
	.string "verdienen.$"

MauvilleCity_PokemonCenter_1F_Text_IWishMorePeopleWereInterested:: @ 81AEFA5
	.string "Ich wollte, mehr Leute würden sich für\n"
	.string "meine epischen Geschichten über\l"
	.string "legendäre TRAINER interessieren.$"

MauvilleCity_PokemonCenter_1F_Text_SavedGameTitle:: @ 81AEFFC
	.string "Der speicherfreudige TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_SavedGameAction:: @ 81AF013
	.string "Hast das Spiel gespeichert?$"

MauvilleCity_PokemonCenter_1F_Text_SavedGameStory:: @ 81AF022
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat das Spiel\n"
	.string "{STR_VAR_1}-mal gespeichert!\p"
	.string "Einen vorsichtigeren TRAINER als\n"
	.string "{STR_VAR_3} wird man nicht finden!$"

MauvilleCity_PokemonCenter_1F_Text_TrendsStartedTitle:: @ 81AF0A3
	.string "Der TRAINER als Trendsetter$"

MauvilleCity_PokemonCenter_1F_Text_TrendsStartedAction:: @ 81AF0BB
	.string "Hast Trends gesetzt?$"

MauvilleCity_PokemonCenter_1F_Text_TrendsStartedStory:: @ 81AF0CA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "neue Trends gesetzt!\p"
	.string "{STR_VAR_3} setzt den Trend für alle - in\n"
	.string "der ganzen HOENN-Region!$"

MauvilleCity_PokemonCenter_1F_Text_BerriesPlantedTitle:: @ 81AF149
	.string "Der BEEREN pflanzende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_BerriesPlantedAction:: @ 81AF164
	.string "Hast BEEREN gepflanzt?$"

MauvilleCity_PokemonCenter_1F_Text_BerriesPlantedStory:: @ 81AF174
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "BEEREN gepflanzt!\p"
	.string "{STR_VAR_3} ist ein legendärer Lieb-\n"
	.string "haber von BEEREN!$"

MauvilleCity_PokemonCenter_1F_Text_BikeTradesTitle:: @ 81AF1E5
	.string "Der RAD verrückte TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_BikeTradesAction:: @ 81AF1FD
	.string "Hast RÄDER getauscht?$"

MauvilleCity_PokemonCenter_1F_Text_BikeTradesStory:: @ 81AF20A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "das RAD getauscht!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "Passion das RADfahren ist!$"

MauvilleCity_PokemonCenter_1F_Text_InterviewsTitle:: @ 81AF281
	.string "Der Interviews gebende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_InterviewsAction:: @ 81AF299
	.string "Hast Interviews gegeben?$"

MauvilleCity_PokemonCenter_1F_Text_InterviewsStory:: @ 81AF2A9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "interviewt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der überall\n"
	.string "Aufmerksamkeit erregt!$"

MauvilleCity_PokemonCenter_1F_Text_TrainerBattlesTitle:: @ 81AF32C
	.string "Der kampfliebende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_TrainerBattlesAction:: @ 81AF345
	.string "Hast oft gekämpft?$"

MauvilleCity_PokemonCenter_1F_Text_TrainerBattlesStory:: @ 81AF34D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "gekämpft!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der zu\n"
	.string "einem Kampf nicht nein sagt!$"

MauvilleCity_PokemonCenter_1F_Text_PokemonCaughtTitle:: @ 81AF3D0
	.string "Der POKéMON fangende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_PokemonCaughtAction:: @ 81AF3ED
	.string "Hast POKéMON gefangen?$"

MauvilleCity_PokemonCenter_1F_Text_PokemonCaughtStory:: @ 81AF3FC
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Fänger\n"
	.string "von POKéMON!$"

MauvilleCity_PokemonCenter_1F_Text_FishingPokemonCaughtTitle:: @ 81AF46D
	.string "Der angelnde TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_FishingPokemonCaughtAction:: @ 81AF481
	.string "Hast POKéMON mit einer ANGEL gefangen?$"

MauvilleCity_PokemonCenter_1F_Text_FishingPokemonCaughtStory:: @ 81AF49B
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON beim Angeln gefangen!\p"
	.string "{STR_VAR_3} ist ein legendärer Angel-\n"
	.string "experte!$"

MauvilleCity_PokemonCenter_1F_Text_EggsHatchedTitle:: @ 81AF511
	.string "Der EIER wärmende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_EggsHatchedAction:: @ 81AF529
	.string "Hast EIER ausgebrütet?$"

MauvilleCity_PokemonCenter_1F_Text_EggsHatchedStory:: @ 81AF536
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Es passierte {STR_VAR_1}-mal, dass der TRAINER\n"
	.string "ein POKéMON aus einem EI schlüpfen ließ!\p"
	.string "{STR_VAR_3} ist ein legendärer Pfleger\n"
	.string "von EIERN!$"

MauvilleCity_PokemonCenter_1F_Text_PokemonEvolvedTitle:: @ 81AF5A9
	.string "Der TRAINER der Entwicklungen$"

MauvilleCity_PokemonCenter_1F_Text_PokemonEvolvedAction:: @ 81AF5BD
	.string "Hast POKéMON sich entwickeln lassen?$"

MauvilleCity_PokemonCenter_1F_Text_PokemonEvolvedStory:: @ 81AF5CD
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "POKéMON zur Entwicklung gebracht!\p"
	.string "{STR_VAR_3} ist der ultimative Ent-\n"
	.string "wickler von POKéMON!$"

MauvilleCity_PokemonCenter_1F_Text_UsedPokemonCenterTitle:: @ 81AF63F
	.string "Der PKMN-CENTER liebende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_UsedPokemonCenterAction:: @ 81AF661
	.string "Gingst in ein POKéMON-CENTER?$"

MauvilleCity_PokemonCenter_1F_Text_UsedPokemonCenterStory:: @ 81AF676
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal in einem POKéMON-CENTER\l"
	.string "heilen lassen!\p"
	.string "Es gibt keinen größeren Fan der\n"
	.string "POKéMON-CENTER als {STR_VAR_3}!$"

MauvilleCity_PokemonCenter_1F_Text_RestedAtHomeTitle:: @ 81AF711
	.string "Der gastfreundliche TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_RestedAtHomeAction:: @ 81AF726
	.string "POKéMON haben sich bei dir erholt?$"

MauvilleCity_PokemonCenter_1F_Text_RestedAtHomeStory:: @ 81AF73D
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat POKéMON\n"
	.string "{STR_VAR_1}-mal bei sich zu Hause ausruhen\l"
	.string "und heilen lassen.\p"
	.string "Kein TRAINER ist so gastfreundlich\n"
	.string "wie {STR_VAR_3}!$"

MauvilleCity_PokemonCenter_1F_Text_SafariGamesTitle:: @ 81AF7BF
	.string "Der SAFARI liebende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_SafariGamesAction:: @ 81AF7D9
	.string "Bist in die SAFARI-ZONE gegangen?$"

MauvilleCity_PokemonCenter_1F_Text_SafariGamesStory:: @ 81AF7F1
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal in die\n"
	.string "SAFARI-ZONE gegangen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, dessen\n"
	.string "wilde Seite in der SAFARI-ZONE zum\l"
	.string "Vorschein kommt!$"

MauvilleCity_PokemonCenter_1F_Text_UsedCutTitle:: @ 81AF88A
	.string "Der TRAINER als ZERSCHNEIDER$"

MauvilleCity_PokemonCenter_1F_Text_UsedCutAction:: @ 81AF8A1
	.string "Hast ZERSCHNEIDER eingesetzt?$"

MauvilleCity_PokemonCenter_1F_Text_UsedCutStory:: @ 81AF8AA
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERSCHNEIDER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, etwas zu ZERSCHNEIDEN.$"

MauvilleCity_PokemonCenter_1F_Text_UsedRockSmashTitle:: @ 81AF91B
	.string "Der TRAINER als ZERTRÜMMERER$"

MauvilleCity_PokemonCenter_1F_Text_UsedRockSmashAction:: @ 81AF935
	.string "Hast Felsen ZERTRÜMMERT?$"

MauvilleCity_PokemonCenter_1F_Text_UsedRockSmashStory:: @ 81AF943
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "ZERTRÜMMERER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der keinen\n"
	.string "Felsen unbeschädigt lassen kann.$"

MauvilleCity_PokemonCenter_1F_Text_MovedBasesTitle:: @ 81AF9C8
	.string "Der Umzüge liebende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_MovedBasesAction:: @ 81AF9E0
	.string "Bist du mit der GEHEIMBASIS umgezogen?$"

MauvilleCity_PokemonCenter_1F_Text_MovedBasesStory:: @ 81AF9F6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal mit\n"
	.string "seiner GEHEIMBASIS umgezogen!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, sich ein neues Haus einzurichten.$"

MauvilleCity_PokemonCenter_1F_Text_UsedSplashTitle:: @ 81AFA79
	.string "Der PLATSCHER des TRAINERS$"

MauvilleCity_PokemonCenter_1F_Text_UsedSplashAction:: @ 81AFA92
	.string "Hast PLATSCHER eingesetzt?$"

MauvilleCity_PokemonCenter_1F_Text_UsedSplashStory:: @ 81AFA9E
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "PLATSCHER eingesetzt!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, zu PLATSCHEN.$"

MauvilleCity_PokemonCenter_1F_Text_UsedStruggleTitle:: @ 81AFB17
	.string "Der verbissene TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_UsedStruggleAction:: @ 81AFB2D
	.string "Hast VERZWEIFLER angewendet?$"

MauvilleCity_PokemonCenter_1F_Text_UsedStruggleStory:: @ 81AFB48
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat sich {STR_VAR_1}-mal\n"
	.string "auf VERZWEIFLER verlassen!\p"
	.string "{STR_VAR_3}... Ein verbissener TRAINER,\n"
	.string "der auch in der Not nicht aufgibt.$"

MauvilleCity_PokemonCenter_1F_Text_SlotJackpotsTitle:: @ 81AFBD8
	.string "Der König der EINARMIGEN BANDITEN$"

MauvilleCity_PokemonCenter_1F_Text_SlotJackpotsAction:: @ 81AFBE7
	.string "Hast den EINARMIGEN BANDITEN besiegt?$"

MauvilleCity_PokemonCenter_1F_Text_SlotJackpotsStory:: @ 81AFC04
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "am EINARMIGEN BANDITEN gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der am\n"
	.string "EINARMIGEN BANDITEN Glück hat.$"

MauvilleCity_PokemonCenter_1F_Text_RouletteWinsTitle:: @ 81AFC8A
	.string "Der König des ROULETTES$"

MauvilleCity_PokemonCenter_1F_Text_RouletteWinsAction:: @ 81AFC9D
	.string "Hast in Folge beim ROULETTE gewonnen,$"

MauvilleCity_PokemonCenter_1F_Text_RouletteWinsStory:: @ 81AFCBE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal in Folge\n"
	.string "beim ROULETTE gewonnen!\p"
	.string "{STR_VAR_3}... Ein TRAINER, dem die Kugel\n"
	.string "beim ROULETTE gehorcht.$"

MauvilleCity_PokemonCenter_1F_Text_BattleTowerChallengesTitle:: @ 81AFD44
	.string "Der Herausforderer im DUELLTURM$"

MauvilleCity_PokemonCenter_1F_Text_BattleTowerChallengesAction:: @ 81AFD60
	.string "Hast Gegner im DUELLTURM gefordert?$"

MauvilleCity_PokemonCenter_1F_Text_BattleTowerChallengesStory:: @ 81AFD80
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal Gegner\n"
	.string "im DUELLTURM herausgefordert!\p"
	.string "{STR_VAR_3}... Ein TRAINER, der im DUELL-\n"
	.string "TURM nach Perfektion strebt.$"

MauvilleCity_PokemonCenter_1F_Text_MadePokeblocksTitle:: @ 81AFE1D
	.string "Der mixende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_MadePokeblocksAction:: @ 81AFE36
	.string "Hast {POKEBLOCK} hergestellt?$"

MauvilleCity_PokemonCenter_1F_Text_MadePokeblocksStory:: @ 81AFE42
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "{POKEBLOCK} hergestellt!\p"
	.string "Niemand bedient den BEERENMIXER\n"
	.string "besser als {STR_VAR_3}.$"

MauvilleCity_PokemonCenter_1F_Text_EnteredContestsTitle:: @ 81AFEC2
	.string "Der Fan der WETTBEWERBE$"

MauvilleCity_PokemonCenter_1F_Text_EnteredContestsAction:: @ 81AFEDD
	.string "Hast an WETTBEWERBEN teilgenommen?$"

MauvilleCity_PokemonCenter_1F_Text_EnteredContestsStory:: @ 81AFEEE
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "an einem WETTBEWERB teilgenommen!\p"
	.string "{STR_VAR_3} liebt es, anderen seine\n"
	.string "POKéMON zu zeigen.$"

MauvilleCity_PokemonCenter_1F_Text_WonContestsTitle:: @ 81AFF68
	.string "Der Meister der WETTBEWERBE$"

MauvilleCity_PokemonCenter_1F_Text_WonContestsAction:: @ 81AFF7B
	.string "Hast WETTBEWERBE gewonnen?$"

MauvilleCity_PokemonCenter_1F_Text_WonContestsStory:: @ 81AFF88
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "einen WETTBEWERB gewonnen!\p"
	.string "{STR_VAR_3} ist ein unvergleichlicher\n"
	.string "Meister der WETTBEWERBE.$"

MauvilleCity_PokemonCenter_1F_Text_TimesShoppedTitle:: @ 81AFFFB
	.string "Der glückliche Einkäufer$"

MauvilleCity_PokemonCenter_1F_Text_TimesShoppedAction:: @ 81B000D
	.string "Bist einkaufen gegangen?$"

MauvilleCity_PokemonCenter_1F_Text_TimesShoppedStory:: @ 81B0015
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in einem Geschäft Items gekauft!\p"
	.string "{STR_VAR_3} ein geborener Einkäufer.$"

MauvilleCity_PokemonCenter_1F_Text_UsedItemFinderTitle:: @ 81B009D
	.string "Der TRAINER, der Items findet$"

MauvilleCity_PokemonCenter_1F_Text_UsedItemFinderAction:: @ 81B00B6
	.string "Hast den DETEKTOR eingesetzt?$"

MauvilleCity_PokemonCenter_1F_Text_UsedItemFinderStory:: @ 81B00C9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "den DETEKTOR eingesetzt!\p"
	.string "{STR_VAR_3} liebt es, den Boden nach\n"
	.string "verborgenen Items abzusuchen.$"

MauvilleCity_PokemonCenter_1F_Text_TimesRainedTitle:: @ 81B014D
	.string "Der regennasse TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_TimesRainedAction:: @ 81B0165
	.string "Wurdest nass geregnet?$"

MauvilleCity_PokemonCenter_1F_Text_TimesRainedStory:: @ 81B0173
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER wurde {STR_VAR_1}-mal\n"
	.string "nass geregnet!\p"
	.string "Das Charisma von {STR_VAR_3} zieht\n"
	.string "sogar den Regen an.$"

MauvilleCity_PokemonCenter_1F_Text_CheckedPokedexTitle:: @ 81B01E9
	.string "Der passionierte POKéDEX-Leser$"

MauvilleCity_PokemonCenter_1F_Text_CheckedPokedexAction:: @ 81B0201
	.string "Hast im POKéDEX nachgeschlagen?$"

MauvilleCity_PokemonCenter_1F_Text_CheckedPokedexStory:: @ 81B0213
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "im POKéDEX nachgeschlagen!\p"
	.string "{STR_VAR_3} liebt es, alles über\n"
	.string "POKéMON im POKéDEX nachzulesen.$"

MauvilleCity_PokemonCenter_1F_Text_ReceivedRibbonsTitle:: @ 81B0290
	.string "Der Sammler der BÄNDER$"

MauvilleCity_PokemonCenter_1F_Text_ReceivedRibbonsAction:: @ 81B02A5
	.string "Hast BÄNDER erhalten?$"

MauvilleCity_PokemonCenter_1F_Text_ReceivedRibbonsStory:: @ 81B02B6
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}\n"
	.string "BÄNDER erhalten!\p"
	.string "{STR_VAR_3} ist ein TRAINER, der es\n"
	.string "liebt, BÄNDER zu sammeln.$"

MauvilleCity_PokemonCenter_1F_Text_LedgesJumpedTitle:: @ 81B0337
	.string "Der springende TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_LedgesJumpedAction:: @ 81B0351
	.string "Bist Absätze heruntergesprungen?$"

MauvilleCity_PokemonCenter_1F_Text_LedgesJumpedStory:: @ 81B0364
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "einen Absatz hinabgesprungen!\p"
	.string "Sobald er an einen Absatz kommt, muss\n"
	.string "TRAINER {STR_VAR_3} einfach hinab-\l"
	.string "springen.$"

MauvilleCity_PokemonCenter_1F_Text_TVWatchedTitle:: @ 81B03E9
	.string "Der legendäre Fernsehzuschauer$"

MauvilleCity_PokemonCenter_1F_Text_TVWatchedAction:: @ 81B0401
	.string "Hast ferngeschaut?$"

MauvilleCity_PokemonCenter_1F_Text_TVWatchedStory:: @ 81B040C
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "Fernsehen geschaut!\p"
	.string "{STR_VAR_3} liebt es, fernzusehen.$"

MauvilleCity_PokemonCenter_1F_Text_CheckedClockTitle:: @ 81B046E
	.string "Der zeitbewusste TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_CheckedClockAction:: @ 81B0489
	.string "Hast nach der Uhrzeit gesehen?$"

MauvilleCity_PokemonCenter_1F_Text_CheckedClockStory:: @ 81B049A
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "nach der Uhrzeit geschaut!\p"
	.string "{STR_VAR_3} ist ein pünktlicher\n"
	.string "TRAINER, der sich der Zeit bewusst ist.$"

MauvilleCity_PokemonCenter_1F_Text_WonLotteryTitle:: @ 81B0523
	.string "Der Zauberer der POKéMON-LOTTERIE$"

MauvilleCity_PokemonCenter_1F_Text_WonLotteryAction:: @ 81B053E
	.string "Hast in der LOTTERIE gewonnen?$"

MauvilleCity_PokemonCenter_1F_Text_WonLotteryStory:: @ 81B0554
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in der POKéMON-LOTTERIE gewonnen!\p"
	.string "TRAINER {STR_VAR_3} hat viele Freunde,\n"
	.string "die mit ihm POKéMON tauschen.$"

MauvilleCity_PokemonCenter_1F_Text_UsedDaycareTitle:: @ 81B05D8
	.string "Der TRAINER und die PENSION$"

MauvilleCity_PokemonCenter_1F_Text_UsedDaycareAction:: @ 81B05F3
	.string "Hast POKéMON in die PENSION gebracht?$"

MauvilleCity_PokemonCenter_1F_Text_UsedDaycareStory:: @ 81B0610
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "seine POKéMON in die PENSION gegeben!\p"
	.string "{STR_VAR_3} ist ein Ellenbogentyp, der\n"
	.string "alles für die Entwicklung seiner\l"
	.string "POKéMON tut.$"

MauvilleCity_PokemonCenter_1F_Text_RodeCableCarTitle:: @ 81B06A9
	.string "Der SEILBAHN verrückte TRAINER$"

MauvilleCity_PokemonCenter_1F_Text_RodeCableCarAction:: @ 81B06C6
	.string "Bist mit der SEILBAHN gefahren?$"

MauvilleCity_PokemonCenter_1F_Text_RodeCableCarStory:: @ 81B06D9
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER ist {STR_VAR_1}-mal\n"
	.string "mit der SEILBAHN gefahren!\p"
	.string "{STR_VAR_3} ein sehr beschäftigter\n"
	.string "TRAINER, der ständig rauf und runter\l"
	.string "fährt.$"

MauvilleCity_PokemonCenter_1F_Text_HotSpringsTitle:: @ 81B0763
	.string "Der Liebhaber der Heißen Quellen$"

MauvilleCity_PokemonCenter_1F_Text_HotSpringsAction:: @ 81B0781
	.string "Hast in den Heißen Quellen gebadet?$"

MauvilleCity_PokemonCenter_1F_Text_HotSpringsStory:: @ 81B0797
	.string "Dies ist die Geschichte eines TRAINERS\n"
	.string "namens {STR_VAR_3}.\p"
	.string "Dieser TRAINER hat {STR_VAR_1}-mal\n"
	.string "in den Heißen Quellen gebadet!\p"
	.string "{STR_VAR_3} wird eine babyweiche Haut\n"
	.string "haben.$"
