Route102_Text_CalvinIntro:: @ 81B79C3
	.string "Wenn du POKéMON bei dir hast, bist du\n"
	.string "offiziell ein POKéMON-TRAINER! Daher\l"
	.string "kannst du meine Herausforderung nicht\l"
	.string "ablehnen!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Aargh, ich habe verloren... Ich\n"
	.string "hätte fleißiger trainieren sollen.$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Hör mal! Du hättest mir vorher sagen\n"
	.string "sollen, dass du so stark bist.$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Seit ich gegen dich verloren habe,\n"
	.string "trainiere ich verzweifelt meine\l"
	.string "POKéMON. Sag nicht nein zu einem Kampf!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Aaaah, ich habe schon wieder verloren...\n"
	.string "Ob ich nicht richtig trainiere?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "Wenn du stärker wirst, werde ich auch\n"
	.string "stärker.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Bist du gerade erst TRAINER geworden?\n"
	.string "Dann sind wir ja beide Anfänger.$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "Ich habe dich angesprochen, weil ich\n"
	.string "dachte, ich könnte dich besiegen.$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "Ich habe noch nicht ein Mal gewonnen...\n"
	.string "Ich hoffe, ich werde bald gewinnen!$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Haha! Unsere Augen haben sich\n"
	.string "getroffen! Ich kämpfe mit meinen\l"
	.string "KÄFER-POKéMON gegen dich!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Auaaa! Besiegt und verloren!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "Wenn du einem TRAINER in die Augen\n"
	.string "schaust, forderst du ihn heraus! Das\l"
	.string "ist die Regel!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "Mein Ziel? Stets gewinnen und der beste\n"
	.string "TRAINER aller Zeiten werden.\p"
	.string "Hilf mir bei meiner Karriere!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "Da habe ich wohl deine Karriere\n"
	.string "angekurbelt.$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "Um auf der Straße der Sieger laufen zu\n"
	.string "können, brauche ich mehr POKéMON.$"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

.include "data/maps/Route114/trainer_text.inc"

.include "data/maps/Route115/trainer_text.inc"

.include "data/maps/Route116/trainer_text.inc"

.include "data/maps/Route117/trainer_text.inc"

.include "data/maps/Route118/trainer_text.inc"

.include "data/maps/Route119/trainer_text.inc"

.include "data/maps/Route120/trainer_text.inc"

.include "data/maps/Route121/trainer_text.inc"

.include "data/maps/Route123/trainer_text.inc"

.include "data/maps/Route124/trainer_text.inc"

.include "data/maps/Route125/trainer_text.inc"

.include "data/maps/Route126/trainer_text.inc"

.include "data/maps/Route127/trainer_text.inc"

.include "data/maps/Route128/trainer_text.inc"

.include "data/maps/Route129/trainer_text.inc"

.include "data/maps/Route130/trainer_text.inc"

.include "data/maps/Route131/trainer_text.inc"

.include "data/maps/Route132/trainer_text.inc"

.include "data/maps/Route133/trainer_text.inc"

.include "data/maps/Route134/trainer_text.inc"
