.include "data/maps/Route102/trainer_text.inc"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

.include "data/maps/Route114/trainer_text.inc"

.include "data/maps/Route115/trainer_text.inc"

.include "data/maps/Route116/trainer_text.inc"

.include "data/maps/Route117/trainer_text.inc"

.include "data/maps/Route118/trainer_text.inc"

.include "data/maps/Route119/trainer_text.inc"

.include "data/maps/Route120/trainer_text.inc"

.include "data/maps/Route121/trainer_text.inc"

.include "data/maps/Route123/trainer_text.inc"

.include "data/maps/Route124/trainer_text.inc"

.include "data/maps/Route125/trainer_text.inc"

.include "data/maps/Route126/trainer_text.inc"

.include "data/maps/Route127/trainer_text.inc"

.include "data/maps/Route128/trainer_text.inc"

.include "data/maps/Route129/trainer_text.inc"

.include "data/maps/Route130/trainer_text.inc"

.include "data/maps/Route131/trainer_text.inc"

.include "data/maps/Route132/trainer_text.inc"

.include "data/maps/Route133/trainer_text.inc"

.include "data/maps/Route134/trainer_text.inc"
