Route102_Text_CalvinIntro:: @ 81B79C3
	.string "Wenn du POKéMON bei dir hast, bist du\n"
	.string "offiziell ein POKéMON-TRAINER! Daher\l"
	.string "kannst du meine Herausforderung nicht\l"
	.string "ablehnen!$"

Route102_Text_CalvinDefeated:: @ 81B7A2C
	.string "Aargh, ich habe verloren... Ich\n"
	.string "hätte fleißiger trainieren sollen.$"

Route102_Text_CalvinPostBattle:: @ 81B7A60
	.string "Hör mal! Du hättest mir vorher sagen\n"
	.string "sollen, dass du so stark bist.$"

Route102_Text_CalvinRematchIntro:: @ 81B7A9F
	.string "Seit ich gegen dich verloren habe,\n"
	.string "trainiere ich verzweifelt meine\l"
	.string "POKéMON. Sag nicht nein zu einem Kampf!$"

Route102_Text_CalvinRematchDefeated:: @ 81B7AFD
	.string "Aaaah, ich habe schon wieder verloren...\n"
	.string "Ob ich nicht richtig trainiere?$"

Route102_Text_CalvinRematchPostBattle:: @ 81B7B2F
	.string "Wenn du stärker wirst, werde ich auch\n"
	.string "stärker.$"

Route102_Text_AllenIntro:: @ 81B7B68
	.string "Bist du gerade erst TRAINER geworden?\n"
	.string "Dann sind wir ja beide Anfänger.$"

Route102_Text_AllenDefeated:: @ 81B7B9D
	.string "Ich habe dich angesprochen, weil ich\n"
	.string "dachte, ich könnte dich besiegen.$"

Route102_Text_AllenPostBattle:: @ 81B7BD0
	.string "Ich habe noch nicht ein Mal gewonnen...\n"
	.string "Ich hoffe, ich werde bald gewinnen!$"

Route102_Text_RickIntro:: @ 81B7C05
	.string "Haha! Unsere Augen haben sich\n"
	.string "getroffen! Ich kämpfe mit meinen\l"
	.string "KÄFER-POKéMON gegen dich!$"

Route102_Text_RickDefeated:: @ 81B7C40
	.string "Auaaa! Besiegt und verloren!$"

Route102_Text_RickPostBattle:: @ 81B7C52
	.string "Wenn du einem TRAINER in die Augen\n"
	.string "schaust, forderst du ihn heraus! Das\l"
	.string "ist die Regel!$"

Route102_Text_TianaIntro:: @ 81B7C97
	.string "Mein Ziel? Stets gewinnen und der beste\n"
	.string "TRAINER aller Zeiten werden.\p"
	.string "Hilf mir bei meiner Karriere!$"

Route102_Text_TianaDefeated:: @ 81B7CEC
	.string "Da habe ich wohl deine Karriere\n"
	.string "angekurbelt.$"

Route102_Text_TianaPostBattle:: @ 81B7D11
	.string "Um auf der Straße der Sieger laufen zu\n"
	.string "können, brauche ich mehr POKéMON.$"

.include "data/maps/Route103/trainer_text.inc"

.include "data/maps/Route104/trainer_text.inc"

.include "data/maps/Route105/trainer_text.inc"

.include "data/maps/Route106/trainer_text.inc"

.include "data/maps/Route107/trainer_text.inc"

.include "data/maps/Route108/trainer_text.inc"

.include "data/maps/Route109/trainer_text.inc"

.include "data/maps/Route111/trainer_text.inc"

.include "data/maps/Route112/trainer_text.inc"

.include "data/maps/Route113/trainer_text.inc"

.include "data/maps/Route114/trainer_text.inc"

.include "data/maps/Route115/trainer_text.inc"

.include "data/maps/Route116/trainer_text.inc"

.include "data/maps/Route117/trainer_text.inc"

.include "data/maps/Route118/trainer_text.inc"

.include "data/maps/Route119/trainer_text.inc"

.include "data/maps/Route120/trainer_text.inc"

.include "data/maps/Route121/trainer_text.inc"

.include "data/maps/Route123/trainer_text.inc"

.include "data/maps/Route124/trainer_text.inc"

.include "data/maps/Route125/trainer_text.inc"

.include "data/maps/Route126/trainer_text.inc"

.include "data/maps/Route127/trainer_text.inc"

.include "data/maps/Route128/trainer_text.inc"

Route129_Text_ChaseIntro:: @ 81C2161
	.string "Das ist mein erster Triathlon.\n"
	.string "Ich bin schon ganz hibbelig und nervös!$"

Route129_Text_ChaseDefeat:: @ 81C2198
	.string "Wooooaaaaaargh! Ich habe es\n"
	.string "nicht geschafft, zu gewinnen.$"

Route129_Text_ChasePostBattle:: @ 81C21B4
	.string "Wenn ich so hibbelig bin, kann ich nicht\n"
	.string "alles geben.$"

Route129_Text_AllisonIntro:: @ 81C21ED
	.string "Ich bin mitten in einem Triathlon, aber\n"
	.string "warum sollten wir nicht kämpfen?$"

Route129_Text_AllisonDefeat:: @ 81C222F
	.string "Ich war sicher, ich würde gewinnen!$"

Route129_Text_AllisonPostBattle:: @ 81C2243
	.string "Weißt du, was das Beste am Triathlon\n"
	.string "ist?\p"
	.string "Man kommt an seine eigenen Grenzen und\n"
	.string "zeigt seine Ausdauer gegenüber Mutter\l"
	.string "Natur.$"

Route129_Text_ReedIntro:: @ 81C22C8
	.string "Sag: Hey, hey!\n"
	.string "Los geht's!$"

Route129_Text_ReedDefeat:: @ 81C22EC
	.string "Geschlagen, ich wurde geschlagen.\n"
	.string "Das war's. Fertig!$"

Route129_Text_ReedPostBattle:: @ 81C230F
	.string "Hier gibt es für Verlierer nichts zu tun.\n"
	.string "Zeit für mich, nach Hause zu gehen.$"

Route129_Text_TishaIntro:: @ 81C2349
	.string "Warum so eilig?\n"
	.string "Immer mit der Ruhe...$"

Route129_Text_TishaDefeat:: @ 81C2378
	.string "Oh, meine Güte. Dabei wollte ich\n"
	.string "nur ein bisschen entspannen.$"

Route129_Text_TishaPostBattle:: @ 81C23A3
	.string "Hasst du es nicht auch, Fehler zu\n"
	.string "machen, nur weil du es eilig hast?\p"
	.string "Daher gehe ich alles langsam an.$"

Route130_Text_RodneyIntro:: @ 81C2401
	.string "Was für eine Überraschung! Ich habe im\n"
	.string "Meer keinen TRAINER erwartet.\p"
	.string "Ich denke, wir sollten kämpfen.$"

Route130_Text_RodneyDefeat:: @ 81C245D
	.string "Dieses Kind ist unglaublich stark.$"

Route130_Text_RodneyPostBattle:: @ 81C2479
	.string "Deine Augen haben den Ausdruck eines\n"
	.string "Menschen, der harte Herausforderungen\l"
	.string "siegreich gemeistert hat. Das steht dir.$"

Route130_Text_KatieIntro:: @ 81C24DC
	.string "Im tiefen, blauen Meer fand mein\n"
	.string "schwermütiges Herz Trost in den\l"
	.string "wogenden Wellen.$"

Route130_Text_KatieDefeat:: @ 81C2525
	.string "Wie das weite Meer umspannt auch die \n"
	.string "Welt der POKéMON Weiten jenseits\l"
	.string "unseres Erfahrungshorizontes.$"

Route130_Text_KatiePostBattle:: @ 81C256E
	.string "Die Kinder dieser Welt träumen davon,\n"
	.string "eines Tages der POKéMON CHAMP zu\l"
	.string "werden.$"

Route131_Text_RichardIntro:: @ 81C25B3
	.string "Das Meer wimmelt von POKéMON.\n"
	.string "Es ist nicht leicht, hier zu schwimmen.$"

Route131_Text_RichardDefeat:: @ 81C25F8
	.string "POKéMON, die von TRAINERN aufgezogen\n"
	.string "wurden, sind sehr stark...$"

Route131_Text_RichardPostBattle:: @ 81C262A
	.string "Keuch... Schnauf... Ich bin K.O.\p"
	.string "Der Hinweg ist leicht. Der Heimweg umso\n"
	.string "härter.\p"
	.string "Ob ich genug Energie für die Heimreise\n"
	.string "habe?$"

Route131_Text_HermanIntro:: @ 81C26B9
	.string "Die See... Die See... Die See...\n"
	.string "Die See... So weit ich mit den Augen seh.\l"
	.string "Das Meer macht mich krank und müde.$"

Route131_Text_HermanDefeat:: @ 81C271F
	.string "Bah!$"

Route131_Text_HermanPostBattle:: @ 81C2726
	.string "Gelangweilt bin ich von der See, aber\n"
	.string "ich muss schwimmen.\p"
	.string "Ich bin der geborene Schwimmer!\n"
	.string "Das bin ich.$"

Route131_Text_SusieIntro:: @ 81C2774
	.string "Hey, Engelchen, warte!\n"
	.string "Wir sollten kämpfen, du und ich!$"

Route131_Text_SusieDefeat:: @ 81C27A4
	.string "Du bist stärker, als du aussiehst.$"

Route131_Text_SusiePostBattle:: @ 81C27CF
	.string "Hast du einen Typen gesehen, der heult,\n"
	.string "weil das Meer ihn langweilt?\p"
	.string "Das ist nur Gerede.\n"
	.string "Er liebt das Meer aus tiefstem Herzen!$"

Route131_Text_KaraIntro:: @ 81C284A
	.string "Warum lieben Männer Bikinis nur so?\p"
	.string "Sie starren alle meinen Bikini an.$"

Route131_Text_KaraDefeat:: @ 81C2883
	.string "Ich bin erledigt.$"

Route131_Text_KaraPostBattle:: @ 81C2898
	.string "Vielleicht bewundern die Männer nicht\n"
	.string "meinen Bikini, sondern mich!$"

Route131_Text_ReliIntro:: @ 81C28E2
	.string "UNA: Wir nehmen es als Geschwister mit\n"
	.string "dir auf!$"

Route131_Text_ReliDefeat:: @ 81C2918
	.string "UNA: Wir konnten nicht gewinnen. Trotz\n"
	.string "unserer Zusammenarbeit.$"

Route131_Text_ReliPostBattle:: @ 81C2950
	.string "UNA: Die Menschen in FLOSSBRUNN\n"
	.string "leben von Geburt an mit POKéMON\l"
	.string "und dem Meer zusammen.$"

Route131_Text_ReliNotEnoughMons:: @ 81C29B2
	.string "UNA: Du hast keine zwei POKéMON?\n"
	.string "Dann werden wir keinen Spaß haben!$"

Route131_Text_IanIntro:: @ 81C29F3
	.string "TOBI: Ich gebe zusammen mit meiner\n"
	.string "Schwester mein Bestes!$"

Route131_Text_IanDefeat:: @ 81C2A20
	.string "TOBI: Meine Schwester und ich gaben\n"
	.string "unser Bestes und haben doch verloren.$"

Route131_Text_IanPostBattle:: @ 81C2A5D
	.string "TOBI: Du weißt, dass FLOSSBRUNN\n"
	.string "eine schwimmende Stadt ist?\p"
	.string "Wo immer auch das Meer ist, ist es Teil\n"
	.string "von FLOSSBRUNN!$"

Route131_Text_IanNotEnoughMons:: @ 81C2ACA
	.string "TOBI: Wenn du zwei POKéMON mitbringst,\n"
	.string "werden wir es mit dir aufnehmen!$"

Route132_Text_GilbertIntro:: @ 81C2AFB
	.string "Als Kind war ich andauernd erkältet,\n"
	.string "aber seit ich mit dem Schwimmen\l"
	.string "angefangen habe, bin ich fit.$"

Route132_Text_GilbertDefeat:: @ 81C2B5B
	.string "Ich bitte um mehr Kraft...$"

Route132_Text_GilbertPostBattle:: @ 81C2B71
	.string "TRAINER reisen über Berg und Tal\n"
	.string "und müssen deshalb auch fit sein.$"

Route132_Text_DanaIntro:: @ 81C2BB5
	.string "Ich versuche, mich von den Strömungen\n"
	.string "fern zu halten.$"

Route132_Text_DanaDefeat:: @ 81C2BEA
	.string "Oh, bitte, nein!$"

Route132_Text_DanaPostBattle:: @ 81C2BFA
	.string "Ich wurde weggespült. Ich habe voll-\n"
	.string "ständig die Orientierung verloren.$"

Route132_Text_RonaldIntro:: @ 81C2C32
	.string "Sieg oder Niederlage. Das weiß man\n"
	.string "erst, wenn man es ausprobiert hat.$"

Route132_Text_RonaldDefeat:: @ 81C2C60
	.string "Aaah!\n"
	.string "Ich versinke in einer Niederlage.$"

Route132_Text_RonaldPostBattle:: @ 81C2C78
	.string "Ich kämpfe nie, wenn ich weiß, dass ich\n"
	.string "gewinne. Ich liebe den Kampf an der\l"
	.string "Grenze zwischen Sieg und Niederlage.$"

Route132_Text_KiyoIntro:: @ 81C2CD9
	.string "Ich widme mich 24 Stunden am Tag den\n"
	.string "POKéMON. Ob du mich besiegen kannst?$"

Route132_Text_KiyoDefeat:: @ 81C2D1F
	.string "Ich habe verloren.\n"
	.string "Ich gestehe die Niederlage ein.$"

Route132_Text_KiyoPostBattle:: @ 81C2D3E
	.string "Aargh...\n"
	.string "Du bist ein POKéMON-Fanatiker, oder?\p"
	.string "Du widmest dich den POKéMON\n"
	.string "24 Stunden am Tag, oder?$"

Route133_Text_FranklinIntro:: @ 81C2DA5
	.string "Hat die Strömung dich hergebracht? Das\n"
	.string "nenne ich Schicksal. Lass uns kämpfen!$"

Route133_Text_FranklinDefeat:: @ 81C2DF4
	.string "Stark!\n"
	.string "Viel zu stark!$"

Route133_Text_FranklinPostBattle:: @ 81C2E09
	.string "Soll ich das jetzt Glück nennen, dass ich\n"
	.string "auf einen so starken TRAINER wie dich\l"
	.string "gestoßen bin? Ich bin verflucht...$"

Route133_Text_DebraIntro:: @ 81C2E61
	.string "Ich führte ein Leben in Kummer und\n"
	.string "Elend. Es hat mich hierher verschlagen\l"
	.string "und hier bin ich gestrandet...$"

Route133_Text_DebraDefeat:: @ 81C2EBD
	.string "Eine weitere Niederlage...$"

Route133_Text_DebraPostBattle:: @ 81C2ECD
	.string "Treibend auf dem Meer des Lebens...\n"
	.string "Ich habe dazu keine Lust mehr!$"

Route133_Text_LindaIntro:: @ 81C2EF7
	.string "Willkommen!\n"
	.string "Ich habe dich schon erwartet!$"

Route133_Text_LindaDefeat:: @ 81C2F19
	.string "Nein! Bitte!$"

Route133_Text_LindaPostBattle:: @ 81C2F25
	.string "Ein Kind als starker TRAINER...\n"
	.string "Boh, ist das äääärgerlich!$"

Route133_Text_WarrenIntro:: @ 81C2F53
	.string "Ich möchte, wie jeder andere auch,\n"
	.string "gewinnen, aber ich ziehe meine POKéMON\l"
	.string "nicht auf wie jeder andere auch...$"

Route133_Text_WarrenDefeat:: @ 81C2FA3
	.string "Mist!\n"
	.string "Meine Art und Weise reicht nicht aus!$"

Route133_Text_WarrenPostBattle:: @ 81C2FC7
	.string "Es macht mehr Spaß, die Dinge auf meine\n"
	.string "Art zu erledigen, als auf die Art aller\l"
	.string "anderen. Das ist doch klar!$"

Route133_Text_BeckIntro:: @ 81C302D
	.string "Ich bin mit meinen VOGEL-POKéMON\n"
	.string "hierher gekommen.$"

Route133_Text_BeckDefeat:: @ 81C305F
	.string "Du...\n"
	.string "Du bist total cool!$"

Route133_Text_BeckPostBattle:: @ 81C307E
	.string "Ich könnte nach BAUMHAUSEN CITY zu-\n"
	.string "rückkehren, aber ich mag Orte wie diese.$"

Route134_Text_JackIntro:: @ 81C30C6
	.string "Selbst POKéMON, die schwimmen können,\n"
	.string "werden oft von der Strömung erfasst.$"

Route134_Text_JackDefeat:: @ 81C3110
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:: @ 81C311A
	.string "Ich glaube, POKéMON mögen diese\n"
	.string "schnellen Strömungen hier sehr.$"

Route134_Text_LaurelIntro:: @ 81C315E
	.string "Meine LIEBISKUS möchten ihren Spaß\n"
	.string "bei einem Kampf haben. Machst du mit?$"

Route134_Text_LaurelDefeat:: @ 81C3198
	.string "Huupsie!$"

Route134_Text_LaurelPostBattle:: @ 81C31A0
	.string "Es gibt da einen Sammler, der sich für \n"
	.string "SCHUPPEN von LIEBISKUS interessiert.$"

Route134_Text_AlexIntro:: @ 81C31D7
	.string "Okeydokey! Genug gerastet, Jungs!\n"
	.string "Zeit für ein Kämpfchen!$"

Route134_Text_AlexDefeat:: @ 81C3213
	.string "Wir wurden wieder fertig gemacht.$"

Route134_Text_AlexPostBattle:: @ 81C3229
	.string "Mein VOGEL-POKéMON wird nach einem\n"
	.string "langen Flug schnell müde...$"

Route134_Text_HitoshiIntro:: @ 81C3262
	.string "Du bist ein POKéMON-TRAINER.\n"
	.string "Worte sind da überflüssig. Wir kämpfen.$"

Route134_Text_HitoshiDefeat:: @ 81C329E
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:: @ 81C32D6
	.string "Ich habe dich herausgefordert und\n"
	.string "doch verloren. Ich bin tief beschämt.$"

Route134_Text_AaronIntro:: @ 81C3319
	.string "Die wilde Strömung in dieser Region hilft\n"
	.string "uns dabei, stärker denn je zu werden.$"

Route134_Text_AaronDefeat:: @ 81C335C
	.string "Ich gebe meine Niederlage zu.$"

Route134_Text_AaronPostBattle:: @ 81C336E
	.string "Wir werden für weiteres Training nach\n"
	.string "METEORFÄLLE zurückkehren.\p"
	.string "Wenn du magst, komm doch auch mit.\n"
	.string "Das wird auch dich stärker machen!$"
