MtPyre_6F_Text_ValerieIntro:: @ 81969FE
	.string "When I'm here...\n"
	.string "A curious power flows into me...$"

MtPyre_6F_Text_ValerieDefeat:: @ 8196A30
	.string "The power is ebbing away...$"

MtPyre_6F_Text_ValeriePostBattle:: @ 8196A4C
	.string "Perhaps the power is from the spirits\n"
	.string "of POKéMON in fitful sleep here...$"

MtPyre_6F_Text_ValerieRematchIntro:: @ 8196A95
	.string "Behind you...\n"
	.string "What is it...$"

MtPyre_6F_Text_ValerieRematchDefeat:: @ 8196AB1
	.string "Something faded away...$"

MtPyre_6F_Text_ValeriePostRematch:: @ 8196AC9
	.string "The POKéMON at rest here...\n"
	.string "Sometimes, they play...$"
