Route109_SeashoreHouse_Text_SeashoreHouseIntro:: @ 819B4D9
	.string "I'm the owner of the SEASHORE HOUSE.\n"
	.string "But you can call me MR. SEA!\p"
	.string "What I love above all is to see hot\n"
	.string "POKéMON battles.\p"
	.string "Let me see that your heart burns hot!\p"
	.string "If you can defeat all the TRAINERS\n"
	.string "here, I'll reward your efforts.$"

Route109_SeashoreHouse_Text_ShowMeSomeHotMatches:: @ 819B5B9
	.string "Show me some hot matches!\p"
	.string "I run this SEASHORE HOUSE just for\n"
	.string "that reason alone!$"

Route109_SeashoreHouse_Text_TakeTheseSodaPopBottles:: @ 819B609
	.string "You're scorching hot!\n"
	.string "Those battles blazed!\l"
	.string "I'm more than just satisfied!\p"
	.string "As thanks for showing me your hot\n"
	.string "streak, I want you to take these.\p"
	.string "It's half a dozen bottles of SODA POP!$"

Route109_SeashoreHouse_Text_BagFull:: @ 819B6BE
	.string "Oh, but hey, your BAG's jammed full.\n"
	.string "I'll hang on to these for you.$"

Route109_SeashoreHouse_Text_WantToBuySodaPop:: @ 819B702
	.string "Want to buy some SODA POP?\n"
	.string "POKéMON love it!\p"
	.string "Just ¥300 a bottle!\n"
	.string "Buy some!$"

Route109_SeashoreHouse_Text_HereYouGo:: @ 819B74C
	.string "Here you go!$"

Route109_SeashoreHouse_Text_NotEnoughMoney:: @ 819B759
	.string "You don't have the money.$"

Route109_SeashoreHouse_Text_ThatsTooBad:: @ 819B773
	.string "No?\n"
	.string "That's too bad.$"

Route109_SeashoreHouse_Text_UnusedSodaPopSalesPrompt: @ 819B787
	.string "SODA POP! The POKéMON favorite!\n"
	.string "Just ¥300 a bottle! Want one?$"

Route109_SeashoreHouse_Text_UnusedSodaPopSalesSuccess: @ 819B7C5
	.string "Here you go!$"

Route109_SeashoreHouse_Text_UnusedSodaPopSalesNotEnoughMoney: @ 819B7D2
	.string "Oh, dear!\n"
	.string "You don't have enough money.$"

Route109_SeashoreHouse_Text_UnusedSodaPopSalesDeclined: @ 819B7F9
	.string "That's too bad.$"

Route109_SeashoreHouse_Text_DwayneIntro:: @ 819B809
	.string "If you're looking for a battle on the\n"
	.string "high seas, you'll find no hotter \l"
	.string "TRAINER than me, matey!$"

Route109_SeashoreHouse_Text_DwayneDefeated:: @ 819B869
	.string "That was a hot battle!\n"
	.string "I can accept that loss, matey!$"

Route109_SeashoreHouse_Text_DwaynePostBattle:: @ 819B89F
	.string "Whenever I'm in SLATEPORT, I enjoy\n"
	.string "hot battles and ice-cold SODA POP!$"

Route109_SeashoreHouse_Text_JohannaIntro:: @ 819B8E5
	.string "Boring battles aren't worth the effort.\p"
	.string "Fiery hot battles are what toughen up\n"
	.string "TRAINERS and POKéMON!$"

Route109_SeashoreHouse_Text_JohannaDefeated:: @ 819B949
	.string "That's hot!$"

Route109_SeashoreHouse_Text_JohannaPostBattle:: @ 819B955
	.string "Whew, I'm all thirsty.\n"
	.string "Maybe I'll have a SODA POP.$"

Route109_SeashoreHouse_Text_SimonIntro:: @ 819B988
	.string "I'm going to show you how great my\n"
	.string "POKéMON are, but don't cry!$"

Route109_SeashoreHouse_Text_SimonDefeated:: @ 819B9C7
	.string "...I lost, but I won't cry...$"

Route109_SeashoreHouse_Text_SimonPostBattle:: @ 819B9E5
	.string "If one of my POKéMON knew the move\n"
	.string "for carrying me across water on its\l"
	.string "back, I could get rid of this inner tube.$"
