Route114_Text_AllMyMonDoesIsRoarTakeThis:: @ 8170154
	.string "Alles was mein POKéMON von sich gibt, ist\n"
	.string "BRÜLLER... Niemand wagt sich nah heran...\p"
	.string "Seufz... Wenn du magst, dann nimm mir\n"
	.string "diese Bürde... äh, diese TM ab...$"

Route114_Text_ExplainRoar:: @ 81701C5
	.string "TM05 enthält BRÜLLER.\n"
	.string "Ein BRÜLLER schlägt POKéMON in\l"
	.string "die Flucht.$"

Route114_Text_Poochyena:: @ 81701F9
	.string "Bow! Bowwow!$"

Route114_Text_MeteorFallsSign:: @ 8170206
	.string "METEORFÄLLE\n"
	.string "HIER ENTLANG NACH METAROST CITY$"

Route114_Text_FossilManiacsHouseSign:: @ 817022E
	.string "FOSSILMANIAC\n"
	.string "“Fossilien gesucht!”$"

Route114_Text_LanettesHouse:: @ 8170263
	.string "LANETTES HAUS$"
