Route114_Text_LennyIntro:: @ 81BC05B
	.string "Hollerididudljö!\p"
	.string "... ...\p"
	.string "Du musst jetzt mit “Hollerididudljö!”\n"
	.string "antworten, da es hier kein Echo gibt!$"

Route114_Text_LennyDefeat:: @ 81BC0B5
	.string "Hollerididudljö!$"

Route114_Text_LennyPostBattle:: @ 81BC0C3
	.string "Als ich noch ein kleiner Lausbub war,\n"
	.string "habe ich immer gedacht, da wäre jemand,\l"
	.string "der mich ärgern will und \l"
	.string "“Hollerididudljö” antwortet.$"

Route114_Text_LucasIntro:: @ 81BC125
	.string "Ohne eine gute Ausrüstung solltest du\n"
	.string "dich nicht in die Berge wagen.$"

Route114_Text_LucasDefeat:: @ 81BC163
	.string "Die Berge sind unerbittlich...$"

Route114_Text_LucasPostBattle:: @ 81BC184
	.string "Im Winter sind Berge lebensgefährlich,\n"
	.string "wegen der Blizzards und Lawinen.$"

Route114_Text_ShaneIntro:: @ 81BC1C8
	.string "Campen macht Spaß! Du kannst angeln,\n"
	.string "Würstchen braten und andere mit\l"
	.string "Spukgeschichten zu Tode erschrecken!\p"
	.string "Aber das Beste sind die POKéMON-\n"
	.string "Kämpfe!$"

Route114_Text_ShaneDefeat:: @ 81BC23F
	.string "Das war etwas zu schwer für mich!$"

Route114_Text_ShanePostBattle:: @ 81BC24F
	.string "Ich finde es großartig, dass ich mit\n"
	.string "meinen POKéMON campen gehen kann.$"

Route114_Text_NancyIntro:: @ 81BC289
	.string "Nach dem Essen muss ich Sport treiben.\n"
	.string "Also lass uns kämpfen.$"

Route114_Text_NancyDefeat:: @ 81BC2BE
	.string "Oh, nein!$"

Route114_Text_NancyPostBattle:: @ 81BC2C6
	.string "Ich hatte so ein leckeres Essen. Des-\n"
	.string "halb bin ich jetzt pappsatt und müde.$"

Route114_Text_SteveIntro:: @ 81BC2F5
	.string "Hufhufhufhufhufhuf...\n"
	.string "Komm, trete gegen mein POKéMON an.$"

Route114_Text_SteveDefeat:: @ 81BC327
	.string "Mei... Mein POKéMON... hiiii...$"

Route114_Text_StevePostBattle:: @ 81BC337
	.string "Einen großen Körper, der plump und hart\n"
	.string "ist, riesige Hörner und scharfe Fänge...\p"
	.string "Hufhufhufhuf...\n"
	.string "So ein POKéMON hätte ich gerne...$"

Route114_Text_SteveRematchIntro:: @ 81BC3B3
	.string "Hufhufhufhufhuf...\n"
	.string "Komm, mein POKéMON ist bereit.$"

Route114_Text_SteveRematchDefeat:: @ 81BC3E0
	.string "Ich bin so froh, dass ich deine POKéMON\n"
	.string "sehen durfte...$"

Route114_Text_StevePostRematch:: @ 81BC40F
	.string "Hufhufhufhufhuf...\p"
	.string "Wenn ich POKéMON kämpfen sehe, fange\n"
	.string "ich an zu zittern und zu schaudern...$"

Route114_Text_BernieIntro:: @ 81BC45A
	.string "Wenn du ein Lagerfeuer entzündest,\n"
	.string "muss immer Wasser in der Nähe sein.$"

Route114_Text_BernieDefeat:: @ 81BC499
	.string "Gut, du hast mein Feuer gelöscht.$"

Route114_Text_BerniePostBattle:: @ 81BC4B5
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_BernieRematchIntro:: @ 81BC525
	.string "Hast du gelernt, dass man immer Wasser\n"
	.string "neben einem Lagerfeuer stehen hat?$"

Route114_Text_BernieRematchDefeat:: @ 81BC559
	.string "Ich wurde schon gelöscht, bevor ich\n"
	.string "überhaupt zur Flamme ansetzen konnte.$"

Route114_Text_BerniePostRematch:: @ 81BC58C
	.string "Du musst im Wald mit allen Arten von\n"
	.string "Feuer wirklich sehr vorsichtig sein.\p"
	.string "Unterschätze nie die Gefahr des\n"
	.string "Feuers!$"

Route114_Text_ClaudeIntro:: @ 81BC5FC
	.string "Wenn wir angeln wären, hättest du nicht\n"
	.string "den Hauch einer Chance gegen mich.\l"
	.string "Also, dann zeig mal deine POKéMON.$"

Route114_Text_ClaudeDefeat:: @ 81BC653
	.string "Wären wir Angeln, hätte ich gewonnen!$"

Route114_Text_ClaudePostBattle:: @ 81BC679
	.string "Ich werde mein Glück bei METEORFÄLLE\n"
	.string "versuchen und ein dickes Ding an Land\l"
	.string "ziehen.\p"
	.string "Da muss es etwas geben, das weiß ich\n"
	.string "genau!$"

Route114_Text_NolanIntro:: @ 81BC6EC
	.string "Ich liebe das Angeln. Aber ich liebe auch\n"
	.string "das Kämpfen!\p"
	.string "Wenn mich jemand herausfordern will, ich\n"
	.string "bin bereit. Auch wenn ich angle.$"

Route114_Text_NolanDefeat:: @ 81BC750
	.string "Ich liebe Kämpfe, aber das heißt nicht,\n"
	.string "dass ich gut darin bin...$"

Route114_Text_NolanPostBattle:: @ 81BC78A
	.string "Dieses Mal werde ich trainieren!\p"
	.string "Das denke ich jedes Mal und dann\n"
	.string "kann ich mich doch nicht von meiner\l"
	.string "Angel und meinen POKéMON trennen.$"

Route114_Text_TyraIntro:: @ 81BC7E3
	.string "TYRA: Natürlich. Ich bin in der\n"
	.string "richtigen Stimmung. Ich werde dir\l"
	.string "etwas über POKéMON beibringen.$"

Route114_Text_TyraDefeat:: @ 81BC834
	.string "TYRA: Was für ein atemberaubender\n"
	.string "Kampfstil.$"

Route114_Text_TyraPostBattle:: @ 81BC858
	.string "TYRA: Ich bringe meiner Juniorin IVY\n"
	.string "etwas über POKéMON bei.$"

Route114_Text_TyraNotEnoughMons:: @ 81BC88A
	.string "TYRA: Kicher...\n"
	.string "Wenn du mit uns kämpfen willst, reicht\l"
	.string "ein POKéMON nicht aus.$"

Route114_Text_IvyIntro:: @ 81BC8D8
	.string "IVY: Wer hat dir das alles über POKéMON\n"
	.string "beigebracht?$"

Route114_Text_IvyDefeat:: @ 81BC8FB
	.string "IVY: Was für ein unglaublicher Kampfstil!$"

Route114_Text_IvyPostBattle:: @ 81BC91E
	.string "IVY: Ich habe angefangen, POKéMON zu\n"
	.string "trainieren, weil TYRA, meine Mentorin,\l"
	.string "es mir beigebracht hat!$"

Route114_Text_IvyNotEnoughMons:: @ 81BC96A
	.string "IVY: Hast du nur ein POKéMON? Ich\n"
	.string "glaube, das fühlt sich einsam!$"
