Route121_Text_OkayMoveOutToMtPyre:: @ 8171C8F
	.string "Okay!\n"
	.string "We're to move out to MT. PYRE!$"

Route121_Text_AheadLoomsMtPyre:: @ 8171CB4
	.string "Ahead looms MT. PYRE...\p"
	.string "It is a natural monument to the spirits \n"
	.string "of departed POKéMON...$"

Route121_Text_MtPyrePierSign:: @ 8171D0C
	.string "MT. PYRE PIER\p"
	.string "...The sign is old and worn out.\n"
	.string "The words are barely legible...$"

Route121_Text_SafariZoneSign:: @ 8171D5B
	.string "“Filled with rare POKéMON!”\n"
	.string "SAFARI ZONE$"
