Route121_Text_VanessaIntro:: @ 81BF96E
	.string "Will you play with my delightfully\n"
	.string "pretty POKéMON?$"

Route121_Text_VanessaDefeat:: @ 81BF9A1
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle:: @ 81BF9BA
	.string "I'm going to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON should have no problem\n"
	.string "sweeping the MASTER CLASS.$"

Route121_Text_WalterIntro:: @ 81BFA1B
	.string "With my POKéMON, I have traveled the\n"
	.string "world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat:: @ 81BFA8C
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle:: @ 81BFA9D
	.string "I would like to circle the globe once\n"
	.string "again with my POKéMON.$"

Route121_Text_WalterRematchIntro:: @ 81BFADA
	.string "With my POKéMON, I have traveled the\n"
	.string "world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat:: @ 81BFB4B
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch:: @ 81BFB5C
	.string "Your POKéMON and you...\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro:: @ 81BFBB4
	.string "There are powers beyond our\n"
	.string "understanding in the world...$"

Route121_Text_TammyDefeat:: @ 81BFBEE
	.string "I have lost...$"

Route121_Text_TammyPostBattle:: @ 81BFBFD
	.string "MT. PYRE...\n"
	.string "There is a mysterious power\l"
	.string "at work there...$"

Route121_Text_KateIntro:: @ 81BFC36
	.string "KATE: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat:: @ 81BFC7A
	.string "KATE: I blew it in front of my junior\n"
	.string "student partner...$"

Route121_Text_KatePostBattle:: @ 81BFCB3
	.string "KATE: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them...$"

Route121_Text_KateNotEnoughMons:: @ 81BFD08
	.string "KATE: If you've only got one POKéMON,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:: @ 81BFD60
	.string "JOY: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat:: @ 81BFDA3
	.string "JOY: Please forgive me, KATE!$"

Route121_Text_JoyPostBattle:: @ 81BFDC1
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons:: @ 81BFE0D
	.string "JOY: You need at least two POKéMON\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro:: @ 81BFE51
	.string "Stop! Have a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:: @ 81BFE80
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle:: @ 81BFEAE
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRematchIntro:: @ 81BFEDE
	.string "My precious POKéMON grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat:: @ 81BFF0A
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch:: @ 81BFF3A
	.string "Maybe I'll go catch more POKéMON at\n"
	.string "the SAFARI.$"
