Route132_Text_GilbertIntro:: @ 81C2AFB
	.string "Als Kind war ich andauernd erkältet,\n"
	.string "aber seit ich mit dem Schwimmen\l"
	.string "angefangen habe, bin ich fit.$"

Route132_Text_GilbertDefeat:: @ 81C2B5B
	.string "Ich bitte um mehr Kraft...$"

Route132_Text_GilbertPostBattle:: @ 81C2B71
	.string "TRAINER reisen über Berg und Tal\n"
	.string "und müssen deshalb auch fit sein.$"

Route132_Text_DanaIntro:: @ 81C2BB5
	.string "Ich versuche, mich von den Strömungen\n"
	.string "fern zu halten.$"

Route132_Text_DanaDefeat:: @ 81C2BEA
	.string "Oh, bitte, nein!$"

Route132_Text_DanaPostBattle:: @ 81C2BFA
	.string "Ich wurde weggespült. Ich habe voll-\n"
	.string "ständig die Orientierung verloren.$"

Route132_Text_RonaldIntro:: @ 81C2C32
	.string "Sieg oder Niederlage. Das weiß man\n"
	.string "erst, wenn man es ausprobiert hat.$"

Route132_Text_RonaldDefeat:: @ 81C2C60
	.string "Aaah!\n"
	.string "Ich versinke in einer Niederlage.$"

Route132_Text_RonaldPostBattle:: @ 81C2C78
	.string "Ich kämpfe nie, wenn ich weiß, dass ich\n"
	.string "gewinne. Ich liebe den Kampf an der\l"
	.string "Grenze zwischen Sieg und Niederlage.$"

Route132_Text_KiyoIntro:: @ 81C2CD9
	.string "Ich widme mich 24 Stunden am Tag den\n"
	.string "POKéMON. Ob du mich besiegen kannst?$"

Route132_Text_KiyoDefeat:: @ 81C2D1F
	.string "Ich habe verloren.\n"
	.string "Ich gestehe die Niederlage ein.$"

Route132_Text_KiyoPostBattle:: @ 81C2D3E
	.string "Aargh...\n"
	.string "Du bist ein POKéMON-Fanatiker, oder?\p"
	.string "Du widmest dich den POKéMON\n"
	.string "24 Stunden am Tag, oder?$"
