MossdeepCity_MysteryEventsHouse_Text_OldManGreeting:: @ 818E59A
	.string "Als ich noch jung war, bin ich als\n"
	.string "POKéMON-TRAINER durch die Welt\l"
	.string "gereist.\p"
	.string "Nun, da ich ein alter Knabe geworden bin,\n"
	.string "beobachte ich mit Freuden die jungen\l"
	.string "TRAINER bei ihren Kämpfen.$"

MossdeepCity_MysteryEventsHouse_Text_DoorIsLocked:: @ 818E631
	.string "Diese Tür ist verschlossen.$"

MossdeepCity_MysteryEventsHouse_Text_ChallengeVisitingTrainer:: @ 818E650
	.string "Ein TRAINER namens {STR_VAR_1} ist bei\n"
	.string "mir zu Besuch.\p"
	.string "Möchtest du einmal gegen {STR_VAR_1}\n"
	.string "antreten?$"

MossdeepCity_MysteryEventsHouse_Text_YouWontBattle:: @ 818E698
	.string "Du möchtest nicht kämpfen? Es ent-\n"
	.string "täuscht mich, dass ich dich nicht\l"
	.string "kämpfen sehen kann.$"

MossdeepCity_MysteryEventsHouse_Text_KeepItToA3On3:: @ 818E6DA
	.string "Oh, sehr gut!\p"
	.string "Aber mein Haus ist nicht sehr stabil.\p"
	.string "Könntet ihr einen 3-gegen-3-Kampf\n"
	.string "ausfechten?$"

MossdeepCity_MysteryEventsHouse_Text_SaveYourProgress:: @ 818E741
	.string "Bevor ihr gegeneinander antretet,\n"
	.string "solltet ihr eure Spiele speichern!$"

MossdeepCity_MysteryEventsHouse_Text_HopeToSeeAGoodMatch:: @ 818E777
	.string "Ich hoffe, einen guten Kampf zu sehen!$"

MossdeepCity_MysteryEventsHouse_Text_UnusedEReaderBattleResult1:: @ 818E793
	.string "{STR_VAR_1}$"

MossdeepCity_MysteryEventsHouse_B1F_Text_MatchEndedUpDraw:: @ 818E796
	.string "Der Kampf endet unentschieden.$"

MossdeepCity_MysteryEventsHouse_Text_BattleTie:: @ 818E7B1
	.string "So, also ist es ein Unentschieden.\p"
	.string "Ein brillanter Kampf, in dem niemand\n"
	.string "auch nur einen Schritt ausgewichen ist.$"

MossdeepCity_MysteryEventsHouse_Text_UnusedEReaderBattleResult2:: @ 818E80B
	.string "{STR_VAR_1}$"

MossdeepCity_MysteryEventsHouse_Text_BattleWon:: @ 818E80E
	.string "Das war absolute Spitzenklasse!\p"
	.string "Ich habe mich wieder erkannt - mich in\n"
	.string "meinen jungen Jahren!$"

MossdeepCity_MysteryEventsHouse_Text_UnusedEReaderBattleResult3:: @ 818E856
	.string "{STR_VAR_1}$"

MossdeepCity_MysteryEventsHouse_Text_BattleLost:: @ 818E859
	.string "Ach, wie bedauerlich für dich!\p"
	.string "Aber es war ein guter Kampf.\n"
	.string "Ich hoffe, das nächste Mal gewinnst du.$"
