Route129_Text_ChaseIntro:: @ 81C2161
	.string "Das ist mein erster Triathlon.\n"
	.string "Ich bin schon ganz hibbelig und nervös!$"

Route129_Text_ChaseDefeat:: @ 81C2198
	.string "Wooooaaaaaargh! Ich habe es\n"
	.string "nicht geschafft, zu gewinnen.$"

Route129_Text_ChasePostBattle:: @ 81C21B4
	.string "Wenn ich so hibbelig bin, kann ich nicht\n"
	.string "alles geben.$"

Route129_Text_AllisonIntro:: @ 81C21ED
	.string "Ich bin mitten in einem Triathlon, aber\n"
	.string "warum sollten wir nicht kämpfen?$"

Route129_Text_AllisonDefeat:: @ 81C222F
	.string "Ich war sicher, ich würde gewinnen!$"

Route129_Text_AllisonPostBattle:: @ 81C2243
	.string "Weißt du, was das Beste am Triathlon\n"
	.string "ist?\p"
	.string "Man kommt an seine eigenen Grenzen und\n"
	.string "zeigt seine Ausdauer gegenüber Mutter\l"
	.string "Natur.$"

Route129_Text_ReedIntro:: @ 81C22C8
	.string "Sag: Hey, hey!\n"
	.string "Los geht's!$"

Route129_Text_ReedDefeat:: @ 81C22EC
	.string "Geschlagen, ich wurde geschlagen.\n"
	.string "Das war's. Fertig!$"

Route129_Text_ReedPostBattle:: @ 81C230F
	.string "Hier gibt es für Verlierer nichts zu tun.\n"
	.string "Zeit für mich, nach Hause zu gehen.$"

Route129_Text_TishaIntro:: @ 81C2349
	.string "Warum so eilig?\n"
	.string "Immer mit der Ruhe...$"

Route129_Text_TishaDefeat:: @ 81C2378
	.string "Oh, meine Güte. Dabei wollte ich\n"
	.string "nur ein bisschen entspannen.$"

Route129_Text_TishaPostBattle:: @ 81C23A3
	.string "Hasst du es nicht auch, Fehler zu\n"
	.string "machen, nur weil du es eilig hast?\p"
	.string "Daher gehe ich alles langsam an.$"
