Route114_Text_AllMyMonDoesIsRoarTakeThis:: @ 8170154
	.string "All my POKéMON does is ROAR...\n"
	.string "No one dares to come near me...\p"
	.string "Sigh... If you would, please take\n"
	.string "this TM away...$"

Route114_Text_ExplainRoar:: @ 81701C5
	.string "TM05 contains ROAR.\n"
	.string "A ROAR sends POKéMON scurrying.$"

Route114_Text_Poochyena:: @ 81701F9
	.string "Bow! Bowwow!$"

Route114_Text_MeteorFallsSign:: @ 8170206
	.string "METEOR FALLS\n"
	.string "RUSTBORO CITY THROUGH HERE$"

Route114_Text_FossilManiacsHouseSign:: @ 817022E
	.string "FOSSIL MANIAC'S HOUSE\n"
	.string "“Fossils gratefully accepted!”$"

Route114_Text_LanettesHouse:: @ 8170263
	.string "LANETTE'S HOUSE$"
