Route114_Text_LennyIntro:: @ 81BC05B
	.string "Yodelayhihoo!\p"
	.string "... ...\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” since it doesn't\l"
	.string "echo here!$"

Route114_Text_LennyDefeat:: @ 81BC0B5
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:: @ 81BC0C3
	.string "When I was a wee tyke, I believed there\n"
	.string "was someone copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:: @ 81BC125
	.string "If you're not prepared, you shouldn't\n"
	.string "be up in the mountains!$"

Route114_Text_LucasDefeat:: @ 81BC163
	.string "The mountains are unforgiving...$"

Route114_Text_LucasPostBattle:: @ 81BC184
	.string "In the winter, mountains turn deadly\n"
	.string "with blizzards and avalanches.$"

Route114_Text_ShaneIntro:: @ 81BC1C8
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best of all are the POKéMON\n"
	.string "battles!$"

Route114_Text_ShaneDefeat:: @ 81BC23F
	.string "Way too strong!$"

Route114_Text_ShanePostBattle:: @ 81BC24F
	.string "I think it's great that I can go\n"
	.string "camping with my POKéMON.$"

Route114_Text_NancyIntro:: @ 81BC289
	.string "I need to exercise after a meal.\n"
	.string "Let's have a match!$"

Route114_Text_NancyDefeat:: @ 81BC2BE
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:: @ 81BC2C6
	.string "I just had a tasty meal.\n"
	.string "I'm getting drowsy...$"

Route114_Text_SteveIntro:: @ 81BC2F5
	.string "Ufufufufufu...\n"
	.string "Want to battle against my POKéMON?$"

Route114_Text_SteveDefeat:: @ 81BC327
	.string "M-My POKéMON...$"

Route114_Text_StevePostBattle:: @ 81BC337
	.string "A big body that's all lumpy and hard,\n"
	.string "enormous horns, and vicious fangs...\p"
	.string "Ufufufufu...\n"
	.string "I wish I had a POKéMON like that...$"

Route114_Text_SteveRematchIntro:: @ 81BC3B3
	.string "Ufufufufufu...\n"
	.string "Come on, battle my POKéMON...$"

Route114_Text_SteveRematchDefeat:: @ 81BC3E0
	.string "I feel so lucky getting to see your\n"
	.string "POKéMON...$"

Route114_Text_StevePostRematch:: @ 81BC40F
	.string "Ufufufufufu...\p"
	.string "When I see POKéMON battling, I get all\n"
	.string "shivery and shaky...$"

Route114_Text_BernieIntro:: @ 81BC45A
	.string "If you're lighting a campfire, make\n"
	.string "sure you have water handy.$"

Route114_Text_BernieDefeat:: @ 81BC499
	.string "Thanks for dousing my fire!$"

Route114_Text_BerniePostBattle:: @ 81BC4B5
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_BernieRematchIntro:: @ 81BC525
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat:: @ 81BC559
	.string "I got hosed down before I could flare\n"
	.string "up, I guess.$"

Route114_Text_BerniePostRematch:: @ 81BC58C
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro:: @ 81BC5FC
	.string "If we were fishing, you wouldn't stand\n"
	.string "a chance against me.\l"
	.string "So, bring on your POKéMON!$"

Route114_Text_ClaudeDefeat:: @ 81BC653
	.string "If we were fishing, I would've won...$"

Route114_Text_ClaudePostBattle:: @ 81BC679
	.string "I think I'll try my luck at landing\n"
	.string "a big one at METEOR FALLS.\p"
	.string "There has to be something in there.\n"
	.string "I just know it.$"

Route114_Text_NolanIntro:: @ 81BC6EC
	.string "I like to fish. But I also like to\n"
	.string "battle!\p"
	.string "If anyone challenges me, I'm there,\n"
	.string "even if I'm fishing.$"

Route114_Text_NolanDefeat:: @ 81BC750
	.string "I like to battle, but that doesn't\n"
	.string "mean I'm good at it...$"

Route114_Text_NolanPostBattle:: @ 81BC78A
	.string "This time I'll do it!\p"
	.string "I always think that, so I can't walk\n"
	.string "away from fishing or POKéMON.$"

Route114_Text_TyraIntro:: @ 81BC7E3
	.string "TYRA: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about POKéMON.$"

Route114_Text_TyraDefeat:: @ 81BC834
	.string "TYRA: What an amazing battle style!$"

Route114_Text_TyraPostBattle:: @ 81BC858
	.string "TYRA: I was teaching my junior IVY\n"
	.string "about POKéMON.$"

Route114_Text_TyraNotEnoughMons:: @ 81BC88A
	.string "TYRA: Giggle...\n"
	.string "If you want to battle with us, just one\l"
	.string "POKéMON isn't enough!$"

Route114_Text_IvyIntro:: @ 81BC8D8
	.string "IVY: Who taught you about POKéMON?$"

Route114_Text_IvyDefeat:: @ 81BC8FB
	.string "IVY: What an amazing battle style!$"

Route114_Text_IvyPostBattle:: @ 81BC91E
	.string "IVY: I started training POKéMON\n"
	.string "because TYRA, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons:: @ 81BC96A
	.string "IVY: Do you only have one POKéMON?\n"
	.string "I think it must feel lonesome.$"
