Route118_Text_RoseIntro:: @ 81BDFF4
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses us body and soul.$"

Route118_Text_RoseDefeat:: @ 81BE03C
	.string "Oh, dear me.\n"
	.string "I seem to have lost.$"

Route118_Text_RosePostBattle:: @ 81BE05E
	.string "Flowers, POKéMON...\n"
	.string "I love whatever smells nice.\p"
	.string "Stinky things...\n"
	.string "I'll pass.$"

Route118_Text_RoseRematchIntro:: @ 81BE0AB
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:: @ 81BE0D3
	.string "The power of aroma...\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch:: @ 81BE104
	.string "If you use a sweet aroma properly,\n"
	.string "POKéMON will be attracted by it.$"

Route118_Text_PerryIntro:: @ 81BE148
	.string "BIRD POKéMON that FLY elegantly in\n"
	.string "the sky... They're the best!$"

Route118_Text_PerryDefeat:: @ 81BE188
	.string "Urgh... I crashed...$"

Route118_Text_PerryPostBattle:: @ 81BE19D
	.string "You've got great POKéMON.\n"
	.string "I'll have to train mine better.$"

Route118_Text_ChesterIntro:: @ 81BE1D7
	.string "Take flight!\n"
	.string "My BIRD POKéMON!$"

Route118_Text_ChesterDefeat:: @ 81BE1F5
	.string "They did take flight...$"

Route118_Text_ChesterPostBattle:: @ 81BE20D
	.string "If they'd get stronger, they'd be able\n"
	.string "to fly more freely...$"

Route118_Text_BarnyIntro:: @ 81BE24A
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'm raising the POKéMON I caught.$"

Route118_Text_BarnyDefeat:: @ 81BE291
	.string "I thought I was doing okay in my\n"
	.string "training...$"

Route118_Text_BarnyPostBattle:: @ 81BE2BE
	.string "I couldn't win by training POKéMON\n"
	.string "while I fished...\p"
	.string "Was I doing things in half measures?$"

Route118_Text_WadeIntro:: @ 81BE318
	.string "For FISHERMEN, equipment is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are POKéMON and heart, of course!$"

Route118_Text_WadeDefeat:: @ 81BE385
	.string "I was beaten in heart?$"

Route118_Text_WadePostBattle:: @ 81BE39C
	.string "Come to think of it, fishing is a battle\n"
	.string "between a FISHERMAN and a POKéMON.$"

Route118_Text_DaltonIntro:: @ 81BE3E8
	.string "Let my melody rock your soul!$"

Route118_Text_DaltonDefeat:: @ 81BE406
	.string "La-lalala...$"

Route118_Text_DaltonPostBattle:: @ 81BE413
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy...\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody...$"

Route118_Text_DaltonRematchIntro:: @ 81BE489
	.string "A melody from my POKéMON and me...\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat:: @ 81BE4CC
	.string "La-lalala...$"

Route118_Text_DaltonPostRematch:: @ 81BE4D9
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar...$"
