Route106_Text_ElliotIntro:: @ 81B8EF0
	.string "Was bevorzugst du? Fischen im\n"
	.string "Meer oder im Fluss?$"

Route106_Text_ElliotDefeated:: @ 81B8F25
	.string "Wie beim Tiefseefischen habe ich auch\n"
	.string "hier geradezu spektakulär verloren.$"

Route106_Text_ElliotPostBattle:: @ 81B8F55
	.string "Angeln ist das Größte, egal ob im Meer\n"
	.string "oder im Fluss. Stimmst du mir zu?$"

Route106_Text_ElliotRematchIntro:: @ 81B8FAC
	.string "Ich habe beim Angeln eine Menge\n"
	.string "POKéMON gefangen. Ich zeige sie dir!$"

Route106_Text_ElliotRematchDefeated:: @ 81B8FF5
	.string "Ich habe wieder ganz famos verloren!$"

Route106_Text_ElliotRematchPostBattle:: @ 81B9011
	.string "Gewinnen, verlieren, POKéMON sind groß-\n"
	.string "artig! Stimmst du mir zu?$"

Route106_Text_NedIntro:: @ 81B9052
	.string "Was machen Angler, wenn sie mal auf die\n"
	.string "Toilette müssen?\p"
	.string "Ich gehe nicht. Niemals! In der Zeit\n"
	.string "könnte ja etwas anbeißen.$"

Route106_Text_NedDefeated:: @ 81B90D3
	.string "Ich habe verloren, weil ich nicht auf die\n"
	.string "Toilette gegangen bin.$"

Route106_Text_NedPostBattle:: @ 81B910A
	.string "Oh! Ich habe das Gefühl, bald\n"
	.string "etwas Großes zu fangen.$"

Route106_Text_DouglasIntro:: @ 81B913D
	.string "Hahaha! Ich bin ein lausiger Läufer,\n"
	.string "aber im Wasser fängst du mich nicht!$"

Route106_Text_DouglasDefeated:: @ 81B917F
	.string "Ich gebe auf!$"

Route106_Text_DouglasPostBattle:: @ 81B918A
	.string "Beim Wettschwimmen wäre ich der Sieger!$"

Route106_Text_NicoleIntro:: @ 81B91AC
	.string "Das Meer ist mein Garten. Ich werde es\n"
	.string "dir nicht leicht machen, Kind!$"

Route106_Text_NicoleDefeated:: @ 81B91F8
	.string "Konntest du es mir nicht leicht machen?$"

Route106_Text_NicolePostBattle:: @ 81B9222
	.string "Sich auf den Wellen treiben lassen...\n"
	.string "Ich liebe das! Versuch es doch auch mal!$"
