Route117_Text_IsaacIntro:: @ 81BD49E
	.string "Listen, could I get you to battle the\n"
	.string "POKéMON I'm raising?$"

Route117_Text_IsaacDefeat:: @ 81BD4D9
	.string "You've raised yours superbly...$"

Route117_Text_IsaacPostBattle:: @ 81BD4F9
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique aspect of one's\n"
	.string "character is another way of enjoying\l"
	.string "POKéMON.$"

Route117_Text_IsaacRematchIntro:: @ 81BD569
	.string "The POKéMON I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat:: @ 81BD5AB
	.string "You know how to raise them properly.\n"
	.string "You might have DAY CARE skills...$"

Route117_Text_IsaacPostRematch:: @ 81BD5F2
	.string "Your POKéMON are growing good!\n"
	.string "You should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:: @ 81BD634
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your POKéMON properly.$"

Route117_Text_LydiaDefeat:: @ 81BD67B
	.string "Yes, they are growing properly.$"

Route117_Text_LydiaPostBattle:: @ 81BD69B
	.string "If you feed {POKEBLOCK}S to POKéMON, the\n"
	.string "unique aspects of their character\l"
	.string "will be enhanced.$"

Route117_Text_LydiaRematchIntro:: @ 81BD6F2
	.string "Allow me to reevaluate if you have\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaRematchDefeat:: @ 81BD733
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch:: @ 81BD74F
	.string "POKéMON seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro:: @ 81BD79A
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's have a battle!$"

Route117_Text_DylanDefeat:: @ 81BD7E0
	.string "I ran out of energy!$"

Route117_Text_DylanPostBattle:: @ 81BD7F5
	.string "I may have blown it...\p"
	.string "I might have dropped to last during\n"
	.string "that battle...$"

Route117_Text_DylanRematchIntro:: @ 81BD83F
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat:: @ 81BD8A2
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch:: @ 81BD8BD
	.string "I was tops in swimming and cycling, but\n"
	.string "I'm not quite that confident with\l"
	.string "POKéMON yet.$"

Route117_Text_MariaIntro:: @ 81BD914
	.string "I do my triathlon training with POKéMON,\n"
	.string "so I'm pretty confident about my speed.$"

Route117_Text_MariaDefeat:: @ 81BD965
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostBattle:: @ 81BD98F
	.string "Training is meaningful only if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training!\n"
	.string "Tomorrow!$"

Route117_Text_MariaRematchIntro:: @ 81BD9F1
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat:: @ 81BDA41
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch:: @ 81BDA6B
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro:: @ 81BDAA7
	.string "Once a BUG CATCHER!\n"
	.string "And now a BUG MANIAC!\p"
	.string "But my love for POKéMON remains\n"
	.string "unchanged!$"

Route117_Text_DerekDefeat:: @ 81BDAFC
	.string "My ineptitude also remains\n"
	.string "unchanged...$"

Route117_Text_DerekPostBattle:: @ 81BDB24
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC...\p"
	.string "Still, I am an expert on BUG POKéMON,\n"
	.string "so it's only natural that they call me\l"
	.string "a BUG MANIAC.$"

Route117_Text_AnnaIntro:: @ 81BDBC3
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_AnnaDefeat:: @ 81BDC07
	.string "ANNA: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_AnnaPostBattle:: @ 81BDC44
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaNotEnoughMons:: @ 81BDC96
	.string "ANNA: If you want to battle us, bring\n"
	.string "two POKéMON with you.$"

Route117_Text_MegIntro:: @ 81BDCD2
	.string "MEG: I'm going to tag up with my super\n"
	.string "senior student partner and beat you!$"

Route117_Text_MegDefeat:: @ 81BDD1E
	.string "MEG: Oh, no!\n"
	.string "I'm sorry, ANNA! I let you down...$"

Route117_Text_MegPostBattle:: @ 81BDD4E
	.string "MEG: I dragged ANNA down...\n"
	.string "If I didn't, she would have won!$"

Route117_Text_MegNotEnoughMons:: @ 81BDD8B
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:: @ 81BDDEF
	.string "ANNA: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat:: @ 81BDE2F
	.string "ANNA: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch:: @ 81BDE55
	.string "ANNA: Your POKéMON have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons:: @ 81BDEA7
	.string "ANNA: If you want to battle us, bring\n"
	.string "two POKéMON with you.$"

Route117_Text_MegRematchIntro:: @ 81BDEE3
	.string "MEG: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat:: @ 81BDF26
	.string "MEG: Too strong!$"

Route117_Text_MegPostRematch:: @ 81BDF37
	.string "MEG: I battled together with my\n"
	.string "senior partner, but we lost...\p"
	.string "That's so discouraging...$"

Route117_Text_MegRematchNotEnoughMons:: @ 81BDF90
	.string "MEG: Do you only have one POKéMON?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"
