Route105_Text_FosterIntro:: @ 81B8B40
	.string "Hier in der Gegend soll es einen\n"
	.string "mystischen Felsen geben. Weißt\l"
	.string "du etwas darüber?$"

Route105_Text_FosterDefeated:: @ 81B8B93
	.string "Ich habe zu sehr über den Felsen nach-\n"
	.string "gedacht, so dass meine POKéMON schwach\l"
	.string "blieben...$"

Route105_Text_FosterPostBattle:: @ 81B8BDE
	.string "Ich kann Stunden damit verbringen,\n"
	.string "einen Felsen anzustarren, ohne dass\l"
	.string "mir langweilig wird.$"

Route105_Text_LuisIntro:: @ 81B8C28
	.string "Puuh! Als ich dich sah, habe ich zuerst\n"
	.string "gedacht, ein Kind würde ertrinken.\p"
	.string "Dir scheint nichts zu fehlen. Wie wäre\n"
	.string "es deshalb mit einem kleinen Kampf?$"

Route105_Text_LuisDefeated:: @ 81B8C99
	.string "Blubb... blubbb... blubb...$"

Route105_Text_LuisPostBattle:: @ 81B8CA9
	.string "Wenn du zu ertrinken drohst, musst du\n"
	.string "mit einem Arm in Richtung Strand winken.$"

Route105_Text_AustinIntro:: @ 81B8CEE
	.string "Im tiefen, blauen Meer schwimmen...\n"
	.string "Das ist das Größte überhaupt!$"

Route105_Text_AustinDefeated:: @ 81B8D23
	.string "Ich bin abgesoffen...$"

Route105_Text_AustinPostBattle:: @ 81B8D45
	.string "Warum ist das Meer blau?\p"
	.string "Im MUSEUM in GRAPHITPORT CITY habe ich\n"
	.string "etwas dazu gelernt, habe es aber\l"
	.string "vergessen.$"

Route105_Text_BeverlyIntro:: @ 81B8D99
	.string "Mein Körper fühlt sich im Wasser\n"
	.string "so leicht an, als hätte ich abgenommen.$"

Route105_Text_BeverlyDefeated:: @ 81B8DDD
	.string "Ich lasse mich treiben...$"

Route105_Text_BeverlyPostBattle:: @ 81B8DED
	.string "Dein Körpergewicht reduziert sich auf\n"
	.string "10 Prozent, wenn du im Wasser bist.\p"
	.string "Dann würde ich nur... Huups! Ich verrate\n"
	.string "dir doch nicht mein Gewicht!$"

Route105_Text_DawnIntro:: @ 81B8E66
	.string "Der blaue, blaue Himmel...\n"
	.string "Das unendliche Meer...\l"
	.string "Es ist so friedlich...$"

Route105_Text_DawnDefeated:: @ 81B8EA0
	.string "Ich habe verloren, weil ich hier nur\n"
	.string "herumhänge...$"

Route105_Text_DawnPostBattle:: @ 81B8EBD
	.string "So war der Kampf mit mir wenigstens\n"
	.string "entspannend. Kicher...$"
