Route117_Text_IsaacIntro:: @ 81BD49E
	.string "Du? Würdest du gegen meine POKéMON\n"
	.string "kämpfen?$"

Route117_Text_IsaacDefeat:: @ 81BD4D9
	.string "Du hast einfach großartige POKéMON...$"

Route117_Text_IsaacPostBattle:: @ 81BD4F9
	.string "POKéMON sind nicht nur durch Stärke\n"
	.string "definiert.\p"
	.string "Jedes POKéMON hat seinen eigenen\n"
	.string "Charakter. Dadurch wird der Umgang\l"
	.string "mit ihnen noch viel interessanter.$"

Route117_Text_IsaacRematchIntro:: @ 81BD569
	.string "Die POKéMON, die ich aufgezogen habe,\n"
	.string "sehen gut aus. Genau wie immer.$"

Route117_Text_IsaacRematchDefeat:: @ 81BD5AB
	.string "Du weißt, wie man sie richtig aufzieht.\n"
	.string "Du hast die Talente, die man in einer\l"
	.string "PENSION braucht.$"

Route117_Text_IsaacPostRematch:: @ 81BD5F2
	.string "Deine POKéMON entwickeln sich gut.\n"
	.string "Du solltest sie zu einem WETTBEWERB\l"
	.string "anmelden!$"

Route117_Text_LydiaIntro:: @ 81BD634
	.string "Bitte lass mich überprüfen, ob du deine\n"
	.string "POKéMON auch richtig aufgezogen hast.$"

Route117_Text_LydiaDefeat:: @ 81BD67B
	.string "Ja, sie sehen sehr gut aus...$"

Route117_Text_LydiaPostBattle:: @ 81BD69B
	.string "Wenn du deinen POKéMON {POKEBLOCK}\n"
	.string "gibst, entwickeln sich ihre individuellen\l"
	.string "Charaktereigenschaften.$"

Route117_Text_LydiaRematchIntro:: @ 81BD6F2
	.string "Erlaube mir, noch einmal zu prüfen, ob\n"
	.string "du deine POKéMON richtig aufziehst.$"

Route117_Text_LydiaRematchDefeat:: @ 81BD733
	.string "Sie wurden sehr, sehr gut aufgezogen...$"

Route117_Text_LydiaPostRematch:: @ 81BD74F
	.string "POKéMON mögen, abhängig von ihrem\n"
	.string "Wesen, die unterschiedlichsten {POKEBLOCK}.$"

Route117_Text_DylanIntro:: @ 81BD79A
	.string "Ich bin mitten in einem Triathlon. Aber\n"
	.string "lass uns trotzdem kämpfen!$"

Route117_Text_DylanDefeat:: @ 81BD7E0
	.string "Ich habe keine Energie mehr!$"

Route117_Text_DylanPostBattle:: @ 81BD7F5
	.string "Ich habe es wohl verpatzt...\p"
	.string "Ich habe in meinem letzten Kampf\n"
	.string "stark nachgelassen...$"

Route117_Text_DylanRematchIntro:: @ 81BD83F
	.string "Ich bin mitten in einem Triathlon, liege\n"
	.string "aber weit an der Spitze. Lass uns zu\l"
	.string "einem schnellen Kampf antreten.$"

Route117_Text_DylanRematchDefeat:: @ 81BD8A2
	.string "Ich habe schon wieder meine Energie\n"
	.string "verloren!$"

Route117_Text_DylanPostRematch:: @ 81BD8BD
	.string "Im Schwimmen und im Radfahren bin ich\n"
	.string "unschlagbar, aber meine Leistungen in\l"
	.string "POKéMON-Kämpfen sind unbefriedigend.$"

Route117_Text_MariaIntro:: @ 81BD914
	.string "Ich trainiere mit meinem POKéMON und\n"
	.string "bin mit meinen Fähigkeiten echt\l"
	.string "zufrieden.$"

Route117_Text_MariaDefeat:: @ 81BD965
	.string "Ich glaube, ich muss wirklich mehr üben.$"

Route117_Text_MariaPostBattle:: @ 81BD98F
	.string "Training zahlt sich nur aus, wenn man\n"
	.string "regelmäßig trainiert.\p"
	.string "Okay! Ich setze mein Training fort!\n"
	.string "Morgen!$"

Route117_Text_MariaRematchIntro:: @ 81BD9F1
	.string "Trainierst du auch fleißig weiter?\n"
	.string "Ich trainiere sehr fleißig!\l"
	.string "Ich liefere dir den Beweis.$"

Route117_Text_MariaRematchDefeat:: @ 81BDA41
	.string "Ich muss, glaube ich, doch noch mehr\n"
	.string "trainieren.$"

Route117_Text_MariaPostRematch:: @ 81BDA6B
	.string "Ich werde mein Training morgen fort-\n"
	.string "setzen. Lass uns bald wieder kämpfen!$"

Route117_Text_DerekIntro:: @ 81BDAA7
	.string "Einst war ich KÄFERSAMMLER.\n"
	.string "Heute bin ich ein KÄFERFREAK!\p"
	.string "Aber meine Liebe zu POKéMON hat sich\n"
	.string "nicht verändert!$"

Route117_Text_DerekDefeat:: @ 81BDAFC
	.string "Meine Ungeschicktheit ist auch\n"
	.string "ungebrochen...$"

Route117_Text_DerekPostBattle:: @ 81BDB24
	.string "Alles, was ich getan habe, war meinem\n"
	.string "Herzen zu folgen, und nun nennen sie\l"
	.string "mich den KÄFERFREAK...\p"
	.string "Aber ich bin ein Experte für KÄFER-\n"
	.string "POKéMON, daher ist es nur natürlich,\l"
	.string "dass sie mich KÄFERFREAK nennen.$"

Route117_Text_AnnaIntro:: @ 81BDBC3
	.string "IRM: Ich bin hier mit meiner hübschen\n"
	.string "Junior-Studentin. Ich muss gut sein!$"

Route117_Text_AnnaDefeat:: @ 81BDC07
	.string "IRM: Ich bin mit meiner hübschen\n"
	.string "Junior-Studentin hier. Ich wollte so\l"
	.string "gerne gewinnen!$"

Route117_Text_AnnaPostBattle:: @ 81BDC44
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_AnnaNotEnoughMons:: @ 81BDC96
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "bring zwei POKéMON mit.$"

Route117_Text_MegIntro:: @ 81BDCD2
	.string "IDA: Ich werde mich mit meiner Super-\n"
	.string "Senior-Studentin verbünden und siegen!$"

Route117_Text_MegDefeat:: @ 81BDD1E
	.string "IDA: Oh, nein! Tut mir Leid, IRM.\n"
	.string "Ich habe dich im Stich gelassen.$"

Route117_Text_MegPostBattle:: @ 81BDD4E
	.string "IDA: Ich habe IRM in eine Niederlage\n"
	.string "gebracht. Ohne mich hätte sie gewonnen!$"

Route117_Text_MegNotEnoughMons:: @ 81BDD8B
	.string "IDA: Hast du nur ein POKéMON?\n"
	.string "Dann können wir nicht mit dir kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"

Route117_Text_AnnaRematchIntro:: @ 81BDDEF
	.string "IRM: Ich kann doch nicht ständig vor\n"
	.string "meiner Junior-Partnerin verlieren...$"

Route117_Text_AnnaRematchDefeat:: @ 81BDE2F
	.string "IRM: Ich komme einfach nicht in Fahrt.$"

Route117_Text_AnnaPostRematch:: @ 81BDE55
	.string "IRM: Deine POKéMON haben einige gute\n"
	.string "Kombinationen auf Lager.\p"
	.string "Trotzdem bist du uns gegenüber nur\n"
	.string "zweite Klasse.$"

Route117_Text_AnnaRematchNotEnoughMons:: @ 81BDEA7
	.string "IRM: Wenn du gegen uns antreten willst,\n"
	.string "brauchst du zwei POKéMON.$"

Route117_Text_MegRematchIntro:: @ 81BDEE3
	.string "IDA: Ich werde mich mit meiner\n"
	.string "Senior-Studentin verbünden und siegen!$"

Route117_Text_MegRematchDefeat:: @ 81BDF26
	.string "IDA: Viel zu stark!$"

Route117_Text_MegPostRematch:: @ 81BDF37
	.string "IDA: Ich habe mit meiner Senior-\n"
	.string "Partnerin gekämpft. Wir haben verloren.\p"
	.string "Das ist so entmutigend...$"

Route117_Text_MegRematchNotEnoughMons:: @ 81BDF90
	.string "IDA: Besitzt du nur ein POKéMON?\n"
	.string "Dann können wir nicht kämpfen.\p"
	.string "Wir wollen einen 2-gegen-2-Kampf.$"
