JaggedPass_Text_EricIntro:: @ 8195DAC
	.string "MT. CHIMNEY's JAGGED PASS...\p"
	.string "Now this is what I've always wanted\n"
	.string "in a mountain.\p"
	.string "This jagged bumpiness...\n"
	.string "It rocks my soul!$"

JaggedPass_Text_EricDefeat:: @ 8195E27
	.string "Losing left me bitter!$"

JaggedPass_Text_EricPostBattle:: @ 8195E3E
	.string "Yes, I did lose at POKéMON...\p"
	.string "But, when it comes to the love of\n"
	.string "the mountains, I have you beat!$"

JaggedPass_Text_DianaIntro:: @ 8195E9E
	.string "This place isn't your casual hike.\n"
	.string "It's not suited for a picnic.$"

JaggedPass_Text_DianaDefeat:: @ 8195EDF
	.string "Ohhh, no!\n"
	.string "The ground is too bumpy...$"

JaggedPass_Text_DianaPostBattle:: @ 8195F04
	.string "Did you know?\p"
	.string "Some people cleverly ride their\n"
	.string "bicycles up this horribly bumpy pass.$"

JaggedPass_Text_DianaRematchIntro:: @ 8195F58
	.string "Picnics are fun wherever you go.\n"
	.string "Just like POKéMON!$"

JaggedPass_Text_DianaRematchDefeat:: @ 8195F8C
	.string "I only lost because the ground is\n"
	.string "too bumpy!$"

JaggedPass_Text_DianaPostRematch:: @ 8195FB9
	.string "I'll forget about losing and just\n"
	.string "enjoy this bumpy hike.$"

JaggedPass_Text_EthanIntro:: @ 8195FF2
	.string "JAGGED PASS is hard to walk on.\n"
	.string "It's a good place for training.$"

JaggedPass_Text_EthanDefeat:: @ 8196032
	.string "It was all over while we were still\n"
	.string "trying to find a good footing...$"

JaggedPass_Text_EthanPostBattle:: @ 8196077
	.string "If I had an ACRO BIKE, I'd be able to\n"
	.string "jump ledges.$"

JaggedPass_Text_EthanRematchIntro:: @ 81960AA
	.string "I got used to this bumpiness.\n"
	.string "I sing while I climb now.$"

JaggedPass_Text_EthanRematchDefeat:: @ 81960E2
	.string "It's still not easy to battle on this\n"
	.string "bumpy ground...$"

JaggedPass_Text_EthanPostRematch:: @ 8196118
	.string "I should get an ACRO BIKE from RYDEL\n"
	.string "in MAUVILLE CITY...$"
