MeteorFalls_1F_2R_Text_NicolasIntro:: @ 81939C5
	.string "Dort trainieren wir DRACHEN-Besitzer...\p"
	.string "Auch der CHAMP kommt manchmal vorbei.\n"
	.string "Verstehst du nun, dass dies ein\l"
	.string "besonderer Ort ist?$"

MeteorFalls_1F_2R_Text_NicolasDefeat:: @ 8193A35
	.string "Argh!\n"
	.string "Ich hätte nicht gedacht, dass du so\l"
	.string "stark bist!$"

MeteorFalls_1F_2R_Text_NicolasPostBattle:: @ 8193A60
	.string "Der Weg vor mir ist lang und\n"
	.string "beschwerlich.\p"
	.string "Wann werden meine POKéMON und ich\n"
	.string "zu den Besten gehören?$"

MeteorFalls_1F_2R_Text_NicolasRematchIntro:: @ 8193AB3
	.string "Seit wir uns das letzte Mal gesehen\n"
	.string "haben, haben wir hart trainiert ver-\l"
	.string "glichen mit unserem ersten Kampf.\p"
	.string "Hilf uns, herauszufinden, wie stark wir\n"
	.string "wirklich sind.$"

MeteorFalls_1F_2R_Text_NicolasRematchDefeat:: @ 8193B21
	.string "Argh!\n"
	.string "Wie kannst du nur so stark sein?$"

MeteorFalls_1F_2R_Text_NicolasPostRematch:: @ 8193B4C
	.string "Du hast uns bei unserem Training\n"
	.string "wirklich sehr geholfen.\p"
	.string "Solange du stärker wirst, kann auch\n"
	.string "ich stärker werden.$"

MeteorFalls_1F_2R_Text_JohnIntro:: @ 8193BB7
	.string "URS: Wir haben immer in trauter Zwei-\n"
	.string "samkeit mit unseren POKéMON gegen\l"
	.string "andere gekämpft. Wir werden siegen!$"

MeteorFalls_1F_2R_Text_JohnDefeat:: @ 8193C10
	.string "URS: O weh.\n"
	.string "Wir haben verloren, liebstes Weib.$"

MeteorFalls_1F_2R_Text_JohnPostBattle:: @ 8193C35
	.string "URS: Wir sind seit 50 Jahren glücklich\n"
	.string "verheiratet.\p"
	.string "Und denk mal, ich habe es noch nie ge-\n"
	.string "schafft, meine Frau zu besiegen.$"

MeteorFalls_1F_2R_Text_JohnNotEnoughMons:: @ 8193C9F
	.string "URS: Nun, was für ein junger TRAINER!\p"
	.string "Möchtest du mit uns kämpfen? Wenn ja,\n"
	.string "dann musst du dir noch mehr POKéMON\l"
	.string "besorgen.$"

MeteorFalls_1F_2R_Text_JayIntro:: @ 8193D10
	.string "EVI: Wir sind seit 50 Jahren glücklich\n"
	.string "verheiratet.\p"
	.string "Das Band, das uns verbindet, kann\n"
	.string "niemand durchtrennen.$"

MeteorFalls_1F_2R_Text_JayDefeat:: @ 8193D6E
	.string "EVI: O weh.\n"
	.string "Wir haben verloren, mein Lieber.$"

MeteorFalls_1F_2R_Text_JayPostBattle:: @ 8193D9A
	.string "EVI: 50 Jahre verheiratet...\p"
	.string "Immer wenn wir uneinig sind, ent-\n"
	.string "scheiden wir es mit einem POKéMON-\l"
	.string "Kampf.$"

MeteorFalls_1F_2R_Text_JayNotEnoughMons:: @ 8193DFB
	.string "EVI: Hmm... Bist du nicht ein bisschen zu\n"
	.string "klein für einen TRAINER?\p"
	.string "Möchtest du mit uns kämpfen? Dann\n"
	.string "musst du dir noch mehr POKéMON\l"
	.string "besorgen.$"

MeteorFalls_1F_2R_Text_JohnRematchIntro:: @ 8193E75
	.string "URS: Wir haben immer in trauter Zwei-\n"
	.string "samkeit mit unseren POKéMON gegen\l"
	.string "andere gekämpft. Wir werden siegen!$"

MeteorFalls_1F_2R_Text_JohnRematchDefeat:: @ 8193ECE
	.string "URS: O weh.\n"
	.string "Wir haben verloren, liebstes Weib.$"

MeteorFalls_1F_2R_Text_JohnPostRematch:: @ 8193EF3
	.string "URS: 50 Jahre verheiratet...\p"
	.string "Rückblickend kann man sagen: Meine Frau\n"
	.string "und ich haben Tag für Tag miteinander\l"
	.string "gekämpft...$"

MeteorFalls_1F_2R_Text_JohnRematchNotEnoughMons:: @ 8193F59
	.string "URS: Nun, was für ein junger TRAINER!\p"
	.string "Möchtest du mit uns kämpfen? Wenn ja,\n"
	.string "dann musst du dir noch mehr POKéMON\l"
	.string "besorgen.$"

MeteorFalls_1F_2R_Text_JayRematchIntro:: @ 8193FCA
	.string "EVI: Wir sind seit 50 Jahren\n"
	.string "verheiratet.\p"
	.string "Wir haben uns immer gegenseitig unter-\n"
	.string "stützt. Das hat uns stark gemacht.$"

MeteorFalls_1F_2R_Text_JayRematchDefeat:: @ 819403A
	.string "EVI: O weh.\n"
	.string "Wir haben verloren, mein Lieber.$"

MeteorFalls_1F_2R_Text_JayPostRematch:: @ 8194066
	.string "EVI: 50 Jahre verheiratet...\n"
	.string "Vieles ist in dieser Zeit passiert.\p"
	.string "Ich hoffe, wir werden noch lange unsere\n"
	.string "Erinnerungen miteinander teilen können.$"

MeteorFalls_1F_2R_Text_JayRematchNotEnoughMons:: @ 81940DF
	.string "EVI: Hmm... Bist du nicht ein bisschen zu\n"
	.string "klein für einen TRAINER?\p"
	.string "Möchtest du gegen uns kämpfen? Dann\n"
	.string "musst du dir noch mehr POKéMON\l"
	.string "besorgen.$"
