#ifndef GUARD_POKENAV_H
#define GUARD_POKENAV_H

#include "main.h"
#include "region_map.h"
#include "mon_markings.h"

enum {
    POKENAV_LIST_CONDITION_SEARCH,
    POKENAV_LIST_RIBBONS,
    POKENAV_LIST_TRAINERS_EYES,
};

struct TrainersEyeStruct {
    /*0x0*/ u16 opponentId;
    /*0x2*/ u16 regionMapSectionId;
    /*0x4*/ u8 rematchTableIdx;
    /*0x5*/ u8 rematchNo;
};

struct UnkPokenavStruct_Sub1 {
    /*0x00*/ void (*unk0)(void);
    /*0x04*/ MainCallback callback;
    /*0x08*/ struct Pokeblock *pokeblock;
    /*0x0C*/ struct Pokemon *pokemon;
    /*0x10*/ u8 stringBuffer[0x40];
    /*0x50*/ u8 unk50;
    /*0x51*/ u8 unk51;
    /*0x52*/ u8 unk52;
    /*0x53*/ u8 unk53;
    /*0x54*/ u8 unk54;
    /*0x55*/ u8 unk55;
    /*0x56*/ u8 unk56;
    /*0x57*/ u8 unk57[5];
    /*0x5c*/ u8 unk5c[5];
    /*0x61*/ u8 unk61[5];
    /*0x66*/ s16 unk66[5];
};

struct UnkPokenavStruct_Sub3 {
    /*0x00*/s16 unk0;
};

struct UnkUsePokeblockSub {
    /*0x0*/ u8 unk0;
    /*0x1*/ u8 unk1;
    /*0x2*/ u16 partyIdx:5;
    /*0x2*/ u16 unk2_5:9;
    /*0x3*/ u16 unk3_14:1;
};

struct UnkPokenav11 {
    u16 unk0;
    u16 unk2;
};

struct UnknownStruct_Pokenav_8FF0 {
    /*0x000*/ u8 unk0[4][5];
    /*0x014*/ struct UnkPokenav11 unk14[4][5];
    /*0x064*/ struct UnkPokenav11 unk64[10][5];
    /*0x12C*/ struct UnkPokenav11 unk12C[5];
    /*0x140*/ u16 unk140[66][2];
    /*0x248*/ u16 unk248[66][2];
    /*0x350*/ u16 unk350;
    /*0x352*/ u16 unk352;
    /*0x354*/ u8 unk354;
    /*0x355*/ u8 unk355;
};

struct UnkPokenavStruct {
    /*0x0000*/ u16 unk0[6][0x40];
    /*0x0300*/ void (*callback)(void);
    /*0x0304*/ u16 callbackStep;
    /*0x0306*/ u16 unk306;
    /*0x0306*/ int unk308;
    /*0x030C*/ s16 menuVerticalOffset;
    /*0x030E*/ s8 menuOptionRowCount;
    /*0x030F*/ u8 menuOptionExitStep;
    /*0x0310*/ u8 filler0310[0x1];
    /*0x0311*/ u8 menuOptionBlendMode;
    /*0x0312*/ u16 menuOptionBlendFrame;
    /*0x0314*/ u16 menuOptionWin0V[6];
    /*0x0320*/ struct Sprite *menuOptionSprites[6][4];
    /*0x0380*/ struct SpriteSheet menuOptionSpriteSheet;
    /*0x0388*/ u8 menuOptionsGfx[0x1400];
    /*0x1788*/ u8 conditionMenuGfx[0xC00];
    /*0x2388*/ u8 conditionSearchGfx[0x1800];
    /*0x3B88*/ struct Sprite *largeHeaderSprites[2];
    /*0x3B90*/ struct Sprite *smallHeaderSprites[2];
    /*0x3B98*/ u8 mainMenuHeaderGfx[0x600];
    /*0x4198*/ u8 conditionMenuHeaderGfx[0x600];
    /*0x4798*/ u8 trainersEyesHeaderGfx[0x600];
    /*0x4D98*/ u8 ribbonsHeaderGfx[0x600];
    /*0x5398*/ u8 hoennMapHeaderGfx[0xC00];
    /*0x5F98*/ u8 searchHeaderGfx[0x200];
    /*0x6198*/ u8 partyHeaderGfx[0x200];
    /*0x6398*/ u8 beautyHeaderGfx[0x200];
    /*0x6598*/ u8 cuteHeaderGfx[0x200];
    /*0x6798*/ u8 smartHeaderGfx[0x200];
    /*0x6998*/ u8 toughHeaderGfx[0x200];
    /*0x6B98*/ u8 coolHeaderGfx[0x200];
    /*0x6D98*/ struct Sprite *pokenavIconSprite;
    /*0x6D9C*/ struct Sprite *blueLightSprite;
    /*0x6DA0*/ u16 bg3ScrollFrameCounter;
    /*0x6DA2*/ u16 bg3ScrollOffset;
    /*0x6DA4*/ u16 bg3ScrollTaskId;
    /*0x6DA6*/ u8 filler6DA6[0x5];
    /*0x6DAB*/ u8 unk6DAB;
    /*0x6DAC*/ u8 unk6DAC;
    /*0x6DAD*/ s8 menuCursorPos;
    /*0x6DAE*/ s8 menuItemCount;
    /*0x6DAF*/ u8 filler6DAF[0x3];
    /*0x6DB2*/ u8 mainMenuItemIds[0x2A];
    /*0x6DDC*/ s8 mainMenuCursorPos;
    /*0x6DDD*/ u8 filler6DDD[0x13];
    /*0x6DF0*/ s8 conditionMenuCursorPos;
    /*0x6DF1*/ u8 filler6DF1[0x0B];
    /*0x6DFC*/ u8 conditionSearchCursorPos;
    /*0x6DFD*/ u8 filler6DFD[0x17];
    /*0x6E14*/ u8 transitionMenuType;
    /*0x6E15*/ u8 transitionCursorPos;
    /*0x6E16*/ u8 transitionStep;
    /*0x6E17*/ u8 transitionGfxId;
    /*0x6E18*/ struct RegionMap regionMap;
    /*0x7698*/ u16 regionMapBg0YOffset;
    /*0x769A*/ u16 cityBannerDelay;
    /*0x769C*/ u8 cityBannerFrame;
    /*0x769D*/ u8 cityBannerState;
    /*0x769E*/ u8 cityBannerVisible;
    /*0x769F*/ u8 filler769F[0xB];
    /*0x76AA*/ u8 isConditionGraphSearchMode;
    /*0x76AC*/ struct Sprite *conditionMonMarkingsSprite;
    /*0x76B0*/ struct PokemonMarkMenu conditionMarkingsMenu;
    /*0x8764*/ u16 monInfoHeaderGfxStep;
    /*0x8766*/ s16 monInfoHeaderXOffset;
    /*0x8768*/ struct Sprite *portraitSprite;
    /*0x876C*/ s16 listCursorRow;
    /*0x876E*/ s16 listSelectedIndex;
    /*0x8770*/ s16 unk8770;
    /*0x8772*/ s16 unk8772;
    /*0x8774*/ s16 unk8774;
    /*0x8776*/ s16 listBg3YOffset;
    /*0x8778*/ u16 listTilemapRow;
    /*0x877A*/ s16 listScrollStep;
    /*0x877C*/ s16 listScrollPixelsRemaining;
    /*0x877E*/ u16 listRowToDraw;
    /*0x8780*/ u16 listTilemapRowToDraw;
    /*0x8782*/ u16 unk8782;
    /*0x8784*/ u16 listRowsToDraw;
    /*0x8786*/ u16 unk8786;
    /*0x8788*/ u8 unk8788[0x40];
    /*0x87C8*/ u8 isRibbonsList;
    /*0x87C9*/ u8 hasListScrollArrows;
    /*0x87CA*/ u8 listMode;
    /*0x87CB*/ u8 unk87CB;
    /*0x87CC*/ struct Sprite *listRightArrowSprite;
    /*0x87D0*/ struct Sprite *listUpDownArrowSprites[2];
    /*0x87D8*/ u8 unk87D8;
    /*0x87DA*/ s16 unk87DA;
    /*0x87DC*/ s16 unk87DC;
    /*0x87DE*/ u8 unk87DE;
    /*0x87E0*/ bool8 (*unk87E0)(void);
    /*0x87E4*/ struct Sprite *conditionPartyIconSprites[7];
    /*0x8800*/ struct Sprite *conditionSparkleSprites[10];
    /*0x8828*/ u8 unk8828;
    /*0x8829*/ u8 unk8829[3][64];
    /*0x88E9*/ u8 unk88E9[3][24];
    /*0x8931*/ u8 conditionNumSparkles[3];
    /*0x8934*/ u8 conditionMonMarkings[3];
    /*0x8937*/ u8 unk8937[5];
    /*0x893C*/ struct UnkUsePokeblockSub unk893c[0x1AA];
    /*0x8FE4*/ u16 unk8FE4;
    /*0x8FE6*/ u8 unk8FE6;
    /*0x8FE7*/ u8 unk8FE7;
    /*0x8FE8*/ s8 unk8FE8;
    /*0x8fe9*/ s8 unk8fe9;
    /*0x8fea*/ s8 unk8FEA;
    /*0x8feb*/ s8 unk8FEB;
    /*0x8fec*/ s8 unk8FEC;
    /*0x8fee*/ u16 unk8FEE;

    // UnknownStruct_Pokenav_8FF0
    /*0x8ff0*/ u8 unk8ff0[4][5];
    /*0x9004*/ struct UnkPokenav11 unk9004[4][5];
    /*0x9054*/ struct UnkPokenav11 unk9054[10][5];
    /*0x911C*/ struct UnkPokenav11 unk911C[5];
    /*0x9130*/ u16 unk9130[66][2];
    /*0x9238*/ u16 unk9238[66][2];
    /*0x9340*/ u16 unk9340;
    /*0x9342*/ u16 unk9342;
    /*0x9344*/ u8 unk9344;
    /*0x9345*/ u8 unk9345;

    /*0x9348*/ struct Sprite *bigRibbonSprite;
    /*0x934C*/ u16 ribbonsSummaryTilemap[0x280];
    /*0x984C*/ u8 ribbonIconHalfGfx[0xC][0x100];
    /*0xA44C*/ u8 ribbonIconBigGfx[0xC][0x200];
    /*0xBC4C*/ u8 ribbonIds[0x42];
    /*0xBC8E*/ u8 ribbonCount;
    /*0xBC8F*/ u8 giftRibbonCount;
    /*0xBC90*/ u8 ribbonCursorPos;
    /*0xBC91*/ u8 ribbonPageIndex;
    /*0xBC92*/ u8 isBigRibbonAnimating;
    /*0xBC93*/ u8 ribbonIconLoadIndex;
    /*0xBC94*/ u8 unkBC94;
    /*0xBC95*/ u8 unkBC95;
    /*0xBC96*/ u8 ribbonPageCounts[0x4];
    /*0xBC9A*/ u8 cityMapSectionIndex;
    /*0xBC9B*/ u8 cityMapBufferIndex;
    /*0xBC9C*/ u8 cityMapTilemaps[22][200];
    /*0xCDCC*/ const u8 *cityMapTilemapPtrs[16][2];
    /*0xCE4C*/ u16 paletteGradientIndex;
    /*0xCE4E*/ u16 paletteGradientTarget;
    /*0xCE50*/ u16 paletteGradientDelta;
    /*0xCE52*/ u16 palettesCE52[30];
    /*0xCE8E*/ u16 palettesCE8E[0x21];
    /*0xCED0*/ struct Sprite *trainerEyesPortraitSprite;
    /*0xCED4*/ struct Sprite *trainerEyesNameSprites[5];
    /*0xCEE8*/ struct TrainersEyeStruct trainersEye[69];
    /*0xD110*/ const u8 *trainerEyeDescriptionLines[4];
    /*0xD120*/ u8 fillerD114[0x18];
    /*0xD138*/ u8 unkD138[0x20];
    /*0xD158*/ u16 unkD158;
    /*0xD15A*/ s16 trainerEyesPortraitXOffset;
    /*0xD15C*/ u16 trainerEyesRowStep;
    /*0xD15E*/ u8 unkD15E;
    /*0xD15F*/ u8 unkD15F;
    /*0xD160*/ u16 setupStep;
    /*0xD162*/ u8 unkD162;
    /*0xD164*/ struct UnkPokenavStruct_Sub1 unkD164;
    /*0xD1D4*/ u8 fillerD1D6[0x2];
    /*0xD1D6*/ u16 unkD1D6[3];
    /*0xD1DC*/ u16 portraitPaletteOffset;
    /*0xD1DE*/ u16 portraitTileStart;
    /*0xD1E0*/ u8 *portraitVramDest;
    /*0xD1E4*/ u8 spriteGfxBuffers[3][0x2000];
    /*0x131E4*/ u8 unk131E4[0x1000];
};

extern struct UnkPokenavStruct *const gPokenavStructPtr;

bool8 SlidePokenavMonInfoHeaderIn(void);
bool8 LoadPokeblockConditionGraphScreenStep(void);
void PrintPokeblockMonNature(void);
void BeginPokenavLeftHeaderLoad(u8 headerType);
void InitPokenavMenuHeaderGfx(void);
bool8 LoadPokenavMenuHeaderGfxStep(void);
bool8 LoadPokenavLeftHeaderStep(u8 headerType);
void CreateOrUpdatePokenavPortraitSprite(u8 portraitSlot);
void CreateConditionPartyPokeballIndicators(void);
void LoadConditionSparkles(void);
void CreateConditionSparkleSprites(void);
void BuildPartyConditionGraphMonList(void);
void ConditionGraph_Update(struct UnkPokenav11*);
void ConditionGraph_CalcPositions(u8 *a0, struct UnkPokenav11 a1[]);
void CalcPokeblockConditionGraphPositions(u8 *, struct UnkPokenav11 *);
void ConditionGraph_InitResetScanline(void);
bool8 ConditionGraph_ResetScanline(void);
void ConditionGraph_DrawAtYOffset(u8);
void CB2_InitPokeNav(void);
void BeginConditionGraphMonScroll(bool8);
void DestroyConditionSparkleSprites(void);
bool8 UpdateConditionGraphMonScroll(void);
void StartPokeblockConditionGraphReset(struct UnkPokenav11*, struct UnkPokenav11*);
bool8 UpdatePokeblockConditionGraphReset(void);
void sub_80F7224(u8);
void StopConditionGraphScanlineEffect(void);
void CreateOrUpdateTrainerEyesPortrait(u8 portraitSlot);

bool8 PrintTrainerEyesDescriptionStep(void);
void LoadTrainerEyesDescriptionLines(void);
void PrintTrainerEyesLocation(u8 listIndex);
void RedrawSelectedTrainerEyesListRow(void);
void UpdateTrainerEyesNameSprites(u8 *);
void BeginPokenavListScroll(s16 rowsToScroll);
void UpdatePokenavListIndicesAfterScroll(s16 arg0);
void InitAnyMonHasRibbonScan(void);
bool8 AnyMonHasRibbonScanStep();

void InitPokenavMenuOptions(void);
void InitPokenavBackground(void);
bool8 LoadPokenavBackgroundStep(void);
void ResetPokenavSetupStep(void);
void SetPokenavDisplayForScreen(u8 screenId);
void HandlePokenavMainMenuInput(void);
void SetPokenavDisplayForMenu(void);
void StartPokenavMenuTransition(u8 menuType, u8 cursorPos, u8 gfxId);
bool8 UpdatePokenavMenuTransition(void);
bool8 UpdateMainMenuCursorPos(void);
void PausePokenavCallbackForLink(void);
void OpenRibbonsMonList(void);
void OpenPokenavRegionMap(void);
void OpenPokenavConditionMenu(void);
void ExitPokenav(void);
void OpenTrainerEyes(void);
bool8 SlideMenuHeaderUp(void);
void SetPokenavDisplayForTransition(void);
void HandleRegionMapInput(void);
void HandleConditionMenuInput(void);
bool8 UpdateSubmenuCursorPos(void);
void OpenConditionGraphFromParty(void);
void OpenPokenavConditionSearchMenu(void);
void OpenConditionSearchResults(void);
void HandleConditionSearchMenuInput(void);
void HandleConditionSearchInput(void);
void OpenConditionGraphFromSearchResults(void);
void HandleConditionGraphInput(void);
void HandleRibbonsMonListInput(void);
void RibbonsMonMenu_ReturnToMainMenu(void);
void OpenRibbonsSummaryMenu(void);
void RibbonsSummaryHandleInput(void);
void OpenRibbonsMonListFromRibbonsSummary(void);
void HandleTrainerEyesInput(void);
void ShowTrainerEyesTrainerInfo(void);
void TrainerEyes_ReturnToMainMenu(void);
void WaitForPokenavLinkQueue(void);
void PrintPokenavListSelectionInfo(void);
void QueuePokenavListRows(u16 firstListIndex, u16 firstTilemapRow, u16 rowCount);
bool8 PrintPokenavListRowStep(void);
u8 *BufferRibbonsMonListIndexText(u8*, u16);
void PrintTrainerEyesListStats(u8 drawStep);
bool8 LoadPokenavListRowsStep(void);
u8 *BufferPokenavMonListRowText(u8*, u16, u8);
void sub_80F700C(u8*, u16);
void InitTrainerEyesListErase(void);
bool8 EraseTrainerEyesListStep(void);
void InitTrainerEyesListRestore(void);
bool8 RestoreTrainerEyesListStep(void);
void LoadTrainerEyesDescriptionLines(void);
bool8 PrintTrainerEyesDescriptionStep(void);
void InitTrainerEyesDescriptionErase(void);
bool8 EraseTrainerEyesDescriptionStep(void);
void BeginTrainerEyesDetailEnterScroll(void);
void BeginTrainerEyesDetailExitScroll(void);
bool8 UpdateTrainerEyesDetailScroll(void);
bool8 UpdatePokenavListScroll(void);
void PrintTrainerEyesLocation(u8 listIndex);
void TruncateTrainerEyesLocationAtControlCode(u8 *text);
bool8 LoadRibbonsSummaryScreenStep(void);
void InitPokenavMonInfoHeaderGfx(void);
void DrawMonRibbonIcons(void);
void CopyRibbonsSummaryTilemapToVram(void);
void PrintRibbonsSummaryMonInfo(void);
void PrintRibbonsSummaryDescription(void);
bool8 LoadPokenavMonInfoHeaderGfxStep(u8 forRibbons);
void PrintConditionGraphMonInfo(u16 portraitSlot);
void UpdateRegionMapLinkLandmarks(void);
void StopRegionMapLinkLandmarks(void);
void StartRegionMapLinkLandmarks(void);
void InitPokenavMenuOptionGfx(void);
bool8 LoadPokenavMenuOptionGfxStep(void);
void InitPokenavMenuOptionSprites(u8 menuType);
bool8 LoadPokenavMenuOptionSpritesStep(u8 menuType);
void LoadMenuOptionSpriteSheet(u8 menuType);
void LoadMenuOptionSpritePalettes(u8 menuType);
void StartMenuOptionSpritesSlideIn(void);
void SpriteCB_SlideMenuOptionIn(struct Sprite *sprite);
bool8 UpdateMenuOptionEntryHighlight(void);
bool8 AreMenuOptionSpriteOffsetsAtRest(void);
void StartMenuOptionHighlight(void);
bool8 AreMenuOptionSpriteOffsetsMoving(void);
void StartMenuOptionSpritesSlideOut(void);
void StopMenuOptionHighlight(void);
void SpriteCB_SlideMenuOptionOut(struct Sprite *sprite);
bool8 UpdateMenuOptionSpritesSlideOut(void);
bool8 AreOtherMenuOptionSpritesGone(void);
void StartSelectedMenuOptionFadeOut(void);
bool8 AreSelectedMenuOptionSpritesGone(void);
void StopMenuOptionFadeOut(void);
void UpdateMenuOptionBlendRegisters(void);
void ResetMenuOptionBlendOnPokenavExit(void);
void SpriteCB_UpdateMenuOptionSelectionOffset(struct Sprite *sprite);
void DestroyMenuOptionSprite(struct Sprite *sprite);
void CreateRematchBlueLightSprite(void);
void DestroyRematchBlueLightSprite(void);
void SpriteCB_UpdateRegionMapHeaderZoom(struct Sprite *sprite);
void StartPokenavLeftHeaderSlideOut(u8 headerType);
void DestroyPokenavLeftHeaderSprites(u8 headerType);
void CreatePokenavRegionMapIcons(void);
void FreePokenavRegionMapIcons(void);
void SpriteCB_UpdateTrainerEyesPortraitPosition(struct Sprite *sprite);
void DestroyTrainerEyesPortrait(void);
void CreatePokenavListArrowSprites(u8);
void DestroyPokenavListArrowSprites(void);
void RefreshPokenavListArrowVisibility(void);
void TogglePokenavListArrows(u8);
void CreateConditionMonMarkingsSprite(void);
void MonMarkingsCallback(struct Sprite *sprite);
void SetMonMarkings(u16, u16, u8);
void InitRibbonIconGfx(void);
bool8 LoadRibbonIconGfxStep(void);
void InitRibbonIconExpansion(void);
bool8 ExpandRibbonIconGfxStep(void);
void InitRibbonsSummarySpriteGfx(void);
bool8 LoadRibbonsSummarySpriteGfxStep(void);
void InitRibbonIconSpriteSheets(void);
bool8 LoadRibbonIconSpriteSheetStep(void);
void CreateAndZoomInSelectedRibbon(void);
bool8 IsRibbonZoomInAnimating(void);
void ZoomOutSelectedRibbon(void);
bool8 UpdateRibbonZoomOutAndDestroySprite(void);
void FreeRibbonsSummarySprites(void);
void InitConditionSparkles(u8, u8);
void ShowAllConditionSparkles(void);
void InitPokenavIconSprite(void);
bool8 LoadPokenavIconSpriteStep(void);
void CreateTrainerEyesNameSprites(u8*);
void DestroyTrainerEyesNameSprites(void);
u8 *BufferPokenavMonNameGenderLevelText(u8*, u16, u8);
u8 *BufferConditionSearchRankText(u8 *, u16);
void ConditionGraph_CalcPositions(u8*, struct UnkPokenav11 *);
void PrepareConditionGraphFromSearchResult(void);
void InitConditionSearchResults(void);
bool8 BuildConditionSearchResultsStep(void);
void ConditionGraph_SetNewPositions(struct UnkPokenav11*, struct UnkPokenav11*);
bool8 ConditionGraph_TryUpdate(void);
bool8 UpdateConditionGraphScrollToMon(void);
bool8 UpdateConditionGraphScrollToEmpty(void);
bool8 UpdateConditionGraphScrollBetweenMons(void);

void InitPokenavListRows(void);
void SetConditionGraphWindowRegs(void);
void InitRegionMapCityBanner(void);
void sub_8095C8C();
void HideRegionMapCityBanner(void);
void ShowRegionMapCityBanner(void);
bool8 DecompressCityMapsStep(void);
void InitCityMapDecompression(void);
void BuildPokenavPaletteGradient(const u16 *startColors, const u16 *endColors, u8 stepCount, u8 colorCount, u16 *gradient);
void StartPokenavBg3Scroll(void);
void SetPokenavMenuPalette(u8 menuType);
void InitPokenavPaletteGradient(u8 stage);
void sub_80F6FFC();
void sub_80F6FB8(bool8);
void sub_80F6DB8();
bool8 sub_80F6E9C();
bool8 sub_80F6ED4();
bool8 sub_80F70FC();
void sub_80F708C(s8);
void sub_80F6F10();
void PrintRibbonsSummaryCount(void);
void sub_80F6A4C(s8);
bool8 sub_80F6AF0();
u8 sub_80F68E8();
void InitRibbonsSummaryMonData();
void InitRibbonsMonList();
bool8 BuildRibbonsMonListStep();
void InitConditionGraphScreen(void);
bool8 LoadConditionGraphScreenStep(void);
void RestorePokenavListSelection();
u8 HandlePokenavListDpadInput();
void InitPokenavListScreen(u8 listMode);
bool8 LoadPokenavListScreenStep(void);
void UpdateMapSecInfoWindow(void);
bool8 UpdateRegionMapBgYForZoom(bool8 zoomOut);
void UpdateRegionMapBottomToolbar(void);
void DrawPokenavBottomToolbar(u8 toolbarId);
void StopPokenavBg3Scroll(void);
void InitPokenavRegionMapGfx(void);
bool8 LoadPokenavRegionMapGfxStep(void);
bool8 AnyMonHasRibbonScanStep();
void sub_80F6C20();
void InitPokenavMenuGfx(u8 menuType);
bool8 LoadPokenavMenuGfxStep(u8 menuType);
void PrintPokenavMenuDescription(u8 menuType, u8 itemId);
bool8 SlideMenuHeaderDown(void);
void InitPokenavState(void);
void SetPokenavCallback(void (*callback)(void));
void CB2_ContinueInitPokeNav(void);
void InitPokenavMainMenu(void);
void CB2_Pokenav(void);
void VBlankCB_Pokenav(void);
void sub_80FB260();
void UpdateRegionMapCityBanner(void);
void ConditionGraph_Draw();
void sub_80F6F64();

#endif // GUARD_POKENAV_H
