Route109_Text_DavidIntro:: @ 81B9A1C
	.string "Hiya! Schau dir meine gemeißelten \n"
	.string "Vollmatrosen an! Das nennt\l"
	.string "man einen “Schnitt”!$"

Route109_Text_DavidDefeated:: @ 81B9A59
	.string "Aiyah!\n"
	.string "Ausgerutscht.$"

Route109_Text_DavidPostBattle:: @ 81B9A6D
	.string "Hiyah!\p"
	.string "Meine gemeißelten Vollmatrosen haben\n"
	.string "nichts mit meinen Kämpfen zu tun!$"

Route109_Text_AliceIntro:: @ 81B9AAD
	.string "Hast du dich auch gut mit Sonnenmilch\n"
	.string "eingerieben?$"

Route109_Text_AliceDefeated:: @ 81B9AD9
	.string "Aua, aua, aua.$"

Route109_Text_AlicePostBattle:: @ 81B9AEB
	.string "An den Wangen bekommt man als Erstes\n"
	.string "einen Sonnenbrand.$"

Route109_Text_HueyIntro:: @ 81B9B11
	.string "Ich habe meinen Anker in vielen Häfen\n"
	.string "der Welt geworfen, aber GRAPHITPORT\l"
	.string "CITY ist der schönste Hafen.$"

Route109_Text_HueyDefeated:: @ 81B9B57
	.string "Du bist der Beste!$"

Route109_Text_HueyPostBattle:: @ 81B9B68
	.string "Im besten Hafen gibt es auch den\n"
	.string "besten TRAINER...$"

Route109_Text_EdmondIntro:: @ 81B9B91
	.string "Urrrrppp...\n"
	.string "Kämpfen? Mit mir?$"

Route109_Text_EdmondDefeated:: @ 81B9BAE
	.string "Böör... Ooooooohhhhhh...\n"
	.string "Bööörrppp...$"

Route109_Text_EdmondPostBattle:: @ 81B9BD3
	.string "Normalerweise bin ich viel stärker!\n"
	.string "Ich bin seekrank!\p"
	.string "Ich bin MATROSE, aber...$"

Route109_Text_RickyIntro:: @ 81B9C23
	.string "Ich bin durstig... Ich könnte im\n"
	.string "STRANDHAUS etwas SPRUDEL kaufen...$"

Route109_Text_RickyDefeated:: @ 81B9C65
	.string "Grummel...$"

Route109_Text_RickyPostBattle:: @ 81B9C6E
	.string "Ich bin am Verhungern... Mein Schwimm-\n"
	.string "reifen sieht aus wie ein Schmalzkringel.$"

Route109_Text_RickyRematchIntro:: @ 81B9CB3
	.string "Ich habe tierischen Hunger, aber ich\n"
	.string "habe genug Kraft für einen Kampf!$"

Route109_Text_RickyRematchDefeated:: @ 81B9CEB
	.string "Ich habe verloren...\n"
	.string "Und das nur, weil ich so hungrig bin...$"

Route109_Text_RickyRematchPostBattle:: @ 81B9D10
	.string "Wenn man am Strand sitzt und isst,\n"
	.string "schmeckt alles gleich viel besser.$"

Route109_Text_LolaIntro:: @ 81B9D54
	.string "So ein Sonnenschirm sieht doch aus wie\n"
	.string "eine riesige Blume, findest du nicht?$"

Route109_Text_LolaDefeated:: @ 81B9D87
	.string "Maaaami!$"

Route109_Text_LolaPostBattle:: @ 81B9D8E
	.string "Ein Strand sieht aus der Luft be-\n"
	.string "trachtet wie ein Blumengarten aus.$"

Route109_Text_LolaRematchIntro:: @ 81B9DD8
	.string "Ich verliere nicht wieder gegen dich!\n"
	.string "Schließlich habe ich einen Schwimm-\l"
	.string "reifen um!$"

Route109_Text_LolaRematchDefeated:: @ 81B9E16
	.string "Maaaaaaaaaaamiiiii!$"

Route109_Text_LolaRematchPostBattle:: @ 81B9E1D
	.string "Sobald ich den Schwimmreifen trage,\n"
	.string "sehen meine POKéMON und ich noch\l"
	.string "niedlicher aus!$"

Route109_Text_CarmenIntro:: @ 81B9E60
	.string "Ohne Schwimmreifen kann ich nicht\n"
	.string "schwimmen, aber im Kampf siege ich.$"

Route109_Text_CarmenDefeated:: @ 81B9EA1
	.string "Habe ich verloren, weil ich einen\n"
	.string "Schwimmreifen trage?$"

Route109_Text_CarmenPostBattle:: @ 81B9ECA
	.string "Mein Schwimmreifen ist voll in Mode. Ohne\n"
	.string "ihn kann ich mich nicht sehen lassen!$"

Route109_Text_GwenIntro:: @ 81B9F07
	.string "Hey, großer TRAINER!\n"
	.string "Kämpfst du mit mir?$"

Route109_Text_GwenDefeated:: @ 81B9F31
	.string "Oh, bist du aber stark!$"

Route109_Text_GwenPostBattle:: @ 81B9F44
	.string "Wie bist du so stark geworden?$"

Route109_Text_CarterIntro:: @ 81B9F65
	.string "Hahaha! Dieser Kerl hier wird jetzt\n"
	.string "einen großen Fang machen!$"

Route109_Text_CarterDefeated:: @ 81B9F9C
	.string "Dieser Kerl hier hat ganz groß verloren.$"

Route109_Text_CarterPostBattle:: @ 81B9FB7
	.string "Dieser Kerl hier denkt, dass du ganz\n"
	.string "groß bist. Nein, ein Gernegroß bist!$"

Route109_Text_PaulIntro:: @ 81B9FF6
	.string "OLE: Nun, das ist ein Stimmungstöter!\p"
	.string "Ich wünschte, du würdest uns nicht \n"
	.string "unsere kostbare Zeit rauben!$"

Route109_Text_PaulDefeated:: @ 81BA052
	.string "OLE: Nun, ich gebe mich geschlagen.$"

Route109_Text_PaulPostBattle:: @ 81BA069
	.string "OLE: Nun, sag niemandem, dass wir\n"
	.string "hier sind. Das ist unsere kleine, private\l"
	.string "Welt!$"

Route109_Text_PaulNotEnoughPokemon:: @ 81BA0BF
	.string "OLE: Wir sind total heftig ineinander\n"
	.string "verliebt. Deshalb lassen wir unsere\l"
	.string "POKéMON auch gemeinsam kämpfen.$"

Route109_Text_MelIntro:: @ 81BA114
	.string "GELI: Wir sind total ineinander verliebt.\n"
	.string "Unsere Romanze wärmt ganz HOENN!$"

Route109_Text_MelDefeated:: @ 81BA15F
	.string "GELI: Wir haben verloren. Das ist meine\n"
	.string "Schuld. OLE wird mich hassen!$"

Route109_Text_MelPostBattle:: @ 81BA193
	.string "GELI: Ähm, OLE, bist du böse auf mich?\n"
	.string "Bitte sei nicht böse auf mich!$"

Route109_Text_MelNotEnoughPokemon:: @ 81BA1D0
	.string "GELI: Wir sind total heftig ineinander\n"
	.string "verliebt. Daher kämpfen wir auch mit\l"
	.string "unseren POKéMON zusammen.$"
