Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:: @ 81C5EC6
	.string "Hello!\p"
	.string "This is the PRETTY PETAL flower shop.\n"
	.string "Spreading flowers throughout the world!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:: @ 81C5F1B
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:: @ 81C5F48
	.string "Your name is?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "That's a nice name.\p"
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:: @ 81C5F9D
	.string "BERRIES grow on trees that thrive\n"
	.string "only in dark, loamy soil.\p"
	.string "If you take some BERRIES, be sure to\n"
	.string "plant one in the loamy soil again.\p"
	.string "A planted BERRY will soon sprout,\n"
	.string "grow into a plant, flower beautifully,\l"
	.string "then grow BERRIES again.\p"
	.string "I want to see the whole wide world\n"
	.string "filled with beautiful flowers.\l"
	.string "That's my dream.\p"
	.string "Please help me, {PLAYER}{KUN}. Plant BERRIES\n"
	.string "and bring more flowers into the world.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:: @ 81C6121
	.string "Flowers bring so much happiness to\n"
	.string "people, don't they?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:: @ 81C6158
	.string "Hello!\p"
	.string "The more attention you give to flowers,\n"
	.string "the more beautifully they bloom.\p"
	.string "You'll like tending flowers. I'm sure\n"
	.string "of it. You can have this.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:: @ 81C61E8
	.string "While BERRY plants are growing,\n"
	.string "water them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground.\l"
	.string "But they'll sprout again.\p"
	.string "Isn't that awesome?\n"
	.string "It's like they have the will to live.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:: @ 81C62DA
	.string "I'm trying to be like my big sisters.\n"
	.string "I'm growing flowers, too!\p"
	.string "Here you go! It's for you!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:: @ 81C6335
	.string "You can plant a BERRY and grow it big,\n"
	.string "or you can make a POKéMON hold it.\p"
	.string "But now they have a machine that mixes\n"
	.string "up different BERRIES and makes candies\l"
	.string "for POKéMON.\p"
	.string "I want some candy, too.$"
