ShoalCave_LowTideLowerRoom_Text_CanOvercomeColdWithFocus:: @ 8198200
	.string "Die eisige Kälte in dieser Gegend ist\n"
	.string "ein gewaltiges Hindernis beim Training.\p"
	.string "Aber wenn man sich konzentriert, kann\n"
	.string "man doch gewinnen!\p"
	.string "Mit diesem FOKUS-BAND kannst du dich\n"
	.string "besser konzentrieren und der Kälte\l"
	.string "widerstehen.$"

ShoalCave_LowTideLowerRoom_Text_EverythingStartsWithFocus:: @ 81982A2
	.string "Alles hängt von der Konzentration ab!$"
