Route115_Text_NeverKnowWhenCavePokemonWillAppear:: @ 8170273
	.string "Höhlenforschung ist nicht mit einem\n"
	.string "Spaziergang auf einer Straße zu\l"
	.string "vergleichen.\p"
	.string "Du weißt nie, wann ein wildes POKéMON\n"
	.string "auftaucht. Du bist immer angespannt.$"

Route115_Text_RouteSignRustboro:: @ 81702E7
	.string "ROUTE 115\n"
	.string "{DOWN_ARROW} METAROST CITY$"

Route115_Text_MeteorFallsSign:: @ 8170301
	.string "METEORFÄLLE\n"
	.string "LAUBWECHSELFELD HIER ENTLANG$"
