Route115_Text_TimothyIntro:: @ 81BC9AC
	.string "Hm...\n"
	.string "Du siehst ganz kompetent aus...\l"
	.string "Ich leiste dir Gesellschaft!$"

Route115_Text_TimothyDefeat:: @ 81BC9E6
	.string "Du bist viel stärker, als ich mir das\n"
	.string "vorgestellt hatte.$"

Route115_Text_TimothyPostBattle:: @ 81BCA0E
	.string "Man wird nicht als Genie geboren!\n"
	.string "Alles basiert auf Anstrengung!\l"
	.string "Das ist meine Meinung...$"

Route115_Text_TimothyRematchIntro:: @ 81BCA6B
	.string "Hm... Deine Flinkheit spricht mal wieder\n"
	.string "für sich.\l"
	.string "Komm, leiste mir erneut Gesellschaft!$"

Route115_Text_TimothyRematchDefeat:: @ 81BCAB3
	.string "Stark wie immer!$"

Route115_Text_TimothyPostRematch:: @ 81BCAC6
	.string "Alles verlangt ein Maß an Anstrengung!\p"
	.string "Ich habe verloren, weil ich mich nicht\n"
	.string "genügend angestrengt habe.$"

Route115_Text_KoichiIntro:: @ 81BCB0D
	.string "Du!\p"
	.string "Meine MACHOLLO!\p"
	.string "Verlangen einen Kampf!$"

Route115_Text_KoichiDefeat:: @ 81BCB2E
	.string "Aua aua aua aua!$"

Route115_Text_KoichiPostBattle:: @ 81BCB40
	.string "Meine MACHOLLO haben gejauchzt!\p"
	.string "Solange meine POKéMON nach Stärke\n"
	.string "suchen, werde auch ich stärker!$"

Route115_Text_NobIntro:: @ 81BCB8A
	.string "Mein Talent ist, Ziegelsteine mit meiner\n"
	.string "Stirn zu zertrümmern.$"

Route115_Text_NobDefeat:: @ 81BCBC1
	.string "Uguaaah!\n"
	.string "Mein Kopf wurde zertrümmert.$"

Route115_Text_NobPostBattle:: @ 81BCBDE
	.string "Ich bringe meinem POKéMON Karate bei.\p"
	.string "Und es sieht so aus, als wäre es darin\n"
	.string "viel besser als ich. Das freut mich.$"

Route115_Text_NobRematchIntro:: @ 81BCC4C
	.string "Nachdem du uns besiegt hattest, haben\n"
	.string "wir hart trainiert, um besser zu werden.\l"
	.string "Heute fordern wir Revanche!$"

Route115_Text_NobRematchDefeat:: @ 81BCCA2
	.string "Uguaaah!\n"
	.string "Wir haben schon wieder verloren!$"

Route115_Text_NobPostRematch:: @ 81BCCBA
	.string "Meine POKéMON werden stärker! Ich\n"
	.string "habe mein Trainingspensum verdoppelt.$"

Route115_Text_CyndyIntro:: @ 81BCCF4
	.string "Dieser Strand ist mein geheimer\n"
	.string "Trainingsort. Du hast mich gestört!$"

Route115_Text_CyndyDefeat:: @ 81BCD32
	.string "Ich habe nicht genug trainiert.$"

Route115_Text_CyndyPostBattle:: @ 81BCD4C
	.string "Der Sand ist wie ein Kissen, das den\n"
	.string "Sturz abfängt und Verletzungen ver-\l"
	.string "hindert. Der perfekte Trainingsort.$"

Route115_Text_CyndyRematchIntro:: @ 81BCDB0
	.string "Okay, lass uns weiter kämpfen.$"

Route115_Text_CyndyRematchDefeat:: @ 81BCDD0
	.string "Ich kann kämpfen, aber meine POKéMON...$"

Route115_Text_CyndyPostRematch:: @ 81BCDEF
	.string "Sogar wenn ich verliere, habe ich meine\n"
	.string "Freude an dem Kampf. Wahrscheinlich\l"
	.string "weil ich die POKéMON liebe.$"

Route115_Text_HectorSapphireIntro: @ 81BCE47
	.string "Ich habe ein seltenes POKéMON.\n"
	.string "Möchtest du das mal sehen?$"

Route115_Text_HectorSapphireDefeat: @ 81BCE7D
	.string "Du...\n"
	.string "Du willst mein POKéMON haben, oder?$"

Route115_Text_HectorSapphirePostBattle: @ 81BCEA4
	.string "Ich habe ein seltenes POKéMON. Das\n"
	.string "reicht mir, um zufrieden zu sein.$"

Route115_Text_HectorIntro:: @ 81BCEE0
	.string "Ich habe ein seltenes POKéMON.\n"
	.string "Willst du das mal sehen?$"

Route115_Text_HectorDefeat:: @ 81BCF16
	.string "Du... Du versuchst mir mein POKéMON\n"
	.string "abspenstig zu machen, oder?$"

Route115_Text_HectorPostBattle:: @ 81BCF3D
	.string "Und ich habe immer noch mein seltenes\n"
	.string "POKéMON, und damit bin ich zufrieden!$"
