Route104_Prototype_Text_CindyIntro:: @ 819AD9B
	.string "Oh! Du siehst wie ein guter TRAINER aus.\n"
	.string "Schaust du dir mal meine POKéMON an?$"

Route104_Prototype_Text_CindyDefeated:: @ 819ADDA
	.string "Ich bin nicht gut genug für dich.$"

Route104_Prototype_Text_CindyPostBattle:: @ 819ADF7
	.string "Ich habe den Kampf richtig genossen.\n"
	.string "Bitte kämpfe bald wieder mit mir.$"

Route104_Prototype_Text_AmyAndLivIntro:: @ 819AE3E
	.string "Los!\n"
	.string "Los, POKéMON!$"

Route104_Prototype_Text_AmyAndLivDefeated:: @ 819AE53
	.string "Oh... Wir hatten keine Chance.$"

Route104_Prototype_Text_AmyAndLivPostBattle:: @ 819AE6A
	.string "Überrascht es dich, dass zwei POKéMON\n"
	.string "zur gleichen Zeit kämpften?$"

Route104_Prototype_Text_AmyAndLivNotEnoughPokemon:: @ 819AEA9
	.string "Du kannst nicht mit uns kämpfen, wenn\n"
	.string "du nur ein POKéMON hast. Warum nicht?\l"
	.string "Nun, weil wir stark sind!$"

Route104_Prototype_Text_MikeIntro:: @ 819AEFB
	.string "Hey, hey! Das ist seit langer Zeit mein\n"
	.string "erster Kampf. Ich gebe mein Bestes!$"

Route104_Prototype_Text_MikeDefeated:: @ 819AF3E
	.string "Ich habe doch mein Bestes gegeben...$"

Route104_Prototype_Text_MikePostBattle:: @ 819AF56
	.string "Du bist viel zu stark!\n"
	.string "Du musst ein großer TRAINER sein!$"

Route104_Prototype_Text_BriannaIntro:: @ 819AF8A
	.string "Meine POKéMON sind sehr niedlich und\n"
	.string "sehr stark.\l"
	.string "Das möchte ich dir gerne zeigen.$"

Route104_Prototype_Text_BriannaDefeated:: @ 819AFDB
	.string "Ich gebe mich geschlagen.\n"
	.string "Du bist wirklich stark.$"

Route104_Prototype_Text_BriannaPostBattle:: @ 819B00D
	.string "Wenn wir uns das nächste Mal treffen, \n"
	.string "werden meine POKéMON stärker sein!\p"
	.string "Und erwarte dann keine Gnade!$"

Route104_Prototype_Text_LucasIntro:: @ 819B066
	.string "Wir WANDERER sind stets voller Energie!\n"
	.string "Auch meine POKéMON sind voller Energie!\l"
	.string "Wir sind stets auf einen Kampf aus!$"

Route104_Prototype_Text_LucasDefeated:: @ 819B0D7
	.string "Uns ist die Energie ausgegangen...$"

Route104_Prototype_Text_LucasPostBattle:: @ 819B0EF
	.string "Hahahaha! Natürlich, wir haben verloren.\n"
	.string "Aber es war ein toller Kampf, oder?\l"
	.string "Wir sind jedenfalls zufrieden damit!$"

Route104_Prototype_Text_GinaAndMiaIntro:: @ 819B148
	.string "Du siehst wie ein starker TRAINER aus,\n"
	.string "aber kannst du uns auch schlagen?$"

Route104_Prototype_Text_GinaAndMiaDefeated:: @ 819B17D
	.string "Waaah!\n"
	.string "Wir haben verloren!$"

Route104_Prototype_Text_GinaAndMiaPostBattle:: @ 819B18D
	.string "Wenn zwei POKéMON zur gleichen Zeit\n"
	.string "kämpfen können, ist alles möglich.$"

Route104_Prototype_Text_GinaAndMiaNotEnoughPokemon:: @ 819B1DD
	.string "Hast du nur ein POKéMON, das\n"
	.string "kämpfen kann?\p"
	.string "Dann können wir nicht mit dir kämpfen.$"

Route104_Prototype_Text_BoyAskDefeatAllTrainers:: @ 819B22E
	.string "Hast du versucht, alle anderen TRAINER\n"
	.string "im Kampf zu besiegen?$"

Route104_Prototype_Text_BoyThankYouForComing:: @ 819B267
	.string "Danke, dass du heute gekommen bist!\p"
	.string "Ich hoffe, du freust dich auch auf das\n"
	.string "Erscheinen dieses Spiels!$"

Route104_Prototype_Text_GirlAskDefeatAllTrainers:: @ 819B2B6
	.string "Was? Du bist schon gegen alle TRAINER\n"
	.string "angetreten?$"

Route104_Prototype_Text_GirlThankYouForComing:: @ 819B2E9
	.string "Danke, dass du heute gekommen bist!\p"
	.string "Ich hoffe, du freust dich auch auf das\n"
	.string "Erscheinen dieses Spiels!$"

Route104_Prototype_Text_NeverSeenPokemonLikeYours:: @ 819B33B
	.string "POKéMON, wie du sie hast, habe ich noch\n"
	.string "nie gesehen. Ich bin richtig neidisch!$"

Route104_Prototype_Text_TrainersAreWaitingForYou:: @ 819B37F
	.string "Schau dir all diese TRAINER an! Sie\n"
	.string "haben alle die unterschiedlichsten\l"
	.string "POKéMON. Und sie warten alle auf dich!$"

Route104_Prototype_Text_WelcomeToWorldOfPokemon:: @ 819B3DE
	.string "Willkommen in der Welt der POKéMON!$"

Route104_Prototype_Text_PokemonBattlesMessage:: @ 819B3FF
	.string "Mögen alle POKéMON-Kämpfe strahlend,\n"
	.string "unterhaltsam und wild sein!$"
