Route113_Text_NealIntro:: @ 81BB9BA
	.string "Can you guess why it's so cool\n"
	.string "around here?$"

Route113_Text_NealDefeat:: @ 81BB9E6
	.string "Peeuuw!\n"
	.string "That stinks!$"

Route113_Text_NealPostBattle:: @ 81BB9FB
	.string "The volcanic ash blocks the sun, so it\n"
	.string "doesn't get very warm.\p"
	.string "That's good for me - I can't stand heat!$"

Route113_Text_DillonIntro:: @ 81BBA62
	.string "The volcano's eruption is proof that\n"
	.string "the earth is alive.$"

Route113_Text_DillonDefeat:: @ 81BBA9B
	.string "You're some kind of strong!$"

Route113_Text_DillonPostBattle:: @ 81BBAB7
	.string "Ouch! Owww! I can't see!\n"
	.string "I got ashes in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was bad, sorry...$"

Route113_Text_MadelineIntro:: @ 81BBB27
	.string "I use this parasol to ward off this\n"
	.string "filthy, yucky volcanic ash from my\l"
	.string "dear NUMEL.$"

Route113_Text_MadelineDefeat:: @ 81BBB7A
	.string "Huff, huff...\n"
	.string "I am exhausted...$"

Route113_Text_MadelinePostBattle:: @ 81BBB9A
	.string "You're very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_MadelineRematchIntro:: @ 81BBBCE
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:: @ 81BBC0D
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch:: @ 81BBC1C
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_LaoIntro:: @ 81BBC59
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoDefeat:: @ 81BBC90
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostBattle:: @ 81BBCAB
	.string "I must refine the art of concealment.\n"
	.string "I bid thee farewell.$"

Route113_Text_LaoRematchIntro:: @ 81BBCE6
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat:: @ 81BBD1D
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch:: @ 81BBD38
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills...\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:: @ 81BBD92
	.string "Thanks for finding me!\n"
	.string "But we still have to battle!$"

Route113_Text_LungDefeat:: @ 81BBDC6
	.string "I'll use my ninjutsu on you...\n"
	.string "“VOLCANIC ASH SWIRL CLOAK”!\p"
	.string "...What? It's already over?$"

Route113_Text_LungPostBattle:: @ 81BBE1D
	.string "You know what's crummy about hiding?\n"
	.string "It's lonely if no one comes along.$"

Route113_Text_ToriIntro:: @ 81BBE65
	.string "TORI: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_ToriDefeat:: @ 81BBEA1
	.string "TORI: We lost... It's boring, so I'm going\n"
	.string "to get some more ashes.$"

Route113_Text_ToriPostBattle:: @ 81BBEE4
	.string "TORI: How much ash do we have?\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_ToriNotEnoughMons:: @ 81BBF25
	.string "TORI: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_TiaIntro:: @ 81BBF62
	.string "TIA: Both of us, we collect ashes.\n"
	.string "We battle POKéMON, too.$"

Route113_Text_TiaDefeat:: @ 81BBF9D
	.string "TIA: We couldn't win... It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_TiaPostBattle:: @ 81BBFE2
	.string "TIA: We have a lot of ashes!\n"
	.string "I think enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:: @ 81BC021
	.string "TIA: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"
