Route130_Text_RodneyIntro:: @ 81C2401
	.string "Was für eine Überraschung! Ich habe im\n"
	.string "Meer keinen TRAINER erwartet.\p"
	.string "Ich denke, wir sollten kämpfen.$"

Route130_Text_RodneyDefeat:: @ 81C245D
	.string "Dieses Kind ist unglaublich stark.$"

Route130_Text_RodneyPostBattle:: @ 81C2479
	.string "Deine Augen haben den Ausdruck eines\n"
	.string "Menschen, der harte Herausforderungen\l"
	.string "siegreich gemeistert hat. Das steht dir.$"

Route130_Text_KatieIntro:: @ 81C24DC
	.string "Im tiefen, blauen Meer fand mein\n"
	.string "schwermütiges Herz Trost in den\l"
	.string "wogenden Wellen.$"

Route130_Text_KatieDefeat:: @ 81C2525
	.string "Wie das weite Meer umspannt auch die \n"
	.string "Welt der POKéMON Weiten jenseits\l"
	.string "unseres Erfahrungshorizontes.$"

Route130_Text_KatiePostBattle:: @ 81C256E
	.string "Die Kinder dieser Welt träumen davon,\n"
	.string "eines Tages der POKéMON CHAMP zu\l"
	.string "werden.$"
