Route129_Text_ChaseIntro:: @ 81C2161
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat:: @ 81C2198
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle:: @ 81C21B4
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro:: @ 81C21ED
	.string "I'm in the middle of a triathlon, but,\n"
	.string "sure, why don't we battle?$"

Route129_Text_AllisonDefeat:: @ 81C222F
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle:: @ 81C2243
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro:: @ 81C22C8
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat:: @ 81C22EC
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle:: @ 81C230F
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro:: @ 81C2349
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat:: @ 81C2378
	.string "Oh, my.\n"
	.string "I wanted to relax a little more...$"

Route129_Text_TishaPostBattle:: @ 81C23A3
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"
