Hideout_B2F_Text_EvilTeamAdminIntro:: @ 8197093
	.string "Hehehe...\p"
	.string "Got here already, did you?\n"
	.string "We underestimated you!\p"
	.string "But this is it!\p"
	.string "I'm a cut above the GRUNTS you've seen\n"
	.string "so far.\p"
	.string "I'm not stalling for time. I'm going\n"
	.string "to pulverize you!$"

Hideout_B2F_Text_EvilTeamAdminDefeat:: @ 8197145
	.string "Hehehe...\n"
	.string "So, I lost, too...$"

Hideout_B2F_Text_BossPreparedSubmarine:: @ 8197162
	.string "Hehehe!\p"
	.string "While I was toying with you, our BOSS\n"
	.string "got through his preparations!$"

Hideout_B2F_Text_EvilTeamAdminPostBattle:: @ 81971AE
	.string "Hehehe!\p"
	.string "Our BOSS has already gone on his way to\n"
	.string "some cave under the sea!\p"
	.string "If you're going to give chase, you'd\n"
	.string "better search the big, wide sea beyond\l"
	.string "LILYCOVE.\p"
	.string "But will you find it then?\n"
	.string "Hehehe!$"

Hideout_B2F_Text_EvilTeamGrunt2Intro:: @ 8197270
	.string "Wahahah, I grew weary of waiting!\n"
	.string "You owe me a battle, too!$"

Hideout_B2F_Text_EvilTeamGrunt2Defeat:: @ 81972AC
	.string "Tired of waiting...\n"
	.string "Lost and dazed...$"

Hideout_B2F_Text_EvilTeamGrunt2PostBattle:: @ 81972D2
	.string "BOSS...\n"
	.string "Is this good enough?$"

Hideout_B2F_Text_EvilTeamGrunt3Intro:: @ 81972EF
	.string "Warp panels, the HIDEOUT's pride\n"
	.string "and joy!\p"
	.string "You're clueless about where you are,\n"
	.string "aren't you?\p"
	.string "Fluster and tire out the enemy, then\n"
	.string "lower the boom! That's our plan!$"

Hideout_B2F_Text_EvilTeamGrunt3Defeat:: @ 8197390
	.string "What's wrong with you?\n"
	.string "You're not tired at all!$"

Hideout_B2F_Text_EvilTeamGrunt3PostBattle:: @ 81973C0
	.string "That reminds me... I can't remember\n"
	.string "where I put the MASTER BALL.\p"
	.string "If I fail to guard it, our BOSS will\n"
	.string "chew me out...$"
