BattleTower_BattleRoom_Text_RestoreMonsToFullHealth:: @ 819ACDC
	.string "We will restore your POKéMON to\n"
	.string "full health.$"

BattleTower_BattleRoom_Text_ReadyForOpponent:: @ 819AD09
	.string "You will be facing opponent no. {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_SaveAndQuitGame:: @ 819AD3C
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleTower_BattleRoom_Text_CancelYourChallenge:: @ 819AD66
	.string "Would you like to cancel your BATTLE\n"
	.string "ROOM challenge?$"
