LilycoveCity_ContestHall_Text_TodayWonSmartnessContest:: @ 81890D4
	.string "Dieses POKéMON hat den vorherigen\n"
	.string "SCHÖNHEITSWETTBEWERB gewonnen.\p"
	.string "Weißt du was? Heute werde ich den\n"
	.string "KLUGHEITS-WETTBEWERB gewinnen!\p"
	.string "Meine Fähigkeiten erstaunen sogar\n"
	.string "mich...$"

LilycoveCity_ContestHall_Text_EnteredBunchOfContests:: @ 818915F
	.string "Ich habe einige WETTBEWERBE mitge-\n"
	.string "macht, weil ich wissen wollte, wie\l"
	.string "das so läuft.\p"
	.string "Wenn du an einem COOLNESS-WETTBEWERB\n"
	.string "teilnimmst, zählen coole Attacken.\p"
	.string "Anmutige oder kluge Attacken sind\n"
	.string "dagegen nicht so angesagt.$"

LilycoveCity_ContestHall_Text_ManWhoWonEarlierHadPokeblocks:: @ 8189221
	.string "Der junge Mann, der vor kurzem hier ge-\n"
	.string "wonnen hat, hatte viele verschiedene\l"
	.string "{POKEBLOCK} bei sich.\p"
	.string "Ob man gewinnt, wenn man genug dieser\n"
	.string "Items dabei hat?$"

LilycoveCity_ContestHall_Text_IsntThisPlaceHumongous:: @ 8189299
	.string "Wow, dieser Ort ist einfach riesig!\p"
	.string "Diese Spannung in der Luft... Das ist\n"
	.string "kein Vergleich zu einer WETTBEWERBS-\l"
	.string "HALLE in der tiefsten Provinz.$"

LilycoveCity_ContestHall_Text_GiveItBestSmartAppeal:: @ 8189301
	.string "MC: Okay, KLUGE POKéMON und TRAINER.\n"
	.string "Seid ihr bereit?!?\p"
	.string "Gebt euer Bestes!\n"
	.string "Es geht um den Ausdruck!$"

LilycoveCity_ContestHall_Text_AreYouEnjoyingThisContest:: @ 8189366
	.string "JUROR: Gefällt euch dieser\n"
	.string "WETTBEWERB?\p"
	.string "Komm mit drei Freunden wieder her,\n"
	.string "dann könnt ihr alle gemeinsam am\l"
	.string "WETTBEWERB teilnehmen.$"

LilycoveCity_ContestHall_Text_EnteredWrongContest:: @ 81893CE
	.string "Eieieiei...\n"
	.string "Ich habe am falschen WETTBEWERB teil-\l"
	.string "genommen. Hach...\p"
	.string "Ich habe dieses starke POKéMON in\n"
	.string "einen KLUGHEITS-WETTBEWERB geschickt.\p"
	.string "Los, beeindrucke mit einem\n"
	.string "klugen ZERTRÜMMERER.$"

LilycoveCity_ContestHall_Text_RaisedMonToBeSmart:: @ 8189463
	.string "Ich habe viele Jahre und all meine\n"
	.string "Weisheit gebraucht, um dieses POKéMON\l"
	.string "klug zu machen.\p"
	.string "Damit mache ich es den jungen Spunden\n"
	.string "nicht leicht, mein POKéMON zu über-\l"
	.string "trumpfen.\p"
	.string "Mein holdes Weib, siehst du das?$"

LilycoveCity_ContestHall_Text_IfMonPullsSmartMoveNext:: @ 8189512
	.string "Das ist es!\p"
	.string "Wenn mein POKéMON eine kluge Attacke\n"
	.string "vorführt, wird das Publikum ausflippen\l"
	.string "vor Begeisterung!$"

LilycoveCity_ContestHall_Text_DontAppreciateCuteLeechLife:: @ 818956B
	.string "Oh, du liebe Güte, nein!\p"
	.string "Der BLUTSAUGER meines ZUBAT ist\n"
	.string "wirklich anmutig, daher setze ich ihn\l"
	.string "immer wieder ein!\p"
	.string "Aber diese gemeinen Leute wissen das\n"
	.string "überhaupt nicht zu schätzen!$"

LilycoveCity_ContestHall_Text_YoureBeautifulGrandpa:: @ 81895F3
	.string "Kiaaayh! Du bist wunderbar, Opa!$"

LilycoveCity_ContestHall_Text_AllSeemToUseDifferentMoves:: @ 8189617
	.string "Selbst wenn die TRAINER die gleichen\n"
	.string "POKéMON einsetzen, so führen sie doch\l"
	.string "unterschiedliche Attacken vor.\p"
	.string "Das ist so wie bei den Kämpfen: Jeder\n"
	.string "hat seinen eigenen Stil.$"

LilycoveCity_ContestHall_Text_PokemonSmarterThanTrainers:: @ 81896BE
	.string "Ich denke, die POKéMON machen einen\n"
	.string "klügeren Eindruck als ihre TRAINER.$"

LilycoveCity_ContestHall_Text_StillLoveSmartnessContests:: @ 81896FE
	.string "Jetzt, wo alles vorbei ist, liebe ich\n"
	.string "KLUGHEITS-WETTBEWERBE noch immer.\p"
	.string "Diese intellektuelle, grüne Farbe...\n"
	.string "Das ist so... so... so cooool!$"

LilycoveCity_ContestHall_Text_AreYouEnteringBeautyContest:: @ 8189771
	.string "MC: Nimmst du auch am SCHÖNHEITS-\n"
	.string "WETTBEWERB teil? Viel Glück!$"

LilycoveCity_ContestHall_Text_EveryPokemonPristineBeauty:: @ 81897AA
	.string "JUROR: Ah, jedes POKéMON ist ein\n"
	.string "Beispiel makelloser Schönheit!\p"
	.string "Huch, fast hätte ich vergessen, sie zu\n"
	.string "bewerten...$"

LilycoveCity_ContestHall_Text_EyesWillBeGluedToMyBeauty:: @ 818980B
	.string "Ein POKéMON von dieser Schönheit...\n"
	.string "Es gibt keines wie dieses.\p"
	.string "Jedem werden die Augen übergehen, wenn\n"
	.string "er diese Schönheit betrachtet.$"

LilycoveCity_ContestHall_Text_OverdidGrooming:: @ 8189874
	.string "Aaaaargh!\p"
	.string "Ich habe mein POKéMON für diesen WETT-\n"
	.string "BEWERB sorgfältig gebürstet und\l"
	.string "gestriegelt.\p"
	.string "Dabei habe ich wohl übertrieben...\n"
	.string "Das Fell meines POKéMON ist nun ganz\l"
	.string "voller Fusseln...\p"
	.string "Was soll ich jetzt nur tun?$"

LilycoveCity_ContestHall_Text_JudgeWontSeeAuroraBeam:: @ 818990A
	.string "Der AURORASTRAHL ist eine so blendende\n"
	.string "Erscheinung, dass der JUROR sie nicht\l"
	.string "sehen wird.\p"
	.string "Äh, einen Moment mal...\n"
	.string "Dann ist sie ja völlig sinnlos...$"

LilycoveCity_ContestHall_Text_PokemonLooksLikeYoungerMe:: @ 8189981
	.string "Dieses hübsche POKéMON sieht genau\n"
	.string "aus wie ich, als ich jünger war.\p"
	.string "Als ich das zu meinem Mann sagte, hat er\n"
	.string "den Kaffee, den er trank, ausgespuckt.\p"
	.string "Was ist daran so lustig?$"

LilycoveCity_ContestHall_Text_WinBeautyContestMakesMeHappy:: @ 8189A1D
	.string "Natürlich, als Frau wäre ich überglück-\n"
	.string "lich, wenn ich den SCHÖNHEITS-\l"
	.string "WETTBEWERB gewinnen würde.$"

LilycoveCity_ContestHall_Text_GanderAtAllThosePrettyPokemon:: @ 8189A82
	.string "Ahahahahaha!\p"
	.string "Wirf mal einen Blick auf all diese\n"
	.string "schönen POKéMON!\l"
	.string "Ich liebe diesen Liebreiz!$"

LilycoveCity_ContestHall_Text_CantWinOnBeautyAlone:: @ 8189AE1
	.string "Du kannst nicht immer nur aufgrund von\n"
	.string "Schönheit gewinnen.\p"
	.string "Du musst dein POKéMON striegeln, damit\n"
	.string "es so schön und glänzend ist wie meines.$"

LilycoveCity_ContestHall_Text_InTheMiddleOfContest:: @ 8189B4E
	.string "MC: Oh oh! Hallo!\n"
	.string "Wir sind mitten in einem WETTBEWERB!\p"
	.string "Lass dich bitte zuerst am Schalter\n"
	.string "registrieren und komm dann wieder, ja?$"

LilycoveCity_ContestHall_Text_SuchCharmingCuteAppeals:: @ 8189BBF
	.string "JUROR: Oh, was für reizende und\n"
	.string "anmutige Ausdrücke!\p"
	.string "Oh, meine Güte! Was für ein perfekter\n"
	.string "NASSMACHER-Ausdruck!$"

LilycoveCity_ContestHall_Text_MyAzurillWasDistracted:: @ 8189C29
	.string "Oh, nein... Mein AZURILL wurde von\n"
	.string "einem anderen POKéMON abgelenkt.$"

LilycoveCity_ContestHall_Text_NeverWonBattleButContest:: @ 8189C67
	.string "Mein POKéMON hat noch nie einen Kampf\n"
	.string "gewonnen. Aber geh mit ihm in einen\l"
	.string "WETTBEWERB und pass auf, was passiert.$"

LilycoveCity_ContestHall_Text_PetalDanceIsMarvel:: @ 8189CB3
	.string "Der BLÄTTERTANZ meines POKéMON ist der\n"
	.string "Inbegriff von Eleganz.\p"
	.string "Ich lasse es nicht zu, dass irgend-\n"
	.string "jemand es dabei stört.$"

LilycoveCity_ContestHall_Text_MyMonAppealSoMuchCuter:: @ 8189D11
	.string "All diese POKéMON sind anmutig.\p"
	.string "Aber, wenn mein POKéMON einen\n"
	.string "anmutigen Ausdruck vorführt...\p"
	.string "Ich bin sicher, dass es dann anmutiger\n"
	.string "als all die anderen POKéMON sein wird.$"

LilycoveCity_ContestHall_Text_MyChildIsInContest:: @ 8189DA2
	.string "Mein Kind nimmt an diesem WETTBEWERB\n"
	.string "teil.\p"
	.string "Los, mein Schatz! Zeig es ihnen!\n"
	.string "Dein POKéMON ist das Beste!$"

LilycoveCity_ContestHall_Text_ThatGirlThereIsCutest:: @ 8189DF3
	.string "Ich finde, das Mädchen dort drüben ist\n"
	.string "das anmutigste Geschöpf von allen.\p"
	.string "Wie bitte? Sie bewerten die POKéMON\n"
	.string "nach ihrer Anmut?!?$"

LilycoveCity_ContestHall_Text_WantCuteMonOfMyOwn:: @ 8189E5F
	.string "Oooh, all diese anmutigen POKéMON!\n"
	.string "Ich möchte auch gerne eines haben!\p"
	.string "Ich werde mir jetzt eines fangen.$"

LilycoveCity_ContestHall_Text_CoolnessContestStage:: @ 8189EC0
	.string "BÜHNE des COOLNESS-WETTBEWERBS\n"
	.string "ERZITTERE VOR DEN COOLEN POKéMON!$"

LilycoveCity_ContestHall_Text_BeautyContestStage:: @ 8189EF3
	.string "BÜHNE des SCHÖNHEITSWETTBEWERBS\n"
	.string "SEI GEBLENDET VON SCHÖNEN POKéMON!$"

LilycoveCity_ContestHall_Text_CuteContestStage:: @ 8189F29
	.string "BÜHNE des ANMUT-WETTBEWERBS\n"
	.string "SEI GEFESSELT VON ANMUTIGEN POKéMON!$"

LilycoveCity_ContestHall_Text_SmartContestStage:: @ 8189F5C
	.string "BÜHNE des KLUGHEITS-WETTBEWERBS\n"
	.string "SEI BEEINDRUCKT VON KLUGEN POKéMON!$"

LilycoveCity_ContestHall_Text_ToughnessContestStage:: @ 8189F93
	.string "BÜHNE des STÄRKEWETTBEWERBS\n"
	.string "FÜRCHTE DICH VOR STARKEN POKéMON!$"
