Route128_Text_IsaiahIntro:: @ 81C1C67
	.string "PRACHTPOLIS CITY ist weit entfernt...$"

Route128_Text_IsaiahDefeat:: @ 81C1C95
	.string "Mein erster Sieg scheint weit entfernt\n"
	.string "zu sein...$"

Route128_Text_IsaiahPostBattle:: @ 81C1CC3
	.string "Mein ganzes Leben ist eine einzige\n"
	.string "Niederlage, aber ich gebe nicht auf!$"

Route128_Text_IsaiahRematchIntro:: @ 81C1D02
	.string "Ich fühle mich gut. Ich werde weiter\n"
	.string "Richtung PRACHTPOLIS CITY schwimmen.$"

Route128_Text_IsaiahRematchDefeat:: @ 81C1D45
	.string "Ich möchte sehr gerne einmal vom Sieg\n"
	.string "kosten...$"

Route128_Text_IsaiahPostRematch:: @ 81C1D6B
	.string "Ich werde PRACHTPOLIS CITY eventuell\n"
	.string "erreichen und dort eventuell gewinnen...$"

Route128_Text_KatelynIntro:: @ 81C1DB0
	.string "In einem Triathlon musst du schwimmen,\n"
	.string "Rad fahren und einen Marathon laufen.\p"
	.string "Es ist ein mörderisches Rennen, das aus\n"
	.string "drei Disziplinen besteht.$"

Route128_Text_KatelynDefeat:: @ 81C1E25
	.string "Ein POKéMON-Kampf ist auch mörderisch.$"

Route128_Text_KatelynPostBattle:: @ 81C1E4A
	.string "Ich muss als Nächstes mit dem RAD\n"
	.string "fahren, aber... Ich möchte eigentlich\l"
	.string "das Handtuch werfen.$"

Route128_Text_KatelynRematchIntro:: @ 81C1E90
	.string "Ein Triathlon ist lang. Aber ich glaube,\n"
	.string "um POKéMON CHAMP zu werden, hat\l"
	.string "man auch einen langen Weg vor sich.$"

Route128_Text_KatelynRematchDefeat:: @ 81C1EFA
	.string "Ein POKéMON-Kampf ist hart und \n"
	.string "unbarmherzig...$"

Route128_Text_KatelynPostRematch:: @ 81C1F2E
	.string "Du solltest ernsthaft darüber nach-\n"
	.string "denken, die SIEGESSTRASSE zu betreten.$"

Route128_Text_AlexaIntro:: @ 81C1F6D
	.string "Wir haben hart dafür gearbeitet, die\n"
	.string "POKéMON LIGA herauszufordern...\p"
	.string "Wir können es uns nicht erlauben,\n"
	.string "jetzt zu verlieren!$"

Route128_Text_AlexaDefeat:: @ 81C1FCC
	.string "Oh!\n"
	.string "Wie konnte das passieren?$"

Route128_Text_AlexaPostBattle:: @ 81C1FE8
	.string "Ich bin so weit gekommen, ich gebe\n"
	.string "jetzt bestimmt nicht auf.$"

Route128_Text_RubenIntro:: @ 81C202C
	.string "Es gibt keinen stärkeren TRAINER als\n"
	.string "mich!$"

Route128_Text_RubenDefeat:: @ 81C2051
	.string "Das darf nicht wahr sein!$"

Route128_Text_RubenPostBattle:: @ 81C2060
	.string "Es gibt wohl keinen stärkeren TRAINER\n"
	.string "als dich!$"

Route128_Text_WayneIntro:: @ 81C2090
	.string "Ich will nach PRACHTPOLIS CITY, daher\n"
	.string "habe ich ein POKéMON gefangen, das\p"
	.string "weiß, wie man mit KASKADE den Wasserfall\n"
	.string "erklimmt.$"

Route128_Text_WayneDefeat:: @ 81C20FC
	.string "Ich bin abgestürzt.$"

Route128_Text_WaynePostBattle:: @ 81C210D
	.string "Ooh, jeeeeh!\p"
	.string "Mein POKéMON kennt KASKADE, aber mir\n"
	.string "fehlt der ORDEN der ARENA von\l"
	.string "XENEROVILLE!$"
