SSTidalRooms_Text_TakeRestOnBed:: @ 819956B
	.string "It's a bed.\n"
	.string "Let's take a rest.$"

SSTidalRooms_Text_ColtonIntro:: @ 819958A
	.string "Go back and forth between LILYCOVE\n"
	.string "and SLATEPORT, that's what I do.\p"
	.string "It's my hobby - going from port to port\n"
	.string "to take in POKéMON CONTESTS.$"

SSTidalRooms_Text_ColtonDefeat:: @ 8199613
	.string "That was an enjoyable match!$"

SSTidalRooms_Text_ColtonPostBattle:: @ 8199630
	.string "I get so excited imagining what kinds\n"
	.string "of POKéMON I'll get to see in the next\l"
	.string "CONTEST. The anticipation of it thrills!$"

SSTidalRooms_Text_TuckerIntro:: @ 81996A6
	.string "Are your friends strong?$"

SSTidalRooms_Text_TuckerDefeat:: @ 81996BF
	.string "Your friends are, indeed, strong.$"

SSTidalRooms_Text_TuckerPostBattle:: @ 81996E1
	.string "Friends need not be human.\n"
	.string "For me, POKéMON are treasured friends!$"

SSTidalRooms_Text_ThomasIntro:: @ 8199723
	.string "Child...\n"
	.string "Did you knock on the door?$"

SSTidalRooms_Text_ThomasDefeat:: @ 8199747
	.string "A loss is to be accepted without haste\n"
	.string "or panic.$"

SSTidalRooms_Text_ThomasPostBattle:: @ 8199778
	.string "To be never ruffled in any situation is\n"
	.string "the GENTLEMAN's code of conduct.$"

SSTidalRooms_Text_JedIntro:: @ 81997C1
	.string "JED: I feel a little shy about this, but...\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_JedDefeat:: @ 8199813
	.string "JED: Sigh...$"

SSTidalRooms_Text_JedPostBattle:: @ 8199820
	.string "JED: It's the first time that our lovey-\n"
	.string "dovey power couldn't prevail!\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_JedNotEnoughMons:: @ 8199887
	.string "JED: You only have one POKéMON?\n"
	.string "Isn't that just too lonesome?$"

SSTidalRooms_Text_LeaIntro:: @ 81998C5
	.string "LEA: I feel a little silly, but...\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_LeaDefeat:: @ 819990E
	.string "LEA: Oh, boo!$"

SSTidalRooms_Text_LeaPostBattle:: @ 819991C
	.string "LEA: I can't believe it!\n"
	.string "Our lovey-dovey power failed...\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_LeaNotEnoughMons:: @ 8199975
	.string "LEA: I wanted to battle...\n"
	.string "But you don't even have two POKéMON...$"

SSTidalRooms_Text_GarretIntro:: @ 81999B7
	.string "Ah, you've come just in time.\p"
	.string "I'm bored, you see.\n"
	.string "You may entertain me.$"

SSTidalRooms_Text_GarretDefeat:: @ 81999FF
	.string "...That will do.$"

SSTidalRooms_Text_GarretPostBattle:: @ 8199A10
	.string "Perhaps I shall get Father to acquire\n"
	.string "a yacht for me.\l"
	.string "A yacht for me and POKéMON!$"

SSTidalRooms_Text_AnetteIntro:: @ 8199A62
	.string "Oh, you're such an adorable TRAINER.\n"
	.string "Would you like to have tea?\l"
	.string "Or would you rather battle?$"

SSTidalRooms_Text_AnetteDefeat:: @ 8199ABF
	.string "I see.\n"
	.string "You're the active sort.$"

SSTidalRooms_Text_AnettePostBattle:: @ 8199ADE
	.string "A world cruise on a luxury liner has its\n"
	.string "charms, I must say...\p"
	.string "But, I will admit there is an appealing\n"
	.string "side to touring HOENN by ferry.$"

SSTidalRooms_Text_NotSuspiciousTakeThis:: @ 8199B65
	.string "Uh... Hi! I... I'm not acting suspicious!\n"
	.string "Uh... You can have this! For free!\p"
	.string "It... Honestly, I didn't SNATCH it from\n"
	.string "someone! I'd never do such a thing!\l"
	.string "It's clean! You can use it!$"

SSTidalRooms_Text_ExplainSnatch:: @ 8199C1A
	.string "SNATCH steals the foe's move in\n"
	.string "advance, and then uses the snatched\l"
	.string "move on the foe.$"
